### ISSUE TITLE
Usersnap Feedback - The quick submit button is missing. --Amber

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#100]
**Sender**: amberfj@gmail.com
**Comment**: The quick submit button is missing. --Amber
[Open #114 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/114)

<a href='https://usersnappublic.s3.amazonaws.com/2017-09-07/01-29/1c16232e-493e-45b4-8548-cc0f93be49a1.png'>![Usersnap Feedback - The quick submit button is missing. --Amber](https://usersnappublic.s3.amazonaws.com/2017-09-07/01-29/ffd8b251-6e85-43b4-8bec-ce8c2fe775db.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-09-07/01-29/1c16232e-493e-45b4-8548-cc0f93be49a1.png'>Download original image</a>

**Browser**: Chrome 60 (macOS Sierra)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 2560 x 1440 **Browser size**: 2532 x 1219

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Quick submit button in menu fixed in PR participedia/frontend#609
