### ISSUE TITLE
Usersnap Feedback - Just published 3 new images, but the slideshow displays grey boxes. I'll g[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1001]
**Sender**: jesi.carson@gmail.com
**Comment**: Just published 3 new images, but the slideshow displays grey boxes. I'll give it a few minutes and check again, but this seems strange.
[Open #695 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/695)

<a href='https://usersnappublic.s3.amazonaws.com/2020-02-28/22-53/9dd17c7b-98e0-49b3-804b-bbc248e7610a.png'>![Usersnap Feedback - Just published 3 new images, but the slideshow displays grey boxes. I'll g(...)](https://usersnappublic.s3.amazonaws.com/2020-02-28/22-53/c6344af6-63cb-4bbd-a15d-83d0207fc650.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-02-28/22-53/9dd17c7b-98e0-49b3-804b-bbc248e7610a.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://participedia.net/case/5600](https://participedia.net/case/5600)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 929

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson this sometimes happens right after adding photos, as they are still uploading to aws in the background, so when you refresh the page they load correctly. it would be nice to fix this, but i'm not sure we should prioritize it right now.

**Comment by jesicarson** [comment]
Fair enough! Back burner is fine.
