### ISSUE TITLE
Usersnap Feedback - Images that are very small stretch out to be all pixelated in our current [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1004]
**Sender**: jesi.carson@gmail.com
**Comment**: Images that are very small stretch out to be all pixelated in our current display system (which zooms to the centre of all images to fill the display box). Wondering if we need an alternate treatment for very small images - and/or if we should add explanatory text that offers a suggested image resolution/size, or even a minimum file size we won't accept? @ascott - thoughts?
[Open #698 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/698)

<a href='https://usersnappublic.s3.amazonaws.com/2020-02-28/22-59/347c4040-0b7e-482b-984b-d55d3b825916.png'>![Usersnap Feedback - Images that are very small stretch out to be all pixelated in our current (...)](https://usersnappublic.s3.amazonaws.com/2020-02-28/22-59/d76bb8d7-1d0a-40ee-8ac0-ba48ff6c932f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-02-28/22-59/347c4040-0b7e-482b-984b-d55d3b825916.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://participedia.net/organization/331](https://participedia.net/organization/331)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 929

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson we can definitely add something to the photos instructional text to suggest a minimum file resolution. in terms of existing images that are not large enough, this might be something for editors to take on? if they see a logo that is very small, they could source and update the entry with a new logo.

**Comment by jesicarson** [comment]
Ok, lets add a suggested minimum size/resolution to the instruction text, and keep this issue in the editors repo.
