### ISSUE TITLE
Usersnap Feedback - entries that used gifs don't display thumbnails

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1007]
**Sender**: alanna.scott@gmail.com
**Comment**: entries that used gifs don't display thumbnails
[Open #701 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/701)

<a href='https://usersnappublic.s3.amazonaws.com/2020-03-03/21-10/a4fb82dc-2a0a-4a15-9f4c-448ade4ffd3a.png'>![Usersnap Feedback - entries that used gifs don't display thumbnails](https://usersnappublic.s3.amazonaws.com/2020-03-03/21-10/8b70abd8-5ed1-4c3f-afb6-8e89eb2bb156.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-03-03/21-10/a4fb82dc-2a0a-4a15-9f4c-448ade4ffd3a.png'>Download original image</a>

**Browser**: Chrome 80 (macOS Mojave)
**Referer**: [https://participedia.net/?query=APSA+Task+Force+on+Democracy%2C+Economic+Security%2C+and+Social+Justice](https://participedia.net/?query=APSA+Task+Force+on+Democracy%2C+Economic+Security%2C+and+Social+Justice)
**Screen size**: 1680 x 1050 **Browser size**: 1678 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
here's a list of entries that have uploaded gifs, they need to be  reviewed and new images uploaded or deleted if a better image cannot be sourced. https://docs.google.com/spreadsheets/d/11McbzpbMLPl4Px3ctEl4hAAu97hc9sm4vWDyO2hTdIA/edit#gid=0

**Comment by ascott** [comment]
the edit form is still showing this instructional text for photos. update to reflect we only allow jpg and pngs as images, and also update with a recommended image size.

<img width="759" alt="Screen Shot 2020-03-03 at 1 12 01 PM" src="https://user-images.githubusercontent.com/130878/75820152-af6acb80-5d50-11ea-82c4-2d7d74c87bc2.png">

**Comment by paninee** [comment]
Completed. Deployed on stage and prod.
