### ISSUE TITLE
Usersnap Feedback - How do I delete a case that I've authored? --amber

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#101]
**Sender**: amberfj@gmail.com
**Comment**: How do I delete a case that I've authored? --amber
[Open #115 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/115)

<a href='https://usersnappublic.s3.amazonaws.com/2017-09-14/20-38/a1af2779-8aa1-46e9-95df-e68874cf7264.png'>![Usersnap Feedback - How do I delete a case that I've authored? --amber](https://usersnappublic.s3.amazonaws.com/2017-09-14/20-38/aed76295-aa55-45b4-a977-0d9d460e8937.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-09-14/20-38/a1af2779-8aa1-46e9-95df-e68874cf7264.png'>Download original image</a>

**Browser**: Chrome 60 (macOS Sierra)
**Referer**: [https://participedia.xyz/case/4618](https://participedia.xyz/case/4618)
**Screen size**: 2560 x 1440 **Browser size**: 1820 x 1219

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
We don't have any provision for deleting (can't undo, has ramifications across other places that may link to that item), but we do have a way to hide items which removes them from search results, lists, etc.

<img width="829" alt="screen shot 2017-09-15 at 1 50 22 pm" src="https://user-images.githubusercontent.com/16825/30502915-0ce7311c-9a1d-11e7-9283-15fb681459c5.png">

Currently we only expose the Hidden toggle to users in the Curators group, but maybe it would be a good idea to extend it to users who are editing an item they created? What to do about subsequent authors in that case though? Deleting shared content is tricky from a UX point of view.

**Comment by dethe** [comment]
Covered here: https://github.com/participedia/frontend/issues/687
