### ISSUE TITLE
Usersnap Feedback - I have been left much worse off by allowing myself to participate in an ev[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1010]
**Sender**: petergatsoris@gmail.com
**Comment**: I have been left much worse off by allowing myself to participate in an event run by this deliberately engaging group. They have no business in conducting any activity that may remotely be described as democratic or independent. I can't speak lowly enough of them.
[Open #704 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/704)

<a href='https://usersnappublic.s3.amazonaws.com/2020-03-17/10-38/44ccb940-8234-45b1-9a26-904bb73d1c49.png'>![Usersnap Feedback - I have been left much worse off by allowing myself to participate in an ev(...)](https://usersnappublic.s3.amazonaws.com/2020-03-17/10-38/07586ccf-e8d6-4ef7-9b32-629aadd8f1b2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-03-17/10-38/44ccb940-8234-45b1-9a26-904bb73d1c49.png'>Download original image</a>

**Browser**: Chrome 80 (Android 10)
**Referer**: [https://participedia.net/organization/5938#](https://participedia.net/organization/5938#)
**Screen size**: 412 x 869 **Browser size**: 412 x 733

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson @plscully not sure if this is something to follow up on or not? i will close it but please re-open if you want to follow up and keep this open.

**Comment by jesicarson** [comment]
Sorry, should have closed this. i checked with Pat about this when i saw it, we agree it can be closed. thx!
