### ISSUE TITLE
Usersnap Feedback - Hi there! I was wondering how I could go about deleting a contribution on [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1011]
**Sender**: selina.h.chau@gmail.com
**Comment**: Hi there!
I was wondering how I could go about deleting a contribution on my profile? I never added anything to the case study, thus, want to remove it from my page where it shows that I did. Please let me know what I can do. Thanks!
[Open #705 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/705)

<a href='https://usersnappublic.s3.amazonaws.com/2020-03-24/02-44/560d6f7b-ef22-4aa5-94f5-9528df2e5062.png'>![Usersnap Feedback - Hi there! I was wondering how I could go about deleting a contribution on (...)](https://usersnappublic.s3.amazonaws.com/2020-03-24/02-44/56277bb7-779d-48f6-9441-1e2fb0f8e099.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-03-24/02-44/560d6f7b-ef22-4aa5-94f5-9528df2e5062.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://participedia.net/case/4624](https://participedia.net/case/4624)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 789

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott we haven’t had this use case before. Not sure if it’s a bug or if they just clicked edit, didn’t make changes, then clicked publish, and therefore this shows up on that person’s profile. We don’t want to hide the entry. Any way to remove a contributor from the wiki history? Thx

**Comment by ascott** [comment]
@jesicarson i think she must have clicked edit and published without making any changes, i removed her as an author on this entry which will remove it from her profile page.

**Comment by jesicarson** [comment]
thank you! i'll shoot her a quick email to let her know.
