### ISSUE TITLE
Usersnap Feedback - collections filtering for methods and organizations is not working as expected

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1012]
**Sender**: alanna.scott@gmail.com
**Comment**: collections filtering for methods and organizations is not working as expected
[Open #706 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/706)

<a href='https://usersnappublic.s3.amazonaws.com/2020-03-27/05-55/be9cc3ee-c6bb-460b-83d2-8d360e91bc08.png'>![Usersnap Feedback - collections filtering for methods and organizations is not working as expected](https://usersnappublic.s3.amazonaws.com/2020-03-27/05-55/82d7d946-1771-45bf-aca9-f099cd49a6f5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-03-27/05-55/be9cc3ee-c6bb-460b-83d2-8d360e91bc08.png'>Download original image</a>

**Browser**: Chrome 80 (macOS Mojave)
**Referer**: [https://ppedia-stage.herokuapp.com/?selectedCategory=method&collections=gov_of_canada](https://ppedia-stage.herokuapp.com/?selectedCategory=method&collections=gov_of_canada)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@paninee collections filtering for methods and organizations is not working on staging. could you please take a look before we ship this to prod? thanks!

**Comment by paninee** [comment]
Fixed on http://ppedia-stage.herokuapp.com/

**Comment by paninee** [comment]
Tested on stage. Deployed to prod.
