### ISSUE TITLE
Usersnap Feedback - BUG - Duplicated Organization Entry on Prod @ascott

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1013]
**Sender**: jesi.carson@gmail.com
**Comment**: BUG - Duplicated Organization Entry on Prod @ascott
[Open #707 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/707)

<a href='https://usersnappublic.s3.amazonaws.com/2020-03-27/18-31/5f4e7fb3-95c1-46e2-9a2d-b3867dc2f88a.png'>![Usersnap Feedback - BUG - Duplicated Organization Entry on Prod @ascott](https://usersnappublic.s3.amazonaws.com/2020-03-27/18-31/3033b1fa-f3fa-49b6-9df4-0e7656fd659f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-03-27/18-31/5f4e7fb3-95c1-46e2-9a2d-b3867dc2f88a.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
looks like Org https://participedia.net/organization/6449 is functional, but 6448, 6446, etc get an internal server error:
![Screen Shot 2020-03-27 at 10 33 27 AM](https://user-images.githubusercontent.com/13560530/77783727-9800c480-7016-11ea-8451-33dde165eded.png)
![Screen Shot 2020-03-27 at 10 33 40 AM](https://user-images.githubusercontent.com/13560530/77783728-98995b00-7016-11ea-9ed7-f8b755203ce0.png)


![Screen Shot 2020-03-27 at 10 32 33 AM](https://user-images.githubusercontent.com/13560530/77783723-97682e00-7016-11ea-99f1-6fd9c915143c.png)

**Comment by ascott** [comment]
this is a weird one, i'm not sure why these are showing as internal server errors. they look like empty entries in the database. I have hidden them and left just the correct entry which is working as expected. https://participedia.net/organization/6449
