### ISSUE TITLE
Usersnap Feedback - collections field missing for methods and orgs view and edit pages

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1016]
**Sender**: alanna.scott@gmail.com
**Comment**: collections field missing for methods and orgs view and edit pages
[Open #710 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/710)

<img width="1680" alt="Screen Shot 2020-03-31 at 1 24 34 PM" src="https://user-images.githubusercontent.com/130878/78071818-fe595000-7352-11ea-95f8-34154f29547d.png">

**Browser**: Chrome 80 (macOS Mojave)
**Referer**: [https://participedia.net/method/184/edit?full=1](https://participedia.net/method/184/edit?full=1)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Fixed on Stage. http://ppedia-stage.herokuapp.com/

**Comment by paninee** [comment]
Tested on stage. Deployed to prod.
