### ISSUE TITLE
Usersnap Feedback - Multiple FAQ items list Scott's personal gmail account as the point of con[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1017]
**Sender**: jesi.carson@gmail.com
**Comment**: Multiple FAQ items list Scott's personal gmail account as the point of contact. This needs to be removed.
[Open #711 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/711)

<a href='https://usersnappublic.s3.amazonaws.com/2020-04-03/19-52/ddae34c3-9edc-4574-889d-202804ea0785.png'>![Usersnap Feedback - Multiple FAQ items list Scott's personal gmail account as the point of con(...)](https://usersnappublic.s3.amazonaws.com/2020-04-03/19-52/164a193e-9f08-47f6-aac8-8bee9d60c057.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-04-03/19-52/ddae34c3-9edc-4574-889d-202804ea0785.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://participedia.net/case/5697#](https://participedia.net/case/5697#)
**Screen size**: 1680 x 1050 **Browser size**: 1677 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson should we change this to the info@participedia.net email address?

**Comment by jesicarson** [comment]
No i think just delete that part of the sentence. End it with "Please read our guidelines on how to write an organization entry."
They're in the help and contact menu so if they want to email us they can.
