### ISSUE TITLE
Usersnap Feedback - many of the entries that i assigned to the covid 19 response collection ar[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1020]
**Sender**: jesi.carson@gmail.com
**Comment**: many of the entries that i assigned to the covid 19 response collection are no longer listed (there were over 12 entries previously, now only 6)
[Open #714 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/714)

<a href='https://usersnappublic.s3.amazonaws.com/2020-04-09/07-16/35dae413-5495-40ad-b1b4-09940dd33901.png'>![Usersnap Feedback - many of the entries that i assigned to the covid 19 response collection ar(...)](https://usersnappublic.s3.amazonaws.com/2020-04-09/07-16/093facf3-df98-4e67-8813-4de6c1ddba5c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-04-09/07-16/35dae413-5495-40ad-b1b4-09940dd33901.png'>Download original image</a>

**Browser**: Chrome 80 (Windows 10)
**Referer**: [https://participedia.net/?selectedCategory=method&collections=covid_19_response](https://participedia.net/?selectedCategory=method&collections=covid_19_response)
**Screen size**: 1504 x 1003 **Browser size**: 1504 x 892

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
ignore me - this was on the methods tab. closing
