### ISSUE TITLE
Usersnap Feedback - This is the first time I've seen outright vandalism on the site. It looks [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1027]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: This is the first time I've seen outright vandalism on the site. It looks like the user changed the title and added a link to an existing Method entry. I will hide the entry for now. Please let me know after you've blocked the user and I will then ask Lucy to review the rest of the entry and repair it.
[Open #721 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/721)

<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/16-15/4c3364a0-9bd9-468a-b1c3-d79832838974.png'>![Usersnap Feedback - This is the first time I've seen outright vandalism on the site. It looks (...)](https://usersnappublic.s3.amazonaws.com/2020-04-24/16-15/5b542f79-d988-4c09-9068-5a141f107565.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/16-15/4c3364a0-9bd9-468a-b1c3-d79832838974.png'>Download original image</a>

**Browser**: Firefox 75 (Windows 10)
**Referer**: [https://participedia.net/method/4241](https://participedia.net/method/4241)
**Screen size**: 1600 x 1000 **Browser size**: 1600 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully I have blocked the user in Auth0. Thanks for flagging this. @ascott might be able to get a backup of the entry from before it was edited, is that right Alanna?

**Comment by jesicarson** [comment]
another note is that even though the user is blocked - their profile remains on Participedia (https://participedia.net/user/418616) maybe we should think about a way for admins to hide spam profiles. though this isn't a huge priority yet as we don't get this happening too often.

**Comment by ascott** [comment]
@jesicarson @plscully i've reverted the title and description to the last saved content before this, and deleted the spam link as well. i have also deleted the user from our db and the record of their contribution manually. with the block on auth0 that jesi did, this user wont be able to create a new account.

**Comment by plscully** [comment]
Thank you!
