### ISSUE TITLE
Usersnap Feedback - STAGING TEST of collections landing pages:  Design feedback  The results t[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1028]
**Sender**: jesi.carson@gmail.com
**Comment**: STAGING TEST of collections landing pages:

Design feedback

The results text below the tabs could be more descriptive, including the name of the collection. (to me this design still feels like the banner is disconnected from the results)

amber also suggested populating the search bar with a query that allows the user to search the collection.
[Open #722 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/722)

<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/22-31/2e6a0a1c-c03e-4b84-a515-50e1db704d3f.png'>![Usersnap Feedback - STAGING TEST of collections landing pages:  Design feedback  The results t(...)](https://usersnappublic.s3.amazonaws.com/2020-04-24/22-31/18aba39e-ea5b-4fc5-9951-95ef0fe2661c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/22-31/2e6a0a1c-c03e-4b84-a515-50e1db704d3f.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/collection/5912?selectedCategory=case](https://ppedia-stage.herokuapp.com/collection/5912?selectedCategory=case)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
dealt with here https://github.com/participedia/api/issues/897 
closing
