### ISSUE TITLE
Usersnap Feedback - Can't click "ok" on the calendar pop up on iPhone 6. The bottom nav in saf[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#103]
**Sender**: jesi.carson@gmail.com
**Comment**: Can't click "ok" on the calendar pop up on iPhone 6. The bottom nav in safari keeps popping up and getting in the way. Can we move the calendar up higher on the page?
[Open #117 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/117)

<a href='https://usersnappublic.s3.amazonaws.com/2017-09-20/23-45/620bb519-2e64-4508-8132-6dc1ca994bbf.png'>![Usersnap Feedback - Can't click "ok" on the calendar pop up on iPhone 6. The bottom nav in saf(...)](https://usersnappublic.s3.amazonaws.com/2017-09-20/23-45/06765902-4fca-44a1-afcf-fde23dd00b9c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-09-20/23-45/620bb519-2e64-4508-8132-6dc1ca994bbf.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/case/4627/edit](https://participedia.xyz/case/4627/edit)
**Screen size**: 320 x 568 **Browser size**: 320 x 568

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Here's a better screenshot to illustrate this issue. 

![image](https://user-images.githubusercontent.com/13560530/40324222-bd9f5628-5cec-11e8-90c0-0496346bc11c.png)
