### ISSUE TITLE
Usersnap Feedback - It used to be that a keyword search would populate the results text -  thi[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1030]
**Sender**: jesi.carson@gmail.com
**Comment**: It used to be that a keyword search would populate the results text -  this should be: 1-20 results of 25 for "covid-19" (page 1 of 2)

can we re-implement this feature? 

this is related to clarifying the results for collections landing pages, where it could similarly display: 1-15 results of 15 in "Covid-19 Response" Collection (page 1 of 1)
[Open #724 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/724)

<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/22-43/ebadc7ca-a29f-4c63-91bf-0a7c13727cc9.png'>![Usersnap Feedback - It used to be that a keyword search would populate the results text -  thi(...)](https://usersnappublic.s3.amazonaws.com/2020-04-24/22-43/cff8c78e-2854-4185-804e-b742a15d78a1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/22-43/ebadc7ca-a29f-4c63-91bf-0a7c13727cc9.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://participedia.net/?query=covid-19](https://participedia.net/?query=covid-19)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Amber suggests being even more explicit, ie: 
The Covid-19 Response collection contains 5 cases, 2 methods and 1 organization
