### ISSUE TITLE
Usersnap Feedback - STAGING TEST of landing pages for collections: Newest entry (just publishe[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1031]
**Sender**: jesi.carson@gmail.com
**Comment**: STAGING TEST of landing pages for collections: Newest entry (just published this) shows up last in results on collections tab on homepage.
[Open #725 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/725)

<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/22-48/fda24223-20f1-4c0e-8101-e33c7027c789.png'>![Usersnap Feedback - STAGING TEST of landing pages for collections: Newest entry (just publishe(...)](https://usersnappublic.s3.amazonaws.com/2020-04-24/22-48/2c8cd4c2-a25b-411e-ba5b-98ef17a29c6c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/22-48/fda24223-20f1-4c0e-8101-e33c7027c789.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/?selectedCategory=collections](https://ppedia-stage.herokuapp.com/?selectedCategory=collections)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Fixed and deployed on prod.
