### ISSUE TITLE
Usersnap Feedback - STAGING TEST of collections landing pages:   Design feedback   Not loving [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1032]
**Sender**: jesi.carson@gmail.com
**Comment**: STAGING TEST of collections landing pages: 

Design feedback 

Not loving that the collections tab dissapears here - i automatically go back there looking for the rest of the collections. there's a bit of a messed up logic for having it as part of the tabs, but i also don't want to suddenly move it to a new location for people. not exactly sure the best way to address this, but perhaps this suggestion:

what about on the homepage, instead of treating "Collections" in the same visual way as the other tabs, we make it a button with the text "View all collections" and then just keep it there on the landing pages for collections.
[Open #726 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/726)

<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/22-52/ec660c91-bbd4-4af7-8e2e-239575826431.png'>![Usersnap Feedback - STAGING TEST of collections landing pages:   Design feedback   Not loving (...)](https://usersnappublic.s3.amazonaws.com/2020-04-24/22-52/3e4cec09-e8dd-4643-ac45-9ca347046fbd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/22-52/ec660c91-bbd4-4af7-8e2e-239575826431.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/collection/5914](https://ppedia-stage.herokuapp.com/collection/5914)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson i'm not sure about the button solution for the collections tab. It behaves just like the other tabs, so to change it to look like a button doesn't make sense to me. Part of the tab behavior is that when it is selected it is shown with a red underline to indicate the active tab/page. If we used a button instead of the tab, we lose that indication of what tab/page you are viewing.

<img width="1680" alt="Screen Shot 2020-04-27 at 3 47 39 PM" src="https://user-images.githubusercontent.com/130878/80428433-af91ce00-889e-11ea-9c15-01ebb0dd9f0c.png">

As an alternative, what do you think about making the "View all collections" link a button on the collections landing page, to make it a bit easier to spot on the page.

<img width="1680" alt="Screen Shot 2020-04-27 at 3 51 29 PM" src="https://user-images.githubusercontent.com/130878/80428595-0c8d8400-889f-11ea-9d76-216584d49f53.png">

In terms of the collection page not having the Collections tab, I think it makes sense that a collection wouldn't contain collections, which explains why that tab is not there.

**Comment by jesicarson** [comment]
@ascott the latest design is here: https://github.com/participedia/api/issues/897#issuecomment-619279267 (closing this)
