### ISSUE TITLE
Usersnap Feedback - STAGING TEST of collections landing pages: Also on the homepage, this feat[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1033]
**Sender**: jesi.carson@gmail.com
**Comment**: STAGING TEST of collections landing pages: Also on the homepage, this featured collection was updated more recently than the featured case, but doesn't display in that order.
[Open #727 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/727)

<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/23-01/70228800-3f74-477d-8e6f-6b29ed81861c.png'>![Usersnap Feedback - STAGING TEST of collections landing pages: Also on the homepage, this feat(...)](https://usersnappublic.s3.amazonaws.com/2020-04-24/23-01/c7d4239d-c0ce-47f0-9434-7aa40614b167.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-04-24/23-01/70228800-3f74-477d-8e6f-6b29ed81861c.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/](https://ppedia-stage.herokuapp.com/)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
taking a look into this...

**Comment by ascott** [comment]
@paninee would you be able to take a look at this one?

**Comment by paninee** [comment]
Hey @ascott I couldn't reproduce this. Have you already added a fix? The newer collections appears at the top (May 9 ones)
![image](https://user-images.githubusercontent.com/29439995/81465028-b3b1cb80-917b-11ea-9c9c-b44207672412.png)

**Comment by ascott** [comment]
@paninee i couldn't reproduce either. closing.
