### ISSUE TITLE
Usersnap Feedback - add "what is a collection" faq item

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1035]
**Sender**: alanna.scott@gmail.com
**Comment**: add "what is a collection" faq item
[Open #729 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/729)

<a href='https://usersnappublic.s3.amazonaws.com/2020-04-28/00-59/d6fdf6f0-e85e-4d0e-ab91-706a52607403.png'>![Usersnap Feedback - add "what is a collection" faq item](https://usersnappublic.s3.amazonaws.com/2020-04-28/00-59/61b0ab3d-3339-4cfc-b612-58c9a306b310.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-04-28/00-59/d6fdf6f0-e85e-4d0e-ab91-706a52607403.png'>Download original image</a>

**Browser**: Chrome 80 (macOS Mojave)
**Referer**: [https://ppedia-stage.herokuapp.com/?selectedCategory=collections#](https://ppedia-stage.herokuapp.com/?selectedCategory=collections#)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson I think we should add a "What is a collection?" item to the FAQ section. Would you be able to write that up?

**Comment by jesicarson** [comment]
@ascott yes will do. pretty sure i have that text somewhere.

**Comment by jesicarson** [comment]
@ascott How about [this](https://docs.google.com/document/d/1EcFFA9BDE_6WqsVLtgPIV9vSSDFdEiLQ3rh7QuapO9k/edit?usp=sharing)

**Comment by ascott** [comment]
sounds great! thanks @jesicarson

**Comment by jesicarson** [comment]
Thanks for the edits @plscully. The text in the linked doc above is good to go @ascott .
