### ISSUE TITLE
Usersnap Feedback - On the collections tab - the map overlay dissapears

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1038]
**Sender**: jesi.carson@gmail.com
**Comment**: On the collections tab - the map overlay dissapears
[Open #732 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/732)

<a href='https://usersnappublic.s3.amazonaws.com/2020-04-30/18-11/e0afe1a8-67b4-4aef-819c-7f8b9930cc11.png'>![Usersnap Feedback - On the collections tab - the map overlay dissapears](https://usersnappublic.s3.amazonaws.com/2020-04-30/18-11/249de4ea-d224-4027-a8bb-121c997f998d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-04-30/18-11/e0afe1a8-67b4-4aef-819c-7f8b9930cc11.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://participedia.net/?selectedCategory=collections](https://participedia.net/?selectedCategory=collections)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott did you see this one? would be good to have the standard tagline overlay remain in place on  the collections tab on the homepage as soon as possible, as we'll be promoting this soon. thanks!

**Comment by ascott** [comment]
@jesicarson yep, working on this this morning :)
