### ISSUE TITLE
Usersnap Feedback - The short description disappears on smallest screen size (it is visible as [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1039]
**Sender**: jesi.carson@gmail.com
**Comment**: The short description disappears on smallest screen size (it is visible as soon as you make the screen slightly wider).
[Open #733 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/733)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-02/00-16/5d9313e3-7989-4b74-86f2-8f81f446b81b.png'>![Usersnap Feedback - The short description disappears on smallest screen size (it is visible as (...)](https://usersnappublic.s3.amazonaws.com/2020-05-02/00-16/089f0ded-2100-4c53-a4a4-f4190841b54a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-02/00-16/5d9313e3-7989-4b74-86f2-8f81f446b81b.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://participedia.net/collection/6499](https://participedia.net/collection/6499)
**Screen size**: 1680 x 1050 **Browser size**: 500 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson i adjust the layout of the overlay card for really small screens to fix this issue. i also adjusted the layout for very large screens to jump to 2 columns instead of three so the text isn't in such a long line for reading comfort. what do you think? ps. ignore the overlay text, this is just placeholder in my local setup

**width: 325px**
<img width="327" alt="Screen Shot 2020-05-04 at 8 51 44 AM" src="https://user-images.githubusercontent.com/130878/80985948-bb244e00-8de4-11ea-8dc1-e13d504b4504.png">

**width: 930px**
<img width="932" alt="Screen Shot 2020-05-04 at 8 51 14 AM" src="https://user-images.githubusercontent.com/130878/80985952-bcee1180-8de4-11ea-9e6f-38ababc88912.png">

**width: 1320px**
<img width="1326" alt="Screen Shot 2020-05-04 at 8 50 56 AM" src="https://user-images.githubusercontent.com/130878/80985956-beb7d500-8de4-11ea-9079-d62ec2c0ee8a.png">

**width: 1430px**
<img width="1437" alt="Screen Shot 2020-05-04 at 8 50 42 AM" src="https://user-images.githubusercontent.com/130878/80985964-c11a2f00-8de4-11ea-9957-b8cd3c4001b5.png">

**Comment by jesicarson** [comment]
@ascott perfect, thanks!
