### ISSUE TITLE
Usersnap Feedback - Weird spacing between form fields here. Confusing photo and video adding f[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#104]
**Sender**: jesi.carson@gmail.com
**Comment**: Weird spacing between form fields here. Confusing photo and video adding functions. 
[Open #118 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/118)

<a href='https://usersnappublic.s3.amazonaws.com/2017-09-20/23-56/2445b31c-565f-4ec0-a89a-4a5958f8bda1.png'>![Usersnap Feedback - Weird spacing between form fields here. Confusing photo and video adding f(...)](https://usersnappublic.s3.amazonaws.com/2017-09-20/23-56/8dc1d52b-507e-4f5b-a836-751363bb6f64.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-09-20/23-56/2445b31c-565f-4ec0-a89a-4a5958f8bda1.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/case/4627/edit](https://participedia.xyz/case/4627/edit)
**Screen size**: 320 x 568 **Browser size**: 320 x 568

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by andreadelrio** [comment]
@jesicarson what if we add labels for both Photos and Videos?

**Comment by jesicarson** [comment]
That could work. We might also want to be able to add links to podcasts/audio files (like SoundCloud) as a type of media eventually... so maybe try sub headings under the main media heading? For now just photos and videos.
