### ISSUE TITLE
Usersnap Feedback - @ascott - spacing

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1041]
**Sender**: jesi.carson@gmail.com
**Comment**: @ascott - spacing
[Open #734 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/734)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-05/00-37/9c611911-8250-4d1d-838c-a911fb3c3539.png'>![Usersnap Feedback - @ascott - spacing](https://usersnappublic.s3.amazonaws.com/2020-05-05/00-37/c9bd01be-bd1c-46d6-849f-57c6ddd283f2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-05/00-37/9c611911-8250-4d1d-838c-a911fb3c3539.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson sorry i can't remember what you said about this. can you let me know what spacing changes you wanted to see?

**Comment by jesicarson** [comment]
original design had less spacing above the tabs, but honestly it's fine as is, and we may do some other changes to the homepage anyway so no point fiddling with it now. closing this.
