### ISSUE TITLE
Usersnap Feedback - Why is the landing page image banner not as tall as the homepage map?

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1042]
**Sender**: jesi.carson@gmail.com
**Comment**: Why is the landing page image banner not as tall as the homepage map?
[Open #735 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/735)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-05/00-42/d3ac6eda-31a8-413e-b923-8d9851c8cd65.png'>![Usersnap Feedback - Why is the landing page image banner not as tall as the homepage map?](https://usersnappublic.s3.amazonaws.com/2020-05-05/00-42/d3379c78-ceb6-4d16-bf27-610b02962f56.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-05/00-42/d3ac6eda-31a8-413e-b923-8d9851c8cd65.png'>Download original image</a>

**Browser**: Chrome 80 (Macintosh)
**Referer**: [https://participedia.net/collection/6499](https://participedia.net/collection/6499)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson i made the height of the banner responsive to the width of the screen and the amount of text, so that it would work well on small screen sizes as well. i can give this a minimum height tho so it is always at least as high as the map on the home page.

**Comment by jesicarson** [comment]
Gotcha. This setup makes sense, just makes choosing the right image a little trickier as it's getting pretty narrow. Let's leave it as is for now and see how it goes.
