### ISSUE TITLE
Usersnap Feedback - Please delete the 2nd file in this list of 3. It doesn't belong with this [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1047]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Please delete the 2nd file in this list of 3. It doesn't belong with this case entry
[Open #740 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/740)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-07/18-24/f6650d5e-3460-4008-8b42-bb567946cb70.png'>![Usersnap Feedback - Please delete the 2nd file in this list of 3. It doesn't belong with this (...)](https://usersnappublic.s3.amazonaws.com/2020-05-07/18-24/53e6cf11-db31-431b-a5d0-199d1fff7474.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-07/18-24/f6650d5e-3460-4008-8b42-bb567946cb70.png'>Download original image</a>

**Browser**: Firefox 76 (Windows 10)
**Referer**: [https://participedia.net/case/1353](https://participedia.net/case/1353)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott there's something buggy here - the files section of the form isn't matching the data sidebar.

**Comment by plscully** [comment]
@ascott @jesicarson  The reason the section of the form doesn't match the sidebar is probably b/c I tried to delete the file by deleting the entry in the form. I selected the 'x' at the top right of the entry. But the result was that it simply deleted the name of the file and reverted to our back-end file name. I can see that this is the way it should work so that users don't accidentally delete files that we can't recover.

**Comment by ascott** [comment]
@jesicarson @plscully it sounds like a bug if you clicked the `x` icon on a file entry and it only deleted the tile of the file. looking at the edit form, it matches what is shown in the data side bar. if the file doesn't have a title, we use the file name. i can see how this is not super clear, since we don't show the filename in the title field. i tested deleting files on another entry and it works for me as expected, so i'll go ahead and delete this second file on this entry as well.
