### ISSUE TITLE
values for `Open to All or Limited to Some?` and `Recruitment Method for Limited Subset of Population` should be capitalized

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1050]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: This is a small thing, but it is similar to another issue I submitted earlier today from this sequence of questions in that the responses should be capitalized.
[Open #743 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/743)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-12/02-32/6a304ce8-ff31-475e-8958-c168b089cf6a.png'>![Usersnap Feedback - This is a small thing, but it is similar to another issue I submitted earl(...)](https://usersnappublic.s3.amazonaws.com/2020-05-12/02-32/73b3f6d1-85b4-4c45-b0b8-637e4c58b4ff.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-12/02-32/6a304ce8-ff31-475e-8958-c168b089cf6a.png'>Download original image</a>

**Browser**: Firefox 76 (Windows 10)
**Referer**: [https://participedia.net/case/6488](https://participedia.net/case/6488)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
values for `Open to All or Limited to Some?` and `Recruitment Method for Limited Subset of Population` should be capitalized

**Comment by paninee** [comment]
Fixed and deployed to prod.
