### ISSUE TITLE
Usersnap Feedback - This is such an in depth representation of Cameroon's reality in the heart [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1054]
**Sender**: chrisbay21@yahoo.com
**Comment**: This is such an in depth representation of Cameroon's reality in the heart of the COVID-19 pandemic. Perhaps what kills faster in Cameroon isn't just the COVID-19. Perhaps shattered dreams, lack of accountability, deep seated corruption and other inequalities. These could just be other pandemics that need to be treated with all urgency...
[Open #747 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/747)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-15/09-50/d2ab28ac-a31a-448d-aedc-e76ae086e62d.png'>![Usersnap Feedback - This is such an in depth representation of Cameroon's reality in the heart (...)](https://usersnappublic.s3.amazonaws.com/2020-05-15/09-50/51f3b5c9-1aaa-4969-962e-88f312de3eef.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-15/09-50/d2ab28ac-a31a-448d-aedc-e76ae086e62d.png'>Download original image</a>

**Browser**: Chrome 81 (Android 9)
**Referer**: [https://participedia.net/case/6544](https://participedia.net/case/6544)
**Screen size**: 412 x 846 **Browser size**: 412 x 718

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson @plscully user comment. closing.

**Comment by jesicarson** [comment]
I'm prepping a boilerplate email for when this happens. I'm thinking of suggesting that if people want to comment on an entry, they can tweet a link to the entry with their thoughts, or post a link to the entry along with their thoughts in the ppedia facebook group.
