### ISSUE TITLE
Usersnap Feedback - More spam. Please block this user. I have hidden the case entry https://pa[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1055]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: More spam. Please block this user. I have hidden the case entry https://participedia.net/case/6555
[Open #748 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/748)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-18/18-43/600252c3-949c-425a-aa31-4be5b6d804cd.png'>![Usersnap Feedback - More spam. Please block this user. I have hidden the case entry https://pa(...)](https://usersnappublic.s3.amazonaws.com/2020-05-18/18-43/2095ef51-77ec-4345-8cd6-ca5ee357d2b2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-18/18-43/600252c3-949c-425a-aa31-4be5b6d804cd.png'>Download original image</a>

**Browser**: Firefox 76 (Windows 10)
**Referer**: [https://participedia.net/user/418716](https://participedia.net/user/418716)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Thanks Pat. I blocked the user.
