### ISSUE TITLE
Usersnap Feedback - The collections name appears in German even though I entered it in English[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1056]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: The collections name appears in German even though I entered it in English. This happened to both me and Antonin
[Open #749 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/749)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-20/20-31/b17b9a2e-c3d7-4389-84f1-8a6bf1580d2e.png'>![Usersnap Feedback - The collections name appears in German even though I entered it in English(...)](https://usersnappublic.s3.amazonaws.com/2020-05-20/20-31/d9c02440-8ed7-45c2-91fe-f8b246db6fdb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-20/20-31/b17b9a2e-c3d7-4389-84f1-8a6bf1580d2e.png'>Download original image</a>

**Browser**: Firefox 76 (Windows 10)
**Referer**: [https://participedia.net/case/6560](https://participedia.net/case/6560)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
https://github.com/participedia/usersnaps/issues/1056

**Comment by paninee** [comment]
fixed. deployed on stage. tested. deployed on prod. tested
