### ISSUE TITLE
Other language versions of entry do not have correct translations

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1057]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I think this is the 2nd time this has happened within the last few days when we linked to a method. Instead of the name of the method appearing in the sidebar, a series of numbers appears instead. Here is the method entry https://participedia.net/method/6478
[Open #750 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/750)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-20/22-23/360294df-ba35-40c2-87c5-d5654eda89bd.png'>![Usersnap Feedback - I think this is the 2nd time this has happened within the last few days wh(...)](https://usersnappublic.s3.amazonaws.com/2020-05-20/22-23/c05575bf-ef83-4bc4-a9db-ad3457e84008.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-20/22-23/360294df-ba35-40c2-87c5-d5654eda89bd.png'>Download original image</a>

**Browser**: Firefox 76 (Windows 10)
**Referer**: [https://participedia.net/case/6560](https://participedia.net/case/6560)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@paninee can you take a look at this one please? it looks like this entry https://participedia.net/method/6478/es in ES has numbers for content, while in EN it has text https://participedia.net/method/6478/en

<img width="1680" alt="Screen Shot 2020-05-26 at 12 25 30 PM" src="https://user-images.githubusercontent.com/130878/82942044-3e504400-9f4c-11ea-9bae-d76e28f214f7.png">
<img width="1680" alt="Screen Shot 2020-05-26 at 12 25 45 PM" src="https://user-images.githubusercontent.com/130878/82942142-5758f500-9f4c-11ea-87c4-e44b341f9bf6.png">

**Comment by plscully** [comment]
@ascott @paninee  It is not only the Spanish translation that displays a number instead of the name of the method. The same thing happens for all the other languages, except for English. Before localization was implemented, the same thing was happening for En -- that is, a number instead of the name appeared for this particular method. D&T fixed that, but after localization was launched, the 'number instead of name' issue arose for all the other languages

**Comment by paninee** [comment]
@ascott It looks like the translated data was old. They were translated in 2017. Do you have a suggestion to fix this? Should we just remove the rows and re-translate them?

![image](https://user-images.githubusercontent.com/29439995/83106363-32aa6d80-a071-11ea-855c-a228cd5856f5.png)

**Comment by jesicarson** [comment]
Im not sure if this is relevant for this particular issue - but be careful deleting things that were translated in the past - they may have been done so manually by researchers, or entered in other languages. We don't want to overwrite someones work with a machine translation. Again, not sure if this is relevant, but wanted to flag that.

**Comment by paninee** [comment]
Fixed with https://github.com/participedia/api/issues/888
