### ISSUE TITLE
Usersnap Feedback - Hi, I just came upon the idea of the idea jam in the context of rising a c[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1058]
**Sender**: krueger.julia@protonmail.com
**Comment**: Hi, I just came upon the idea of the idea jam in the context of rising a competition over the best ideas for public corona subsidies in Germany despite of support for national airlines. But as I imagine other uses, as well, I wonder: Are there any good open-source solutions for the method developed by now?

Yours sincerely
Julia

phaenomen.org
[Open #751 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/751)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-24/14-44/1cf1b0c2-a0ee-41a2-8909-bbc706b28abc.png'>![Usersnap Feedback - Hi, I just came upon the idea of the idea jam in the context of rising a c(...)](https://usersnappublic.s3.amazonaws.com/2020-05-24/14-44/28352997-ecb4-4c3f-a7d7-d2544bc2864e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-24/14-44/1cf1b0c2-a0ee-41a2-8909-bbc706b28abc.png'>Download original image</a>

**Browser**: Firefox 75 (Ubuntu)
**Referer**: [https://participedia.net/method/4620](https://participedia.net/method/4620)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 761

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
I'll write to her.
