### ISSUE TITLE
Usersnap Feedback - I entered the first version of this test case in Spanish, but when I view [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1059]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I entered the first version of this test case in Spanish, but when I view it in English, it is missing the last two paragraphs
[Open #752 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/752)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-25/20-53/6bf61449-8324-4e58-9c43-e21771451783.png'>![Usersnap Feedback - I entered the first version of this test case in Spanish, but when I view (...)](https://usersnappublic.s3.amazonaws.com/2020-05-25/20-53/fa99a62f-5087-4d41-99e9-4e959cab72cb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-25/20-53/6bf61449-8324-4e58-9c43-e21771451783.png'>Download original image</a>

**Browser**: Firefox 76 (Windows 10)
**Referer**: [https://participedia.net/case/6561](https://participedia.net/case/6561)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
There's also something up with the typography here. @ascott

**Comment by jesicarson** [comment]
Though I believe Pat's actual snap was about translation - im pretty sure he edited the case after first publish, which is why we don't see the rest of the edits. he is now clear on the forked versions. (we can discuss some feedback he has about our explanatory text on the D&T call tomorrow)

**Comment by ascott** [comment]
@jesicarson  this type of formatting isn't achievable with the rich text editor we have, so i'm not sure how it got into this state unless formatted text was pasted into the field. i don't think we've seen this happen in many entries, and it's fixable by selecting the text and then clicking the remove formatting icon 
<img width="51" alt="Screen Shot 2020-05-26 at 12 20 27 PM" src="https://user-images.githubusercontent.com/130878/82941618-828f1480-9f4b-11ea-9a72-0985e49fe347.png">
