### ISSUE TITLE
Usersnap Feedback - "Related content" text repeated on mobile case reader accordion.

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#106]
**Sender**: jesi.carson@gmail.com
**Comment**: "Related content" text repeated on mobile case reader accordion. 
[Open #120 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/120)

<a href='https://usersnappublic.s3.amazonaws.com/2017-09-20/23-59/1787084e-1288-4064-a297-b84823093d2c.png'>![Usersnap Feedback - "Related content" text repeated on mobile case reader accordion.](https://usersnappublic.s3.amazonaws.com/2017-09-20/23-59/80889cfe-0963-4380-8b97-ccff8fd8c5e8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-09-20/23-59/1787084e-1288-4064-a297-b84823093d2c.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/case/4627](https://participedia.xyz/case/4627)
**Screen size**: 320 x 568 **Browser size**: 320 x 568

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by andreadelrio** [comment]
@jesicarson not sure what you mean here, would it be possible to add another screenshot? (ideally not using Usersnap because the one generated above seems to belong to desktop).

**Comment by jesicarson** [comment]
Weird! I'll email you a screenshot because I can't seem to add it on github on mobile.

**Comment by andreadelrio** [comment]
@jesicarson thanks! I got it. Yeah Usernaps generates unuseful/weird screenshots sometimes.
