### ISSUE TITLE
Usersnap Feedback - Although the problem was fixed in the English interface of this number app[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1060]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Although the problem was fixed in the English interface of this number appearing instead of the case's name, the problem persists for other languages
[Open #753 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/753)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-25/20-58/a7348c18-e402-486a-a6e9-c488b71e9526.png'>![Usersnap Feedback - Although the problem was fixed in the English interface of this number app(...)](https://usersnappublic.s3.amazonaws.com/2020-05-25/20-58/7769132d-30e1-482b-ba70-64629445a16d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-25/20-58/a7348c18-e402-486a-a6e9-c488b71e9526.png'>Download original image</a>

**Browser**: Firefox 76 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Solved by https://github.com/participedia/api/issues/888
