### ISSUE TITLE
Fix i18n text for How do I create content FAQ answer

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1063]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: random text
[Open #756 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/756)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-29/09-15/5c983511-f880-4d3c-99c6-800f9e2dc01d.png'>![Usersnap Feedback - random text](https://usersnappublic.s3.amazonaws.com/2020-05-29/09-15/8387ae89-44cd-4ca7-bfb8-b1c86b85cc66.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-29/09-15/5c983511-f880-4d3c-99c6-800f9e2dc01d.png'>Download original image</a>

**Browser**: Chrome 81 (Windows 10)
**Referer**: [https://participedia.net/collection/6501#](https://participedia.net/collection/6501#)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 657

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
@jesicarson I don't understand what this issue is, do you? I don't see any issue with the i18n text. I changed the site to FR, the help section content becomes French.

**Comment by jesicarson** [comment]
Change text to "...or contact us for more information."

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/113909346-6de6f400-978c-11eb-803c-699ae5a695f1.png)
