### ISSUE TITLE
Usersnap Feedback - Please block this user who posted spam. I have hidden their entries

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1064]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Please block this user who posted spam. I have hidden their entries
[Open #757 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/757)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-29/15-52/8d7fe1c2-d42a-4231-9ec8-bf11069914ba.png'>![Usersnap Feedback - Please block this user who posted spam. I have hidden their entries](https://usersnappublic.s3.amazonaws.com/2020-05-29/15-52/70136ec8-aab7-4fa8-a3db-01869de2d7c1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-29/15-52/8d7fe1c2-d42a-4231-9ec8-bf11069914ba.png'>Download original image</a>

**Browser**: Firefox 76 (Windows 10)
**Referer**: [https://participedia.net/organization/6568](https://participedia.net/organization/6568)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
the user has been blocked. thanks for the heads up.
