### ISSUE TITLE
Usersnap Feedback - Increase the size of this info icon by approx 40% and make it red. It is b[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1065]
**Sender**: jesi.carson@gmail.com
**Comment**: Increase the size of this info icon by approx 40% and make it red. It is being missed by users, and there's important info in there.
[Open #758 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/758)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-29/20-40/a88dc6bb-7f24-4f40-b4ba-89a5aee60a47.png'>![Usersnap Feedback - Increase the size of this info icon by approx 40% and make it red. It is b(...)](https://usersnappublic.s3.amazonaws.com/2020-05-29/20-40/3a788ff0-0129-4c44-8792-f1c6ceea823c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-29/20-40/a88dc6bb-7f24-4f40-b4ba-89a5aee60a47.png'>Download original image</a>

**Browser**: Chrome 83 (Macintosh)
**Referer**: [https://participedia.net/case/5600](https://participedia.net/case/5600)
**Screen size**: 1680 x 1050 **Browser size**: 1394 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott could you make this change while updating the FAQ and modal text? thanks. i'll make an issue for that in API now, as the text has been updated.
