### ISSUE TITLE
Usersnap Feedback - Is it posisble to identify the volume of traffic viewing specific entries [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1066]
**Sender**: rick.davies@gmail.com
**Comment**: Is it posisble to identify the volume of traffic viewing specific entries in Participedia?
[Open #759 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/759)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-31/11-43/6a927408-64b6-4e8e-a6c1-efaa255d649d.png'>![Usersnap Feedback - Is it posisble to identify the volume of traffic viewing specific entries (...)](https://usersnappublic.s3.amazonaws.com/2020-05-31/11-43/370e10d9-61d3-4a69-80c1-9d7ad8b8418c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-31/11-43/6a927408-64b6-4e8e-a6c1-efaa255d649d.png'>Download original image</a>

**Browser**: Chrome 83 (Windows 10)
**Referer**: [https://participedia.net/method/6569](https://participedia.net/method/6569)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 888

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully do you know Rick Davies? Sounds familiar. Let me know if you want me to follow up about this. Short answer - yes we can.

**Comment by jesicarson** [comment]
I'm also closing this since it is not a dev issue, but it will remain in the closed issue archive for reference.

**Comment by plscully** [comment]
I don't know him, but I tracked him down and found his website https://richardjdavies.wordpress.com/ 
When I skimmed the page, I recognized [ParEvo](https://participedia.net/method/6569) as something that had recently been added to PPedia. Here is [his user entry](https://participedia.net/user/418747) ... It looks as though he is very well networked with many solid organizations, so please do our best to answer his question.

**Comment by ascott** [comment]
here are the pageviews for this entry and edit page for the last 30 days 

<img width="1414" alt="Screen Shot 2020-06-05 at 1 34 17 PM" src="https://user-images.githubusercontent.com/130878/83920562-58024000-a731-11ea-8856-b9ab9573f2bf.png">

**Comment by jesicarson** [comment]
Thanks, I'll send this to him, we've been emailing.
