### ISSUE TITLE
Bug? Email from Antonin (he's going to usersnap if it happens again)

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1067]
Something went wrong when I tried to publish a case. I received an error message, and two (incomplete) versions ended up on the website. I hid these two entries:

https://participedia.net/case/6571 
https://participedia.net/case/6572

I tried again and the same mistake occurred. The case narrative this time is good, but I am not able to publish the data section (https://participedia.net/case/6573). I’ll leave this new entry public and try to edit it another time.

**Comment by paninee** [comment]
Should be fixed with https://github.com/participedia/usersnaps/issues/1069.
