### ISSUE TITLE
Usersnap Feedback - Please provide some information regarding what is involved in supporting t[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1068]
**Sender**: robyn@cochraneresearch.com.au
**Comment**: Please provide some information regarding what is involved in supporting the Participedia Project's global mission by becoming a partner. Thank you.
[Open #760 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/760)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-02/03-04/10666e2e-022f-4aee-9aa2-13c17fde6a7e.png'>![Usersnap Feedback - Please provide some information regarding what is involved in supporting t(...)](https://usersnappublic.s3.amazonaws.com/2020-06-02/03-04/2483b419-805f-435b-b0ca-c30dc62a764e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-02/03-04/10666e2e-022f-4aee-9aa2-13c17fde6a7e.png'>Download original image</a>

**Browser**: Chrome 83 (Windows 10)
**Referer**: [https://participedia.net/about](https://participedia.net/about)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 937

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by plscully** [comment]
@jesicarson Please respond to this person. I'm happy to help or to review your draft note, 
Also, do we have a document where we store standard responses to people who send us questions via UserSnap or info@ (other than ones where people are identifying bugs)? If not, can you please start one? It looks like we may be receiving more of these types of inquiries as traffic to our site increases. Thanks!
BTW, I tracked this person down. Looks like she is an independent researcher. See http://www.cochraneresearch.com.au/index.html and https://www.linkedin.com/in/robyncochrane/?originalSubdomain=au

**Comment by jesicarson** [comment]
Hi @plscully - I did make a template reply for usersnaps, but not related to this particular question. I’ll draft something up today and slack you to review.

**Comment by jesicarson** [comment]
Followed up with @plscully by email. Closing this.
