### ISSUE TITLE
Usersnap Feedback - I am trying to enter more data for one of my entries (case 6573), but it d[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1069]
**Sender**: antonin.lwebster@gmail.com
**Comment**: I am trying to enter more data for one of my entries (case 6573), but it doesn't work. I have tried multiple times and I received an error message or it simply won't publish the new information. Thanks!
[Open #761 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/761)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-02/20-07/2ccdfbde-4233-40d1-9d55-b7ce61706b44.png'>![Usersnap Feedback - I am trying to enter more data for one of my entries (case 6573), but it d(...)](https://usersnappublic.s3.amazonaws.com/2020-06-02/20-07/2c758257-4469-4836-850d-a0359fb194a4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-02/20-07/2ccdfbde-4233-40d1-9d55-b7ce61706b44.png'>Download original image</a>

**Browser**: Safari 13 (Macintosh)
**Referer**: [https://participedia.net/case/6573/edit?full=1](https://participedia.net/case/6573/edit?full=1)
**Screen size**: 1440 x 900 **Browser size**: 1250 x 814

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@paninee can you take a look into this issue please?

**Comment by jesicarson** [comment]
see also - #1067

**Comment by jesicarson** [comment]
Antonin is on the participedia team, and he can be reached on slack if need be.

**Comment by paninee** [comment]
I could not reproduce the issue. Reached out to Antonin asking for more info.

**Comment by paninee** [comment]
I think I know what the issue is. The datepicker is not working and probably Antonin enters a date manually. (only in safari) causing the format to be wrong.

**Comment by paninee** [comment]
I added a date validation error message on the date fields. Valid format is `YYYY-MM-DD`.
![image](https://user-images.githubusercontent.com/29439995/84190946-99099580-aa4c-11ea-81bd-acc282312056.png)
