### ISSUE TITLE
Usersnap Feedback - When searching using the search bar query, the all tab doesn't include col[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1070]
**Sender**: alanna.scott@gmail.com
**Comment**: When searching using the search bar query, the all tab doesn't include collections
[Open #762 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/762)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-03/21-31/b06585e3-7da7-47b2-b5f1-fc5b9a054360.png'>![Usersnap Feedback - When searching using the search bar query, the all tab doesn't include col(...)](https://usersnappublic.s3.amazonaws.com/2020-06-03/21-31/dff9404f-da39-4216-9c74-baef8521f799.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-03/21-31/b06585e3-7da7-47b2-b5f1-fc5b9a054360.png'>Download original image</a>

**Browser**: Chrome 81 (macOS Mojave)
**Referer**: [https://participedia.net/?selectedCategory=all&query=LATINNO](https://participedia.net/?selectedCategory=all&query=LATINNO)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
@ascott it does, it's just deep down on the 3rd page.
![image](https://user-images.githubusercontent.com/29439995/85505110-6ca05e00-b5a2-11ea-9554-2718d531b2e2.png)
