### ISSUE TITLE
Usersnap Feedback - photo credit missing on collection landing page header

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1072]
**Sender**: alanna.scott@gmail.com
**Comment**: photo credit missing on collection landing page header
[Open #764 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/764)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-05/22-41/65d5bffa-887b-4f5f-bd40-28eb2be4dcb4.png'>![Usersnap Feedback - photo credit missing on collection landing page header](https://usersnappublic.s3.amazonaws.com/2020-06-05/22-41/73192614-045b-44dd-8704-d5998cc4f3b5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-05/22-41/65d5bffa-887b-4f5f-bd40-28eb2be4dcb4.png'>Download original image</a>

**Browser**: Chrome 81 (macOS Mojave)
**Referer**: [https://participedia.net/collection/6580](https://participedia.net/collection/6580)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott since collections landing pages don't display image credit information, I've added a credit to the short description. we may want to address this going forward.
