### ISSUE TITLE
Usersnap Feedback - Improve search bar functionality. Add `x` icon to righ hand side of search [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1076]
**Sender**: alanna.scott@gmail.com
**Comment**: Improve search bar functionality. Add `x` icon to righ hand side of search input if there is text in the field. When you click on the `x`, clear the field, remove the query param, and reload the page with no search query
[Open #768 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/768)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-11/03-31/b7ca9e6c-2e34-4b82-bd30-9fa31628c5d4.png'>![Usersnap Feedback - Improve search bar functionality. Add `x` icon to righ hand side of search (...)](https://usersnappublic.s3.amazonaws.com/2020-06-11/03-31/a4c9bf5e-6baa-419e-84c5-505c909b50f6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-11/03-31/b7ca9e6c-2e34-4b82-bd30-9fa31628c5d4.png'>Download original image</a>

**Browser**: Chrome 81 (macOS Mojave)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Completed. Deployed on stage and prod.
