### ISSUE TITLE
Usersnap Feedback - cut off graph on research page

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1079]
**Sender**: jesi.carson@gmail.com
**Comment**: cut off graph on research page
[Open #771 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/771)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-11/20-34/433a477b-b452-4c81-9ea3-2a6c74100a0f.png'>![Usersnap Feedback - cut off graph on research page](https://usersnappublic.s3.amazonaws.com/2020-06-11/20-34/762cbd90-56d2-4922-b55d-78f12be417e0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-11/20-34/433a477b-b452-4c81-9ea3-2a6c74100a0f.png'>Download original image</a>

**Browser**: Chrome 83 (Macintosh)
**Referer**: [https://participedia.net/research](https://participedia.net/research)
**Screen size**: 1680 x 1050 **Browser size**: 1355 x 894

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson did you resize your window after the page had loaded? if you reload the page at smaller sizes the graph loads correctly, but if you load the page and then resize, the graph doesn't reload to accommodate the new page width. since it works when the page is reloaded i'd say we can leave this as is.

**Comment by jesicarson** [comment]
sounds good. i probably did resize the page, i do that a lot.
