### ISSUE TITLE
Usersnap Feedback - Entries are repeating - and none of them have a contributor history. Our n[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1081]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: Entries are repeating - and none of them have a contributor history. Our new volunteer, Joyce, is unable to submit and says she's getting an error message when she tries to upload
[Open #773 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/773)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-21/06-30/2c8ae2ca-ac87-42d5-ad60-ba123ef641d9.png'>![Usersnap Feedback - Entries are repeating - and none of them have a contributor history. Our n(...)](https://usersnappublic.s3.amazonaws.com/2020-06-21/06-30/c06d12b2-72f2-478b-bde5-e5992219aae0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-21/06-30/2c8ae2ca-ac87-42d5-ad60-ba123ef641d9.png'>Download original image</a>

**Browser**: Chrome 83 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1368 x 912 **Browser size**: 1710 x 1003

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by plscully** [comment]
I have hidden all the entries that Jaskiran mentioned -- 
(Case) Europe Wide Views on Sustainable Consumption  --  https://participedia.net/case/6602         https://participedia.net/case/6621  https://participedia.net/case/6620 

(Method_ Participatory Modeling  --  https://participedia.net/method/6597    https://participedia.net/method/6598   https://participedia.net/method/6600  https://participedia.net/method/6601

**Comment by jesicarson** [comment]
Thanks for reporting folks. Hopefully @ascott or @paninee can have a look at this today.

**Comment by ascott** [comment]
just saw this happen again for a set of cases with the title `Romanian Council of Students` @paninee could this be related to your recent bug fixes?

https://participedia.net/case/6627
https://participedia.net/case/6659

**Comment by ascott** [comment]
full list of affected entries for `Romanian Council of Students` entries (i've hidden them all know)

https://participedia.net/case/6627
https://participedia.net/case/6659
https://participedia.net/case/6658
https://participedia.net/case/6657
https://participedia.net/case/6656
https://participedia.net/case/6655
https://participedia.net/case/6654
https://participedia.net/case/6653
https://participedia.net/case/6652
https://participedia.net/case/6651
https://participedia.net/case/6650
https://participedia.net/case/6649
https://participedia.net/case/6648
https://participedia.net/case/6647
https://participedia.net/case/6646
https://participedia.net/case/6645
https://participedia.net/case/6644
https://participedia.net/case/6643
https://participedia.net/case/6642
https://participedia.net/case/6641
https://participedia.net/case/6640
https://participedia.net/case/6639
https://participedia.net/case/6638
https://participedia.net/case/6637
https://participedia.net/case/6636
https://participedia.net/case/6635
https://participedia.net/case/6634
https://participedia.net/case/6633
https://participedia.net/case/6632
https://participedia.net/case/6631
https://participedia.net/case/6630
https://participedia.net/case/6629
https://participedia.net/case/6628
https://participedia.net/case/6626
https://participedia.net/case/6625
https://participedia.net/case/6624
https://participedia.net/case/6623


digging in further for one of these entries https://participedia.net/case/6659
- there is only 1 authors record, which is mine when i set it to hidden
<img width="520" alt="Screen Shot 2020-06-23 at 10 58 02 AM" src="https://user-images.githubusercontent.com/130878/85438108-7d1fec80-b540-11ea-95b2-5d299653e633.png">

the entry was added in 2017, and had not other edits until today when i hid it?
<img width="1651" alt="Screen Shot 2020-06-23 at 10 59 00 AM" src="https://user-images.githubusercontent.com/130878/85438284-aa6c9a80-b540-11ea-9a8b-f136991b312a.png">

there are a bunch of versions of entries with this title from 2017, including 6659:
<img width="1645" alt="Screen Shot 2020-06-23 at 11 15 50 AM" src="https://user-images.githubusercontent.com/130878/85440459-f4568000-b542-11ea-8960-0fa02e26d8b7.png">

still not sure what has happened here yet.

**Comment by plscully** [comment]
Another thing that is peculiar is that although the case is highly detailed -- someone did a lot of work writing this case -- none of the data fields have been completed. I also see that the last two footnotes link to one other case  https://participedia.net /method/5450 and one method  https://participedia.net/case/50

**Comment by paninee** [comment]
Fixed and deployed on prod.
