### ISSUE TITLE
Usersnap Feedback - Hi! I'm having trouble when adding citations. It takes a very long time wh[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1082]
**Sender**: inesdemarcos@gmail.com
**Comment**: Hi! I'm having trouble when adding citations. It takes a very long time when I press Publish. When I press refresh I loose al the work.
[Open #774 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/774)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-22/18-33/6b380109-691d-4777-80dd-6696ccfc2674.png'>![Usersnap Feedback - Hi! I'm having trouble when adding citations. It takes a very long time wh(...)](https://usersnappublic.s3.amazonaws.com/2020-06-22/18-33/f11d8fb9-d947-4115-b2be-2081bec4207e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-22/18-33/6b380109-691d-4777-80dd-6696ccfc2674.png'>Download original image</a>

**Browser**: Chrome 83 (macOS High Sierra)
**Referer**: [https://participedia.net/case/5988/edit?full=1](https://participedia.net/case/5988/edit?full=1)
**Screen size**: 1440 x 900 **Browser size**: 1398 x 694

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@paninee this sounds similar to the publishing issue you were dealing with before (with antonin) - could you have a peek at this one? Thanks!

**Comment by jesicarson** [comment]
I emailed Ines (who submitted the usersnap), she has offered some more detail, which I'll forward to @paninee. 
"The content of the case is the same, I was trying to add hyperlinks, external references, two academic papers, and a PPT in the FILES section.
If you could help me with this it would be much appreciated as I've been trying all morning without success."

**Comment by paninee** [comment]
Could be related to https://github.com/participedia/usersnaps/issues/1081. I tried with Ines content and I can save. @jesicarson can you ask her to try again? Now that we've deployed the fix on prod.
