### ISSUE TITLE
Usersnap Feedback - My login with my email (France) and my password with seven lettres and two [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1085]
**Sender**: bill.lowry@wanadoo.fr
**Comment**: My login with my email (France) and my password with seven lettres and two numbers not accepted….?
[Open #777 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/777)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-25/07-32/85b04987-6432-49b5-823b-cf11cc62021e.png'>![Usersnap Feedback - My login with my email (France) and my password with seven lettres and two (...)](https://usersnappublic.s3.amazonaws.com/2020-06-25/07-32/0fa7c75b-61c6-472f-bef7-1e20acd4576f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-25/07-32/85b04987-6432-49b5-823b-cf11cc62021e.png'>Download original image</a>

**Browser**: Edge 18 (Windows 10)
**Referer**: [https://participedia.net/case/4415](https://participedia.net/case/4415)
**Screen size**: 853 x 480 **Browser size**: 709 x 382

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Emailed, but keeping this one open in case there's a login bug. Guessing he either needs to reset his password, or choose a new password that aligns with Auth0 requirements? @ascott do you know what Auth0 requires in terms of a password, or why it wouldn't accept a pw as described in this snap?

**Comment by ascott** [comment]
@jesicarson i just tested this to create an account with a fake `@wanadoo.fr` domain and everything works as expected. there are also no requirements on passwords currently, so you can create an account with any password you like. 

i also took a look and there is no account with the email address in our system. perhaps what is happening is he is trying to log in with the email, when he should be signing up? or he has another account with a different email address? definitely need more info to help further with this one.

**Comment by jesicarson** [comment]
Thanks for checking those things. Ok, let's wait and see what he says. Your guess that he was in the login tab, as opposed to the sign up tab, might be right. Which reminds me it might be nice to have those separated login/sign up buttons on the header :)
