### ISSUE TITLE
Usersnap Feedback - when the language isn't set to English, search produces an error message: [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1086]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: when the language isn't set to English, search produces an error message: {"OK":false,"error":{"name":"error","length":115,"severity":"ERROR","code":"42P01","position":"178","file":"parse_relation.c","line":"1180","routine":"parserOpenTable"}}

I've tried on both a PC & Mac (Google Chrome, Firefox, and Safari)
[Open #778 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/778)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-26/03-25/de6d6676-a6aa-40f4-adf3-868db9e21c5c.png'>![Usersnap Feedback - when the language isn't set to English, search produces an error message: (...)](https://usersnappublic.s3.amazonaws.com/2020-06-26/03-25/069c018b-9355-4005-9b78-3fcde0c5fa2d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-26/03-25/de6d6676-a6aa-40f4-adf3-868db9e21c5c.png'>Download original image</a>

**Browser**: Chrome 83 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1368 x 912 **Browser size**: 1710 x 1003

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Yep I'm seeing this too. @ascott

**Comment by paninee** [comment]
Completed. Deployed on stage and prod.
