### ISSUE TITLE
Usersnap Feedback - Hi Jesi,  I am having trouble finding a case I submitted as hidden. I subm[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1088]
**Sender**: vhurtado@alumni.ubc.ca
**Comment**: Hi Jesi,

I am having trouble finding a case I submitted as hidden. I submitted the case on Friday night, and the name is "Coronavirus (COVID-19): framework for decision making - public engagement exercise". I am thinking it might have not been uploaded in the end, but wanted to check with you before I submitted it again. Thank you!
[Open #780 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/780)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-30/02-47/61912ac2-6d14-4b73-a072-3db1c5716491.png'>![Usersnap Feedback - Hi Jesi,  I am having trouble finding a case I submitted as hidden. I subm(...)](https://usersnappublic.s3.amazonaws.com/2020-06-30/02-47/354a16cf-5e28-4eb0-86da-8f6e00325c11.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-30/02-47/61912ac2-6d14-4b73-a072-3db1c5716491.png'>Download original image</a>

**Browser**: Safari 13 (Macintosh)
**Referer**: [https://participedia.net/case/new#](https://participedia.net/case/new#)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 812

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott can you help with this one? Just need a link to the hidden case from the database, and I can do the emailing. Cheers!

**Comment by ascott** [comment]
@jesicarson https://participedia.net/case/6667
