### ISSUE TITLE
Usersnap Feedback - Has D&T noticed the problem that it is very difficult to clear text from t[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1089]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Has D&T noticed the problem that it is very difficult to clear text from the search bar after your search is done? I still don't know what the trick is to make it disappear. I just now tried deleting it, refreshing, and both of those actions together. Usually I have to close the site and go back to it to clear the search.
[Open #781 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/781)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-30/19-13/c03d6f27-abab-4ae9-99a0-6a8d34046cc4.png'>![Usersnap Feedback - Has D&T noticed the problem that it is very difficult to clear text from t(...)](https://usersnappublic.s3.amazonaws.com/2020-06-30/19-13/b369c3be-a68c-48b6-89ee-067f32be31c3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-30/19-13/c03d6f27-abab-4ae9-99a0-6a8d34046cc4.png'>Download original image</a>

**Browser**: Firefox 77 (Windows 10)
**Referer**: [https://participedia.net/?selectedCategory=method&query=%22Climate+Assembly+UK%22](https://participedia.net/?selectedCategory=method&query=%22Climate+Assembly+UK%22)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
I just tested (on Mac, Chrome) with these results: 
- Deleting the text from the search bar and hitting enter doesn't clear the search (@ascott - should it?) 
- Clicking the participedia logo beside the hamburger menu (the "home" button) successfully clears the search.
- Deleting the text from the search bar and then refreshing the page successfully clears the search. 
- Deleting the **query text** from the URL (https://participedia.net **/?query=covid**) and hitting enter successfully clears the search. 

@plscully - If after trying these things you are unable to clear the search at all, please let us know. Thanks!

**Comment by jesicarson** [comment]
Looks like Pan is working on an additional function to clear searches too https://github.com/participedia/api/pull/937

**Comment by plscully** [comment]
Thanks for checking. I am using Firefox with Windows 10.
-  Deleting the text from the search bar and hitting enter doesn't clear the search (@ascott - should it?)
-     Clicking the participedia logo beside the hamburger menu (the "home" button) successfully clears the search.
YES THIS WORKS FOR ME
-     Deleting the text from the search bar and then refreshing the page successfully clears the search.
I TRIED AGAIN. THE 1ST TIME IT WORKED, BUT IT DIDN'T WORK THE 2ND TIME
-     Deleting the query text from the URL (https://participedia.net /?query=covid) and hitting enter successfully clears the search.
THIS WORKED, BUT IT SEEMS LIKE A LOT TO AS OF A USER

**Comment by jesicarson** [comment]
Thanks Pat. 
Clicking the "home" button is typically the best way to deal with clearing a search anyway, so if that worked for you that's good - it would be a bug if the home button didn't do the trick. The other ways are more like backups that should work if clicking 'home' fails, but we're not necessarily expecting users to know them. 
For further clarity, in addition to the home button option for clearing searches, we're going to add an X to the search bar as well.

**Comment by jesicarson** [comment]
I think we can close this, but feel free to re-open if I've missed anything @ascott. I don't think we're seeing a bug here, except possibly the refresh thing not working every time.

**Comment by ascott** [comment]
@plscully @jesicarson is correct, @paninee is working on a PR to add an `X` icon to the search bar to make this easier for users https://github.com/participedia/api/pull/937
