### ISSUE TITLE
Usersnap Feedback - I'm doing the user test survey right now - one thing I noticed was the nee[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#109]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I'm doing the user test survey right now - one thing I noticed was the need for a clean-up of the Tags (which, I presume, were imported from the existing platform). This is a good example of a tag we don't need. 
[Open #123 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/123)

<a href='https://usersnappublic.s3.amazonaws.com/2017-09-23/22-55/2111bb09-63b3-4877-817c-0c6e1eb89a77.png'>![Usersnap Feedback - I'm doing the user test survey right now - one thing I noticed was the nee(...)](https://usersnappublic.s3.amazonaws.com/2017-09-23/22-55/95c22e19-e778-4cd6-91bb-47e3d27e9e85.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-09-23/22-55/2111bb09-63b3-4877-817c-0c6e1eb89a77.png'>Download original image</a>

**Browser**: Chrome 60 (Windows 10)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 1280 x 720 **Browser size**: 1600 x 677

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by andreadelrio** [comment]
Currently being discussed here: https://github.com/participedia/frontend/issues/445 
Closing to avoid duplication.
