### ISSUE TITLE
Usersnap Feedback - Using the site in French, but most of the entry titles on this search quer[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1090]
**Sender**: jesi.carson@gmail.com
**Comment**: Using the site in French, but most of the entry titles on this search query are in English. Bug?
[Open #782 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/782)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-01/18-25/f8a46758-bce6-4cbc-aa97-05c475714d57.png'>![Usersnap Feedback - Using the site in French, but most of the entry titles on this search quer(...)](https://usersnappublic.s3.amazonaws.com/2020-07-01/18-25/d7884921-3ec2-4a09-915b-bdeb5e8cc95e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-01/18-25/f8a46758-bce6-4cbc-aa97-05c475714d57.png'>Download original image</a>

**Browser**: Chrome 83 (Macintosh)
**Referer**: [https://participedia.net/?query=chat](https://participedia.net/?query=chat)
**Screen size**: 1680 x 1050 **Browser size**: 1414 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Closing in favour of #1091
