### ISSUE TITLE
Usersnap Feedback - Homepage in FR showing all English entry titles.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1091]
**Sender**: jesi.carson@gmail.com
**Comment**: Homepage in FR showing all English entry titles.
[Open #783 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/783)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-01/18-26/b23559f8-f826-4c1e-9295-0daa4d93d593.png'>![Usersnap Feedback - Homepage in FR showing all English entry titles.](https://usersnappublic.s3.amazonaws.com/2020-07-01/18-26/93f62e78-1a9b-4e6c-b5fd-2f6747ee0912.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-01/18-26/b23559f8-f826-4c1e-9295-0daa4d93d593.png'>Download original image</a>

**Browser**: Chrome 83 (Macintosh)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1680 x 1050 **Browser size**: 1414 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Note that when I click on the case, the reader page displays correctly in French. @paninee

**Comment by ascott** [comment]
i'm seeing this too. @paninee could you take a look?

**Comment by paninee** [comment]
@ascott it seems like the issue was from https://github.com/participedia/api/commit/56ecadf5d13e415c826fbd84c2259db93dc1bbe5. the language variable passed to sql queries is hard coded to English.

**Comment by ascott** [comment]
@paninee great, thanks for looking into this. looks like we just need to remove the comment and return 
`return getLanguage(req);` 
rather than the hardcoded value now that we have our translation system in place.

**Comment by paninee** [comment]
Fixed tested on prod.
