### ISSUE TITLE
Usersnap Feedback - Value for the response should read "Not Applicable" instead of "not"

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1093]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Value for the response should read "Not Applicable" instead of "not"
[Open #785 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/785)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-07/02-10/ce2acb98-04a8-4b3a-9af9-8d4dfe83777a.png'>![Usersnap Feedback - Value for the response should read "Not Applicable" instead of "not"](https://usersnappublic.s3.amazonaws.com/2020-07-07/02-10/0d8ce2d8-c684-4041-9c74-57ef25c8ae7d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-07/02-10/ce2acb98-04a8-4b3a-9af9-8d4dfe83777a.png'>Download original image</a>

**Browser**: Firefox 78 (Windows 10)
**Referer**: [https://participedia.net/case/6687](https://participedia.net/case/6687)
**Screen size**: 1920 x 1200 **Browser size**: 1704 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Fixed, tested in https://participedia.net/case/6687.
