### ISSUE TITLE
Usersnap Feedback - I've hidden this spam entry  https://participedia.net/organization/6688

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1094]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I've hidden this spam entry  https://participedia.net/organization/6688
[Open #786 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/786)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-08/17-43/eeb493a8-a04e-470e-b675-cda855d63b4d.png'>![Usersnap Feedback - I've hidden this spam entry  https://participedia.net/organization/6688](https://usersnappublic.s3.amazonaws.com/2020-07-08/17-43/0c70f44b-6ab8-411b-b707-50a328ce82e0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-08/17-43/eeb493a8-a04e-470e-b675-cda855d63b4d.png'>Download original image</a>

**Browser**: Firefox 78 (Windows 10)
**Referer**: [https://participedia.net/organization/6688](https://participedia.net/organization/6688)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott need help with this one - how do I get an email address from a user profile to block on Auth0? This one changed their name I guess, usually it's easy to spot the email associated with the spam account, but this one seems more mysterious :P https://participedia.net/user/418850

**Comment by ascott** [comment]
@jesicarson daviddolezal@evenweb.com

**Comment by jesicarson** [comment]
blocked
