### ISSUE TITLE
Usersnap Feedback - I've hidden this spam case entry   https://participedia.net/case/6689

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1095]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I've hidden this spam case entry   https://participedia.net/case/6689
[Open #787 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/787)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-08/17-45/a80bd540-ffc8-400f-b120-9a169702fa65.png'>![Usersnap Feedback - I've hidden this spam case entry   https://participedia.net/case/6689](https://usersnappublic.s3.amazonaws.com/2020-07-08/17-45/7ac23be7-1ce3-4bd0-820d-cb9975dd5bd1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-08/17-45/a80bd540-ffc8-400f-b120-9a169702fa65.png'>Download original image</a>

**Browser**: Firefox 78 (Windows 10)
**Referer**: [https://participedia.net/case/6689](https://participedia.net/case/6689)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
User blocked on Auth0.
