### ISSUE TITLE
Usersnap Feedback - Map is not populating. This is what appeared when I first opened the site. [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1096]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Map is not populating. This is what appeared when I first opened the site. I am using Windows and this happened with both Google & Firefox
[Open #788 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/788)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-09/16-20/d54b7521-a684-4e16-832d-4f7c7b31f4ae.png'>![Usersnap Feedback - Map is not populating. This is what appeared when I first opened the site. (...)](https://usersnappublic.s3.amazonaws.com/2020-07-09/16-20/3ac770df-0a35-427c-a2e5-13e993e2b95d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-09/16-20/d54b7521-a684-4e16-832d-4f7c7b31f4ae.png'>Download original image</a>

**Browser**: Chrome 83 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1067

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
I can't reproduce this. @plscully is it working now for you?

**Comment by plscully** [comment]
@jesicarson I checked again just now and it's working. Sorry, I don't know why this was happening.

**Comment by jesicarson** [comment]
@plscully no worries. good to report regardless. glad its back online now.
