### ISSUE TITLE
Usersnap Feedback - 2017-09-23 23:14:18

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#110]
**Sender**: scottowenfletcher@gmail.com
[Open #124 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/124)

<a href='https://usersnappublic.s3.amazonaws.com/2017-09-23/23-13/3df5d047-6055-4b05-ab11-3893721ca2de.png'>![Usersnap Feedback - 2017-09-23 23:14:18](https://usersnappublic.s3.amazonaws.com/2017-09-23/23-13/d63f7402-fe78-4440-a0ed-8b9d984e21ea.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-09-23/23-13/3df5d047-6055-4b05-ab11-3893721ca2de.png'>Download original image</a>

**Browser**: Chrome 60 (Windows 10)
**Referer**: [https://participedia.xyz/case/4630](https://participedia.xyz/case/4630)
**Screen size**: 1280 x 720 **Browser size**: 1600 x 737

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by andreadelrio** [comment]
Already filed here: https://github.com/participedia/frontend/issues/633
