### ISSUE TITLE
Usersnap Feedback - Change case (written in Italian) from EN to IT in database + re-run translations

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1100]
**Sender**: jesi.carson@gmail.com
**Comment**: Viewing the site in English, seeing Italian (I think!) for this case. Alex is on the pp team, it’s possible he usually uses the site in English, but entered this in Italian without realizing he needed to change that setting first. Let’s look into this.
[Open #792 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/792)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-17/17-20/ef2872b9-eb58-450f-a882-faa4b5b1537a.png'>![Usersnap Feedback - Viewing the site in English, seeing Italian (I think!) for this case. Alex (...)](https://usersnappublic.s3.amazonaws.com/2020-07-17/17-20/2468ca1f-57bd-49c0-9c86-efe45901946d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-17/17-20/ef2872b9-eb58-450f-a882-faa4b5b1537a.png'>Download original image</a>

**Browser**: Safari 13 (iOS)
**Referer**: [https://participedia.net/case/6739](https://participedia.net/case/6739)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by plscully** [comment]
My guess is that @jesicarson is right about how this happened.  Notice, though, that two days ago Alex added a new case and appears to have switched the setting to Italian before doing so. See https://participedia.net/case/6732 ... Also, shouldn't our settings recognize that the default setting on his system is Italian?

**Comment by plscully** [comment]
I also see that Alex added this companion organization entry, but did so with his setting on Italian  https://participedia.net/organization/6740

**Comment by jesicarson** [comment]
From Slack #code channel: 

plscully  8:52 AM
Looking at this entry https://participedia.net/organization/6740 helped me see that if I open an entry with my language setting on EN and then select the option to see it in its original language, my language setting stays on IT for the rest of my session unless I intentionally change my setting back to EN. Something like this may have happened to Alex. Should we/Is it possible to -- add pop up warnings that remind users that they may want to return to their default language setting?

jesi_carson  8:57 AM
Thanks pat. I was wondering if this may come up. I’ll chat with @ascott about a strategy soon, and meanwhile she or @paninee can change the language setting for this case in the database manually. I’ll also shoot an email to Alex later today, I’ll cc you.

**Comment by paninee** [comment]
Fixed https://participedia.net/case/6739.
