### ISSUE TITLE
Usersnap Feedback - the tagline doesn't show up even if i havent activated the map

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1101]
**Sender**: jesi.carson@gmail.com
**Comment**: the tagline doesn't show up even if i havent activated the map
[Open #793 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/793)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-22/19-49/7567d2f1-b121-4fcf-9479-8d96ee5bd967.png'>![Usersnap Feedback - the tagline doesn't show up even if i havent activated the map](https://usersnappublic.s3.amazonaws.com/2020-07-22/19-49/f178b774-bdca-483a-bd15-be87d75594a7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-22/19-49/7567d2f1-b121-4fcf-9479-8d96ee5bd967.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1680 x 1050 **Browser size**: 1395 x 790

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
If you've clicked on the Activate map link once, we always show the activated map everytime you visit the site after that. If a user is visiting the site for the first time and has never clicked on activate map, they will always see the tagline. A user can see the tagline again by clicking the info icon next to the map legend. We can change this, but this is how we originally designed the functionality.

**Comment by jesicarson** [comment]
OK, I see the logic. I thought it worked differently before the latest map update. At any rate with the redesign on the way, this will be moot soon. Closing.
