### ISSUE TITLE
Usersnap Feedback - Can we allow admins can add entries to hidden collections? This is an edit[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1104]
**Sender**: jesi.carson@gmail.com
**Comment**: Can we allow admins can add entries to hidden collections? This is an editing team request. (they want to populate a collection before making it public)
[Open #796 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/796)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-28/19-29/28021025-c33e-449a-bcc1-485b4f3f9735.png'>![Usersnap Feedback - Can we allow admins can add entries to hidden collections? This is an edit(...)](https://usersnappublic.s3.amazonaws.com/2020-07-28/19-29/51f4536d-6100-4384-965d-0f6154b536b8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-28/19-29/28021025-c33e-449a-bcc1-485b4f3f9735.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/collection/6786](https://participedia.net/collection/6786)
**Screen size**: 1680 x 1050 **Browser size**: 1549 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Completed. Tested to make sure of the following:

- the collections are still hidden from the collection list view page. I tested it by comparing the result from /selectedCategory=collections and from the dropdown selection in create/edit case.
- there's no migration script needed to be run.

![image](https://user-images.githubusercontent.com/29439995/90449372-23e5bc80-e09c-11ea-8c50-a7831f328a58.png)

**Comment by paninee** [comment]
Deployed on stage.

**Comment by jesicarson** [comment]
lucy figured out that this is actually displaying the total number of entries per page in the explanatory text, when we should be calculating the total number in the entire collection. i've started a new issue, for ref:  https://github.com/participedia/usersnaps/issues/1118, so closing this one.

**Comment by paninee** [comment]
Deployed on prod

**Comment by jesicarson** [comment]
@plscully FYI, your team can now add entries to hidden collections.
