### ISSUE TITLE
Usersnap Feedback - This case was entered in french prior to localization. Should be corrected [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1106]
**Sender**: jesi.carson@gmail.com
**Comment**: This case was entered in french prior to localization. Should be corrected in the database, then translated from french to the other languages.
[Open #798 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/798)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-29/23-18/108a46b9-b8da-4b7c-9c58-4bb2534025f3.png'>![Usersnap Feedback - This case was entered in french prior to localization. Should be corrected (...)](https://usersnappublic.s3.amazonaws.com/2020-07-29/23-18/0cbf81ba-8300-455d-8752-405243ef9385.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-29/23-18/108a46b9-b8da-4b7c-9c58-4bb2534025f3.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/case/5015](https://participedia.net/case/5015)
**Screen size**: 1680 x 1050 **Browser size**: 1549 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@paninee - do you think these french ones were overlooked in the spreadsheet when you were doing that manual work? Thanks for reviewing this again.

**Comment by paninee** [comment]
Fixed https://participedia.net/case/5015.
