### ISSUE TITLE
Usersnap Feedback - Same localization issue - originally entered in french prior to localizati[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1107]
**Sender**: jesi.carson@gmail.com
**Comment**: Same localization issue - originally entered in french prior to localization. Needs to be corrected in database, and translated from french to other languages.
[Open #799 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/799)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-29/23-19/96f97739-efeb-4caf-96c0-cdb24f0ba219.png'>![Usersnap Feedback - Same localization issue - originally entered in french prior to localizati(...)](https://usersnappublic.s3.amazonaws.com/2020-07-29/23-19/7e16841e-2d45-495b-9d25-fe2c717d8473.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-29/23-19/96f97739-efeb-4caf-96c0-cdb24f0ba219.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/case/5029](https://participedia.net/case/5029)
**Screen size**: 1680 x 1050 **Browser size**: 1549 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Fixed https://participedia.net/case/5029.
