### ISSUE TITLE
Usersnap Feedback - French issue again.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1108]
**Sender**: jesi.carson@gmail.com
**Comment**: French issue again.
[Open #800 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/800)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-29/23-23/c00728e4-c676-49b8-8935-4fe98e641df1.png'>![Usersnap Feedback - French issue again.](https://usersnappublic.s3.amazonaws.com/2020-07-29/23-23/23408e2f-210e-48f5-ae7d-13779c8a358f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-29/23-23/c00728e4-c676-49b8-8935-4fe98e641df1.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/case/5017](https://participedia.net/case/5017)
**Screen size**: 1680 x 1050 **Browser size**: 1549 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Fixed https://participedia.net/case/5017
