### ISSUE TITLE
Usersnap Feedback - I forgot to mention this in my user survey - when you do the 'quick edit' [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#111]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I forgot to mention this in my user survey - when you do the 'quick edit' the 'button is a red "Save" but when you do a 'full edit' this is the button. I think the red "Save" should be at the end for both (otherwise it implies you're entering a new case which might confuse some authors).
[Open #125 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/125)

<a href='https://usersnappublic.s3.amazonaws.com/2017-09-23/23-14/694c8242-13e5-4b06-92c9-725db0929796.png'>![Usersnap Feedback - I forgot to mention this in my user survey - when you do the 'quick edit' (...)](https://usersnappublic.s3.amazonaws.com/2017-09-23/23-14/b836abe3-c1c0-42dc-82a9-6f1fa2cb63b5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-09-23/23-14/694c8242-13e5-4b06-92c9-725db0929796.png'>Download original image</a>

**Browser**: Chrome 60 (Windows 10)
**Referer**: [https://participedia.xyz/case/4630/edit](https://participedia.xyz/case/4630/edit)
**Screen size**: 1280 x 720 **Browser size**: 1600 x 737

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
closing. buttons need an overhaul. see: https://github.com/participedia/frontend/issues/723
