### ISSUE TITLE
Usersnap Feedback - this English entry isn't translating to any language normally (Letter to a [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1110]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: this English entry isn't translating to any language normally (Letter to a Friend)
[Open #802 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/802)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-05/23-19/45950760-2b1c-4c37-a507-121c3a60ea06.png'>![Usersnap Feedback - this English entry isn't translating to any language normally (Letter to a (...)](https://usersnappublic.s3.amazonaws.com/2020-08-05/23-19/c32401f9-2406-4cd6-9918-7e645b86c57d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-05/23-19/45950760-2b1c-4c37-a507-121c3a60ea06.png'>Download original image</a>

**Browser**: Safari 12 (macOS Mojave)
**Referer**: [https://participedia.net/method/6244](https://participedia.net/method/6244)
**Screen size**: 1440 x 900 **Browser size**: 1324 x 749

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Verified bug. 
I see numbers instead of text for all languages except english in the open text fields.

**Comment by paninee** [comment]
Fixed the data https://participedia.net/method/6244
