### ISSUE TITLE
Usersnap Feedback - same translation issue

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1111]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: same translation issue
[Open #803 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/803)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-05/23-59/8c493024-e77c-43ae-b8c7-389c19cad61b.png'>![Usersnap Feedback - same translation issue](https://usersnappublic.s3.amazonaws.com/2020-08-05/23-59/d88c0052-f868-480d-b37f-7a88f78e9ea1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-05/23-59/8c493024-e77c-43ae-b8c7-389c19cad61b.png'>Download original image</a>

**Browser**: Safari 12 (macOS Mojave)
**Referer**: [https://participedia.net/method/6256](https://participedia.net/method/6256)
**Screen size**: 1440 x 900 **Browser size**: 1324 x 749

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Fixed translation https://participedia.net/method/6256
