### ISSUE TITLE
User feedback: Difficulty figuring out how to add text in the case form

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1114]
this particular user didn't see the full version button, or know what it was.
we might consider adding a full version button on the content chooser page, and adding descriptions of what quick submit means vs full version on our FAQ page.

**Comment by ascott** [comment]
@jesicarson what do you think of using an alert below the quick submit heading like this?

<img width="1440" alt="Screen Shot 2020-08-13 at 6 15 10 PM" src="https://user-images.githubusercontent.com/130878/90202773-7b7de280-dd93-11ea-85c7-ed3cc3059f8e.png">

**Comment by jesicarson** [comment]
Great solution! Let’s launch and test it.

**Comment by ascott** [comment]
@jesicarson this is on prod now

**Comment by jesicarson** [comment]
Can't hurt!
