### ISSUE TITLE
Usersnap Feedback - We still need to update this to "Phrase" with their new url, pretty sure I [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1115]
**Sender**: jesi.carson@gmail.com
**Comment**: We still need to update this to "Phrase" with their new url, pretty sure I made an api issue, will check.
[Open #805 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/805)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-12/19-52/e71bffa6-a4d0-4e28-88d0-8e58aacc338e.png'>![Usersnap Feedback - We still need to update this to "Phrase" with their new url, pretty sure I (...)](https://usersnappublic.s3.amazonaws.com/2020-08-12/19-52/8ac0f757-0d35-4f13-9ed5-f32ac687bc1c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-12/19-52/e71bffa6-a4d0-4e28-88d0-8e58aacc338e.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/about](https://participedia.net/about)
**Screen size**: 1680 x 1050 **Browser size**: 1326 x 865

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
yeah we do https://github.com/participedia/api/issues/947 closing this one
