### ISSUE TITLE
Usersnap Feedback - Search bug for languages other than english

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1116]
**Sender**: jesi.carson@gmail.com
**Comment**: Search bug. Reported by Alex Mengozzi to Jesi by email. Testing now, search works in english, but I got an error message in Italian. 

[Open #806 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/806)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-17/20-54/693dadc7-9315-40fa-85a7-4cc414759610.png'>![Usersnap Feedback - Search bug. Reported by Alex Mengozzi to Jesi by email. Testing now, searc(...)](https://usersnappublic.s3.amazonaws.com/2020-08-17/20-54/87dc4a67-fa30-41cf-8aa4-e5bc7ca3e4f6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-17/20-54/693dadc7-9315-40fa-85a7-4cc414759610.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1680 x 1050 **Browser size**: 1555 x 861

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Italian:
{"OK":false,"error":{"name":"error","length":115,"severity":"ERROR","code":"42P01","position":"175","file":"parse_relation.c","line":"1180","routine":"parserOpenTable"}}

**Comment by jesicarson** [comment]
The X seems to be missing from the search bar UI as well.

**Comment by jesicarson** [comment]
French: 
{"OK":false,"error":{"name":"error","length":115,"severity":"ERROR","code":"42P01","position":"170","file":"parse_relation.c","line":"1180","routine":"parserOpenTable"}}

**Comment by paninee** [comment]
@ascott @jesicarson If we were going to allow the user to search in other languages, it'd be a big change. We don't currently have a Materialized View for other languages other than English. To fix it right, we need to create a new view for each language and re-index, and keep the view refreshed when an article is saved.

Another choice would be to only allow the user to search in English. We can return the articles for other languages according to user's current language but not the search query string itself.


I suggest the first option and re-index all the languages we support. It'd be more user friendly but it'd be a lot more work. What do you think?

**Comment by jesicarson** [comment]
Thanks for this summary Pan. I think we should discuss on Weds. We definitely need a solution that is more user friendly than an error message in all languages other than english.

**Comment by plscully** [comment]
I agree that the optimal approach will be to allow users to search in languages other than English. If you all decide to go that route, please prepare a revised budget for the tech services cost for (1) the initial re-indexing, and (2) total annual costs for all web services.

**Comment by ascott** [comment]
i remember we had an issue related to this in june and i was under the impression that it was fixed, and that search did work in all languages. i agree, search should work in all languages, not just english. let's discuss further wednesday and come up with a plan to resolve.

this is the issue we had in June, and @paninee you reported that it was fixed. any insight on this?
https://github.com/participedia/usersnaps/issues/1086

**Comment by ascott** [comment]
@jesicarson in terms of the `X` in the search box, it only shows up if there is text entered in the search box.

<img width="1440" alt="Screen Shot 2020-08-18 at 2 08 09 PM" src="https://user-images.githubusercontent.com/130878/90565859-640c7400-e15c-11ea-95a5-36f2b77dfacc.png">

<img width="1440" alt="Screen Shot 2020-08-18 at 2 08 27 PM" src="https://user-images.githubusercontent.com/130878/90565871-67076480-e15c-11ea-9d15-cc97d0eabada.png">

**Comment by jesicarson** [comment]
Thanks @ascott !

Re X: Yes, but when I hit the back button after getting the error message, in Italian for example, the x disappears:
![Screen Shot 2020-08-18 at 2 57 41 PM](https://user-images.githubusercontent.com/13560530/90569685-2bbc6400-e163-11ea-9a86-f7d5328a5686.png)

**Comment by ascott** [comment]
ah i see, thanks @jesicarson. i created another issue for that bug. https://github.com/participedia/usersnaps/issues/1120

**Comment by ascott** [comment]
@pan and i discussed this and came up with a couple different ideas for an interim solution while Pan works on the full solution to get keyword search happening in all languages. current ballpark estimate (without researching further) for the full solution is ~20h - 30h.

here are the options for the interim solution: 
- If a user enters a keyword search and they are viewing the site in a language that is not english, send the search query to the english index and if there are no entries return the no entries search page. Also on that page, add text saying that key word search does not work in [French] but they can search if they use english keywords. Time estimate 3-4hrs for pan.
<img width="1113" alt="Screen Shot 2020-08-19 at 2 07 38 PM" src="https://user-images.githubusercontent.com/130878/90689735-5ec72c00-e225-11ea-85fe-838c3c2a2adb.png">



- If a user enters a keyword search and they are viewing the site in a language that is not english, show them a search error page with some text and links to search filter tabs.  Time estimate 1hr ish for alanna.
![Keyword-search-error-page](https://user-images.githubusercontent.com/130878/90689253-9e414880-e224-11ea-8d90-92a20fc8b114.png)
<img width="1440" alt="Screen Shot 2020-08-19 at 2 02 57 PM" src="https://user-images.githubusercontent.com/130878/90689309-b9ac5380-e224-11ea-9d42-6296de70d23b.png">


### TODOs
- [ ] create a new github issue outlining what needs to be done and how long it might take to allow keyword searches in all languages. @pan
- [x] design & implement an interim solution to replace the error message users are currenly seeing @ascott

**Comment by ascott** [comment]
@jesicarson would you weigh in on these two ideas for the interim solutions above?

**Comment by jesicarson** [comment]
This is great thanks! I ran this past Amber also. In the interest of spending Pan's time on the final solution, we agree that launching the error page now is good enough. Then, let's review Pans remaining assigned issues, and especially prioritize any homepage work first. Then after any priority issues are taken care of, Pan can get to work on the proper fix for this.

**Comment by paninee** [comment]
> i remember we had an issue related to this in june and i was under the impression that it was fixed, and that search did work in all languages. i agree, search should work in all languages, not just english. let's discuss further wednesday and come up with a plan to resolve.
> 
> this is the issue we had in June, and @paninee you reported that it was fixed. any insight on this?
> #1086

It was not an actual fix. We defaulted the search to `en` to get rid of the error. Now when I see this issue, I dig further on how the multi-language search work, and realized we never support multi-language search.

**Comment by paninee** [comment]
@ascott I hit a snag. Can't figure out a way for postgres text search feature to support other languages. I'm looking into how to make this work, worst case scenario we may have to migrate to ES or something else for text search. 

Reference: https://www.postgresql.org/docs/9.1/textsearch-controls.html

**Comment by ascott** [comment]
@paninee ok thanks for looking into this. based on what @jesicarson said above, i think we should put a pin in this issue for now in order to prioritise the new homepage/search redesign work. 

i put together a [PR](https://github.com/participedia/api/pull/972) with the interim solution for this issue. once we are done with the new homepage/search work, we can revisit this and finish planning/estimating for this fix.

**Comment by paninee** [comment]
@ascott I created an issue https://github.com/participedia/api/issues/974. Won't' start working on it yet.

**Comment by jesicarson** [comment]
Thanks!!
