### ISSUE TITLE
Usersnap Feedback - This is wrong..

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1117]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: This is wrong..
[Open #807 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/807)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-17/21-19/4a11e343-8cf5-49e2-9494-087878e32bdd.png'>![Usersnap Feedback - This is wrong..](https://usersnappublic.s3.amazonaws.com/2020-08-17/21-19/24abd943-dbc4-4556-a720-e6947bb6bb2c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-17/21-19/4a11e343-8cf5-49e2-9494-087878e32bdd.png'>Download original image</a>

**Browser**: Chrome 84 (Windows 10)
**Referer**: [https://participedia.net/collection/6774?page=3](https://participedia.net/collection/6774?page=3)
**Screen size**: 1366 x 768 **Browser size**: 1242 x 553

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
hmm.. i'm seeing this:
![Screen Shot 2020-08-17 at 12 58 48 PM](https://user-images.githubusercontent.com/13560530/90438900-86818d00-e089-11ea-985d-b4e7cf876b5c.png)

**Comment by jesicarson** [comment]
lucy figured out that this is actually displaying the total number of entries per page in the explanatory text, when we should be calculating the total number in the entire collection. i've started a new issue, for ref: #1118, so closing this one.
