### ISSUE TITLE
Summary text for collections landing page/search results displays incorrect values

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1118]
**Sender**: jesi.carson@gmail.com
**Comment**: We should put the total number of entries in the explanatory text (10+3+7 does not add up to 51) and there shouldnt be 2 separate lines of explanatory text.
[Open #808 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/808)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-18/00-06/4cb6e4f5-583e-4e0a-ac8c-51c4e1210448.png'>![Usersnap Feedback - We should put the total number of entries in the explanatory text (10+3+7 (...)](https://usersnappublic.s3.amazonaws.com/2020-08-18/00-06/4d0dc797-a19a-432c-bd29-b87aeed7ce1a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-18/00-06/4cb6e4f5-583e-4e0a-ac8c-51c4e1210448.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/collection/6774](https://participedia.net/collection/6774)
**Screen size**: 1680 x 1050 **Browser size**: 1549 x 905

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
looks like we were assuming that `results` contains all the results and not just results for the current page when calculating the total entries for each type. `results` is an array of entries, and each entry has a `total` key/value representing total number of entries for the query, but `results` only contains up to 20 entries for the current page. 

https://github.com/participedia/api/blob/master/api/controllers/collection.js#L275
<img width="720" alt="Screen Shot 2020-08-18 at 3 24 21 PM" src="https://user-images.githubusercontent.com/130878/90571607-f7e33d80-e166-11ea-9568-8198da33548d.png">

i think the data we need returned from the `ENTRIES_BY_COLLECTION_ID` query to fix this would be something like: 

```js
results : {
  entries : Array, 
  totalEntries: Number,
  totalCases: Number,
  totalOrganizations: Number,
  totalMethods: Number
}
```

what do you think @paninee?

**Comment by paninee** [comment]
@ascott At the moment we make 1 query to search, and just count them manually. If we were to display the total number of cases, methods and orgs, I think the simplest solution would be to make another query to group and count the total entries.

**Comment by ascott** [comment]
@pan and @ascott discussed in slack: 
> The solution for this is going to take 3-4h to do, so I think the thing to do is to remove the summary text for now and move that work to the new search redesign project, in favor of spending time now on fixing the issue with keyword search in other languages. 

- [ ] remove the summary for now, and add this task to the new search redesign issue. @ascott

**Comment by jesicarson** [comment]
@ascott does the above note affect this> https://github.com/participedia/api/issues/1011 ?

**Comment by ascott** [comment]
@jesicarson yes, this is the same issue. and looks like we meant to fix this as part of the homepage work, but it did not get done.  i will remove this for now, and we have https://github.com/participedia/api/issues/1011 proritized for @paninee to work on next week.
