### ISSUE TITLE
Usersnap Feedback - bug verified - issue with images embedded in narrative

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1127]
**Sender**: jesi.carson@gmail.com
**Comment**: Edge bug verified - images embedded in narrative of case entered in english result in random text being inserted in all other language versions
[Open #816 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/816)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-27/00-41/ccaff78d-d056-4ba3-80b8-6d27dd6fbf26.png'>![Usersnap Feedback - Edge bug verified - images embedded in narrative of case entered in englis(...)](https://usersnappublic.s3.amazonaws.com/2020-08-27/00-41/a68f7d73-79dd-45d3-9217-71d843dea759.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-27/00-41/ccaff78d-d056-4ba3-80b8-6d27dd6fbf26.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/case/6880](https://participedia.net/case/6880)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
related to #1123 
I've hidden this test case

to do:
- [ ] determine order of priority for this fix TBC 

notes:
likely not a lot of images are being embedded in narratives currently, but it's a pretty nasty result if it does happen 

questions:
@ascott could we disable image embedding in the narrative editor fairly easily?

**Comment by jesicarson** [comment]
For now - disable the ability to embed images in narrative (remove image button from editor)

**Comment by ascott** [comment]
queried the db to find out how many entries this is affecting, only 13 entries include an image in the body.

`select DISTINCT thingid from localized_texts where body LIKE '%<img src="data:%'`

```
2197
5106
5209
5569
5993
6041
6071
6145
6180
6585
6869
6880
6907
```

**Comment by jesicarson** [comment]
@ascott thanks, good to have this list. will you still disable the image button in the narrative editor?

**Comment by ascott** [comment]
@jesicarson yes, i'm still going to remove the image button on the editor as well. i will ship that today. meant to get it in on friday, but i wasn't able to get to it.
