### ISSUE TITLE
Usersnap Feedback - Italian org didn't translate to EN (but did translate to all other languages)

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1128]
**Sender**: jesi.carson@gmail.com
**Comment**: Alex M entered this org entry in Italian, while using the site in Italian, and all the translations worked in every language except English - which is showing up in Italian.
[Open #817 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/817)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-27/16-00/6a6f5b48-7b39-4ce6-b47b-2e2b2f32ef50.png'>![Usersnap Feedback - Alex M entered this org entry in Italian, while using the site in Italian, (...)](https://usersnappublic.s3.amazonaws.com/2020-08-27/16-00/4ba0e5ed-40f6-405e-8eda-bfd5b35e7ae2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-27/16-00/6a6f5b48-7b39-4ce6-b47b-2e2b2f32ef50.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/organization/6879](https://participedia.net/organization/6879)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Alex re-entered it, and i've hidden the original. It worked when he re-entered it, so not sure what happened here, but for now no further action is required.

**Comment by ascott** [comment]
@jesicarson the `edge-bug` label is for bugs related to the edge browser. i'm going to remove and add the i18n label.

**Comment by jesicarson** [comment]
haha ok

**Comment by jesicarson** [comment]
This entry must have been entered in Italian while using the site in EN. Closing.
