### ISSUE TITLE
Usersnap Feedback - This entry (hidden) was working correctly, then on a subsequent edit the t[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1130]
**Sender**: jesi.carson@gmail.com
**Comment**: This entry (hidden) was working correctly, then on a subsequent edit the translation stopped working.
[Open #819 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/819)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-28/18-47/c3e6cdef-f17b-4033-9d65-ebe52b0544f7.png'>![Usersnap Feedback - This entry (hidden) was working correctly, then on a subsequent edit the t(...)](https://usersnappublic.s3.amazonaws.com/2020-08-28/18-47/8db67b64-a520-4c15-9dc6-5cc5e41a3af8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-28/18-47/c3e6cdef-f17b-4033-9d65-ebe52b0544f7.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/case/6884](https://participedia.net/case/6884)
**Screen size**: 1920 x 1080 **Browser size**: 1409 x 934

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Likely entered in Italian while using the site in EN
