### ISSUE TITLE
Usersnap Feedback - This link isn't working

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1144]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: This link isn't working
[Open #833 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/833)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-02/09-29/d305b409-be83-4e29-91b0-1082d59b111d.png'>![Usersnap Feedback - This link isn't working](https://usersnappublic.s3.amazonaws.com/2020-09-02/09-29/06e6e328-fc5a-4d1b-9f09-2dd66ca4f594.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-02/09-29/d305b409-be83-4e29-91b0-1082d59b111d.png'>Download original image</a>

**Browser**: Chrome 85 (Windows 10)
**Referer**: [https://participedia.net/research](https://participedia.net/research)
**Screen size**: 1366 x 768 **Browser size**: 1242 x 597

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by drlucyjparry** [comment]
The DOI for this article is behind a paywall and the researchgate free version is request only. This one from Archon's website seems to work: https://static1.squarespace.com/static/5ce018c4d711f30001ff4dab/t/5ce0af6a0f06d30001fcb8f6/1558228842361/FungParticipedia201112.pdf
