### ISSUE TITLE
Usersnap Feedback - Spam - I hid the entry

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1145]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - I hid the entry
[Open #834 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/834)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-03/15-51/6ea31529-9a0a-4408-82c6-67adce37aa59.png'>![Usersnap Feedback - Spam - I hid the entry](https://usersnappublic.s3.amazonaws.com/2020-09-03/15-51/3a2c871d-fe05-41d8-8fad-f36b79503add.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-03/15-51/6ea31529-9a0a-4408-82c6-67adce37aa59.png'>Download original image</a>

**Browser**: Firefox 80 (Windows 10)
**Referer**: [https://participedia.net/case/6909](https://participedia.net/case/6909)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Thanks @plscully. Blocked the user in Auth0.
