### ISSUE TITLE
Usersnap Feedback - homepage staging test - resizing screen makes boxes jump to top of values

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1149]
**Sender**: jesi.carson@gmail.com
**Comment**: homepage staging test - resizing screen makes boxes jump to top of values
[Open #838 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/838)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-04/00-16/3566ba30-2b39-4926-a7af-0ced526131ae.png'>![Usersnap Feedback - homepage staging test - resizing screen makes boxes jump to top of values](https://usersnappublic.s3.amazonaws.com/2020-09-04/00-16/cbde96e3-01dd-4877-9655-9c6fe4968066.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-04/00-16/3566ba30-2b39-4926-a7af-0ced526131ae.png'>Download original image</a>

**Browser**: Chrome 85 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/search](https://participedia-homepage-2020.herokuapp.com/search)
**Screen size**: 1680 x 1050 **Browser size**: 846 x 792

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
covered by https://github.com/participedia/api/issues/967#issuecomment-686792944 closing
