### ISSUE TITLE
Usersnap Feedback - When I'm not logged in, clicking on the bookmark makes an effect but doesn[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#115]
**Sender**: amberfj@gmail.com
**Comment**: When I'm not logged in, clicking on the bookmark makes an effect but doesn't do anything useful like ask me to login to bookmark. Can you do that? --amber
[Open #129 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/129)

<a href='https://usersnappublic.s3.amazonaws.com/2017-10-05/21-16/abc89361-ac52-42ee-bfc1-a68c041cef5f.png'>![Usersnap Feedback - When I'm not logged in, clicking on the bookmark makes an effect but doesn(...)](https://usersnappublic.s3.amazonaws.com/2017-10-05/21-16/5f28ff7f-e9b4-4652-b952-4d302e045829.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-10-05/21-16/abc89361-ac52-42ee-bfc1-a68c041cef5f.png'>Download original image</a>

**Browser**: Chrome 61 (macOS Sierra)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 2560 x 1440 **Browser size**: 2429 x 1253

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Covered here: https://github.com/participedia/frontend/issues/651
