### ISSUE TITLE
Usersnap Feedback - Localization didn't work for this entry

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1151]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Localization didn't work for this entry
[Open #840 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/840)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-04/23-22/884de007-177a-4c07-ab54-cc3070cef024.png'>![Usersnap Feedback - MaGeMaBe1932](https://usersnappublic.s3.amazonaws.com/2020-09-04/23-22/8c1bb831-c0b2-4c8e-9482-aaf5085e2261.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-04/23-22/884de007-177a-4c07-ab54-cc3070cef024.png'>Download original image</a>

**Browser**: Firefox 80 (Windows 10)
**Referer**: [https://participedia.net/case/5762](https://participedia.net/case/5762)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
User entered text remains spanish in all language versions

**Comment by paninee** [comment]
Fixed the data.
