### ISSUE TITLE
Usersnap Feedback - Notice says it was entered in English but it also displays in English for [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1154]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Notice says it was entered in English but it also displays in English for every other supported language
[Open #843 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/843)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-07/16-02/f87e4a13-f791-427b-a079-1d2c20f84cd5.png'>![Usersnap Feedback - Notice says it was entered in English but it also displays in English for (...)](https://usersnappublic.s3.amazonaws.com/2020-09-07/16-02/847caa74-1ed9-4fcf-a010-f4c5d9261689.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-07/16-02/f87e4a13-f791-427b-a079-1d2c20f84cd5.png'>Download original image</a>

**Browser**: Firefox 80 (Windows 10)
**Referer**: [https://participedia.net/case/6573](https://participedia.net/case/6573)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Fixed the translation.
![image](https://user-images.githubusercontent.com/29439995/113196370-4803a180-9218-11eb-8477-42239494a05f.png)
