### ISSUE TITLE
Usersnap Feedback - Do we know why there is a discrepancy in the count of the collection's content?

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1155]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Do we know why there is a discrepancy in the count of the collection's content?
[Open #844 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/844)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-08/00-01/70ce8016-67af-4b91-a895-1d3aa617f59a.png'>![Usersnap Feedback - Do we know why there is a discrepancy in the count of the collection's content?](https://usersnappublic.s3.amazonaws.com/2020-09-08/00-01/17c32506-7248-442a-9e4f-32f7596d4f3b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-08/00-01/70ce8016-67af-4b91-a895-1d3aa617f59a.png'>Download original image</a>

**Browser**: Firefox 80 (Windows 10)
**Referer**: [https://participedia.net/collection/6786?selectedCategory=case](https://participedia.net/collection/6786?selectedCategory=case)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Yes, this is a known issue, with a fix in the queue to be prioritized along with a few other things after the new homepage is released.

**Comment by jesicarson** [comment]
covered by https://github.com/participedia/api/issues/1011
