### ISSUE TITLE
Usersnap Feedback - Hi, I am not able to add the following url (https://letsprepare.monopinion[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1156]
**Sender**: antonin.lwebster@gmail.com
**Comment**: Hi, I am not able to add the following url (https://letsprepare.monopinion.brussels) to a case entry. Thanks.
[Open #845 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/845)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-09/16-19/8ab07869-b012-4953-9a4c-2c12d2d9e786.png'>![Usersnap Feedback - Hi, I am not able to add the following url (https://letsprepare.monopinion(...)](https://usersnappublic.s3.amazonaws.com/2020-09-09/16-19/3e872e1e-98b4-468a-846e-68dc11e1a066.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-09/16-19/8ab07869-b012-4953-9a4c-2c12d2d9e786.png'>Download original image</a>

**Browser**: Safari 13 (Macintosh)
**Referer**: [https://participedia.net/case/6913/edit?full=1](https://participedia.net/case/6913/edit?full=1)
**Screen size**: 1440 x 900 **Browser size**: 1157 x 789

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
@jesicarson URL validation needs fixing. Anything that isn't .com does not seem to work.

**Comment by paninee** [comment]
Fixed. Deployed on stage and prod.
