### ISSUE TITLE
Usersnap Feedback - French entries showing up with EN titles on users profile page.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1157]
**Sender**: jesi.carson@gmail.com
**Comment**: French entries showing up with EN titles on users profile page.
[Open #846 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/846)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-09/20-31/a22335c1-e65a-47f2-b7bf-2a0df5f0f5ff.png'>![Usersnap Feedback - French entries showing up with EN titles on users profile page.](https://usersnappublic.s3.amazonaws.com/2020-09-09/20-31/d4440d92-1520-4d9b-9270-bbd8b8015da4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-09/20-31/a22335c1-e65a-47f2-b7bf-2a0df5f0f5ff.png'>Download original image</a>

**Browser**: Chrome 85 (Macintosh)
**Referer**: [https://participedia.net/user/418343](https://participedia.net/user/418343)
**Screen size**: 1920 x 1080 **Browser size**: 1278 x 846

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/113329546-907f9580-92d2-11eb-8e58-8d0f0f3d45cb.png)

**Comment by paninee** [comment]
tested on stage and prod

![image](https://user-images.githubusercontent.com/29439995/113909657-c6b68c80-978c-11eb-9283-480f040ba00b.png)
