### ISSUE TITLE
Usersnap Feedback - I've hidden these four duplicate entries (https://participedia.net/case/69[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1158]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: I've hidden these four duplicate entries (https://participedia.net/case/6955 - 58) - none have a contributor history, this issue has come up  before
[Open #847 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/847)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-14/03-56/a8767f93-7918-422c-b389-b0d34a0c918b.png'>![Usersnap Feedback - I've hidden these four duplicate entries (https://participedia.net/case/69(...)](https://usersnappublic.s3.amazonaws.com/2020-09-14/03-56/057d6b87-94f2-4e18-b73e-c4bf1a8def01.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-14/03-56/a8767f93-7918-422c-b389-b0d34a0c918b.png'>Download original image</a>

**Browser**: Chrome 85 (Windows 10)
**Referer**: [https://participedia.net/?page=1](https://participedia.net/?page=1)
**Screen size**: 1368 x 912 **Browser size**: 1710 x 1003

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
I see the history here, not sure what's wrong. 
![image](https://user-images.githubusercontent.com/29439995/114761103-ef9eca80-9d14-11eb-9712-c79b8e135ced.png)
