### ISSUE TITLE
Usersnap Feedback - These is bookmarked cases but they do not appear bookmarked (filled in) so [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#116]
**Sender**: amberfj@gmail.com
**Comment**: These is bookmarked cases but they do not appear bookmarked (filled in) so when I click the bookmark icon it turns black, but unexpectedly unbookmarks the content. Please leave the bookmark icon black on the users profile page. --amber
[Open #130 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/130)

<a href='https://usersnappublic.s3.amazonaws.com/2017-10-05/21-24/ced84b82-90c3-4ea9-8dda-177aec33ccb0.png'>![Usersnap Feedback - These is bookmarked cases but they do not appear bookmarked (filled in) so (...)](https://usersnappublic.s3.amazonaws.com/2017-10-05/21-24/b4808933-a171-4add-ae8f-00970f9f483c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-10-05/21-24/ced84b82-90c3-4ea9-8dda-177aec33ccb0.png'>Download original image</a>

**Browser**: Chrome 61 (macOS Sierra)
**Referer**: [https://participedia.xyz/profile](https://participedia.xyz/profile)
**Screen size**: 2560 x 1440 **Browser size**: 2429 x 1253

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Still true as of May 18, 2018
