### ISSUE TITLE
Usersnap Feedback - The person who changed (vandalized?) the title of this method appears to b[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1160]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: The person who changed (vandalized?) the title of this method appears to be a new user. Please look into whether their email address is on any public lists of known spammers. In the meantime, I have changed the entry back to its correct title "New England Town Meeting"
[Open #849 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/849)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-17/15-50/1fdd51f5-14f6-4187-a030-ab98d729176a.png'>![Usersnap Feedback - The person who changed (vandalized?) the title of this method appears to b(...)](https://usersnappublic.s3.amazonaws.com/2020-09-17/15-50/90aed95e-b42d-46f3-a53c-8b77ab2eebaa.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-17/15-50/1fdd51f5-14f6-4187-a030-ab98d729176a.png'>Download original image</a>

**Browser**: Firefox 80 (Windows 10)
**Referer**: [https://participedia.net/method/159](https://participedia.net/method/159)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
I found the user on auth0, so I could block them if needed. it could have been an error. @ascott is there a way to see if they've done anything else on the site? looks like their last login was yesterday so i guess we could check back in a few days and block them if they do anything else?
