### ISSUE TITLE
Usersnap Feedback - Spam - Please block the user. I have hidden these entries  -- Method #s 70[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1161]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block the user. I have hidden these entries  -- Method #s 7012 & 7013 and Orgs #7010 & 7011
[Open #850 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/850)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-24/22-45/51b43452-f48d-45a1-a561-96446b09cc05.png'>![Usersnap Feedback - Spam - Please block the user. I have hidden these entries  -- Method #s 70(...)](https://usersnappublic.s3.amazonaws.com/2020-09-24/22-45/db88d219-f1db-45e5-adaf-869874da93c6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-24/22-45/51b43452-f48d-45a1-a561-96446b09cc05.png'>Download original image</a>

**Browser**: Firefox 81 (Windows 10)
**Referer**: [https://participedia.net/user/419057](https://participedia.net/user/419057)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
user blocked
