### ISSUE TITLE
Usersnap Feedback - Spam - Please block the user. I have hidden this entry  -- Method 7017

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1162]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block the user. I have hidden this entry  -- Method 7017
[Open #851 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/851)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-24/22-50/62988e43-151a-435c-bcac-0590d2a1e36b.png'>![Usersnap Feedback - Spam - Please block the user. I have hidden this entry  -- Method 7017](https://usersnappublic.s3.amazonaws.com/2020-09-24/22-50/a99d1778-89b1-42d0-81ed-cd5e50660765.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-24/22-50/62988e43-151a-435c-bcac-0590d2a1e36b.png'>Download original image</a>

**Browser**: Firefox 81 (Windows 10)
**Referer**: [https://participedia.net/user/419059](https://participedia.net/user/419059)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
user blocked
