### ISSUE TITLE
Usersnap Feedback - Spam - Please block the user. I have hidden these entries  -- Orgs #7014, [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1163]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block the user. I have hidden these entries  -- Orgs #7014, 7015 & 7016
[Open #852 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/852)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-24/22-51/0498b69c-dad2-4950-8469-95fa2066bd27.png'>![Usersnap Feedback - Spam - Please block the user. I have hidden these entries  -- Orgs #7014, (...)](https://usersnappublic.s3.amazonaws.com/2020-09-24/22-51/f4bc7d61-2d7b-4d2f-b174-fb4fd87232b1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-24/22-51/0498b69c-dad2-4950-8469-95fa2066bd27.png'>Download original image</a>

**Browser**: Firefox 81 (Windows 10)
**Referer**: [https://participedia.net/user/419058](https://participedia.net/user/419058)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
user blocked
