### ISSUE TITLE
Usersnap Feedback - Is there a reason methods isn't an option in this dropdown? (Also, it appe[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1164]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: Is there a reason methods isn't an option in this dropdown? (Also, it appears blank when I clicked the feedback button and didn't correct itself until I refreshed the page after)
[Open #853 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/853)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-04/04-10/d65582f4-8983-4b4f-8753-4f39a387d004.png'>![Usersnap Feedback - Is there a reason methods isn't an option in this dropdown? (Also, it appe(...)](https://usersnappublic.s3.amazonaws.com/2020-10-04/04-10/db7bb1a8-bba4-423c-b187-0bac93856b3f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-04/04-10/d65582f4-8983-4b4f-8753-4f39a387d004.png'>Download original image</a>

**Browser**: Safari 12 (macOS Mojave)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/](https://participedia-homepage-2020.herokuapp.com/)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
covered by #1179 , closing
