### ISSUE TITLE
Usersnap Feedback - the title appears twice

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1169]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: the title appears twice
[Open #858 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/858)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-04/04-22/03f9351d-c740-436e-b375-f56e16550cb5.png'>![Usersnap Feedback - the title appears twice](https://usersnappublic.s3.amazonaws.com/2020-10-04/04-22/fa657fe5-2d67-47ef-98b0-be05b9132960.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-04/04-22/03f9351d-c740-436e-b375-f56e16550cb5.png'>Download original image</a>

**Browser**: Safari 12 (macOS Mojave)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/#map](https://participedia-homepage-2020.herokuapp.com/#map)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jgakhal** [comment]
the title I was referring to was the first news entry -- I'm not sure why the image appears differently here
