### ISSUE TITLE
Usersnap Feedback - The content on my profile is missing. I had changed by name to show Jesi C[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#117]
**Sender**: jesi.carson@gmail.com
**Comment**: The content on my profile is missing. I had changed by name to show Jesi Carson (not my email) as well as added a bio. All seems to be missing. 
[Open #131 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/131)

<a href='https://usersnappublic.s3.amazonaws.com/2017-10-25/21-57/8e6bea72-88d0-43a3-a4b8-e197bb5f4704.png'>![Usersnap Feedback - The content on my profile is missing. I had changed by name to show Jesi C(...)](https://usersnappublic.s3.amazonaws.com/2017-10-25/21-57/a689e6f9-2d73-4fa1-ab6e-b0baec0b0dc6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-10-25/21-57/8e6bea72-88d0-43a3-a4b8-e197bb5f4704.png'>Download original image</a>

**Browser**: Chrome 61 (macOS Sierra)
**Referer**: [https://participedia.xyz/profile](https://participedia.xyz/profile)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
I think this was due to a data reset to clear out a pile of cases name Test. Sorry about that. We should be running on live data soon, so no more resets after that.
