### ISSUE TITLE
Usersnap Feedback - Map not loading on case reader.

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#118]
**Sender**: jesi.carson@gmail.com
**Comment**: Map not loading on case reader. 
[Open #132 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/132)

<a href='https://usersnappublic.s3.amazonaws.com/2017-10-25/23-41/c3971319-48f2-41ff-8772-4a76d333464d.png'>![Usersnap Feedback - Map not loading on case reader.](https://usersnappublic.s3.amazonaws.com/2017-10-25/23-41/289c03c3-cf2e-425c-9bdc-8c6fc1264b98.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-10-25/23-41/c3971319-48f2-41ff-8772-4a76d333464d.png'>Download original image</a>

**Browser**: Chrome 61 (macOS Sierra)
**Referer**: [https://participedia.xyz/case/4558](https://participedia.xyz/case/4558)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Covered here: https://github.com/participedia/frontend/issues/317
