### ISSUE TITLE
Usersnap Feedback - This is where I got sent when I selected "institutions" from the homepage [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1180]
**Sender**: jesi.carson@gmail.com
**Comment**: This is where I got sent when I selected "institutions" from the homepage drop down and clicked the search button.
[Open #869 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/869)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-06/01-20/2d6ffcf4-19ac-4341-9fa1-1d92217aee14.png'>![Usersnap Feedback - This is where I got sent when I selected "institutions" from the homepage (...)](https://usersnappublic.s3.amazonaws.com/2020-10-06/01-20/ead4854e-9ec2-4cfa-ada2-90715b49246f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-06/01-20/2d6ffcf4-19ac-4341-9fa1-1d92217aee14.png'>Download original image</a>

**Browser**: Chrome 85 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/search?selectedCategory=institution&query=women](https://participedia-homepage-2020.herokuapp.com/search?selectedCategory=institution&query=women)
**Screen size**: 1920 x 1080 **Browser size**: 1557 x 903

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
reference for https://github.com/participedia/usersnaps/issues/1179 closing
