### ISSUE TITLE
Usersnap Feedback - Link no longer works. Can we upload the document to production so that we [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1191]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Link no longer works. Can we upload the document to production so that we can be sure it is always available?
[Open #880 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/880)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-07/22-27/0cb84d6f-2931-48d1-9a42-31f7e914e6c0.png'>![Usersnap Feedback - Link no longer works. Can we upload the document to production so that we (...)](https://usersnappublic.s3.amazonaws.com/2020-10-07/22-27/0f6999a5-321d-49ce-b8b4-1027664720a1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-07/22-27/0cb84d6f-2931-48d1-9a42-31f7e914e6c0.png'>Download original image</a>

**Browser**: Firefox 81 (Windows 10)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/research](https://participedia-homepage-2020.herokuapp.com/research)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully we can save a PDF on our Google Drive and create a public url for it. do you have access to the document?

**Comment by plscully** [comment]
Here you go 
[Fung and Warren The Participedia Project IPMJ November 2011.pdf](https://github.com/participedia/usersnaps/files/5381506/Fung.and.Warren.The.Participedia.Project.IPMJ.November.2011.pdf)

**Comment by jesicarson** [comment]
@ascott here's a link to the PDF on Participedia's google drive. You can replace the dead link with this: https://drive.google.com/file/d/1D5LGfPzDCUXpZS1R9gpjRw-pmLMld4Lb/view?usp=sharing
