### ISSUE TITLE
Usersnap Feedback - This implies that selecting this results in a search of all featured entri[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1197]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: This implies that selecting this results in a search of all featured entries, but it looks instead as though it simply goes to all entries. ... Also, neither the dots nor arrows work
[Open #886 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/886)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-07/22-40/a75f0b5c-1857-48f6-bd0c-1b3c2edab4c7.png'>![Usersnap Feedback - This implies that selecting this results in a search of all featured entri(...)](https://usersnappublic.s3.amazonaws.com/2020-10-07/22-40/fcfd45c2-e470-4bf7-ae9b-5fd408c85883.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-07/22-40/a75f0b5c-1857-48f6-bd0c-1b3c2edab4c7.png'>Download original image</a>

**Browser**: Firefox 81 (Windows 10)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/](https://participedia-homepage-2020.herokuapp.com/)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott ok I get the feedback in this instance (featured vs all). what about changing this one to "View all entries" even though it's repetitive?
