### ISSUE TITLE
Usersnap Feedback - Don't know if anything can be done about this, but the "link below connect[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1199]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Don't know if anything can be done about this, but the "link below connects to..." text refers to the link in the black box that goes to our jury-rigged Google site for the Covid resources
[Open #888 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/888)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-08/23-03/4f3174b2-a57c-4f09-b2e2-66108d11dfc8.png'>![Usersnap Feedback - Don't know if anything can be done about this, but the "link below connect(...)](https://usersnappublic.s3.amazonaws.com/2020-10-08/23-03/dfc92ef2-7e1d-45ae-a45c-b9c239288511.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-08/23-03/4f3174b2-a57c-4f09-b2e2-66108d11dfc8.png'>Download original image</a>

**Browser**: Firefox 81 (Windows 10)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/#map](https://participedia-homepage-2020.herokuapp.com/#map)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully we can re-write the collection description manually. not a dev issue, but i agree it should be done. if you have any suggestions for the text let me know, or i'll take a crack at it asap.

**Comment by plscully** [comment]
@jesicarson Sorry, I forgot that we can edit that text ourselves. I've taken care of it.
