### ISSUE TITLE
Usersnap Feedback - Would be clear if this said 'view all featured collections' - same for fea[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1206]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: Would be clear if this said 'view all featured collections' - same for featured entries
[Open #895 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/895)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-09/10-51/761947ad-6623-4d7d-94fd-a1981bba9169.png'>![Usersnap Feedback - Would be clear if this said 'view all featured collections' - same for fea(...)](https://usersnappublic.s3.amazonaws.com/2020-10-09/10-51/c18f57a6-8887-468a-acda-e55f0a9edc26.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-09/10-51/761947ad-6623-4d7d-94fd-a1981bba9169.png'>Download original image</a>

**Browser**: Chrome 85 (Windows 10)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/](https://participedia-homepage-2020.herokuapp.com/)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 608

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
D&T discussed and think we can wait on this one to see if we get any further feedback about it. if it ends up really confusing folks we can address it.
