### ISSUE TITLE
Usersnap Feedback - Usability issues on mobile - search links overlapping next section.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1215]
**Sender**: jesi.carson@gmail.com
**Comment**: Usability issues on mobile - search links overlapping next section.
[Open #904 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/904)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-13/18-55/4be9c60d-3cb5-4e68-8e87-7674be7d5505.png'>![Usersnap Feedback - Usability issues on mobile - search links overlapping next section.](https://usersnappublic.s3.amazonaws.com/2020-10-13/18-55/363ae6b8-15ae-4b45-9795-41dbcd9ccf50.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-13/18-55/4be9c60d-3cb5-4e68-8e87-7674be7d5505.png'>Download original image</a>

**Browser**: Safari 13 (iOS)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/](https://participedia-homepage-2020.herokuapp.com/)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott this is crossed off on the master list but doesn't look like its working yet on mobile. one suggestion is to remove the secondary search bar to save space on the hero area on mobile devices, since the search bar in the top nav is more obvious on mobile.... thoughts?

**Comment by ascott** [comment]
@jesicarson i thought i fixed this. i'll take another look. good suggestion on removing the extra search bar.

**Comment by ascott** [comment]
@jesicarson ah i see what happened. i had fixed it but then in doing the new hero changes i broke it. will fix!
