### ISSUE TITLE
Usersnap Feedback - Bug opening hamburger menu on mobile. Menu didn’t open and hamburger icon [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1220]
**Sender**: jesi.carson@gmail.com
**Comment**: Bug opening hamburger menu on mobile. Menu didn’t open and hamburger icon disappeared.
[Open #909 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/909)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-13/19-00/2dc4e5a7-db32-406e-b1dd-1f9f88350293.png'>![Usersnap Feedback - Bug opening hamburger menu on mobile. Menu didn’t open and hamburger icon (...)](https://usersnappublic.s3.amazonaws.com/2020-10-13/19-00/6858f689-8f37-4479-9030-9598e7983417.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-13/19-00/2dc4e5a7-db32-406e-b1dd-1f9f88350293.png'>Download original image</a>

**Browser**: Safari 13 (iOS)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/#](https://participedia-homepage-2020.herokuapp.com/#)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
cant reproduce this so im going to close for now. if it happens again i'll flag it.
