### ISSUE TITLE
Usersnap Feedback - Please block this spammer who vandalized the "front porch democracy" case. [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1225]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Please block this spammer who vandalized the "front porch democracy" case. I also hid these 4 other new "cases" they created - https://participedia.net/case/7118 , https://participedia.net/case/7117 ; https://participedia.net/case/7116 ; https://participedia.net/case/7115
[Open #914 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/914)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-17/16-52/5cd47f28-c02f-4616-a34a-574f32eb25d2.png'>![Usersnap Feedback - Please block this spammer who vandalized the "front porch democracy" case. (...)](https://usersnappublic.s3.amazonaws.com/2020-10-17/16-52/83744b7b-4623-44d8-911a-27be5ef12f74.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-17/16-52/5cd47f28-c02f-4616-a34a-574f32eb25d2.png'>Download original image</a>

**Browser**: Firefox 81 (Windows 10)
**Referer**: [https://participedia.net/user/419201](https://participedia.net/user/419201)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Blocked
