### ISSUE TITLE
Usersnap Feedback - The link which 404s.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1227]
**Sender**: alexandre.enkerli@colabnumerique.com
**Comment**: The link which 404s.
[Open #916 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/916)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-20/22-07/356394db-0c9a-4629-9b4f-a562f9c54ee3.png'>![Usersnap Feedback - The link which 404s.](https://usersnappublic.s3.amazonaws.com/2020-10-20/22-07/7b426f77-c636-41cd-bd9a-5cbc231a0938.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-20/22-07/356394db-0c9a-4629-9b4f-a562f9c54ee3.png'>Download original image</a>

**Browser**: Chrome 86 (Windows 10)
**Referer**: [https://participedia.net/case/6328](https://participedia.net/case/6328)
**Screen size**: 1366 x 768 **Browser size**: 1518 x 641

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
deleted the link + text from all languages for all GOC collection cases.
