### ISSUE TITLE
Usersnap Feedback - 404s (from the .xyz staging)

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1228]
**Sender**: alexandre.enkerli@colabnumerique.com
**Comment**: 404s (from the .xyz staging)
[Open #917 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/917)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-20/22-10/aae41901-7867-4d41-b5b0-51aa290fc488.png'>![Usersnap Feedback - 404s (from the .xyz staging)](https://usersnappublic.s3.amazonaws.com/2020-10-20/22-10/52795a14-57df-4cfe-ac36-19c9b7ff5f2c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-20/22-10/aae41901-7867-4d41-b5b0-51aa290fc488.png'>Download original image</a>

**Browser**: Chrome 86 (Windows 10)
**Referer**: [https://participedia.net/case/4375](https://participedia.net/case/4375)
**Screen size**: 1366 x 768 **Browser size**: 1518 x 641

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
i couldn't reproduce, the xyz link correctly redirected to the .net url for me. however, i updated it in the narrative anyway just to be on the safe side.
