### ISSUE TITLE
Usersnap Feedback - When browsed in French, the link refreshes the same page. (Zaria Channer p[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1229]
**Sender**: alexandre.enkerli@colabnumerique.com
**Comment**: When browsed in French, the link refreshes the same page. (Zaria Channer probably provided the actual French versions for these but the system does as though French versions didn't exist.)
[Open #918 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/918)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-20/22-19/81c5ed51-e264-4219-961e-5299cf987382.png'>![Usersnap Feedback - When browsed in French, the link refreshes the same page. (Zaria Channer p(...)](https://usersnappublic.s3.amazonaws.com/2020-10-20/22-19/d5527e99-c201-47e6-be7e-5f2d71e2e198.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-20/22-19/81c5ed51-e264-4219-961e-5299cf987382.png'>Download original image</a>

**Browser**: Chrome 86 (Windows 10)
**Referer**: [https://participedia.net/case/6328](https://participedia.net/case/6328)
**Screen size**: 1366 x 768 **Browser size**: 1518 x 641

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
i went through and deleted this text for all languages. it was leftover text from pre-localization when we had both english and french versions of the GOC collection entries. closing.
