### ISSUE TITLE
Usersnap Feedback - I will change the title of this entry back to “Fernald Citizens Advisory B[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1233]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I will change the title of this entry back to “Fernald Citizens Advisory Board (FCAB)” and the location to Fernald, OH instead of China,  but please role back to the April 11, 2017 version before the entry was vandalized.  https://participedia.net/organization/4852
[Open #922 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/922)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-22/16-22/756d5113-83da-445a-9a8d-5e0a683e708b.png'>![Usersnap Feedback - I will change the title of this entry back to “Fernald Citizens Advisory B(...)](https://usersnappublic.s3.amazonaws.com/2020-10-22/16-22/4d4c7d8f-9451-4708-93a7-f04e65cf63b8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-22/16-22/756d5113-83da-445a-9a8d-5e0a683e708b.png'>Download original image</a>

**Browser**: Firefox 81 (Windows 10)
**Referer**: [https://participedia.net/organization/4852](https://participedia.net/organization/4852)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by plscully** [comment]
@ascott If you've not already rolled this one back, then let it be. After reviewing it I am pretty sure I fixed the title and one other thing that was wrong. And while I was add it I added a photo and completed a few of the data fields, so I think this one is OK.
