### ISSUE TITLE
Usersnap Feedback - not sure what happened here. the only language that wasn't correctly machi[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1235]
**Sender**: jesi.carson@gmail.com
**Comment**: not sure what happened here. the only language that wasn't correctly machine-translated was portuguese. it is showing english text.
[Open #924 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/924)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-23/21-39/02510a45-2916-49ff-b081-47ba96bdd71a.png'>![Usersnap Feedback - not sure what happened here. the only language that wasn't correctly machi(...)](https://usersnappublic.s3.amazonaws.com/2020-10-23/21-39/6dc843b5-8d40-49c8-8a19-83775ba5d490.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-23/21-39/02510a45-2916-49ff-b081-47ba96bdd71a.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia.net/case/6332](https://participedia.net/case/6332)
**Screen size**: 1920 x 1080 **Browser size**: 1593 x 909

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
i fixed it manually, which took about 25 mins of copy pasting. not ideal, probably wont do that again. lol
