### ISSUE TITLE
Usersnap Feedback - Please fix the image size. In the html add to the "img" element width="num[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1237]
**Sender**: Rand@PeopleCount.org
**Comment**: Please fix the image size. In the html add to the "img" element width="num" (for whatever the desired width is) so the image fills the width- currently it's truncated. If you can't do that, at least tell us what the required size is, or at least the aspect ratio (height/width)
[Open #926 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/926)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-24/20-21/47960817-b784-4b1b-b763-b69d975425dc.png'>![Usersnap Feedback - Please fix the image size. In the html add to the "img" element width="num(...)](https://usersnappublic.s3.amazonaws.com/2020-10-24/20-21/aff8476c-9920-4680-a123-59ef30cc2510.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-24/20-21/47960817-b784-4b1b-b763-b69d975425dc.png'>Download original image</a>

**Browser**: Chrome 86 (macOS High Sierra)
**Referer**: [https://participedia.net/organization/7126](https://participedia.net/organization/7126)
**Screen size**: 2560 x 1440 **Browser size**: 1290 x 766

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
I need to email this user, but I've done a temp fix on the logo image.

**Comment by jesicarson** [comment]
It would be helpful to add suggested image dimensions to the explanatory text in the forms.

**Comment by ascott** [comment]
update image info text to : 

`Upload images here. Supported file types include: jpg, jpeg and png. Max file size is 5MB.
For best results upload an image that is at least 640 pixels wide by 360 pixels high.`
