### ISSUE TITLE
Usersnap Feedback - If the search bar needs to be this short (maybe for mobile?), you could sh[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1239]
**Sender**: jesi.carson@gmail.com
**Comment**: If the search bar needs to be this short (maybe for mobile?), you could shorten the "All" drop down to about 160px wide and make the search bar a bit wider.
[Open #928 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/928)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-26/18-59/8c20c78a-6b63-4866-9adb-76b7b07fda26.png'>![Usersnap Feedback - If the search bar needs to be this short (maybe for mobile?), you could sh(...)](https://usersnappublic.s3.amazonaws.com/2020-10-26/18-59/df3d2c9c-b901-4b64-9c1b-7ec1568c41dc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-26/18-59/8c20c78a-6b63-4866-9adb-76b7b07fda26.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/](https://participedia-homepage-2020.herokuapp.com/)
**Screen size**: 1920 x 1080 **Browser size**: 1534 x 810

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson i revised this styling to make the search input wider on larger screens, and removed it on other screens, depending on the width and height of the device screen. thoughts?

<img width="338" alt="Screen Shot 2020-10-28 at 10 31 18 PM" src="https://user-images.githubusercontent.com/130878/97529739-c6100380-196d-11eb-96ae-f32ae6cf8e81.png">

<img width="385" alt="Screen Shot 2020-10-28 at 10 30 56 PM" src="https://user-images.githubusercontent.com/130878/97529743-c8725d80-196d-11eb-9c3a-0d5e2498cca6.png">

<img width="1440" alt="Screen Shot 2020-10-28 at 10 28 40 PM" src="https://user-images.githubusercontent.com/130878/97529744-c90af400-196d-11eb-8af3-0d64541236f0.png">

<img width="962" alt="Screen Shot 2020-10-28 at 10 32 46 PM" src="https://user-images.githubusercontent.com/130878/97529714-bb556e80-196d-11eb-9f7e-630e50661f90.png">

<img width="773" alt="Screen Shot 2020-10-28 at 10 32 35 PM" src="https://user-images.githubusercontent.com/130878/97529722-bf818c00-196d-11eb-8d46-f2ef193e9607.png">

<img width="321" alt="Screen Shot 2020-10-28 at 10 32 16 PM" src="https://user-images.githubusercontent.com/130878/97529731-c1e3e600-196d-11eb-91cd-86d816d4acb2.png">

<img width="406" alt="Screen Shot 2020-10-28 at 10 31 38 PM" src="https://user-images.githubusercontent.com/130878/97529735-c27c7c80-196d-11eb-8011-6984aaf61717.png">

**Comment by jesicarson** [comment]
looks good.
