### ISSUE TITLE
Usersnap Feedback - The word 'Jury' is underlined (hyperlinked) but when I roll the mouse over [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#124]
**Sender**: scottowenfletcher@gmail.com
**Comment**: The word 'Jury' is underlined (hyperlinked) but when I roll the mouse over it, the entire sentence turns red. 
[Open #138 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/138)

<a href='https://usersnappublic.s3.amazonaws.com/2017-11-16/21-58/30b3919b-cfd3-40d0-9560-588314d78ca7.png'>![Usersnap Feedback - The word 'Jury' is underlined (hyperlinked) but when I roll the mouse over (...)](https://usersnappublic.s3.amazonaws.com/2017-11-16/21-58/85863ca7-8a0d-478f-99ac-c042bfd7a336.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-11-16/21-58/30b3919b-cfd3-40d0-9560-588314d78ca7.png'>Download original image</a>

**Browser**: Chrome 62 (Windows 10)
**Referer**: [https://participedia.xyz/case/4558](https://participedia.xyz/case/4558)
**Screen size**: 1280 x 720 **Browser size**: 1600 x 737

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Fixed this via the case form narrative editor.
