### ISSUE TITLE
Usersnap Feedback - why does it say 1741 cases on the homepage but it says a different total o[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1240]
**Sender**: alanna.scott@gmail.com
**Comment**: why does it say 1741 cases on the homepage but it says a different total on the cases tab on /search?
[Open #929 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/929)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-29/07-45/349f2b98-51c8-4704-930a-4b58bdd095fc.png'>![Usersnap Feedback - why does it say 1741 cases on the homepage but it says a different total o(...)](https://usersnappublic.s3.amazonaws.com/2020-10-29/07-45/5613a0fb-643a-4807-9df7-3aaa26170714.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-29/07-45/349f2b98-51c8-4704-930a-4b58bdd095fc.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/](https://participedia-homepage-2020.herokuapp.com/)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 798

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
<img width="693" alt="Screen Shot 2020-10-28 at 11 45 36 PM" src="https://user-images.githubusercontent.com/130878/97534757-c6ad9780-1977-11eb-9f14-e1e6582fa981.png">
@pan can you please look into this? the total number of cases on the home page and on the cases tab does not match.

**Comment by ascott** [comment]
@pan looks like we should revise this sql to only count entries that are not hidden: https://github.com/participedia/api/blob/bde8bf72b078b8b5a726fe0d85576d89ed65d242/api/controllers/home.js#L61-L61
![Screen Shot 2020-10-29 at 11 10 15 AM](https://user-images.githubusercontent.com/130878/97614573-59c9ea00-19d7-11eb-9c76-3d8b5296bf17.png)

**Comment by ascott** [comment]
@pan could you confirm, does this sql count unique countries only? 
https://github.com/participedia/api/blob/bde8bf72b078b8b5a726fe0d85576d89ed65d242/api/controllers/home.js#L73-L73
![Screen Shot 2020-10-29 at 11 12 38 AM](https://user-images.githubusercontent.com/130878/97614864-b88f6380-19d7-11eb-8fa7-b829cbdb5ce2.png)

**Comment by paninee** [comment]
@ascott I double checked all the counts. They are all should be good now.
