### ISSUE TITLE
Usersnap Feedback - hero slideshow not working on stage

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1241]
**Sender**: jesi.carson@gmail.com
**Comment**: hero slideshow not working on stage
[Open #930 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/930)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-29/17-57/8446e474-55a8-4ea9-868d-26da9645c8b5.png'>![Usersnap Feedback - hero slideshow not working on stage](https://usersnappublic.s3.amazonaws.com/2020-10-29/17-57/bd6e2b08-4420-4927-8c21-c462893f57a0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-29/17-57/8446e474-55a8-4ea9-868d-26da9645c8b5.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/](https://participedia-homepage-2020.herokuapp.com/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson just took a look and this is working for me. does a refresh fix this for you?

**Comment by jesicarson** [comment]
yep it seems fine now. image credit type looks much better!
