### ISSUE TITLE
Usersnap Feedback - We were going to change this to the parent case (https://participedia.net/[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1242]
**Sender**: jesi.carson@gmail.com
**Comment**: We were going to change this to the parent case (https://participedia.net/case/5600) - i believe i noted this in the spreadsheet
[Open #931 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/931)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-29/21-28/24846e11-66e0-4871-9106-8564e0307ec2.png'>![Usersnap Feedback - We were going to change this to the parent case (https://participedia.net/(...)](https://usersnappublic.s3.amazonaws.com/2020-10-29/21-28/94938848-54a9-4548-9dff-d340377a4a05.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-29/21-28/24846e11-66e0-4871-9106-8564e0307ec2.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/#](https://participedia-homepage-2020.herokuapp.com/#)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson ok, i will update this.

**Comment by jesicarson** [comment]
done, thanks.
