### ISSUE TITLE
Usersnap Feedback - make filters checkboxes single column on mobile

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1244]
**Sender**: alanna.scott@gmail.com
**Comment**: make filters checkboxes single column on mobile
[Open #933 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/933)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-29/22-31/a5faa374-8d95-4bef-b55a-9caf5b0659a0.png'>![Usersnap Feedback - make filters checkboxes single column on mobile](https://usersnappublic.s3.amazonaws.com/2020-10-29/22-31/f9417432-d79d-4271-8507-cf22a355559f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-29/22-31/a5faa374-8d95-4bef-b55a-9caf5b0659a0.png'>Download original image</a>

**Browser**: Safari 13 (iOS)
**Referer**: [http://localhost:3001/search?selectedCategory=case&general_issues=arts&scope_of_influence=national](http://localhost:3001/search?selectedCategory=case&general_issues=arts&scope_of_influence=national)
**Screen size**: 375 x 667 **Browser size**: 375 x 667

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@paninee  and this one too :) thanks!

**Comment by jesicarson** [comment]
not yet completed

**Comment by jesicarson** [comment]
@ascott this doesn't have to be P1

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/98685797-accb6780-231c-11eb-8f37-f4ffcc475022.png)

@ascott pushed to `pan-1244`

**Comment by paninee** [comment]
Merged into master. Deployed on stage.
