### ISSUE TITLE
Usersnap Feedback - This will need to be deleted (here and on the help page) when we launch th[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1245]
**Sender**: jesi.carson@gmail.com
**Comment**: This will need to be deleted (here and on the help page) when we launch the new homepage. And we can add a line about search filters to this text also.
[Open #934 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/934)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-30/19-34/d005e571-4646-428f-8068-4bd3460e6d6e.png'>![Usersnap Feedback - This will need to be deleted (here and on the help page) when we launch th(...)](https://usersnappublic.s3.amazonaws.com/2020-10-30/19-34/e25298f8-ec90-4187-bb7c-93d424de7f68.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-30/19-34/d005e571-4646-428f-8068-4bd3460e6d6e.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia.net/#](https://participedia.net/#)
**Screen size**: 1920 x 1080 **Browser size**: 1784 x 978

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
**new text bold**. first paragraph deleted.

How do I search for content?

**Navigate to the [search page](https://participedia.net/search) from the site menu, or** use the search bar at the top of any page to conduct a site-wide keyword search. Once your search results are displayed, you can sort them by content type such as cases, methods, or organizations. **You can further filter results for cases, methods or organizations using the filters button.**

To conduct an advanced **keyword** search, use the following syntax **in the search bar**:

AND: bicycle and rally (this is the default, so the same as bicycle rally) will return items which match both words

OR: bicycle or rally will match items with either or both words

NOT: bicycle not rally will match items which contain bicycle, but only if they do not also contain rally

QUOTES: "womens rights" will return items that have womens followed by rights

PARENTHESES: (bicycle or rally) and (womens rights and UK) will will group logical operations inside the parentheses as a group before applying the operators joining groups

**Comment by ascott** [comment]
@paninee can you work on this one please?

**Comment by jesicarson** [comment]
Not yet completed.

**Comment by ascott** [comment]
@paninee i'll do this one.
