### ISSUE TITLE
Usersnap Feedback - I clicked the bookmark icon on an entry, and it opened up the search filte[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1246]
**Sender**: jesi.carson@gmail.com
**Comment**: I clicked the bookmark icon on an entry, and it opened up the search filters menu. Bug?
[Open #935 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/935)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-30/20-03/139644ae-464c-4691-8739-1c3de9f669f3.png'>![Usersnap Feedback - I clicked the bookmark icon on an entry, and it opened up the search filte(...)](https://usersnappublic.s3.amazonaws.com/2020-10-30/20-03/5abaeda7-1113-407f-a38c-4812858ca599.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-30/20-03/139644ae-464c-4691-8739-1c3de9f669f3.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/search?query=environment&selectedCategory=case&openFilters=1](https://participedia-homepage-2020.herokuapp.com/search?query=environment&selectedCategory=case&openFilters=1)
**Screen size**: 1920 x 1080 **Browser size**: 1280 x 720

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@paninee can you take a look at this one please?

**Comment by jesicarson** [comment]
@ascott i get automatically logged in when i click the bookmark now - doesn't give me the auth0 modal, just logs me in? Then, when I click sign out, I get an error screen:
![Screen Shot 2020-11-05 at 11 13 24 AM](https://user-images.githubusercontent.com/13560530/98285797-edf7fc00-1f57-11eb-9ffc-82db98b54914.png)

**Comment by jesicarson** [comment]
Yes, I can't get the auth0 modal to come up so I can switch accounts. Is there a setting that's making the login automatic?

**Comment by ascott** [comment]
@paninee i'll take a look at this one.

**Comment by ascott** [comment]
i'm not seeing this issue any more. i think it was fixed along with a related bug last week.
