### ISSUE TITLE
Usersnap Feedback - Probably known,but  - Selecting the methods tab doesn't refresh the red pi[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#125]
**Sender**: jesi.carson@gmail.com
**Comment**: Probably known,but  - Selecting the methods tab doesn't refresh the red pins to methods, still shows featured cases as red pins. 

Also, there should be at least one state on the map where someone can select any pin they want (like All, but right now you can only select the featured pins on All)... i'm not sure about not being able to select black pins, at least on the All tab. We should talk about this. 
[Open #139 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/139)

<a href='https://usersnappublic.s3.amazonaws.com/2017-11-21/23-45/557259e2-0c0e-48c3-9342-11a407949800.png'>![Usersnap Feedback - Probably known,but  - Selecting the methods tab doesn't refresh the red pi(...)](https://usersnappublic.s3.amazonaws.com/2017-11-21/23-45/e5ca4910-c837-42ea-8265-da9c7e921f93.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-11-21/23-45/557259e2-0c0e-48c3-9342-11a407949800.png'>Download original image</a>

**Browser**: Chrome 61 (macOS Sierra)
**Referer**: [https://participedia.xyz/methods](https://participedia.xyz/methods)
**Screen size**: 1280 x 800 **Browser size**: 1277 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Covered by https://github.com/participedia/frontend/issues/478 and https://github.com/participedia/frontend/issues/686
