### ISSUE TITLE
Usersnap Feedback - black screen on hero.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1250]
**Sender**: jesi.carson@gmail.com
**Comment**: black screen on hero.
[Open #939 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/939)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-05/18-03/630b500a-0d83-435b-9a03-c37ef162fa7a.png'>![Usersnap Feedback - black screen on hero.](https://usersnappublic.s3.amazonaws.com/2020-11-05/18-03/a4907301-6a8e-48e3-99c2-ba29547f4660.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-05/18-03/630b500a-0d83-435b-9a03-c37ef162fa7a.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/](https://participedia-homepage-2020.herokuapp.com/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson i'm looking into this

**Comment by ascott** [comment]
@jesicarson this should be fixed. let me know if you are still getting it.

**Comment by jesicarson** [comment]
sweet thanks!
