### ISSUE TITLE
Usersnap Feedback - csv download only contains 20 methods, rather than all 100 in this query.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1252]
**Sender**: jesi.carson@gmail.com
**Comment**: csv download only contains 20 methods, rather than all 100 in this query.
[Open #941 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/941)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-05/18-07/131d4007-3b3e-4d8e-a306-215752d289f2.png'>![Usersnap Feedback - csv download only contains 20 methods, rather than all 100 in this query.](https://usersnappublic.s3.amazonaws.com/2020-11-05/18-07/54b94701-03bb-4c31-a850-6b5eadbd2650.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-05/18-07/131d4007-3b3e-4d8e-a306-215752d289f2.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/search?selectedCategory=method&purpose_method=develop](https://participedia-homepage-2020.herokuapp.com/search?selectedCategory=method&purpose_method=develop)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 641

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
for context, i have removed the CSV download button from search until we resolve this bug.

**Comment by paninee** [comment]
Merged into master. Deployed on stage.
