### ISSUE TITLE
Usersnap Feedback - The social share buttons are missing on mobile view on reader pages. There [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1255]
**Sender**: jesi.carson@gmail.com
**Comment**: The social share buttons are missing on mobile view on reader pages. There was a mockup for placement on mobile ages ago... I'll see if I can dig that up.
[Open #944 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/944)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-05/20-10/0b1ecfd5-8311-4481-868f-8555b98cf942.png'>![Usersnap Feedback - The social share buttons are missing on mobile view on reader pages. There (...)](https://usersnappublic.s3.amazonaws.com/2020-11-05/20-10/b9137013-3eca-477d-9caa-349d190e96e0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-05/20-10/0b1ecfd5-8311-4481-868f-8555b98cf942.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/case/6557](https://participedia-homepage-2020.herokuapp.com/case/6557)
**Screen size**: 1680 x 1050 **Browser size**: 1058 x 906

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson how is this?

![Screen Shot 2020-12-04 at 3 08 37 PM](https://user-images.githubusercontent.com/130878/101224511-a8584d00-3643-11eb-85fb-81a4cccfad9e.png)

**Comment by jesicarson** [comment]
perfect thanks!
