### ISSUE TITLE
Usersnap Feedback - Login doesnt bring up the auth0 modal, so i cant switch accounts. also, lo[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1256]
**Sender**: jesi.carson@gmail.com
**Comment**: Login doesnt bring up the auth0 modal, so i cant switch accounts. also, logging out gives an error message.
[Open #945 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/945)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-05/23-54/11119295-46b9-4b57-a6f5-5550bc16044a.png'>![Usersnap Feedback - Login doesnt bring up the auth0 modal, so i cant switch accounts. also, lo(...)](https://usersnappublic.s3.amazonaws.com/2020-11-05/23-54/7c7f5dd6-766e-42c0-a175-4f04c5a5e010.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-05/23-54/11119295-46b9-4b57-a6f5-5550bc16044a.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/](https://participedia-homepage-2020.herokuapp.com/)
**Screen size**: 1680 x 1050 **Browser size**: 1354 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott  i mentioned this problem in an issue that you recently closed (https://github.com/participedia/usersnaps/issues/1246), re-snapping so it has its own issue. This is the screen I get when I try to log out:
![Screen Shot 2020-11-05 at 11 19 04 AM](https://user-images.githubusercontent.com/13560530/98305578-f7dd2780-1f76-11eb-984f-8b7455e35cb5.png)

**Comment by ascott** [comment]
@jesicarson this is only an issue with the homepage-2020 staging site only, so i'm going to leave it for now and we can confirm on staging that logout is working as expected.
