### ISSUE TITLE
Usersnap Feedback - CSV button not visible on cases tab

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1257]
**Sender**: jesi.carson@gmail.com
**Comment**: CSV button not visible on cases tab
[Open #946 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/946)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-06/17-06/d7c3b232-b2f5-42f4-951b-4b112aaaf22e.png'>![Usersnap Feedback - CSV button not visible on cases tab](https://usersnappublic.s3.amazonaws.com/2020-11-06/17-06/f5d4ed14-b60c-48cc-b613-026bbb44a006.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-06/17-06/d7c3b232-b2f5-42f4-951b-4b112aaaf22e.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/search?selectedCategory=case&general_issues=agriculture](https://ppedia-stage.herokuapp.com/search?selectedCategory=case&general_issues=agriculture)
**Screen size**: 1920 x 1080 **Browser size**: 1747 x 871

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
could probably push to prod without this and add later once pan has finished work? but adding p1, because ideally this is launched before we send out a newsletter.

**Comment by ascott** [comment]
@jesicarson i intentionally removed the CSV button since the functionality is not completed yet (ie. only includes results on the 1st page https://github.com/participedia/usersnaps/issues/1252) and thought we can push the rest of the homepage/search work to prod with out this. agreed that ideally we can this fixed before the newsletter goes out. we will have to get an ETA from @pan on fixing the CSV bug. i'm going to make this a p2 for now, so i can track all the p1s for launch to prod.

**Comment by jesicarson** [comment]
Got it, thanks @ascott !
