### ISSUE TITLE
Usersnap Feedback - Selected filter not showing up on the tab or in the modal. I selected and [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1258]
**Sender**: jesi.carson@gmail.com
**Comment**: Selected filter not showing up on the tab or in the modal. I selected and filtered for general issues - agriculture.
[Open #947 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/947)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-06/17-06/b2389831-08fc-4a01-9941-233cd3441720.png'>![Usersnap Feedback - Selected filter not showing up on the tab or in the modal. I selected and (...)](https://usersnappublic.s3.amazonaws.com/2020-11-06/17-06/4e1aee95-565d-4e78-90ae-953263532b79.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-06/17-06/b2389831-08fc-4a01-9941-233cd3441720.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/search?selectedCategory=case&general_issues=agriculture](https://ppedia-stage.herokuapp.com/search?selectedCategory=case&general_issues=agriculture)
**Screen size**: 1920 x 1080 **Browser size**: 1747 x 871

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
tested for methods and orgs as well. selected filters not showing up.
