### ISSUE TITLE
Usersnap Feedback - Hero area image frozen on the map image. I tried clicking the navigation c[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1260]
**Sender**: jesi.carson@gmail.com
**Comment**: Hero area image frozen on the map image. I tried clicking the navigation circle buttons, they change colour but the image doesn't change, it remains on the map.
[Open #949 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/949)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-06/17-15/7642d784-0354-4d5e-aced-421a04123a47.png'>![Usersnap Feedback - Hero area image frozen on the map image. I tried clicking the navigation c(...)](https://usersnappublic.s3.amazonaws.com/2020-11-06/17-15/71a87cab-7964-4445-95c3-84c7cbc72dbe.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-06/17-15/7642d784-0354-4d5e-aced-421a04123a47.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/](https://ppedia-stage.herokuapp.com/)
**Screen size**: 1920 x 1080 **Browser size**: 1747 x 871

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
First refresh reloaded the map but it remained frozen. Second refresh reloaded to another image and it seemed to be working again - I clicked the link to the george floyd case, then the home button, but when the homepage loaded it was on the map slide and frozen again.

**Comment by ascott** [comment]
@jesicarson i haven't been able to reproduce this one on staging or locally. are you still seeing this issue?
