### ISSUE TITLE
Usersnap Feedback - We should un-feature this entry or upload a better image.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1264]
**Sender**: jesi.carson@gmail.com
**Comment**: We should un-feature this entry or upload a better image.
[Open #953 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/953)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-06/17-28/37e462bb-facf-468b-b76b-29731d15e027.png'>![Usersnap Feedback - We should un-feature this entry or upload a better image.](https://usersnappublic.s3.amazonaws.com/2020-11-06/17-28/19d6b8e3-9adb-4b3d-8bd3-05a8814075b0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-06/17-28/37e462bb-facf-468b-b76b-29731d15e027.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/](https://ppedia-stage.herokuapp.com/)
**Screen size**: 1920 x 1080 **Browser size**: 1747 x 871

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson @plscully i could also try and run this image through a process to increase the resolution, or perhaps there is a higher resolution image somewhere we can update the entry with if it should be a feature.

**Comment by plscully** [comment]
@ascott @jesicarson  I turned it off as a featured entry. Six new ones are now live.

**Comment by jesicarson** [comment]
Awesome thanks @plscully !!
