### ISSUE TITLE
Usersnap Feedback - I'm almost certain that all these cases were submitted by Lucy Parry. More[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#127]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I'm almost certain that all these cases were submitted by Lucy Parry. Moreover, I don't see a user named "Ryan Cote" on the pp.net site
[Open #141 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/141)

<a href='https://usersnappublic.s3.amazonaws.com/2017-12-01/01-44/d72fe6c0-1675-4458-a079-ad137d785b4c.png'>![Usersnap Feedback - I'm almost certain that all these cases were submitted by Lucy Parry. More(...)](https://usersnappublic.s3.amazonaws.com/2017-12-01/01-44/4222a4dd-0c18-4c36-8e11-81f84f620b77.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-12-01/01-44/d72fe6c0-1675-4458-a079-ad137d785b4c.png'>Download original image</a>

**Browser**: Chrome 62 (Windows 10)
**Referer**: [https://participedia.xyz/users/134860](https://participedia.xyz/users/134860)
**Screen size**: 1920 x 1200 **Browser size**: 1904 x 1039

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
We are building using faked user data. If I can finish the re-import work we'll have real users again.
