### ISSUE TITLE
Usersnap Feedback - Map not functional on small mobile screen. I can’t get it to zoom out

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1276]
**Sender**: jesi.carson@gmail.com
**Comment**: Map not functional on small mobile screen. I can’t get it to zoom out
[Open #965 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/965)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-11/17-33/fcd60c3d-727a-47d3-b96c-3ac33a3d2824.png'>![Usersnap Feedback - Map not functional on small mobile screen. I can’t get it to zoom out](https://usersnappublic.s3.amazonaws.com/2020-11-11/17-33/2415a1fa-9acb-43e8-a205-1a2cede595d5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-11/17-33/fcd60c3d-727a-47d3-b96c-3ac33a3d2824.png'>Download original image</a>

**Browser**: Safari 13 (iOS)
**Referer**: [https://ppedia-stage.herokuapp.com/](https://ppedia-stage.herokuapp.com/)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson it looks like maybe this is the most you can zoom out? i just tested in chrome and safari and it's working as expected.

**Comment by jesicarson** [comment]
Ya it sort of works. I think we can improve this when we design for integrating the map with search more elegantly. eg: if the map was an actual full page, it would be more like an app interaction on mobile. We can close this for now.
