### ISSUE TITLE
Usersnap Feedback - I think we should adjust the design so that it displays in its largest for[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1277]
**Sender**: jesi.carson@gmail.com
**Comment**: I think we should adjust the design so that it displays in its largest form on 13" laptops. This should still be a desktop experience.
[Open #966 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/966)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-11/17-42/09eddcac-3707-451e-9bbf-45c5dc0d0746.png'>![Usersnap Feedback - I think we should adjust the design so that it displays in its largest for(...)](https://usersnappublic.s3.amazonaws.com/2020-11-11/17-42/eb4459ce-137f-4381-8501-d5bd3060e1aa.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-11/17-42/09eddcac-3707-451e-9bbf-45c5dc0d0746.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/](https://ppedia-stage.herokuapp.com/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
fwiw i have 13" laptop but my resolution is 1440x900 and i get the desktop experience at that size... we can adjust the styles tho to keep the desktop experience for 1280 x 800 as well.

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-12/03-20/1c53b14f-b6fa-4e1d-a89b-6fe0b2c5fd10.png'>![Usersnap Feedback - desktop example](https://usersnappublic.s3.amazonaws.com/2020-11-12/03-20/fac5974f-7b02-4ebb-b051-35f0095638af.jpg)</a>
**Screen size**: 1440 x 900 **Browser size**: 1440 x 798

**Comment by jesicarson** [comment]
I have a mockup for Screen size: 1280 x 720 (uses the 3 columns on the homepage as guides):

![Screen Shot 2020-11-12 at 9 45 05 AM](https://user-images.githubusercontent.com/13560530/98976115-ceb71c80-24cb-11eb-9eaa-7b246b4e0099.png)

**Comment by jesicarson** [comment]
todo add type sizes!

**Comment by jesicarson** [comment]
@ascott type sizes included
![Screen Shot 2020-11-18 at 2 53 27 PM](https://user-images.githubusercontent.com/13560530/99598120-e8fe6800-29ad-11eb-8d5b-56496c873ad9.png)
