### ISSUE TITLE
Usersnap Feedback - Once I've selected a general issue, I can't remove it. I should be able to [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#128]
**Sender**: jesi.carson@gmail.com
**Comment**: Once I've selected a general issue, I can't remove it. I should be able to leave any non-required fields blank if I choose. This includes removing a selection. I expected if I clicked "environment" again once it was selected, it would be removed, OR that there would be some way to remove it. 
[Open #142 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/142)

<a href='https://usersnappublic.s3.amazonaws.com/2017-12-04/21-13/d241d3b6-5020-4295-8789-2df52a5c20c4.png'>![Usersnap Feedback - Once I've selected a general issue, I can't remove it. I should be able to (...)](https://usersnappublic.s3.amazonaws.com/2017-12-04/21-13/9b199673-b47a-4988-8f8b-4de6be3b8dad.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-12-04/21-13/d241d3b6-5020-4295-8789-2df52a5c20c4.png'>Download original image</a>

**Browser**: Chrome 62 (macOS Sierra)
**Referer**: [https://participedia.xyz/case/4568/edit](https://participedia.xyz/case/4568/edit)
**Screen size**: 1280 x 800 **Browser size**: 1277 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Fixed now on staging, will be on .xyz in next release.
