### ISSUE TITLE
Usersnap Feedback - the show results button is hidden on se 2020, we should make the modal ful[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1282]
**Sender**: alanna.scott@gmail.com
**Comment**: the show results button is hidden on se 2020, we should make the modal full screen and ensure, the buttons are not hidden by browser chrome
[Open #971 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/971)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-11/23-55/76c5929a-973d-4f28-9ea9-ea8da2b20869.png'>![Usersnap Feedback - the show results button is hidden on se 2020, we should make the modal ful(...)](https://usersnappublic.s3.amazonaws.com/2020-11-11/23-55/b7590060-001f-40fb-9add-a84dd18a4fcf.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-11/23-55/76c5929a-973d-4f28-9ea9-ea8da2b20869.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [https://ppedia-stage.herokuapp.com/search?selectedCategory=case&openFilters=1](https://ppedia-stage.herokuapp.com/search?selectedCategory=case&openFilters=1)
**Screen size**: 375 x 667 **Browser size**: 375 x 553

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Yep I can’t see the button on my phone either.
