### ISSUE TITLE
hide counts from collections landing for now

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1290]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Is it possible to hide this feature until we are able to fix it so that it provides an accurate count? I think this is happening with every collection.
[Open #979 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/979)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-12/23-21/636f17bd-c8af-4d80-bd9c-e6824fe72322.png'>![Usersnap Feedback - Is it possible to hide this feature until we are able to fix it so that it (...)](https://usersnappublic.s3.amazonaws.com/2020-11-12/23-21/cef64299-e6d4-4dee-94a8-83222efb539c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-12/23-21/636f17bd-c8af-4d80-bd9c-e6824fe72322.png'>Download original image</a>

**Browser**: Firefox 82 (Windows 10)
**Referer**: [https://participedia.net/collection/6497](https://participedia.net/collection/6497)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott do you think @paninee can have a look at this?

**Comment by ascott** [comment]
@jesicarson i have assigned to @paninee

**Comment by jesicarson** [comment]
Thanks! Small note - Unless doing so is very simple and doesn't add hours to the project, I don't think we need to hide the results text until this is fixed, as long as it can be fixed fairly soon.

**Comment by ascott** [comment]
@jesicarson @paninee  is out for the next week i think so would you prefer remove this now or wait a couple weeks to fix it?

**Comment by jesicarson** [comment]
@ascott if easy/quick then Yes please remove. Otherwise we can wait for pan.

**Comment by ascott** [comment]
@jesicarson yeah, it's quick to remove it
