### ISSUE TITLE
Usersnap Feedback - Is it possible without too much work to increase the size of the slide sho[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1294]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Is it possible without too much work to increase the size of the slide show to 6 entries? This would allow us to always feature one case from each of the 6 inhabited continents
[Open #983 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/983)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-16/15-27/a6309c02-27e8-495f-bacd-9eee8a672a56.png'>![Usersnap Feedback - Is it possible without too much work to increase the size of the slide sho(...)](https://usersnappublic.s3.amazonaws.com/2020-11-16/15-27/570d9b7a-b181-42bf-8c76-fd2fae19c2b4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-16/15-27/a6309c02-27e8-495f-bacd-9eee8a672a56.png'>Download original image</a>

**Browser**: Firefox 82 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully are there 6 entries flagged as featured currently? Alanna did say that the slideshow would accommodate 6 featured entries no problem, but it may be that @ascott needs to make an adjustment to display more than 3 on the homepage.

**Comment by jesicarson** [comment]
Confirmed there are 6 entries flagged as featured, but only 3 showing up on the slideshow.

**Comment by ascott** [comment]
@jesicarson i'll take a look into this

**Comment by ascott** [comment]
@jesicarson @plscully this is fixed now, although the fix could be improved. currently we pull featured collections, cases, methods, and orgs with the same query and then filter them to show on the homepage. i've updated the code to pull 10 entries, since we have 4 featured collections, the remaining 6 are featured cases/methods/orgs. this can be improved in the future to have more control over the number of featured collections separate from featured cases/methods/orgs, but it's working for now.

**Comment by plscully** [comment]
@ascott Thank you!
