### ISSUE TITLE
Usersnap Feedback - use different image for this feature so it looks better on home page

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1295]
**Sender**: alanna.scott@gmail.com
**Comment**: use different image for this feature so it looks better on home page
[Open #984 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/984)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-17/20-58/db761bc1-b353-47ff-8bf9-a17e888bd1e4.png'>![Usersnap Feedback - use different image for this feature so it looks better on home page](https://usersnappublic.s3.amazonaws.com/2020-11-17/20-58/a8d74328-af61-46dd-a541-ae95a7b8278d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-17/20-58/db761bc1-b353-47ff-8bf9-a17e888bd1e4.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 798

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson @plscully is there another image to use for this feature ?

**Comment by plscully** [comment]
The same image is also used in case https://participedia.net/case/6671 as well as in this one https://participedia.net/case/6080 , so please change it in both places if we find a new one.  I the image was taken from the project website https://www.climateassembly.uk .  This page on the site includes several version of a final report, so maybe it will have an imagetg that works. If possible, I like using their graphics so that we don't simply have another image of people in a room talking
https://www.climateassembly.uk/report/#

**Comment by plscully** [comment]
Here's Google images search for "UK Climate Assembly" that https://www.google.com/search?q=UK+climate+assembly&client=firefox-b-1-d&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiTw8eAs4rtAhU9B50JHXeICoEQ_AUoA3oECAoQBQ&biw=1920&bih=1045#imgrc=doyff8l67NvNUM 
This page also has a few that might work  _ https://www.google.com/imgres?imgurl=https%3A%2F%2Fvoiceforarran.com%2Fvoiceforarran%2Fwp-content%2Fuploads%2FClimate-assembly.jpg&imgrefurl=https%3A%2F%2Fvoiceforarran.com%2Fissue-107%2Fwhat-is-the-citizens-climate-assembly-uk%2F&tbnid=jMteZf9IyuLmBM&vet=12ahUKEwjpzauCs4rtAhU0oOAKHbYsA0IQMygCegUIARCRAQ..i&docid=XDt5kctRqcZGPM&w=329&h=230&q=UK%20climate%20assembly&client=firefox-b-1-d&ved=2ahUKEwjpzauCs4rtAhU0oOAKHbYsA0IQMygCegUIARCRAQ

**Comment by jesicarson** [comment]
added images from the report, though sorry to say they're pretty much all people talking in a room! i picked one with some post it notes in it for the feature :)
