### ISSUE TITLE
Usersnap Feedback - when search filters accordion is open, show all text should say show less.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1298]
**Sender**: alanna.scott@gmail.com
**Comment**: when search filters accordion is open, show all text should say show less.
[Open #987 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/987)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-18/23-04/c76bbe88-702e-4152-bb5d-dbb767b0ca77.png'>![Usersnap Feedback - when search filters accordion is open, show all text should say show less.](https://usersnappublic.s3.amazonaws.com/2020-11-18/23-04/954f287a-4e1c-4d0d-ac0d-0e46afe0f097.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-18/23-04/c76bbe88-702e-4152-bb5d-dbb767b0ca77.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia.net/search?selectedCategory=case&openFilters=1](https://participedia.net/search?selectedCategory=case&openFilters=1)
**Screen size**: 1920 x 1080 **Browser size**: 1510 x 811

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Fixed, and live on prod.
![image](https://user-images.githubusercontent.com/29439995/102022006-c9eac000-3d38-11eb-8354-bda709b4ed1a.png)
