### ISSUE TITLE
Usersnap Feedback - Clarify if red map pins are search results AND / OR featured items

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#130]
**Sender**: jesi.carson@gmail.com
**Comment**: Did a text search for "children" and when clicking most red pins, the red text in the popup box said "This matched your search" which I'd expect. However when I clicked this particular pin shown in the screenshot, it says "This is a featured item." I'm not sure what this means... are featured items still shown in red even when a text search is conducted? I don't think any red pins should show unless they match the search term. Also if it is featured, it should say FEATURED CASE above the title of the case. 
[Open #144 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/144)

<a href='https://usersnappublic.s3.amazonaws.com/2018-01-14/20-04/2d2096b2-9b59-4677-9465-221333051065.png'>![Usersnap Feedback - Did a text search for "children" and when clicking most red pins, the red (...)](https://usersnappublic.s3.amazonaws.com/2018-01-14/20-04/257806b0-1e74-49c3-bd7a-b94c0d36d826.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-01-14/20-04/2d2096b2-9b59-4677-9465-221333051065.png'>Download original image</a>

**Browser**: Chrome 63 (Macintosh)
**Referer**: [https://participedia.xyz/?query=children](https://participedia.xyz/?query=children)
**Screen size**: 1280 x 800 **Browser size**: 1277 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Also the feedback button screenshot looks nothing like my actual screen... here's a proper screenshot:

![screen shot 2018-01-14 at 11 09 07 am](https://user-images.githubusercontent.com/13560530/34919600-8373736a-f91b-11e7-9d8b-034e7cd89ac2.png)

This might become a problem with user testing if people use the feedback button. 

Also the new map popups look great!! woot woot!

**Comment by jesicarson** [comment]
I guess my main question is: After conducting a search, are the featured items on the map ALSO results of the search that just happen to be featured? If so they should say "This matched your search" not "This is a featured item" and say "FEATURED CASE" above the title. 

![screen shot 2018-06-19 at 10 54 28 am](https://user-images.githubusercontent.com/13560530/41615292-b2c2a262-73af-11e8-8713-05cef153073b.png)
