### ISSUE TITLE
Usersnap Feedback - Today I added this case as a feature but it is displaying the image from a [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1300]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Today I added this case as a feature but it is displaying the image from a different case that is also featured. Before doing this, I turned the 'featured' tag off for https://participedia.net/case/6044
[Open #988 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/988)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-24/16-18/831202ee-af48-406b-b452-36d5607a3eed.png'>![Usersnap Feedback - Today I added this case as a feature but it is displaying the image from a (...)](https://usersnappublic.s3.amazonaws.com/2020-11-24/16-18/1fe3e8b7-40e4-4ed7-9081-5fe2afed8070.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-24/16-18/831202ee-af48-406b-b452-36d5607a3eed.png'>Download original image</a>

**Browser**: Firefox 83 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Also, why is the title in french, but description text in English?
