### ISSUE TITLE
Usersnap Feedback - This is not tagged as "featured" but it shows up here. Please fix this as [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1302]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: This is not tagged as "featured" but it shows up here. Please fix this as soon as possible as it is only a stub.
[Open #990 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/990)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-26/01-09/a2cb063f-f012-467d-8a4a-897ec6da0b98.png'>![Usersnap Feedback - This is not tagged as "featured" but it shows up here. Please fix this as (...)](https://usersnappublic.s3.amazonaws.com/2020-11-26/01-09/88e62044-2043-40f2-b2d1-feef8d1a03fa.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-26/01-09/a2cb063f-f012-467d-8a4a-897ec6da0b98.png'>Download original image</a>

**Browser**: Firefox 83 (Windows 10)
**Referer**: [https://participedia.net/#map](https://participedia.net/#map)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott looks like it's ongoing after all. added this to the top of your priorities for this week on the project page thx
