### ISSUE TITLE
Usersnap Feedback - Something happened so that only featured entries appear. This is happening [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1304]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Something happened so that only featured entries appear. This is happening for all entry types.
[Open #992 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/992)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-26/15-09/50ecde1b-7bd4-4057-b802-70c8b193c450.png'>![Usersnap Feedback - Something happened so that only featured entries appear. This is happening (...)](https://usersnappublic.s3.amazonaws.com/2020-11-26/15-09/283bc54e-5ee6-401b-989c-aa3443407a6b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-26/15-09/50ecde1b-7bd4-4057-b802-70c8b193c450.png'>Download original image</a>

**Browser**: Firefox 83 (Windows 10)
**Referer**: [https://participedia.net/search?selectedCategory=case](https://participedia.net/search?selectedCategory=case)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott can you have a look at this today if possible? Thanks.

**Comment by ascott** [comment]
@jesicarson yes, i will fix this this asap this morning.

**Comment by ascott** [comment]
this is fixed and on prod now
