### ISSUE TITLE
Usersnap Feedback - Boa Tarde! Inseri um "caso" no dia 24/11/2020 e ele não está aparecendo no [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1306]
**Sender**: etzelbarddal@gmail.com
**Comment**: Boa Tarde! Inseri um "caso" no dia 24/11/2020 e ele não está aparecendo no mapa nem nas buscas (inglês e português). Trata-se do "Conselho Municipal de Esportes de Curitiba". O que está faltando eu fazer para que o caso seja inserido na plataforma? Atenciosamente, Fabiana Barddal.
[Open #994 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/994)

<a href='https://usersnappublic.s3.amazonaws.com/2020-12-01/21-05/ef47605a-3935-4643-b2a4-ada4478e65a9.png'>![Usersnap Feedback - Boa Tarde! Inseri um "caso" no dia 24/11/2020 e ele não está aparecendo no (...)](https://usersnappublic.s3.amazonaws.com/2020-12-01/21-05/ea1460fe-0a9d-48c2-a02e-bf72c9e1fa9b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-12-01/21-05/ef47605a-3935-4643-b2a4-ada4478e65a9.png'>Download original image</a>

**Browser**: Chrome 87 (Windows 7)
**Referer**: [https://participedia.net/case/7161#](https://participedia.net/case/7161#)
**Screen size**: 1093 x 615 **Browser size**: 1094 x 474

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
translated: " Good afternoon! I inserted a "case" on 11/24/2020 and it is not appearing on the map or in searches (English and Portuguese). This is the "Municipal Sports Council of Curitiba". What am I missing to do so that the case is inserted in the platform? Sincerely, Fabiana Barddal."

**Comment by jesicarson** [comment]
i figured out why this is happening. 1 - published in portuguese so search won't work (we don't support fulltext search in languages other than english). 2 - it probably does show up on the map, but there are 3 other cases with Curtiba, Brazil as the location, therefore the pins stack on top of each other and only the top pin is displayed on click (known issue.)

also, the user emailed the info@participedia account, so I'll give her an update on why this is happening. 

there's not much @paninee can do here for the moment.

**Comment by jesicarson** [comment]
i guess we should close this, since these are both known issues and covered by other issues. i'll make sure the map thing is listed on our priorities list.
