### ISSUE TITLE
Usersnap Feedback - Fix login button design (rounded corners)

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#131]
**Sender**: jesi.carson@gmail.com
**Comment**: Login button corners look strange - like the grey button has rounded corners, but there's a white box around it so it has little pointy white corners. 
[Open #145 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/145)

<a href='https://usersnappublic.s3.amazonaws.com/2018-01-14/20-08/d6ff9263-c7b7-4a5f-97f7-e9616532af27.png'>![Usersnap Feedback - Login button corners look strange - like the grey button has rounded corne(...)](https://usersnappublic.s3.amazonaws.com/2018-01-14/20-08/213ed50f-5948-4c9e-a49e-735aa4532e42.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-01-14/20-08/d6ff9263-c7b7-4a5f-97f7-e9616532af27.png'>Download original image</a>

**Browser**: Chrome 63 (Macintosh)
**Referer**: [https://participedia.xyz/?query=children](https://participedia.xyz/?query=children)
**Screen size**: 1280 x 800 **Browser size**: 1277 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Again, the screenshot function on usersnap isn't working. I highlighted the login button for this feedback, but it didnt work.

Here it is: 
![screen shot 2018-01-14 at 11 12 32 am](https://user-images.githubusercontent.com/13560530/34919621-da05757a-f91b-11e7-8801-a2067bfd000b.png)
