### ISSUE TITLE
Usersnap Feedback - Please block this spammer. I have hidden the case.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1314]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Please block this spammer. I have hidden the case.
[Open #1002 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1002)

<a href='https://usersnappublic.s3.amazonaws.com/2020-12-05/16-12/a988c0d6-2340-41fb-af22-1b5601308507.png'>![Usersnap Feedback - Please block this spammer. I have hidden the case.](https://usersnappublic.s3.amazonaws.com/2020-12-05/16-12/9dfbeee0-a589-494f-b04b-8881905af220.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-12-05/16-12/a988c0d6-2340-41fb-af22-1b5601308507.png'>Download original image</a>

**Browser**: Firefox 83 (Windows 10)
**Referer**: [https://participedia.net/user/419529](https://participedia.net/user/419529)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
blocked
