### ISSUE TITLE
Usersnap Feedback - Spam. I have hidden their one entry

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1315]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam. I have hidden their one entry
[Open #1003 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1003)

<a href='https://usersnappublic.s3.amazonaws.com/2020-12-09/15-05/adc94086-bbe9-4e10-8cce-955809f2aa27.png'>![Usersnap Feedback - Spam. I have hidden their one entry](https://usersnappublic.s3.amazonaws.com/2020-12-09/15-05/a1cf2b9c-bb17-40e3-b848-5e69c6a1cf71.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-12-09/15-05/adc94086-bbe9-4e10-8cce-955809f2aa27.png'>Download original image</a>

**Browser**: Firefox 83 (Windows 10)
**Referer**: [https://participedia.net/user/419549](https://participedia.net/user/419549)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
blocked
