### ISSUE TITLE
Usersnap Feedback - hi there! thanks for this portal, we are contributing information on free [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1316]
**Sender**: foundation@dyne.org
**Comment**: hi there! thanks for this portal, we are contributing information on free and open source community projects we've been involved in the past 20 years, hoping its contextual to your effort. Please do not hesitate to reach out for enquiries, thanks!
[Open #1004 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1004)

<a href='https://usersnappublic.s3.amazonaws.com/2020-12-10/13-55/c3e1cf7b-a2f6-4658-bdaa-ddc9dadb5f92.png'>![Usersnap Feedback - hi there! thanks for this portal, we are contributing information on free (...)](https://usersnappublic.s3.amazonaws.com/2020-12-10/13-55/45384782-401d-4ed2-8e86-789b6109af5b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-12-10/13-55/c3e1cf7b-a2f6-4658-bdaa-ddc9dadb5f92.png'>Download original image</a>

**Browser**: Chrome 83 (Linux)
**Referer**: [https://participedia.net/organization/7177](https://participedia.net/organization/7177)
**Screen size**: 3840 x 2160 **Browser size**: 1881 x 2044

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully I'll send these folks our guidelines. Looks like they contribute to participatory software projects, including a project we referenced in the latest D&T Paper on feminist HCI (commonfare.net), so I'm interested to see what they end up posting.
