### ISSUE TITLE
Usersnap Feedback - It would be good if we can come up with away to include a language selecto[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1317]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: It would be good if we can come up with away to include a language selector at the top of the page for mobile devices. (In addition to the one at the very end.) This screenshot is of an iPhone 6s
[Open #1005 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1005)

<a href='https://usersnappublic.s3.amazonaws.com/2020-12-16/15-26/010b283c-e4cb-45af-8efa-42ea953e2a2e.png'>![Usersnap Feedback - It would be good if we can come up with away to include a language selecto(...)](https://usersnappublic.s3.amazonaws.com/2020-12-16/15-26/0e7d3957-ffca-4a23-9752-f9165079f66b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-12-16/15-26/010b283c-e4cb-45af-8efa-42ea953e2a2e.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 320 x 568 **Browser size**: 320 x 449

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
done
