### ISSUE TITLE
Usersnap Feedback - Spam - please block this user. I have hidden their one case entry

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1318]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - please block this user. I have hidden their one case entry
[Open #1006 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1006)

<a href='https://usersnappublic.s3.amazonaws.com/2020-12-16/15-45/5ffa5f87-e5ae-4c13-8136-2c7055df917d.png'>![Usersnap Feedback - Spam - please block this user. I have hidden their one case entry](https://usersnappublic.s3.amazonaws.com/2020-12-16/15-45/867d7bcb-cbe2-49bd-8894-a1d4b30125ae.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-12-16/15-45/5ffa5f87-e5ae-4c13-8136-2c7055df917d.png'>Download original image</a>

**Browser**: Firefox 83 (Windows 10)
**Referer**: [https://participedia.net/user/419625](https://participedia.net/user/419625)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
blocked
