### ISSUE TITLE
Usersnap Feedback - Spam - please block this user

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1320]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - please block this user
[Open #1008 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1008)

<a href='https://usersnappublic.s3.amazonaws.com/2020-12-26/17-10/2c5c5de5-778f-47d4-8d52-9c04462089d0.png'>![Usersnap Feedback - Spam - please block this user](https://usersnappublic.s3.amazonaws.com/2020-12-26/17-10/2b1ae928-e705-4801-960e-97705999ad72.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-12-26/17-10/2c5c5de5-778f-47d4-8d52-9c04462089d0.png'>Download original image</a>

**Browser**: Firefox 84 (Windows 10)
**Referer**: [https://participedia.net/user/419669](https://participedia.net/user/419669)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Blocked
