### ISSUE TITLE
Usersnap Feedback - Hi - Whatever you were linking to in this frame, doesn't exist anymore.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1324]
**Sender**: jason.lansky@gmail.com
**Comment**: Hi - Whatever you were linking to in this frame, doesn't exist anymore.
[Open #1012 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1012)

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-05/22-49/ba2a815a-0e4e-432b-a873-cb82c28cde7f.png'>![Usersnap Feedback - Hi - Whatever you were linking to in this frame, doesn't exist anymore.](https://usersnappublic.s3.amazonaws.com/2021-01-05/22-49/2e5a7d7c-e472-4458-ace9-d1ccbf6e14c7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-05/22-49/ba2a815a-0e4e-432b-a873-cb82c28cde7f.png'>Download original image</a>

**Browser**: Chrome 87 (Windows 10)
**Referer**: [https://participedia.net/research](https://participedia.net/research)
**Screen size**: 1920 x 1080 **Browser size**: 1388 x 832

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
I was able to download all the csv's without an issue. I emailed this user to troubleshoot. Closing for now.
