### ISSUE TITLE
Usersnap Feedback - Spam - Please block this user. I hid their one organization entry

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1325]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block this user. I hid their one organization entry
[Open #1013 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1013)

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-06/19-13/3651bab3-c0ba-4fe6-a5c0-b1f0904e1bf0.png'>![Usersnap Feedback - Spam - Please block this user. I hid their one organization entry](https://usersnappublic.s3.amazonaws.com/2021-01-06/19-13/f64c4c2e-d898-4d22-8beb-da988399f5c8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-06/19-13/3651bab3-c0ba-4fe6-a5c0-b1f0904e1bf0.png'>Download original image</a>

**Browser**: Firefox 84 (Windows 10)
**Referer**: [https://participedia.net/user/419740](https://participedia.net/user/419740)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
blocked
