### ISSUE TITLE
Usersnap Feedback - Design idea to avoid incorrect language entries: Add a popup tooltip when [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1326]
**Sender**: jesi.carson@gmail.com
**Comment**: Design idea to avoid incorrect language entries: Add a popup tooltip when the form is opened, reminding users to write in the same language as the UI is set to.
[Open #1014 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1014)
**Notes**:
 - (1) You are using Participedia in English. Please ensure you write in English in this form. To switch languages...

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-07/00-08/dbb27cf4-6f7f-49f7-93ad-be62f3b48741.png'>![Usersnap Feedback - Design idea to avoid incorrect language entries: Add a popup tooltip when (...)](https://usersnappublic.s3.amazonaws.com/2021-01-07/00-08/af3020e4-4834-4af1-a15c-e9eb0aba7eab.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-07/00-08/dbb27cf4-6f7f-49f7-93ad-be62f3b48741.png'>Download original image</a>

**Browser**: Chrome 87 (Macintosh)
**Referer**: [https://participedia.net/case/new](https://participedia.net/case/new)
**Screen size**: 1920 x 1080 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Jesi TODO:
- [ ] mockup due jan 27 or earlier

**Comment by jesicarson** [comment]
A few options to consider:

![Screen Shot 2021-01-25 at 3 32 16 PM](https://user-images.githubusercontent.com/13560530/105779122-89c75180-5f22-11eb-9e25-e31fae00f246.png)

![Screen Shot 2021-01-25 at 11 26 49 AM](https://user-images.githubusercontent.com/13560530/105779042-6d2b1980-5f22-11eb-88af-7bf57b1696dc.png)

![Screen Shot 2021-01-25 at 11 27 05 AM](https://user-images.githubusercontent.com/13560530/105779045-6dc3b000-5f22-11eb-8ea7-d567e87129a2.png)

![Screen Shot 2021-01-25 at 11 27 13 AM](https://user-images.githubusercontent.com/13560530/105779047-6e5c4680-5f22-11eb-8b49-7f3333b1a209.png)

**Comment by jesicarson** [comment]
info icon or "tell me more" would open a standard info icon modal with the "how translation works" text.

**Comment by jesicarson** [comment]
obviously the above options would be for new entries only.

**Comment by jesicarson** [comment]
styling match modal with transparent black overlay, white box.

**Comment by jesicarson** [comment]
next step - add a prompt above the publish button or on publish click - give user the option to select correct language.

**Comment by ascott** [comment]
once user clicks on got it, don't show it again.

**Comment by ascott** [comment]
@jesicarson here are screenshots of the new tooltip and more info modal. i need to get the text translated before opening a PR but wanted to get your eyes on it now to see if you have any changes.

![Screen Shot 2021-02-11 at 2 44 06 PM](https://user-images.githubusercontent.com/130878/107707988-9f08e380-6c77-11eb-8c71-b2235c15f5cf.png)

![Screen Shot 2021-02-11 at 2 44 08 PM](https://user-images.githubusercontent.com/130878/107708000-a16b3d80-6c77-11eb-9030-915ee1cef7e3.png)

**Comment by jesicarson** [comment]
Looks great! 
I assume the modal text is from the faq, the one consideration is that within the context of the case entry form - does it make sense to talk about the edit button? We may also want to take the opportunity to be really clear - “make sure your narrative is as complete as possible before publishing for the first time...”  just thoughts on content. Design looks great to me!

**Comment by ascott** [comment]
@jesicarson yeah this is the text from the FAQ, maybe we need new content for this use?

**Comment by jesicarson** [comment]
As per our chat, leave the text as is for the release, we can update later.

**Comment by plscully** [comment]
@ascott @jesicarson  The design is great! Perhaps the best solution for the "tell me more" piece is to make a slight update to the the text in the FAQ to add something along the lines of what Jesi suggested, i.e. “make sure your narrative is as complete as possible before publishing for the first time...”  No matter how we go about doing this, we will want to have native speakers check the machine translation of our new advice.

**Comment by jesicarson** [comment]
Thanks @plscully :)
We can work on drafting something that can be reviewed by the translators down the line. I agree we can make this text better and more contextual to the entry form. 
However, in the interest of pushing this live quickly, we'll just use the text from the FAQ page for now - since that text has already been translated and reviewed.

**Comment by ascott** [comment]
@jesicarson i've been thinking about the readability/contrast of the white text on red background and checked again WCAG contrast standards which recommends that the white text on this red background shouldn't be smaller than 18px. the text in the tooltip is currently 16px, but we could bump it up to 18px to meet the standard. https://contrastchecker.com/?c=ffffff&b=EC2024

<img width="985" alt="Screen Shot 2021-02-12 at 1 08 15 PM" src="https://user-images.githubusercontent.com/130878/107822728-6c242580-6d33-11eb-96e8-53c05ead152a.png">

<img width="1438" alt="Screen Shot 2021-02-12 at 1 12 01 PM" src="https://user-images.githubusercontent.com/130878/107823043-f076a880-6d33-11eb-8a40-d79d9651e000.png">

alternatively, we could use black text on a white background with the red button: 
<img width="1438" alt="Screen Shot 2021-02-12 at 1 04 30 PM" src="https://user-images.githubusercontent.com/130878/107822815-92e25c00-6d33-11eb-8f66-7615c3cd8c40.png">

what do you think?

**Comment by jesicarson** [comment]
Thanks for that consideration @ascott 
Is the screenshot with the red box showing 18px text?

**Comment by jesicarson** [comment]
Grey box maybe? I like the white idea but it gets a bit lost on the white page.

**Comment by ascott** [comment]
this is the text at 18pt. 

<img width="1438" alt="Screen Shot 2021-02-12 at 1 18 31 PM" src="https://user-images.githubusercontent.com/130878/107823727-15b7e680-6d35-11eb-9c04-6ed1dbc80fc7.png">

**Comment by jesicarson** [comment]
looks good to me.
