### ISSUE TITLE
Usersnap Feedback - I'm unable to change the submission date (should be July 17, 2019)

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1327]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: I'm unable to change the submission date (should be July 17, 2019)
[Open #1015 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1015)

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-15/05-49/8cb28597-dae3-479f-9ea4-20720abbff6f.png'>![Usersnap Feedback - I'm unable to change the submission date (should be July 17, 2019)](https://usersnappublic.s3.amazonaws.com/2021-01-15/05-49/6084800d-d10a-4c00-95af-1886f422c79a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-15/05-49/8cb28597-dae3-479f-9ea4-20720abbff6f.png'>Download original image</a>

**Browser**: Safari 12 (macOS Mojave)
**Referer**: [https://participedia.net/organization/7236](https://participedia.net/organization/7236)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
In the form it shows the correct date, but on the entry itself the date is incorrect. 

![Screen Shot 2021-01-20 at 10 35 46 AM](https://user-images.githubusercontent.com/13560530/105219412-4bd5c200-5b0b-11eb-90ea-e4636b3fc7ee.png)

**Comment by paninee** [comment]
@jesicarson @ascott Wiki The submission date is changed in the database, but the `Wiki Contributor History` only display edit history. Do you want to change it so that it displays the submission date as well?

**Comment by jesicarson** [comment]
@paninee yes the first submitted date and user should always be displayed as the first item in the wiki contributor history drop down.

**Comment by paninee** [comment]
@jesicarson done.
![image](https://user-images.githubusercontent.com/29439995/106038477-d890fa80-608c-11eb-88be-fa71bccd988e.png)
