### ISSUE TITLE
Usersnap Feedback - I can't view this entry in its original language. It says "internal server [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1328]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: I can't view this entry in its original language. It says "internal server error"
[Open #1016 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1016)

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-16/07-27/08db3c23-1acc-46f2-8ebe-d407d56ddebf.png'>![Usersnap Feedback - I can't view this entry in its original language. It says "internal server (...)](https://usersnappublic.s3.amazonaws.com/2021-01-16/07-27/1c6656f3-6fc2-4301-bd9d-eed89a78b51d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-16/07-27/08db3c23-1acc-46f2-8ebe-d407d56ddebf.png'>Download original image</a>

**Browser**: Safari 12 (macOS Mojave)
**Referer**: [https://participedia.net/organization/7242](https://participedia.net/organization/7242)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Clicking "View this entry in original language" produces: 

![Screen Shot 2021-01-19 at 7 53 27 AM](https://user-images.githubusercontent.com/13560530/105058785-6e90a980-5a2b-11eb-9c2b-78312b2b298c.png)

**Comment by jesicarson** [comment]
Same error when selecting PT from the language drop down.

**Comment by ascott** [comment]
@jesicarson i will take a look at this
