### ISSUE TITLE
Usersnap Feedback - I suggest you include citation to thecommonlot.com for your existing entry [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1329]
**Sender**: david67grant@gmail.com
**Comment**: I suggest you include citation to thecommonlot.com for your existing entry 'sortition'.
[Open #1017 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1017)

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-16/17-50/f1b7c2ba-6e57-45d4-a9eb-afcc93e8038d.png'>![Usersnap Feedback - I suggest you include citation to thecommonlot.com for your existing entry (...)](https://usersnappublic.s3.amazonaws.com/2021-01-16/17-50/20224cd6-f1ef-4756-8d51-486210408a5b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-16/17-50/f1b7c2ba-6e57-45d4-a9eb-afcc93e8038d.png'>Download original image</a>

**Browser**: Safari 14 (Macintosh)
**Referer**: [https://participedia.net/method/5507](https://participedia.net/method/5507)
**Screen size**: 1440 x 900 **Browser size**: 1215 x 667

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
I emailed this user and suggested they create an account and make the edit. closing.
