### ISSUE TITLE
Usersnap Feedback - Replace horizontal placeholder image with new design eps

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#133]
**Sender**: jesi.carson@gmail.com
**Comment**: This texture must have an incorrect line weight in it, as some of the horizontal lines look darker than all the rest. 
[Open #147 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/147)

<a href='https://usersnappublic.s3.amazonaws.com/2018-01-23/01-30/dd175719-8679-48b4-ba6c-e422e0ed0c96.png'>![Usersnap Feedback - This texture must have an incorrect line weight in it, as some of the hori(...)](https://usersnappublic.s3.amazonaws.com/2018-01-23/01-30/2774eb07-c695-48ad-bac8-f32e77ce4828.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-01-23/01-30/dd175719-8679-48b4-ba6c-e422e0ed0c96.png'>Download original image</a>

**Browser**: Chrome 63 (Macintosh)
**Referer**: [https://participedia.xyz/?page=2](https://participedia.xyz/?page=2)
**Screen size**: 1280 x 800 **Browser size**: 1277 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Interesting that usersnap screenshot doesn't look the same as a screenshot that I just took on my desktop (this more clearly shows the issue I'm talking about):
![screen shot 2018-01-22 at 4 33 57 pm](https://user-images.githubusercontent.com/13560530/35251866-36e79f6c-ff92-11e7-982b-d7b4e41a0f8f.png)

**Comment by jesicarson** [comment]
I recommend removing this particular placeholder and replacing it with a new one that includes diagonal lines. It's the only one that isn't diagonal. I'll provide an eps, P2 priority.
