### ISSUE TITLE
Usersnap Feedback - Add language drop down to mobile header. Same placement as desktop

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1333]
**Sender**: jesi.carson@gmail.com
**Comment**: Add language drop down to mobile header. Same placement as desktop
[Open #1021 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1021)

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-22/01-17/e5b1ba99-4a95-41d6-8cdc-e15ade605560.png'>![Usersnap Feedback - Add language drop down to mobile header. Same placement as desktop](https://usersnappublic.s3.amazonaws.com/2021-01-22/01-17/cb4f2d4a-c986-4223-9316-046d3c03d386.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-22/01-17/e5b1ba99-4a95-41d6-8cdc-e15ade605560.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
the language drop down is visible on screens up to 400 px wide, but on screens less wide it is hidden because there is not enough room in the header. any ideas on how to fit it in @jesicarson? 
403px wide
<img width="403" alt="Screen Shot 2021-02-10 at 8 59 29 PM" src="https://user-images.githubusercontent.com/130878/107603909-29533800-6be3-11eb-88be-d63cafbd6311.png">

390px wide
<img width="390" alt="Screen Shot 2021-02-10 at 8 59 43 PM" src="https://user-images.githubusercontent.com/130878/107603913-2f491900-6be3-11eb-9003-a4c24446a47a.png">

also to note, the language drop down is available in the footer on all screen sizes. 
<img width="325" alt="Screen Shot 2021-02-10 at 9 02 38 PM" src="https://user-images.githubusercontent.com/130878/107603982-6fa89700-6be3-11eb-9674-8dd31fc95e8d.png">

**Comment by jesicarson** [comment]
@ascott thanks for these screenshots! is this on staging? I'm not seeing the header drop down currently on the production site on my iphone 12 which is not a small screen. 

Based on the image above, it looks like we can squeeze it in on the 390 size with a bit less padding, don't you think? or show it when the user is logged in so there's more space (but not if this is a pain, want this project to be quick) 

ideally we show it on the header always - we want to prioritize visually the global nature of the site, but i'm also ok with it not appearing on very small screens (eg below 400), in those cases folks can use the footer (it's just a bit harder to find for new visitors, thats all).

**Comment by ascott** [comment]
@jesicarson these screenshots are from prod. iphone 12 dimensions are 390 x 844 PX, so that would be why it's not showing up for you since the breakpoint is currently set at 400px. i can change the breakpoint to 389px rather than 400px so it is visible on iphone 12's.

**Comment by jesicarson** [comment]
Per discussion: adjust break point to 380/390 and squeeze in the language drop down for smaller screens if possible.
