### ISSUE TITLE
Usersnap Feedback - Clicking info icons on the case form doesn't bring up the modal. Trying to [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1334]
**Sender**: jesi.carson@gmail.com
**Comment**: Clicking info icons on the case form doesn't bring up the modal. Trying to find out if my browser is blocking it somehow but i cant see how.
[Open #1022 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1022)

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-22/01-50/7b6d6e92-84c7-4e35-986d-992dfa719ba5.png'>![Usersnap Feedback - Clicking info icons on the case form doesn't bring up the modal. Trying to (...)](https://usersnappublic.s3.amazonaws.com/2021-01-22/01-50/551e5dbb-24c7-4cbb-b1bb-4a160b02bc19.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-22/01-50/7b6d6e92-84c7-4e35-986d-992dfa719ba5.png'>Download original image</a>

**Browser**: Chrome 87 (Macintosh)
**Referer**: [https://participedia.net/case/new#](https://participedia.net/case/new#)
**Screen size**: 1680 x 1050 **Browser size**: 1477 x 718

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
Fixed. deployed on prod.

![image](https://user-images.githubusercontent.com/29439995/106800189-ff16de80-6614-11eb-98ed-5911aa4b9ab3.png)
