### ISSUE TITLE
Usersnap Feedback - Spam - please block this account. I have hidden their entry

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1337]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - please block this account. I have hidden their entry
[Open #1025 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1025)

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-26/15-51/5dfa2085-f031-4e5b-bee7-36207784d018.png'>![Usersnap Feedback - Spam - please block this account. I have hidden their entry](https://usersnappublic.s3.amazonaws.com/2021-01-26/15-51/f964c730-948e-4438-b0f9-7e100082ceeb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-26/15-51/5dfa2085-f031-4e5b-bee7-36207784d018.png'>Download original image</a>

**Browser**: Firefox 84 (Windows 10)
**Referer**: [https://participedia.net/method/7252](https://participedia.net/method/7252)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
blocked
