### ISSUE TITLE
Usersnap Feedback - Hi there I created our profile (organization Agora) and it is not visible [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1339]
**Sender**: vojtech.cerny@agorace.cz
**Comment**: Hi there I created our profile (organization Agora) and it is not visible on the map. could you advice me how to tackle it on map?
[Open #1026 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1026)

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-28/11-03/6f471226-4890-49bb-ab56-cb987a1f6224.png'>![Usersnap Feedback - Hi there I created our profile (organization Agora) and it is not visible (...)](https://usersnappublic.s3.amazonaws.com/2021-01-28/11-03/bcb0cbfb-b575-4693-8740-91a7e6bac917.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-28/11-03/6f471226-4890-49bb-ab56-cb987a1f6224.png'>Download original image</a>

**Browser**: Chrome 87 (Windows 10)
**Referer**: [https://participedia.net/organization/6675](https://participedia.net/organization/6675)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 975

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Known issue - cities with multiple entries without a street address entered will only show 1 pin on the map, therefore many entries are un-seen. I will email this user and see if they can include a street address.
