### ISSUE TITLE
Usersnap Feedback - The footer is too close to the pagination buttons on the homepage search r[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#134]
**Sender**: jesi.carson@gmail.com
**Comment**: The footer is too close to the pagination buttons on the homepage search results. Need to give it more space as per all the homepage mockups (maybe about or a little less than half the height of one of the thumbnail images). 
[Open #148 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/148)

<a href='https://usersnappublic.s3.amazonaws.com/2018-01-23/01-33/3789cb39-f8f0-4a97-b9e6-e1e6ab5833d9.png'>![Usersnap Feedback - The footer is too close to the pagination buttons on the homepage search r(...)](https://usersnappublic.s3.amazonaws.com/2018-01-23/01-33/811c0c72-18e5-4ee3-80ab-95963699e829.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-01-23/01-33/3789cb39-f8f0-4a97-b9e6-e1e6ab5833d9.png'>Download original image</a>

**Browser**: Chrome 63 (Macintosh)
**Referer**: [https://participedia.xyz/?page=2](https://participedia.xyz/?page=2)
**Screen size**: 1280 x 800 **Browser size**: 1277 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
closing via https://github.com/participedia/frontend/issues/853
