### ISSUE TITLE
Usersnap Feedback - Spam - please block this account. I have hidden their organization entry

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1340]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - please block this account. I have hidden their organization entry
[Open #1027 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1027)

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-29/15-37/7eb2f2aa-36ef-4489-880f-4f216af2ad8d.png'>![Usersnap Feedback - Spam - please block this account. I have hidden their organization entry](https://usersnappublic.s3.amazonaws.com/2021-01-29/15-37/d049c3c6-7501-423c-8130-5fab70c453ca.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-29/15-37/7eb2f2aa-36ef-4489-880f-4f216af2ad8d.png'>Download original image</a>

**Browser**: Firefox 84 (Windows 10)
**Referer**: [https://participedia.net/user/419906](https://participedia.net/user/419906)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Blocked
