### ISSUE TITLE
csv error on methods

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1341]
<img width="840" alt="Screen Shot 2021-02-10 at 11 12 32 AM" src="https://user-images.githubusercontent.com/130878/107559420-ebc5bf00-6b90-11eb-9bb9-ef3f0f73c44f.png">

https://sentry.io/organizations/participedia-sentry-errors/issues/2186144433/?environment=production&project=1524525&query=is%3Aunresolved

**Comment by paninee** [comment]
Completed. Tested on stage and deployed to prod.
