### ISSUE TITLE
handlebars-helpers.js#searchFilterLabel error

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1342]
<img width="865" alt="Screen Shot 2021-02-10 at 11 26 34 AM" src="https://user-images.githubusercontent.com/130878/107560996-dd78a280-6b92-11eb-8070-6dce81a43164.png">

https://sentry.io/organizations/participedia-sentry-errors/issues/2086831890/?environment=production&project=1524525&query=is%3Aunresolved

**Comment by paninee** [comment]
Deployed and test on stage and prod.
