### ISSUE TITLE
Usersnap Feedback - Spam - please block this user. I will hide their three entries

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1344]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - please block this user. I will hide their three entries
[Open #1029 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1029)

<a href='https://usersnappublic.s3.amazonaws.com/2021-02-13/15-51/7f2e0ebd-f776-4211-a203-4e46a8e3f700.png'>![Usersnap Feedback - Spam - please block this user. I will hide their three entries](https://usersnappublic.s3.amazonaws.com/2021-02-13/15-51/81ba1537-1594-42d0-b5af-ad74fe6ef973.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-02-13/15-51/7f2e0ebd-f776-4211-a203-4e46a8e3f700.png'>Download original image</a>

**Browser**: Firefox 85 (Windows 10)
**Referer**: [https://participedia.net/user/420024](https://participedia.net/user/420024)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Blocked
