### ISSUE TITLE
Usersnap Feedback - Spam - Please block this user. I hid their entry

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1346]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block this user. I hid their entry
[Open #1030 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1030)

<a href='https://usersnappublic.s3.amazonaws.com/2021-02-20/02-56/5f0a869b-be54-4c58-b9b3-fb8c73d0b119.png'>![Usersnap Feedback - Spam - Please block this user. I hid their entry](https://usersnappublic.s3.amazonaws.com/2021-02-20/02-56/78dde3df-b35f-4ef4-a249-6f18b266cf31.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-02-20/02-56/5f0a869b-be54-4c58-b9b3-fb8c73d0b119.png'>Download original image</a>

**Browser**: Firefox 85 (Windows 10)
**Referer**: [https://participedia.net/user/420069](https://participedia.net/user/420069)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
blocked
