### ISSUE TITLE
Usersnap Feedback - Spam - please block user. I have hidden their two case entries

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1348]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - please block user. I have hidden their two case entries
[Open #1032 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1032)

<a href='https://usersnappublic.s3.amazonaws.com/2021-03-04/15-31/121d399b-02b4-4613-bdf4-ba82c3c7309b.png'>![Usersnap Feedback - Spam - please block user. I have hidden their two case entries](https://usersnappublic.s3.amazonaws.com/2021-03-04/15-31/1bd0a54d-2513-4866-8d13-f9100285dc3c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-03-04/15-31/121d399b-02b4-4613-bdf4-ba82c3c7309b.png'>Download original image</a>

**Browser**: Firefox 86 (Windows 10)
**Referer**: [https://participedia.net/user/420183](https://participedia.net/user/420183)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
