### ISSUE TITLE
Usersnap Feedback - Add Vero's Data Guidebook to Research page

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1349]
**Sender**: jesi.carson@gmail.com
**Comment**: Add Vero's Data Guidebook to Research page
[Open #1033 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1033)

<a href='https://usersnappublic.s3.amazonaws.com/2021-03-11/19-16/c869d60e-af09-4938-9dd4-1444cd9de0c7.png'>![Usersnap Feedback - Add Vero's Data Guidebook to Research page](https://usersnappublic.s3.amazonaws.com/2021-03-11/19-16/f9764814-785b-40c8-a00f-2f9839219c41.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-03-11/19-16/c869d60e-af09-4938-9dd4-1444cd9de0c7.png'>Download original image</a>

**Browser**: Chrome 89 (Macintosh)
**Referer**: [https://participedia.net/research](https://participedia.net/research)
**Screen size**: 1920 x 1080 **Browser size**: 1404 x 762

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@vhurtadol What do you think about adding a sentence or two to the Methodology section of the research page and linking to your Data Guidebook? Would you be able to help by drafting a brief intro? We can continue to update the guidebook if needed if we hyperlink to it as view-only a google document. Thoughts?

**Comment by jesicarson** [comment]
Here's the sharing link (currently set to anyone with the link can comment - thinking we can allow comments to collect feedback / address questions that come up): https://drive.google.com/file/d/1hE2fOih3YambGB7Sm8w0YH20_0c2BlZ9/view?usp=sharing

**Comment by vhurtadol** [comment]
> @vhurtadol What do you think about adding a sentence or two to the Methodology section of the research page and linking to your Data Guidebook? Would you be able to help by drafting a brief intro? We can continue to update the guidebook if needed if we hyperlink to it as view-only a google document. Thoughts?

Hi @jesicarson, that sounds good! I honestly think that just adding it to the second paragraph, next to Mark & Archon's paper should work. Something like this: 

For an in-depth explanation of the history, aspirations, theory, and analytical approach of Participedia, see 'The Participedia Project: An Introduction', by project founders, Archon Fung and Mark E. Warren. For a brief introduction on how to use our case data, see our continuously updated [User Guide](https://drive.google.com/file/d/1hE2fOih3YambGB7Sm8w0YH20_0c2BlZ9/view?usp=sharing). For information on how you can contribute to the project, please see our entry-writing guidelines. 

Does that work? I'll work on incorporating the feedback this weekend so we can have a better version up!

**Comment by jesicarson** [comment]
That sounds good to me, thanks @vhurtadol  

I've made a few small edits, and I think perhaps the text would make the most sense in the Real Time downloads section, eg:

For a brief introduction on how to use Participedia data, including analysis examples, please see our [Data Guidebook](https://drive.google.com/file/d/1hE2fOih3YambGB7Sm8w0YH20_0c2BlZ9/view?usp=sharing). Improving the quality of the Participedia dataset is an ongoing process, and we welcome feedback on any aspect of our data and how we enable its use.

Real-time Participedia data is available at the following links:

- Download Cases ... 
etc


What do you think, Vero?

**Comment by vhurtadol** [comment]
> That sounds good to me, thanks @vhurtadol
> 
> I've made a few small edits, and I think perhaps the text would make the most sense in the Real Time downloads section, eg:
> 
> For a brief introduction on how to use Participedia data, including analysis examples, please see our [Data Guidebook](https://drive.google.com/file/d/1hE2fOih3YambGB7Sm8w0YH20_0c2BlZ9/view?usp=sharing). Improving the quality of the Participedia dataset is an ongoing process, and we welcome feedback on any aspect of our data and how we enable its use.
> 
> Real-time Participedia data is available at the following links:
> 
> * Download Cases ...
>   etc
> 
> What do you think, Vero?

I just saw @plscully is making comments on the user guide (thanks Pat!). I'll try to solve all the comments by this afternoon. 

@jesicarson Yes, I think this works better and introduces all the datasets nicely.

**Comment by jesicarson** [comment]
@paninee when you have time, please add the following text to the first paragraph of the Real-time Data Downloads section of https://participedia.net/research :

For a brief introduction on how to use Participedia data, including analysis examples, please see our [Data Guidebook](p): https://drive.google.com/file/d/1hE2fOih3YambGB7Sm8w0YH20_0c2BlZ9/view?usp=sharing).

**Comment by plscully** [comment]
@jesicarson @paninee By coincidence, @vhurtadol and I have been making some edits to this document today, so please check with Vero to verify that she is finished before adding this to the Research page.

**Comment by jesicarson** [comment]
@plscully sure will do. 

@vhurtadol you can give us the go-ahead when you're ready, or let us know if it's ok to post before you're fully done. since its a living document you can continue to make edits even if it is live on the site.

**Comment by vhurtadol** [comment]
> @plscully sure will do.
> 
> @vhurtadol you can give us the go-ahead when you're ready, or let us know if it's ok to post before you're fully done. since its a living document you can continue to make edits even if it is live on the site.

Thanks, @jesicarson! I think the User Guide is ready to go live as it is. As you said, we will keep updating/improving the document as we receive more feedback.

**Comment by jesicarson** [comment]
> Please add the following text to the first paragraph of the Real-time Data Downloads section of https://participedia.net/research :
> 
> For a brief introduction on how to use Participedia data, including analysis examples, please see our [Data Guidebook](p): https://drive.google.com/file/d/1hE2fOih3YambGB7Sm8w0YH20_0c2BlZ9/view?usp=sharing).

@paninee could you get this done this week if possible? While you're in there, please also add the codebooks for Methods and Organizations to the research page (https://github.com/participedia/api/issues/1054):

Methods Codebook: https://docs.google.com/spreadsheets/d/1rwzaIZPNfIp8pMnOUGcIGe1aLk5pTOuP3AJvsDYmJb0/edit?usp=sharing

Organizations Codebook: https://docs.google.com/spreadsheets/d/1UESP8tLowTbeKX0nZLMcq52ZuG5i09NP3FtBu5YTlUg/edit?usp=sharing

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/115136741-a7163400-9fd6-11eb-8034-a24f3992fdc8.png)
