### ISSUE TITLE
Usersnap Feedback - The login button on mobile has moved off the header and covers part of the [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#135]
**Sender**: jesi.carson@gmail.com
**Comment**: The login button on mobile has moved off the header and covers part of the search bar. 
[Open #149 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/149)

<a href='https://usersnappublic.s3.amazonaws.com/2018-01-30/03-23/bfa7ba13-0f92-407e-992e-7a3801b963a1.png'>![Usersnap Feedback - The login button on mobile has moved off the header and covers part of the (...)](https://usersnappublic.s3.amazonaws.com/2018-01-30/03-23/97527bde-1023-403a-9e46-dbfae17e608a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-01-30/03-23/bfa7ba13-0f92-407e-992e-7a3801b963a1.png'>Download original image</a>

**Browser**: Safari 11 (iOS)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 320 x 568 **Browser size**: 320 x 568

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@dethe usersnap is not working correctly. the screenshots are not accurate. here is what it the above screenshot should be:

![usersnap mobile jesi](https://user-images.githubusercontent.com/13560530/35704885-b59f86e2-0755-11e8-9d9f-c5554e1e8a02.png)

**Comment by jesicarson** [comment]
Still happening as of May 18, 2018

**Comment by jesicarson** [comment]
Also when you're logged in on mobile, the profile avatar is in the wrong place, off the header.
![login](https://user-images.githubusercontent.com/13560530/40384689-2e6ccdc8-5db9-11e8-9b14-19c9944a1e61.jpg)
