### ISSUE TITLE
Usersnap Feedback - bug: there are duplicate entries of a case which I can't delete because it [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1351]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: bug: there are duplicate entries of a case which I can't delete because it says 'internal server error'
[Open #1035 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1035)

<a href='https://usersnappublic.s3.amazonaws.com/2021-03-11/22-01/61f44efb-469c-4dca-a11b-69a056e8e241.png'>![Usersnap Feedback - bug: there are duplicate entries of a case which I can't delete because it (...)](https://usersnappublic.s3.amazonaws.com/2021-03-11/22-01/fd2fc44d-20c9-49a1-b687-5ffb65176a86.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-03-11/22-01/61f44efb-469c-4dca-a11b-69a056e8e241.png'>Download original image</a>

**Browser**: Safari 12 (macOS Mojave)
**Referer**: [https://participedia.net/search](https://participedia.net/search)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Hi @paninee - keep this on your radar please. If we see more of these popping up this week, we need to prioritize this over the language detection work. Many thanks!

**Comment by plscully** [comment]
@paninee I have hidden the two duplicates mentioned in this ticket 
 - https://participedia.net/case/7288
 - https://participedia.net/case/7287

**Comment by paninee** [comment]
I will take a look at the deletion/hiding issue.

**Comment by paninee** [comment]
Will try to reproduce the duplication issue the next time this happens. So that we can get to the bottom of this duplication error.
