### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I have hidden their one case entry

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1352]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I have hidden their one case entry
[Open #1036 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1036)

<a href='https://usersnappublic.s3.amazonaws.com/2021-03-12/15-42/318ecbc9-d6e2-41eb-8966-e4b923aa17d6.png'>![Usersnap Feedback - Spam - Please block user. I have hidden their one case entry](https://usersnappublic.s3.amazonaws.com/2021-03-12/15-42/9096c508-c0bc-4efd-a9f8-51a1b79ebd2f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-03-12/15-42/318ecbc9-d6e2-41eb-8966-e4b923aa17d6.png'>Download original image</a>

**Browser**: Firefox 86 (Windows 10)
**Referer**: [https://participedia.net/case/7290](https://participedia.net/case/7290)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
