### ISSUE TITLE
Usersnap Feedback - It looks like this case was entered in Spanish in 2017, but tagged as English

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1353]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: It looks like this case was entered in Spanish in 2017, but tagged as English
[Open #1037 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1037)

<a href='https://usersnappublic.s3.amazonaws.com/2021-03-19/18-04/6c339955-134a-4c37-9dfc-fc9611b580a9.png'>![Usersnap Feedback - It looks like this case was entered in Spanish in 2017, but tagged as English](https://usersnappublic.s3.amazonaws.com/2021-03-19/18-04/d0cbd8e7-4059-4fee-afb1-ae93251101b6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-03-19/18-04/6c339955-134a-4c37-9dfc-fc9611b580a9.png'>Download original image</a>

**Browser**: Firefox 86 (Windows 10)
**Referer**: [https://participedia.net/case/432](https://participedia.net/case/432)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/29439995/113325650-932bbc00-92cd-11eb-91b7-ac6b15064827.png)

![image](https://user-images.githubusercontent.com/29439995/113325708-a179d800-92cd-11eb-9922-df3ef1ac1be8.png)
