### ISSUE TITLE
Usersnap Feedback - Hi guys, there’s a problem with your case filtering. Specifically, if I fi[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1355]
**Sender**: pgoelz@cs.cmu.edu
**Comment**: Hi guys,
there’s a problem with your case filtering. Specifically, if I filter by recruitment method being either “random sample” or “stratified random sample”, I don't get any results. The URL I’m redirected to is https://participedia.net/search?selectedCategory=case&recruitment_method=random,stratified . It would be lovely if you could ping me once you resolve this!
Cheers,
Paul
[Open #1039 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1039)

<a href='https://usersnappublic.s3.amazonaws.com/2021-03-26/20-40/0f8ec03b-2532-40e1-a909-333dc9fc0a85.png'>![Usersnap Feedback - Hi guys, there’s a problem with your case filtering. Specifically, if I fi(...)](https://usersnappublic.s3.amazonaws.com/2021-03-26/20-40/76dd949e-c591-473b-931b-a0eacf1d6d49.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-03-26/20-40/0f8ec03b-2532-40e1-a909-333dc9fc0a85.png'>Download original image</a>

**Browser**: Firefox 86 (Macintosh)
**Referer**: [https://participedia.net/about](https://participedia.net/about)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 838

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by plscully** [comment]
@jesicarson @paninee  Can we come up with a way to flag which filter values are inclusive and which ones are exclusive? This can be confusing for anyone, but especially for users who aren't familiar with Boolean logic. Even now when I use the filters I sometimes have to test which operation applies for each request. ... I identified this user and he's even a doctoral student in computer science at Carnegie Mellon ...https://www.cs.cmu.edu/directory/pgoelz

**Comment by jesicarson** [comment]
Interesting...

@paninee is it true that search filters for multi select fields are inclusive, and single select are exclusive? I actually didn't realize that some search filters worked differently than others - @plscully is this something you would expect? 

I assume Alanna based the filters system on a standard (she drew on her Air BnB experience), but to be honest I didn't realize that filters treated things differently - I thought they were all exclusive which is why you don't get many results if you have too many filters selected. 

Would be good to get clarity on this so we can think through how to communicate it to users.

**Comment by plscully** [comment]
@jesicarson @paninee The more I think about it, while we have good reasons for limiting the number of responses in the data entry forms, we don’t need to make options within the custom filters exclusive. For example, while it makes sense to only allow a single choice for “scope of influence,” it’s reasonable to expect that someone would want to use the filters to search for cases that took place at either the “city town” level (83 cases) or the “neighborhood” level (8 cases), but if I select both, the response comes up as 0. I recommend we make it possible to for users to enter multiple responses for all the custom filters. @vhurtadol I'd love to hear your thoughts about this.

**Comment by vhurtadol** [comment]
@plscully I agree. I think having it as an inclusive filter would probably be the most friendly approach for the users. As you said, if users are not familiarized with the filtering criteria (they don't know that one filter it's single and not multiple select), and they select two categories from, for example, scope, and they could get the impression that there are no cases that fit these categories.

**Comment by jesicarson** [comment]
Ok thanks for your input on this! I'll discuss with Pan today.

**Comment by paninee** [comment]
Fixed it so that we use inclusive filter for within the same filter category, but keep cross-category filter exclusive.

**Comment by plscully** [comment]
@paninee Thank you! 
@jesicarson  Please send a note to the user thanking him for calling this to our attention and letting him know that it has been resolved. This appears to be him https://paulgoelz.de/

**Comment by jesicarson** [comment]
done

**Comment by pgoelz** [comment]
Thanks for addressing this! Yes, my implicit assumption was that the filtering acted as a conjunction (“and”) across categories and as a disjunction (“or”) within each category, and I think the analogy to AirBnB is great! Of course, I also get that 

One more question, just to check:
Currently, [filtering recruitment_method=random](https://participedia.net/search?selectedCategory=case&recruitment_method=random) reports 109 results, [filtering recruitment_method=stratified](https://participedia.net/search?selectedCategory=case&recruitment_method=stratified) reports 403 results, but [combining both filters](https://participedia.net/search?selectedCategory=case&recruitment_method=random,stratified) reports 516 results, which is 4 more than I would expect. Are these numbers of results only approximate?

**Comment by jesicarson** [comment]
@pgoelz Great to hear from you on Github! Very much appreciate your eyes on the site. We'll check this and get back to you.

**Comment by pgoelz** [comment]
Sure thing! And thanks a lot for your work on this great resource!

**Comment by plscully** [comment]
I tested the same filters today and had a similar result. New cases are being added every day this week, so the total numbers have increased, but the discrepancy of there being four more cases than we should expect remains. My search results were: 
- filtering recruitment_method=random reports 110 results
- filtering recruitment_method=stratified reports 404 results
- combining both filters reports 518 results, which is 4 more than we should expect.

**Comment by paninee** [comment]
looking into this

**Comment by paninee** [comment]
After testing out the query from the database. We have

- random 114 results
- stratified 408 results
- both 522 results
![image](https://user-images.githubusercontent.com/29439995/115580977-722b0b00-a27c-11eb-9ed9-b58421c875b6.png)

With hidden entries filtered out.
- random 110 results
- stratified 404 results
- both 514 results

So I think what happens is that the `hidden` filter was missing when there are multiple filters.

**Comment by paninee** [comment]
@plscully Fixed and deployed to stage + prod. The issue was that we got the correct entries back with the filter, but when we do the count to show the number of results, we ignore the `hidden` rule.
