### ISSUE TITLE
Usersnap Feedback - the title is getting cut off for this case -- is there a character limit?

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1356]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: the title is getting cut off for this case -- is there a character limit?
[Open #1040 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1040)

<a href='https://usersnappublic.s3.amazonaws.com/2021-03-27/03-15/70585834-1417-4534-9e3d-17f689fa1d16.png'>![Usersnap Feedback - the title is getting cut off for this case -- is there a character limit?](https://usersnappublic.s3.amazonaws.com/2021-03-27/03-15/29e5a2db-3c57-4f9f-9bf9-edbbebbc0209.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-03-27/03-15/70585834-1417-4534-9e3d-17f689fa1d16.png'>Download original image</a>

**Browser**: Safari 12 (macOS Mojave)
**Referer**: [https://participedia.net/case/7310](https://participedia.net/case/7310)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/29439995/115136835-2e63a780-9fd7-11eb-862f-01e4f1c1ad92.png)
