### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I have hidden their one entry.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1357]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I have hidden their one entry.
[Open #1041 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1041)

<a href='https://usersnappublic.s3.amazonaws.com/2021-03-31/14-15/eb669b73-5682-4f66-95ba-5f0c64c7cc55.png'>![Usersnap Feedback - Spam - Please block user. I have hidden their one entry.](https://usersnappublic.s3.amazonaws.com/2021-03-31/14-15/e20ada77-c1d5-4db9-9194-5a7cc7072606.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-03-31/14-15/eb669b73-5682-4f66-95ba-5f0c64c7cc55.png'>Download original image</a>

**Browser**: Firefox 87 (Windows 10)
**Referer**: [https://participedia.net/user/420392](https://participedia.net/user/420392)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
