### ISSUE TITLE
Usersnap Feedback - I have a deliberative minipublics on social cohesion, but I don't know in [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1358]
**Sender**: julien.vrydagh@vub.be
**Comment**: I have a deliberative minipublics on social cohesion, but I don't know in which general topic I should put it? Thanks in advance! Julien
[Open #1042 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1042)

<a href='https://usersnappublic.s3.amazonaws.com/2021-04-02/09-32/91aded85-06be-499d-b0e3-0a42935fefc0.png'>![Usersnap Feedback - I have a deliberative minipublics on social cohesion, but I don't know in (...)](https://usersnappublic.s3.amazonaws.com/2021-04-02/09-32/515533a4-b413-4d4c-acc1-a267fb9d8c97.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-04-02/09-32/91aded85-06be-499d-b0e3-0a42935fefc0.png'>Download original image</a>

**Browser**: Firefox 87 (Macintosh)
**Referer**: [https://participedia.net/case/new?full=1](https://participedia.net/case/new?full=1)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 1006

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by plscully** [comment]
@jesicarson  I will send Julien a note saying that he made good selections within the limited parameters of the fixed values provided in our forms
