### ISSUE TITLE
Usersnap Feedback - I think this link would be an ok replacement, no? http://www.americaspeaks[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1360]
**Sender**: Jacob.Roberts@educationalequity.org
**Comment**: I think this link would be an ok replacement, no?
http://www.americaspeaks.org/projects/case-studies/unified-new-orleans-plan/
[Open #1044 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1044)

<a href='https://usersnappublic.s3.amazonaws.com/2021-04-15/19-33/d56ed7c2-7f08-441a-8843-cd69c08a708c.png'>![Usersnap Feedback - I think this link would be an ok replacement, no? http://www.americaspeaks(...)](https://usersnappublic.s3.amazonaws.com/2021-04-15/19-33/c32b06f3-afee-4f96-a9e1-341ed26c4f7e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-04-15/19-33/d56ed7c2-7f08-441a-8843-cd69c08a708c.png'>Download original image</a>

**Browser**: Firefox 87 (macOS Mojave)
**Referer**: [https://participedia.net/case/78](https://participedia.net/case/78)
**Screen size**: 2560 x 1440 **Browser size**: 2320 x 1264

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Sent this person an email inviting them to create an account and make the edit. Closing this issue.
