### ISSUE TITLE
Usersnap Feedback - Spam - Please block this user. I have hidden their one entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1368]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block this user. I have hidden their one entry.
[Open #1051 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1051)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-05/15-50/237a2c47-7d22-4b5f-97af-7d7808207e53.png'>![Usersnap Feedback - Spam - Please block this user. I have hidden their one entry.](https://usersnappublic.s3.amazonaws.com/2021-05-05/15-50/3417ebe3-b13e-4528-a165-f8e08296384b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-05/15-50/237a2c47-7d22-4b5f-97af-7d7808207e53.png'>Download original image</a>

**Browser**: Firefox 88 (Windows 10)
**Referer**: [https://participedia.net/user/420535](https://participedia.net/user/420535)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
