### ISSUE TITLE
Usersnap Feedback - Duplicated Entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1369]
**Sender**: jesi.carson@gmail.com
**Comment**: Duplicated Entry
[Open #1052 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1052)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-06/21-33/5a2becff-7c0d-42a0-91d9-1a4ffe52cd55.png'>![Usersnap Feedback - Duplicated Entry](https://usersnappublic.s3.amazonaws.com/2021-05-06/21-33/8b49f7c5-8969-4e01-b33e-cc91a2727268.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-06/21-33/5a2becff-7c0d-42a0-91d9-1a4ffe52cd55.png'>Download original image</a>

**Browser**: Chrome 90 (Macintosh)
**Referer**: [https://participedia.net/search](https://participedia.net/search)
**Screen size**: 1920 x 1080 **Browser size**: 1210 x 842

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Hi @paninee please remind me where we got to with this issue. I'm wondering why the "publishing" modal isn't working to prevent people from clicking publish multiple times.

Also - we are unable to remove the duplicates, just seeing "internal server error" message when you select any of the duplicate entries via the search page. 

If you could take a look at this as soon as you can that would be great. Thanks!

**Comment by paninee** [comment]
@jesicarson  will take a look at this tomorrow.

**Comment by paninee** [comment]
Fixed this entry. We should keep an eye out for the next one and try to contact the author to try and reproduce the issue.
