### ISSUE TITLE
Usersnap Feedback - Form should not allow users to select more than 3 General Issues

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#137]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Form should not allow users to select more than 3 General Issues
[Open #151 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/151)

<a href='https://usersnappublic.s3.amazonaws.com/2018-02-28/14-25/6ba11115-4104-4ef1-b570-a642815de74d.png'>![Usersnap Feedback - Form should not allow users to select more than 3 General Issues](https://usersnappublic.s3.amazonaws.com/2018-02-28/14-25/88001ce4-df37-442e-b080-3c9ae8a7c0f6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-02-28/14-25/6ba11115-4104-4ef1-b570-a642815de74d.png'>Download original image</a>

**Browser**: Chrome 64 (Windows 10)
**Referer**: [https://ppedia.surge.sh/case/4496/edit](https://ppedia.surge.sh/case/4496/edit)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1069

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Fixed on staging, will be on .xyz in next release.
