### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I have hidden their one organization entry, whic[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1373]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I have hidden their one organization entry, which has nothing to do with Palestine, despite the title
[Open #1056 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1056)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-18/14-40/9f7cfdcf-1b7a-4eec-8895-6652488c0624.png'>![Usersnap Feedback - Spam - Please block user. I have hidden their one organization entry, whic(...)](https://usersnappublic.s3.amazonaws.com/2021-05-18/14-40/c934ab6c-a2fb-4cf5-9425-c10f99aac0bd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-18/14-40/9f7cfdcf-1b7a-4eec-8895-6652488c0624.png'>Download original image</a>

**Browser**: Firefox 88 (Windows 10)
**Referer**: [https://participedia.net/user/420617](https://participedia.net/user/420617)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
