### ISSUE TITLE
Usersnap Feedback - Hi! I can't login to my account (I see the message with server error after [...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1374]
**Sender**: darya.garbuzova@platform.io
**Comment**: Hi!
I can't login to my account (I see the message with server error after the attempt). Could you help me with that?
The email of the account is hello@richpush.co
[Open #1057 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1057)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-18/18-22/47eb4c57-cf93-4808-8529-5fb5ba3af09f.png'>![Usersnap Feedback - Hi! I can't login to my account (I see the message with server error after (...)](https://usersnappublic.s3.amazonaws.com/2021-05-18/18-22/69087d38-efa8-443f-bcee-4de0def153c8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-18/18-22/47eb4c57-cf93-4808-8529-5fb5ba3af09f.png'>Download original image</a>

**Browser**: Chrome 90 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1475 x 830 **Browser size**: 1475 x 727

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
I am able to login without an error. I've emailed this user to see if they're still having issues. Will keep open for now.
