### ISSUE TITLE
Usersnap Feedback - Spam - Please block this user robotik.anthony@gmail.com -- They have submi[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1377]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block this user robotik.anthony@gmail.com -- They have submitted many entries that appear to be spam and that I have hidden. Their spam was intermixed with the following nine other entries for which I could not see the user/contributor because they all resulted in the “Internal Server Error” message.
https://participedia.net/case/7509 
https://participedia.net/case/7510 
https://participedia.net/case/7511 
https://participedia.net/case/7512 
https://participedia.net/case/7513 
https://participedia.net/case/7514 
https://participedia.net/case/7516 
https://participedia.net/case/7520 
https://participedia.net/case/7521
[Open #1060 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1060)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-19/17-15/987f8706-06b0-438c-9880-080b08591e36.png'>![Usersnap Feedback - Spam - Please block this user robotik.anthony@gmail.com -- They have submi(...)](https://usersnappublic.s3.amazonaws.com/2021-05-19/17-15/e740393b-733b-4991-bd2f-c0cad89259f5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-19/17-15/987f8706-06b0-438c-9880-080b08591e36.png'>Download original image</a>

**Browser**: Firefox 88 (Windows 10)
**Referer**: [https://participedia.net/search](https://participedia.net/search)
**Screen size**: 1760 x 1100 **Browser size**: 1745 x 930

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked

**Comment by jesicarson** [comment]
@paninee duplication bug again. but i guess we can't contact this person as they're a spammer!
