### ISSUE TITLE
Usersnap Feedback - We have multiple entries today with the same title. This one returns an "i[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1378]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: We have multiple entries today with the same title. This one returns an "internal server error" message - https://participedia.net/case/7531
[Open #1061 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1061)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-19/22-12/6e96dec4-24e8-4b07-b7c8-abb50708bbb5.png'>![Usersnap Feedback - We have multiple entries today with the same title. This one returns an "i(...)](https://usersnappublic.s3.amazonaws.com/2021-05-19/22-12/9b1cd0c9-8219-4a68-af83-b5cfc2f4f768.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-19/22-12/6e96dec4-24e8-4b07-b7c8-abb50708bbb5.png'>Download original image</a>

**Browser**: Chrome 90 (Windows 10)
**Referer**: [https://participedia.net/search](https://participedia.net/search)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1057

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee i'll see if i can get the author's contact details for this one and email them and cc you. maybe we can get them on a zoom call to get to the bottom of the duplication issue.

**Comment by paninee** [comment]
Deleted the duplicate. There's no author information in the data, which is weird. This is different than the existing duplicate issue we fixed with George. I say we keep an eye out for when it happens next. This

**Comment by jesicarson** [comment]
That is wierd - when I looked at the contributor data I think I saw your test account as the author. So I think maybe this happened in the process of testing the George issue? Agreed tho let’s keep an eye out in case that’s not it.
