### ISSUE TITLE
Usersnap Feedback - Chinese language bug

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1379]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Even though we are waiting for Baogang He to complete the PhraseApp process for Chinese, I thought that we were already using the machine translation for the interface.
[Open #1062 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1062)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-19/22-22/11e700c1-ff50-4122-be9b-fafdb3489bfd.png'>![Usersnap Feedback - Even though we are waiting for Baogang He to complete the PhraseApp proces(...)](https://usersnappublic.s3.amazonaws.com/2021-05-19/22-22/d4315ccc-3112-4e91-8c47-2b98a87b043b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-19/22-22/11e700c1-ff50-4122-be9b-fafdb3489bfd.png'>Download original image</a>

**Browser**: Firefox 88 (Windows 10)
**Referer**: [https://participedia.net/case/new?full=1](https://participedia.net/case/new?full=1)
**Screen size**: 1760 x 1100 **Browser size**: 1745 x 930

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
We should be, this seems weird. Let me see if i can reproduce this.

**Comment by jesicarson** [comment]
@paninee Verified bug: Chinese language is not functioning correctly on the site. 
![Screen Shot 2021-05-19 at 3 05 12 PM](https://user-images.githubusercontent.com/13560530/118890522-b0cfd780-b8b3-11eb-84f8-43cba1820d80.png)
