### ISSUE TITLE
Usersnap Feedback - Placeholder text doesn't fit in form field

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#138]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Screenshot from iPhone 6s
[Open #152 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/152)

<a href='https://usersnappublic.s3.amazonaws.com/2018-02-28/22-41/7ea1cfb1-f115-40f4-9e5e-79dc5d17985f.png'>![Usersnap Feedback - Screenshot from iPhone 6s](https://usersnappublic.s3.amazonaws.com/2018-02-28/22-41/c7094fc2-16b3-412b-a486-90b999469568.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-02-28/22-41/7ea1cfb1-f115-40f4-9e5e-79dc5d17985f.png'>Download original image</a>

**Browser**: ChromeiOS 64 (iOS)
**Referer**: [https://ppedia.surge.sh/case/5091/edit](https://ppedia.surge.sh/case/5091/edit)
**Screen size**: 320 x 568 **Browser size**: 320 x 568

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully can you clarify this issue please? Not sure what the issue is. thanks

**Comment by jesicarson** [comment]
@plscully never mind, I forgot that you can't see the entire screenshot on github unless you click on it. I see now that the placeholder text doesn't fit in the box.
