### ISSUE TITLE
Usersnap Feedback - More spam - Please block this user

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1380]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: More spam - Please block this user
[Open #1063 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1063)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-20/21-56/189e0c25-c46e-41c3-9ba7-09fdc66075f4.png'>![Usersnap Feedback - More spam - Please block this user](https://usersnappublic.s3.amazonaws.com/2021-05-20/21-56/b5f44e2a-25b5-4f7c-804d-f8414c511c8f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-20/21-56/189e0c25-c46e-41c3-9ba7-09fdc66075f4.png'>Download original image</a>

**Browser**: Firefox 88 (Windows 10)
**Referer**: [https://participedia.net/user/420213](https://participedia.net/user/420213)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
