### ISSUE TITLE
Usersnap Feedback - Spam - please block user. I hid their one entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1384]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - please block user. I hid their one entry
[Open #1067 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1067)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-26/14-12/e6a77350-6b38-44be-8ba6-bdedd6609c16.png'>![Usersnap Feedback - Spam - please block user. I hid their one entry](https://usersnappublic.s3.amazonaws.com/2021-05-26/14-12/b8b21870-a6bd-45e4-a439-f887770c5515.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-26/14-12/e6a77350-6b38-44be-8ba6-bdedd6609c16.png'>Download original image</a>

**Browser**: Firefox 88 (Windows 10)
**Referer**: [https://participedia.net/user/420617](https://participedia.net/user/420617)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
already blocked
