### ISSUE TITLE
Usersnap Feedback - These were both posted using the Participedia Support Team account. If we [...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1386]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: These were both posted using the Participedia Support Team account. If we are done with them please hide them
[Open #1069 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1069)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-28/04-21/b3acc225-d185-4bbe-8048-3c71bc3b4a0e.png'>![Usersnap Feedback - These were both posted using the Participedia Support Team account. If we (...)](https://usersnappublic.s3.amazonaws.com/2021-05-28/04-21/eacf984f-63d9-475d-9d9b-20f2ee146493.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-28/04-21/b3acc225-d185-4bbe-8048-3c71bc3b4a0e.png'>Download original image</a>

**Browser**: Firefox 88 (Windows 10)
**Referer**: [https://participedia.net/search?page=2](https://participedia.net/search?page=2)
**Screen size**: 1760 x 1100 **Browser size**: 1745 x 930

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
oops will hide. this was me, i forgot!
