### ISSUE TITLE
Usersnap Feedback - If possible, please hide these three and the following six case entries th[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1387]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: If possible, please hide these three and the following six case entries that all result in an "internal service error" message. We need to get rid of them asap as conference participants start to take a close look at the site.
[Open #1070 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1070)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-28/04-24/5f8c62d8-394f-459f-b23a-e71e7f4fe9a6.png'>![Usersnap Feedback - If possible, please hide these three and the following six case entries th(...)](https://usersnappublic.s3.amazonaws.com/2021-05-28/04-24/9bfc783a-0a1f-432a-aa51-8c553412d68f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-28/04-24/5f8c62d8-394f-459f-b23a-e71e7f4fe9a6.png'>Download original image</a>

**Browser**: Firefox 88 (Windows 10)
**Referer**: [https://participedia.net/search?page=2](https://participedia.net/search?page=2)
**Screen size**: 1760 x 1100 **Browser size**: 1745 x 930

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee can you remove these manually, asap, please?
