### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I have hidden the entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1389]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I have hidden the entry.
[Open #1072 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1072)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-29/16-24/01ac09f3-5382-4922-8ba7-8b8c3f524fbd.png'>![Usersnap Feedback - Spam - Please block user. I have hidden the entry.](https://usersnappublic.s3.amazonaws.com/2021-05-29/16-24/ac20ae44-e7c9-4a99-b143-89610eb037cf.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-29/16-24/01ac09f3-5382-4922-8ba7-8b8c3f524fbd.png'>Download original image</a>

**Browser**: Firefox 88 (Windows 10)
**Referer**: [https://participedia.net/organization/7555](https://participedia.net/organization/7555)
**Screen size**: 1760 x 1100 **Browser size**: 1745 x 930

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee please look at this asap

**Comment by paninee** [comment]
@jesicarson This entry was hidden. This user was blocked from Auth0. I think we need to clear his session. I guess what could happen was that he already logged in. Blocking him from Auth0 does not affect Participedia session. We have to kick him out so that he can't log back in.

**Comment by paninee** [comment]
@jesicarson should be fixed now.
