### ISSUE TITLE
Usersnap Feedback - Spam - please block user. I hid this entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1394]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - please block user. I hid this entry.
[Open #1077 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1077)

<a href='https://usersnappublic.s3.amazonaws.com/2021-06-01/15-11/10c65886-6e8f-4f69-b66b-33f68c0b26d2.png'>![Usersnap Feedback - Spam - please block user. I hid this entry.](https://usersnappublic.s3.amazonaws.com/2021-06-01/15-11/aa8b3fe6-6350-4c7d-af7b-dea492841b8a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-06-01/15-11/10c65886-6e8f-4f69-b66b-33f68c0b26d2.png'>Download original image</a>

**Browser**: Firefox 88 (Windows 10)
**Referer**: [https://participedia.net/organization/7565](https://participedia.net/organization/7565)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@plscully are these new entries you’re seeing the top of the search page? 

Cc @paninee

**Comment by plscully** [comment]
@jesicarson @paninee Yes!
