### ISSUE TITLE
Usersnap Feedback - I have troubles to change the Narrative. (it doesn't get updated although [...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1397]
**Sender**: electric.vote@gmail.com
[Open #1080 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1080)
**Notes**:
 - (1) I have troubles to change the Narrative. (it doesn't get updated although all the remaining options / textboxes seem to work...)

<a href='https://usersnappublic.s3.amazonaws.com/2021-06-03/01-12/ed6cb34f-657c-4e83-af81-2363dbaf2a7a.png'>![Usersnap Feedback - I have troubles to change the Narrative. (it doesn't get updated although (...)](https://usersnappublic.s3.amazonaws.com/2021-06-03/01-12/616e188d-3c3a-4059-814f-528f13773e18.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-06-03/01-12/ed6cb34f-657c-4e83-af81-2363dbaf2a7a.png'>Download original image</a>

**Browser**: Chrome 90 (Windows 10)
**Referer**: [https://participedia.net/method/7571/edit?full=1](https://participedia.net/method/7571/edit?full=1)
**Screen size**: 1500 x 1000 **Browser size**: 1500 x 890

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
emailing this person now.
