### ISSUE TITLE
Usersnap Feedback - Edit issue reported by George. 

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1398]
**Sender**: jesi.carson@gmail.com
**Comment**: Can't verify publish bug reported by George. I am able to publish changes. Keep open for ref.
[Open #1081 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1081)

<a href='https://usersnappublic.s3.amazonaws.com/2021-06-05/01-26/4630fa60-59d6-449b-9d3b-530b7d1eedb2.png'>![Usersnap Feedback - Can't verify publish bug reported by George. I am able to publish changes. (...)](https://usersnappublic.s3.amazonaws.com/2021-06-05/01-26/4fdbb2b7-3379-4a3a-8c5b-0631e76b62b3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-06-05/01-26/4630fa60-59d6-449b-9d3b-530b7d1eedb2.png'>Download original image</a>

**Browser**: Chrome 91 (Macintosh)
**Referer**: [https://participedia.net/case/7389](https://participedia.net/case/7389)
**Screen size**: 1920 x 1080 **Browser size**: 1860 x 870

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee see email thread. On Monday I’ll test with the word doc he sent. Any ideas? 

It’s not the Firefox issue. He’s using chrome. 

This is the 2nd “can’t publish” email I’ve gotten this week. I’ll forward the other one too.

**Comment by jesicarson** [comment]
Same issue - https://github.com/participedia/usersnaps/issues/1397

**Comment by paninee** [comment]
Let's setup a meeting with George to do a TeamViewer so we can debug what's going on with his screen.

**Comment by paninee** [comment]
This happens with George's account specifically. We have his account credentials for testing purpose.

**Comment by paninee** [comment]
@jesicarson fixed, and deployed live. Asked George to try editing again. This could potentially solve the duplicate issue as well.

**Comment by jesicarson** [comment]
I'll ask the others who flagged this to test too.
