### ISSUE TITLE
Usersnap Feedback - There were three spam entries on the search page, I was only able to hide [...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1401]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: There were three spam entries on the search page, I was only able to hide one since the other two say internal server error
[Open #1084 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1084)

<a href='https://usersnappublic.s3.amazonaws.com/2021-06-15/05-14/4aed9ac9-70a1-4ee8-951b-2123868deba2.png'>![Usersnap Feedback - There were three spam entries on the search page, I was only able to hide (...)](https://usersnappublic.s3.amazonaws.com/2021-06-15/05-14/283cdeec-db5c-433d-bced-c2675ce829c3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-06-15/05-14/4aed9ac9-70a1-4ee8-951b-2123868deba2.png'>Download original image</a>

**Browser**: Safari 12 (macOS Mojave)
**Referer**: [https://participedia.net/search?page=1](https://participedia.net/search?page=1)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee note that the creator of the case jaskiran is referring also made edits to george's entry. and it looks like a test entry? just flagging since you're working on this. here's the case she hid: https://participedia.net/case/7584
