### ISSUE TITLE
Usersnap Feedback - medium news display bug.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1402]
**Sender**: jesi.carson@gmail.com
**Comment**: medium news display bug.
[Open #1085 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1085)

<a href='https://usersnappublic.s3.amazonaws.com/2021-06-15/22-08/ea7aab5a-368b-43a6-8127-6c7629db3ab3.png'>![Usersnap Feedback - medium news display bug.](https://usersnappublic.s3.amazonaws.com/2021-06-15/22-08/5c2e902a-44b3-4079-bd1a-c57fa1e1b173.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-06-15/22-08/ea7aab5a-368b-43a6-8127-6c7629db3ab3.png'>Download original image</a>

**Browser**: Chrome 91 (Macintosh)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1920 x 1080 **Browser size**: 1425 x 874

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
fixed by deleting the medium post and re-publishing with the first image AFTER at least 1 paragraph of text.
