### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I have hidden this entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1403]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I have hidden this entry
[Open #1086 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1086)

<a href='https://usersnappublic.s3.amazonaws.com/2021-06-22/15-07/2a8b7fd3-24ef-4a13-8362-808c9007db7d.png'>![Usersnap Feedback - Spam - Please block user. I have hidden this entry](https://usersnappublic.s3.amazonaws.com/2021-06-22/15-07/b6dd9455-0032-47b3-8058-ae4a8bc38b92.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-06-22/15-07/2a8b7fd3-24ef-4a13-8362-808c9007db7d.png'>Download original image</a>

**Browser**: Firefox 89 (Windows 10)
**Referer**: [https://participedia.net/organization/7591](https://participedia.net/organization/7591)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
