### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I have hidden their two entries.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1404]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I have hidden their two entries.
[Open #1087 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1087)

<a href='https://usersnappublic.s3.amazonaws.com/2021-06-24/15-07/828966df-7ea7-4757-b9de-c3ae56653867.png'>![Usersnap Feedback - Spam - Please block user. I have hidden their two entries.](https://usersnappublic.s3.amazonaws.com/2021-06-24/15-07/95d45fe5-8295-4ea4-9e40-263b26fe43c9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-06-24/15-07/828966df-7ea7-4757-b9de-c3ae56653867.png'>Download original image</a>

**Browser**: Firefox 89 (Windows 10)
**Referer**: [https://participedia.net/case/7593](https://participedia.net/case/7593)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Blocked
