### ISSUE TITLE
Usersnap Feedback - Links still connected to .xyz

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1407]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: Links still connected to .xyz
[Open #1090 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1090)

<a href='https://usersnappublic.s3.amazonaws.com/2021-07-14/12-08/935fc82d-f5bb-4589-b626-5a5da2281287.png'>![Usersnap Feedback - Links still connected to .xyz](https://usersnappublic.s3.amazonaws.com/2021-07-14/12-08/9805b7f3-1bbb-4abb-9b89-a00ca5f4cdfa.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-07-14/12-08/935fc82d-f5bb-4589-b626-5a5da2281287.png'>Download original image</a>

**Browser**: Chrome 91 (Windows 10)
**Referer**: [https://participedia.net/case/4361](https://participedia.net/case/4361)
**Screen size**: 1708 x 960 **Browser size**: 1707 x 849

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Current status of fix (see slack convo in design tech channel): 

David Ascher can reinstate the xyz domain, but it is owned by namescheap so he has to use his personal namescheap account to do this. 

I requested a credit card number from Paul / McMaster, and if we can't get this I'll put it on my personal CC.

**Comment by paninee** [comment]
Reinstated .xyz domain and setup a new DNS in Cloudflare.
