### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I have hidden their one entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1408]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I have hidden their one entry.
[Open #1091 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1091)

<a href='https://usersnappublic.s3.amazonaws.com/2021-07-16/15-12/2d658b5b-b4ae-4580-83ee-5ca1e6161eb9.png'>![Usersnap Feedback - Spam - Please block user. I have hidden their one entry.](https://usersnappublic.s3.amazonaws.com/2021-07-16/15-12/10cbe45e-cae6-460a-8030-606101693a31.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-07-16/15-12/2d658b5b-b4ae-4580-83ee-5ca1e6161eb9.png'>Download original image</a>

**Browser**: Firefox 89 (Windows 10)
**Referer**: [https://participedia.net/case/7599](https://participedia.net/case/7599)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked

**Comment by jesicarson** [comment]
test
