### ISSUE TITLE
Usersnap Feedback - pas de texte en français

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1409]
**Comment**: pas de texte en français
[Open #1092 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1092)

<a href='https://usersnappublic.s3.amazonaws.com/2021-07-19/16-55/2e58c15d-73ff-4b60-8908-6f22d0c88462.png'>![Usersnap Feedback - pas de texte en français](https://usersnappublic.s3.amazonaws.com/2021-07-19/16-55/67adc0e0-56da-4363-912e-90528b08b4f2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-07-19/16-55/2e58c15d-73ff-4b60-8908-6f22d0c88462.png'>Download original image</a>

**Browser**: Chrome 91 (Windows 10)
**Referer**: [https://participedia.net/method/5764](https://participedia.net/method/5764)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 577

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee verified - i thought maybe this was just someone had manually edited french, but all the languages except for EN have numbers in the narrative instead of text. Seems a bit weird - doubt that someone would manually edit these like this. what do you think? bug?

**Comment by jgakhal** [comment]
This entry has the same issue: https://participedia.net/method/5769

**Comment by jesicarson** [comment]
@jgakhal these entries have to be manually fixed - this can be done by editors by google translating the narrative and pasting it in the other languages. If you or another editor have time to do this, let us know. Otherwise this will be a backlog issue that @paninee can manually fix on the database side when she has time.

**Comment by jgakhal** [comment]
I can take care of manually fixing these two entries.

**Comment by jesicarson** [comment]
Awesome, thank you!
