### ISSUE TITLE
Usersnap Feedback - Clicked my avatar to visit my profile page, and the name and avatar on my [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#141]
**Sender**: jesi.carson@gmail.com
**Comment**: Clicked my avatar to visit my profile page, and the name and avatar on my profile is Lucy J Parry. However the content IS mine from .net.
[Open #155 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/155)

<a href='https://usersnappublic.s3.amazonaws.com/2018-03-18/21-44/a4a505ee-c344-43fc-bf43-123fabd1cd1f.png'>![Usersnap Feedback - Clicked my avatar to visit my profile page, and the name and avatar on my (...)](https://usersnappublic.s3.amazonaws.com/2018-03-18/21-44/4e62c2f9-d15a-457e-95e5-f6731e73c447.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-03-18/21-44/a4a505ee-c344-43fc-bf43-123fabd1cd1f.png'>Download original image</a>

**Browser**: Chrome 64 (Macintosh)
**Referer**: [https://participedia.xyz/users/1189](https://participedia.xyz/users/1189)
**Screen size**: 1280 x 800 **Browser size**: 1275 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Also some of the placeholder images are blank.

**Comment by dethe** [comment]
Fixed the "everyone is Lucy Parry" bug. We can open a bug on frontend for blank placeholder images.
