### ISSUE TITLE
Usersnap Feedback - Hi Participedia. We'd like to update the Democracy Society entry please. H[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1412]
**Sender**: kate@demsoc.eu
**Comment**: Hi Participedia. We'd like to update the Democracy Society entry please. How can we do that?
[Open #1095 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1095)

<a href='https://usersnappublic.s3.amazonaws.com/2021-07-20/11-43/eb723903-02b1-4e76-bdd0-e469cb5e815a.png'>![Usersnap Feedback - Hi Participedia. We'd like to update the Democracy Society entry please. H(...)](https://usersnappublic.s3.amazonaws.com/2021-07-20/11-43/f70a7ba5-bbeb-4134-8568-b19a2282d922.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-07-20/11-43/eb723903-02b1-4e76-bdd0-e469cb5e815a.png'>Download original image</a>

**Browser**: Chrome 91 (macOS Mojave)
**Referer**: [https://participedia.net/organization/6302](https://participedia.net/organization/6302)
**Screen size**: 1920 x 1080 **Browser size**: 1722 x 880

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
I'll write to these folks from the info@account today
