### ISSUE TITLE
Usersnap Feedback - Spam - please block user. I have hidden their one organization entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1413]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - please block user. I have hidden their one organization entry.
[Open #1096 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1096)

<a href='https://usersnappublic.s3.amazonaws.com/2021-07-20/15-18/dfe5b2e1-f93d-47da-aed6-3d4aed4b06fc.png'>![Usersnap Feedback - Spam - please block user. I have hidden their one organization entry.](https://usersnappublic.s3.amazonaws.com/2021-07-20/15-18/875c012f-53ab-4e5b-b648-d6ec9eb3edb0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-07-20/15-18/dfe5b2e1-f93d-47da-aed6-3d4aed4b06fc.png'>Download original image</a>

**Browser**: Firefox 89 (Windows 10)
**Referer**: [https://participedia.net/organization/7600](https://participedia.net/organization/7600)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
