### ISSUE TITLE
Usersnap Feedback - This is not a method but a case !

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1414]
**Comment**: This is not a method but a case !
[Open #1097 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1097)

<a href='https://usersnappublic.s3.amazonaws.com/2021-07-26/22-03/0fe0fb90-8057-476f-8cd3-0c9bfcf59529.png'>![Usersnap Feedback - This is not a method but a case !](https://usersnappublic.s3.amazonaws.com/2021-07-26/22-03/9b6fffe8-e2fd-46e4-8053-63701e078bc6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-07-26/22-03/0fe0fb90-8057-476f-8cd3-0c9bfcf59529.png'>Download original image</a>

**Browser**: Chrome 92 (Windows 10)
**Referer**: [https://participedia.net/method/6462](https://participedia.net/method/6462)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 577

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@jgakhal FYI

**Comment by jgakhal** [comment]
I've converted it to a case and hidden the original method entry.
