### ISSUE TITLE
Usersnap Feedback - I changed the original submission date and it added another date to the co[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1415]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: I changed the original submission date and it added another date to the contributor history
[Open #1098 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1098)

<a href='https://usersnappublic.s3.amazonaws.com/2021-07-28/01-24/a4fd031b-592d-4061-9ff5-210cd8619b69.png'>![Usersnap Feedback - I changed the original submission date and it added another date to the co(...)](https://usersnappublic.s3.amazonaws.com/2021-07-28/01-24/6053f2d6-8ff6-4a63-ac00-ad0fe35f783a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-07-28/01-24/a4fd031b-592d-4061-9ff5-210cd8619b69.png'>Download original image</a>

**Browser**: Safari 14 (macOS Mojave)
**Referer**: [https://participedia.net/case/7634](https://participedia.net/case/7634)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Verified - there's something going on with editing submission details..

I tried editing this case as a test - https://participedia.net/case/6454

first i changed the first submitted by detials to Jaskiran, to the day before the original entry date. Then it added an extra line similar to the usersnap - jaskiran march 26, then jaskiran march 27th

then i changed it back to me, with the original entry date, and it looked fine. 

then i tried again to change it to jaskiran, and now it just adds an additional line with Jesi as the author, even though i changed it to jaskiran.

some screenshots:

![Screen Shot 2021-07-28 at 11 15 06 AM](https://user-images.githubusercontent.com/13560530/127375141-27dae8ea-c345-4c42-a09f-381b9c0423be.png)

![Screen Shot 2021-07-28 at 11 15 21 AM](https://user-images.githubusercontent.com/13560530/127375161-0352d698-d552-4a91-991c-14bd11a613e3.png)

**Comment by paninee** [comment]
@jesicarson what do we expect to happen?

There are 2 different cases here,

1. The entry was only submitted once. No change.
2. The entry has been changed at least once.


For case #1, for example, this case http://ppedia-stage.herokuapp.com/case/7167, shouldn't there be only the "First Submitted By" field showing up in the UI of the edit form? Why do we show "Most Recent Changes By" field, when there has been no change.

For case #2, http://ppedia-stage.herokuapp.com/case/6557, where we have 7 revisions, we still show only the "First Submitted By" and "Most Recent Changes By". Don't we want to show all of the 7 revisions?

I think there maybe a design bug here as well as the logic bug. I suggest we

1. display the "Most Recent Changes" as a list. Show all the revisions. If there's no change, don't show any. [design bug]
2. any changes to either the original's or the revisions' contributor/date, we overwrite them without creating a new revision. [logic bug]

**Comment by paninee** [comment]
We decided to remove the Most Recent Changes section from the admin edit section.

**Comment by jesicarson** [comment]
@paninee per our chat just now:
- remove the "most recent changes by" fields from the UI 
- debug the "first submitted by" fields
