### ISSUE TITLE
Usersnap Feedback - This user --    fidele192 -- created 5 new stubs on July 28 for a case tha[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1416]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: This user --  	fidele192 -- created 5 new stubs on July 28 for a case that already exists on the site. I also see that a few weeks ago they made a change of some kind to the full version of the case. Can someone please contact the user to see what is happening?
[Open #1099 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1099)

<a href='https://usersnappublic.s3.amazonaws.com/2021-07-28/14-51/97b9c635-7cf6-4b20-9bd5-1b359a118e04.png'>![Usersnap Feedback - This user --    fidele192 -- created 5 new stubs on July 28 for a case tha(...)](https://usersnappublic.s3.amazonaws.com/2021-07-28/14-51/9a644daa-7d08-4a8a-bc1c-cb8f86fd8589.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-07-28/14-51/97b9c635-7cf6-4b20-9bd5-1b359a118e04.png'>Download original image</a>

**Browser**: Firefox 90 (Windows 10)
**Referer**: [https://participedia.net/user/420402](https://participedia.net/user/420402)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee this is the case we were working on with George - the University of Southampton student that gave you his login info so you could fix the publishing bug. Please look into what may have happened here. Thanks!

Let's review this on our side before contacting that other user.

**Comment by paninee** [comment]
@plscully @jesicarson This is one of my test accounts. I made sure they are all cleaned up now.
