### ISSUE TITLE
Usersnap Feedback - Three blank entries with the "internal service error" message

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1417]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Three blank entries with the "internal service error" message
[Open #1100 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1100)

<a href='https://usersnappublic.s3.amazonaws.com/2021-07-28/14-55/a53a4e1b-e0aa-4dca-b7ae-bd1a5237d480.png'>![Usersnap Feedback - Three blank entries with the "internal service error" message](https://usersnappublic.s3.amazonaws.com/2021-07-28/14-55/9d611c7b-a86d-4eca-bf28-22b6a1041a4f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-07-28/14-55/a53a4e1b-e0aa-4dca-b7ae-bd1a5237d480.png'>Download original image</a>

**Browser**: Firefox 90 (Windows 10)
**Referer**: [https://participedia.net/search](https://participedia.net/search)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee looks like the publishing bug again. but maybe these are old entries that just need to be cleaned up? lets look at this next week.

**Comment by paninee** [comment]
@jesicarson  can't find entries
![image](https://user-images.githubusercontent.com/29439995/131175029-b1a67786-8de9-4ec8-8ead-337ce19d9448.png)

**Comment by jesicarson** [comment]
Let's close for now.
