### ISSUE TITLE
Usersnap Feedback - 15px space between the text and the box below

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1420]
**Sender**: jesi.carson@gmail.com
**Comment**: 15px space between the text and the box below
[Open #1103 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1103)

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-34/73aa330f-42a7-4860-91e0-0be15679e779.png'>![Usersnap Feedback - 15px space between the text and the box below](https://usersnappublic.s3.amazonaws.com/2021-08-02/00-34/b33332b4-a085-453c-b935-3daed7b19dfc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-34/73aa330f-42a7-4860-91e0-0be15679e779.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [http://ppedia-stage.herokuapp.com/case/new](http://ppedia-stage.herokuapp.com/case/new)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Or 10px, whatever the standard is. I’ll check the guidelines on tues.

**Comment by paninee** [comment]
Fixed on stage.
