### ISSUE TITLE
Usersnap Feedback - Should there be placeholder text here? Ie: “Select language”

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1421]
**Sender**: jesi.carson@gmail.com
**Comment**: Should there be placeholder text here? Ie: “Select language”
[Open #1104 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1104)

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-36/b33e7509-789c-43c8-a29b-6068faedd3a6.png'>![Usersnap Feedback - Should there be placeholder text here? Ie: “Select language”](https://usersnappublic.s3.amazonaws.com/2021-08-02/00-36/8ca9b9b3-4736-4281-949f-2d7cf775e6aa.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-36/b33e7509-789c-43c8-a29b-6068faedd3a6.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [http://ppedia-stage.herokuapp.com/case/new](http://ppedia-stage.herokuapp.com/case/new)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
@jesicarson it's defaulted to the current language the user selected. Maybe we can add it as a hint?

**Comment by jesicarson** [comment]
Oh bizzare - in the screenshot it says “English” but on my phone screen it looked blank.

**Comment by jesicarson** [comment]
Must have been a temporary glitch. I can’t replicate it. Closing
