### ISSUE TITLE
Usersnap Feedback - I selected Spanish but the drop down is empty. It should say the language [...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1422]
**Sender**: jesi.carson@gmail.com
**Comment**: I selected Spanish but the drop down is empty. It should say the language that’s selected
[Open #1105 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1105)

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-37/88964af4-613f-4f99-a960-40d47845efe0.png'>![Usersnap Feedback - I selected Spanish but the drop down is empty. It should say the language (...)](https://usersnappublic.s3.amazonaws.com/2021-08-02/00-37/ba27d065-782c-4e1e-b6b4-f65be936fbe1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-37/88964af4-613f-4f99-a960-40d47845efe0.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [http://ppedia-stage.herokuapp.com/case/new](http://ppedia-stage.herokuapp.com/case/new)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
@jesicarson I don't get this issue. It does say "Spanish" in the dropdown.

**Comment by jesicarson** [comment]
It was blank on my phone. But again this must have been a glitch on my side. If it happens again I’ll use my phone screenshot in addition to the feedback button screenshot. So odd.
