### ISSUE TITLE
Usersnap Feedback - The English text is still visible with Spanish selected, but not when I se[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1423]
**Sender**: jesi.carson@gmail.com
**Comment**: The English text is still visible with Spanish selected, but not when I select another language. Maybe because the field above I selected Spanish too? Not sure what’s happening here. But I’d expect the English text to disappear (or be machine translated to Spanish)
[Open #1106 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1106)

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-38/2a75c784-1cf3-4062-87a0-74a0dd0235ae.png'>![Usersnap Feedback - The English text is still visible with Spanish selected, but not when I se(...)](https://usersnappublic.s3.amazonaws.com/2021-08-02/00-38/d3da5bab-aa06-4bca-9fc8-6e7a527ba164.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-38/2a75c784-1cf3-4062-87a0-74a0dd0235ae.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [http://ppedia-stage.herokuapp.com/case/new](http://ppedia-stage.herokuapp.com/case/new)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
@jesicarson we don't do the machine translation on the fly, while the user inputting the data. We reset the field to empty.
 See https://www.loom.com/share/a0859fc2b5d648e3a828031de9ba3b8c

**Comment by jesicarson** [comment]
Yes, the field wasn’t empty tho. It had the EN text in it. 

I’ll see if I can reproduce. Could have been a 1 time glitch like the blank fields?

**Comment by jesicarson** [comment]
To clarify: I wrote the text in the display language (EN), and when I used the language drop down and selected Spanish, the EN text remained in the field. Only for Spanish tho, the other languages were indeed empty.

**Comment by paninee** [comment]
@jesicarson yes, i understood, but I cannot reproduce. I recorded it here https://www.loom.com/share/a0859fc2b5d648e3a828031de9ba3b8c.
