### ISSUE TITLE
Usersnap Feedback - Also missing the pre-filled narrative headings in all languages.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1424]
**Sender**: jesi.carson@gmail.com
**Comment**: Also missing the pre-filled narrative headings in all languages.
[Open #1107 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1107)

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-39/aeaeda57-d691-4d46-8a6d-c184db02ced0.png'>![Usersnap Feedback - Also missing the pre-filled narrative headings in all languages.](https://usersnappublic.s3.amazonaws.com/2021-08-02/00-39/9ca20c21-9dc0-42c1-967a-b60ea4838410.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-39/aeaeda57-d691-4d46-8a6d-c184db02ced0.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [http://ppedia-stage.herokuapp.com/case/new](http://ppedia-stage.herokuapp.com/case/new)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Never mind this is the brief description!
