### ISSUE TITLE
Usersnap Feedback - No short description or narratives are translated, if not entered in displ[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1426]
**Sender**: jesi.carson@gmail.com
**Comment**: No short description or narratives are translated, if not entered in display language. Need to add logic that finds the next langauage that was entered and translates that. For new entries.
[Open #1109 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1109)

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-47/5cfd0e62-922d-4efa-af2a-85555652ab9f.png'>![Usersnap Feedback - No short description or narratives are translated, if not entered in displ(...)](https://usersnappublic.s3.amazonaws.com/2021-08-02/00-47/805cea72-b8b9-4fcc-8e06-c728f3b40470.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/00-47/5cfd0e62-922d-4efa-af2a-85555652ab9f.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [http://ppedia-stage.herokuapp.com/case/7166](http://ppedia-stage.herokuapp.com/case/7166)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
@jesicarson did you enter the title in multiple languages?

**Comment by jesicarson** [comment]
Yes. English and Spanish.

**Comment by paninee** [comment]
@jesicarson the current logic checks if the user enters any field in other language, we won't auto-translate that language. For example, if you enter title in EN and ES, but only description in EN. Both EN and ES won't get auto-translated. So we want to check for every single field and auto-translate the missing field?

**Comment by jesicarson** [comment]
Yes, the current logic works well for editing an existing entry.  

But for _new_ entries we need a different solution so we end up with auto translated content in all languages. I don’t know the best way to do this automatically… especially if text in more than 1 language (other than the display language) is entered. 

Let’s chat at our next meeting and think it through. This might be pushing us toward the ‘user-controlled synching’ idea.

**Comment by paninee** [comment]
@jesicarson ummm, we don't do any auto-translate on edit existing entry. We never had, and we still don't.

The current logic does not care how many languages the user entered. We use the current selected language as the original to perform auto-translate.

**Comment by jesicarson** [comment]
Right, of course. Existing we don’t translate. Sorry I confused myself for a moment there :p  

Anyway, I think we do still need a way to auto translate new entries into all languages if the display language is blank but another language or languages are entered. Otherwise our translation system won’t be effective, right? 

Can we check if text is entered in those fields and then, if so, require text to also be entered in the display language? I don’t love the idea of throwing a publish error modal at people… But maybe in real life most people wouldn’t leave the display language blank?

**Comment by paninee** [comment]
Will be fixed with the change from https://github.com/participedia/api/issues/1067#issuecomment-892194365
