### ISSUE TITLE
Usersnap Feedback - I'm entering this method in English and it seems to be using the case head[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1428]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: I'm entering this method in English and it seems to be using the case headings for languages other than English. Also, once I click on another language and back to English, the headings also change to the case ones. The same applies for organizations
[Open #1111 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1111)

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/14-24/6f543bce-43b2-4d44-9e6e-82a85766093d.png'>![Usersnap Feedback - I'm entering this method in English and it seems to be using the case head(...)](https://usersnappublic.s3.amazonaws.com/2021-08-02/14-24/74ec7987-fa92-404d-b075-09377668503b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-02/14-24/6f543bce-43b2-4d44-9e6e-82a85766093d.png'>Download original image</a>

**Browser**: Safari 14 (macOS Mojave)
**Referer**: [http://ppedia-stage.herokuapp.com/method/new?full=1](http://ppedia-stage.herokuapp.com/method/new?full=1)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee the pre-filled headings for methods are different than case headings. Orgs are also different. I’m guessing you just used the case ones.

**Comment by paninee** [comment]
Fixed on stage.
