### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I have hidden this case entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1432]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I have hidden this case entry.
[Open #1115 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1115)

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-03/15-15/a0109b94-5ba0-424c-b6b1-c63e5a8a4fe0.png'>![Usersnap Feedback - Spam - Please block user. I have hidden this case entry.](https://usersnappublic.s3.amazonaws.com/2021-08-03/15-15/a0d20355-af59-43d9-b7e7-d37b8a6f8743.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-03/15-15/a0109b94-5ba0-424c-b6b1-c63e5a8a4fe0.png'>Download original image</a>

**Browser**: Firefox 90 (Windows 10)
**Referer**: [https://participedia.net/case/7663](https://participedia.net/case/7663)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Blocked
