### ISSUE TITLE
Usersnap Feedback - Spam - Please Block User. I hid this entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1433]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please Block User. I hid this entry.
[Open #1116 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1116)

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-04/15-41/6d36c590-1555-4348-95ed-13e2b3b5bae6.png'>![Usersnap Feedback - Spam - Please Block User. I hid this entry.](https://usersnappublic.s3.amazonaws.com/2021-08-04/15-41/f355d1af-854d-4d96-a74f-c4d1d8ad9267.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-04/15-41/6d36c590-1555-4348-95ed-13e2b3b5bae6.png'>Download original image</a>

**Browser**: Firefox 90 (Windows 10)
**Referer**: [https://participedia.net/organization/7664](https://participedia.net/organization/7664)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
