### ISSUE TITLE
Usersnap Feedback - Search error -

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1437]
**Sender**: jesi.carson@gmail.com
**Comment**: Search error -
[Open #1120 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1120)

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-26/21-48/4da704d0-9057-4815-b094-8e97b782ee1f.png'>![Usersnap Feedback - Search error -](https://usersnappublic.s3.amazonaws.com/2021-08-26/21-48/b6c0e53a-01b6-489f-8f96-bbf8a9fbb567.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-26/21-48/4da704d0-9057-4815-b094-8e97b782ee1f.png'>Download original image</a>

**Browser**: Chrome 92 (Macintosh)
**Referer**: [https://participedia.net/search](https://participedia.net/search)
**Screen size**: 1920 x 1080 **Browser size**: 1440 x 796

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
full text search appears to be broken.

input search terms, site loads for about 30-40 seconds, then throws an error:

![Screen Shot 2021-08-26 at 12 48 52 PM](https://user-images.githubusercontent.com/13560530/131026638-84d7055e-122b-45f6-91db-11db921c0a1f.png)

**Comment by jesicarson** [comment]
Seems to be resolved.
