### ISSUE TITLE
Usersnap Feedback - Spam

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1438]
**Sender**: scott.bowlsby@gmail.com
**Comment**: Spam
[Open #1121 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1121)

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-27/07-33/00251bde-bfc5-4795-9919-6bfe46eca698.png'>![Usersnap Feedback - Spam](https://usersnappublic.s3.amazonaws.com/2021-08-27/07-33/d961e63a-be65-44c1-8bbe-d450b83a5f34.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-27/07-33/00251bde-bfc5-4795-9919-6bfe46eca698.png'>Download original image</a>

**Browser**: Firefox 91 (Android)
**Referer**: [https://participedia.net/user/421259](https://participedia.net/user/421259)
**Screen size**: 414 x 851 **Browser size**: 414 x 722

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Blocked. Thanks @scottofletcher !!
