### ISSUE TITLE
Usersnap Feedback - I tried entering different titles in English, French, and Spanish, but I c[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1442]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: I tried entering different titles in English, French, and Spanish, but I can't seem to delete the French title  and switch the language (i.e. leave it blank) after entering text
[Open #1124 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1124)

<a href='https://usersnappublic.s3.amazonaws.com/2021-09-02/19-10/5beb5d77-f014-410d-bc1d-b2ab36d732dc.png'>![Usersnap Feedback - I tried entering different titles in English, French, and Spanish, but I c(...)](https://usersnappublic.s3.amazonaws.com/2021-09-02/19-10/884e325b-c64f-4d10-a32e-636cdf014c01.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-09-02/19-10/5beb5d77-f014-410d-bc1d-b2ab36d732dc.png'>Download original image</a>

**Browser**: Safari 14 (macOS Mojave)
**Referer**: [http://ppedia-stage.herokuapp.com/case/new?full=1](http://ppedia-stage.herokuapp.com/case/new?full=1)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee was the fix on stage before jaskiran reported this or after? Thx

**Comment by paninee** [comment]
@jesicarson @jgakhal fixed deployed to stage.
