### ISSUE TITLE
Usersnap Feedback - 2021-09-06 23:15:54

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1444]
[Open #1126 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1126)

<a href='https://usersnappublic.s3.amazonaws.com/2021-09-06/23-15/07ca6e4b-7987-470c-bb93-99a9f39d7da4.png'>![Usersnap Feedback - 2021-09-06 23:15:54](https://usersnappublic.s3.amazonaws.com/2021-09-06/23-15/dbda777e-d511-435b-82e1-22f2b87520dd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-09-06/23-15/07ca6e4b-7987-470c-bb93-99a9f39d7da4.png'>Download original image</a>

**Browser**: Chrome 92 (Android 11)
**Referer**: [https://participedia.net/method/5309](https://participedia.net/method/5309)
**Screen size**: 869 x 412 **Browser size**: 790 x 388

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
dont know what this is. closing.
