### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I hid this case entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1447]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I hid this case entry.
[Open #1129 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1129)

<a href='https://usersnappublic.s3.amazonaws.com/2021-09-08/15-45/01b427d5-7c1f-417f-9fa3-fff92dc41da8.png'>![Usersnap Feedback - Spam - Please block user. I hid this case entry.](https://usersnappublic.s3.amazonaws.com/2021-09-08/15-45/8b55d479-0e0c-4cec-a435-2e2b12cfea63.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-09-08/15-45/01b427d5-7c1f-417f-9fa3-fff92dc41da8.png'>Download original image</a>

**Browser**: Firefox 91 (Windows 10)
**Referer**: [https://participedia.net/case/7680](https://participedia.net/case/7680)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
