### ISSUE TITLE
Usersnap Feedback - Spam - please block user. I hid this organization entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1448]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - please block user. I hid this organization entry
[Open #1130 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1130)

<a href='https://usersnappublic.s3.amazonaws.com/2021-09-10/16-23/8b7284df-5665-4678-99bb-f6937923777b.png'>![Usersnap Feedback - Spam - please block user. I hid this organization entry](https://usersnappublic.s3.amazonaws.com/2021-09-10/16-23/a469270e-8e13-4d5f-8f80-04778abaf662.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-09-10/16-23/8b7284df-5665-4678-99bb-f6937923777b.png'>Download original image</a>

**Browser**: Firefox 91 (Windows 10)
**Referer**: [https://participedia.net/organization/7682](https://participedia.net/organization/7682)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
