### ISSUE TITLE
Usersnap Feedback - Add space between lines of text on subtitles in form

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1449]
**Sender**: jesi.carson@gmail.com
**Comment**: Add space between lines of text on subtitles in form
[Open #1131 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1131)

<a href='https://usersnappublic.s3.amazonaws.com/2021-09-10/23-49/914b7cd8-63eb-45dd-ac92-60b4be778036.png'>![Usersnap Feedback - Add space between lines of text on subtitles in form](https://usersnappublic.s3.amazonaws.com/2021-09-10/23-49/f29e0410-0352-4ea0-9b94-c1a132c38a9c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-09-10/23-49/914b7cd8-63eb-45dd-ac92-60b4be778036.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [https://participedia.net/case/new?full=1](https://participedia.net/case/new?full=1)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
![BC2A0214-2BE1-45EC-B2BB-1CCB1779ADD9](https://user-images.githubusercontent.com/13560530/132922070-cca2d857-ae9f-4091-ac9b-b10cd68f805a.png)
![6C042FD3-04DA-4903-A77F-E2BA76E4BE1F](https://user-images.githubusercontent.com/13560530/132922077-96d84006-d31f-44e5-98d7-101c3ae5a4c8.png)
