### ISSUE TITLE
Usersnap Feedback - No values showing under general issues

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1451]
**Sender**: jesi.carson@gmail.com
**Comment**: No values showing under general issues
[Open #1133 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1133)

<a href='https://usersnappublic.s3.amazonaws.com/2021-09-10/23-52/48680974-7bbd-456a-85ac-aef56da395e9.png'>![Usersnap Feedback - No values showing under general issues](https://usersnappublic.s3.amazonaws.com/2021-09-10/23-52/6c1fef07-e1c1-4ffb-9f69-af8b164bb7bd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-09-10/23-52/48680974-7bbd-456a-85ac-aef56da395e9.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [https://participedia.net/case/new?full=1](https://participedia.net/case/new?full=1)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
This is what I’m seeing on my phone screen:

![CBB4BD3F-897D-42EC-B095-89EBAD0D51B5](https://user-images.githubusercontent.com/13560530/132921630-bd2dca46-e2a7-4865-bdd4-d623763ff520.png)
![A54C2A3F-F5BF-4612-8A25-8956254CE579](https://user-images.githubusercontent.com/13560530/132921634-a3e2b1f5-abeb-44ca-925c-09cbc0af9e6a.png)

**Comment by jesicarson** [comment]
Not sure why the usersnap is seeing values but I’m not.
