### ISSUE TITLE
Usersnap Feedback - 2021-09-15 14:58:36

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1453]
[Open #1135 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1135)

<a href='https://usersnappublic.s3.amazonaws.com/2021-09-15/14-58/2e37147b-2a6f-4aae-b0fd-596ae40cd52f.png'>![Usersnap Feedback - 2021-09-15 14:58:36](https://usersnappublic.s3.amazonaws.com/2021-09-15/14-58/268402c8-f009-44c8-b152-eccc1c51e7f9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-09-15/14-58/2e37147b-2a6f-4aae-b0fd-596ae40cd52f.png'>Download original image</a>

**Browser**: Chrome 93 (Android 10)
**Referer**: [https://participedia.net/method/5188](https://participedia.net/method/5188)
**Screen size**: 846 x 412 **Browser size**: 798 x 388

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
not seeing an issue here.
