### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I hid three organization entries they submitted [...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1456]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I hid three organization entries they submitted on Sept 15
[Open #1138 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1138)

<a href='https://usersnappublic.s3.amazonaws.com/2021-09-16/15-22/c3529d52-6847-4fba-80db-baef8341e7be.png'>![Usersnap Feedback - Spam - Please block user. I hid three organization entries they submitted (...)](https://usersnappublic.s3.amazonaws.com/2021-09-16/15-22/fd010bae-8b2e-4513-a8be-6d54df5c49b1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-09-16/15-22/c3529d52-6847-4fba-80db-baef8341e7be.png'>Download original image</a>

**Browser**: Firefox 92 (Windows 10)
**Referer**: [https://participedia.net/organization/7686](https://participedia.net/organization/7686)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
