### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I hid their case and organization entries.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1457]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I hid their case and organization entries.
[Open #1139 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1139)

<a href='https://usersnappublic.s3.amazonaws.com/2021-09-18/16-36/797530e8-d9c6-48f1-a296-d8a3bc6b2ea3.png'>![Usersnap Feedback - Spam - Please block user. I hid their case and organization entries.](https://usersnappublic.s3.amazonaws.com/2021-09-18/16-36/4d4bd72d-7722-4337-a381-02ee4d756920.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-09-18/16-36/797530e8-d9c6-48f1-a296-d8a3bc6b2ea3.png'>Download original image</a>

**Browser**: Firefox 92 (Windows 10)
**Referer**: [https://participedia.net/case/7690](https://participedia.net/case/7690)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
