### ISSUE TITLE
Usersnap Feedback - Another example of where we need to delete the bracketed text

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#146]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Another example of where we need to delete the bracketed text
[Open #160 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/160)

<a href='https://usersnappublic.s3.amazonaws.com/2018-04-07/01-51/ca296ecf-ee05-4233-9bf2-f58c31b1f9fa.png'>![Usersnap Feedback - Another example of where we need to delete the bracketed text](https://usersnappublic.s3.amazonaws.com/2018-04-07/01-51/32985cdb-f926-4d61-88ec-7d8f1858c1c0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-04-07/01-51/ca296ecf-ee05-4233-9bf2-f58c31b1f9fa.png'>Download original image</a>

**Browser**: Chrome 65 (Windows 10)
**Referer**: [https://participedia.xyz/case/445](https://participedia.xyz/case/445)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1069

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
closing via https://github.com/participedia/usersnaps/issues/145
