### ISSUE TITLE
Usersnap Feedback - Spam - Please block user. I hid this case and another organization entry t[...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1461]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user. I hid this case and another organization entry they made
[Open #1143 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1143)

<a href='https://usersnappublic.s3.amazonaws.com/2021-09-24/15-45/0c810d1d-ac0b-451a-970d-4f393c5e9537.png'>![Usersnap Feedback - Spam - Please block user. I hid this case and another organization entry t(...)](https://usersnappublic.s3.amazonaws.com/2021-09-24/15-45/fde0f2f6-be01-4ab0-96d0-36e867a02b25.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-09-24/15-45/0c810d1d-ac0b-451a-970d-4f393c5e9537.png'>Download original image</a>

**Browser**: Firefox 92 (Windows 10)
**Referer**: [https://participedia.net/case/7697](https://participedia.net/case/7697)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
blocked
