### ISSUE TITLE
Usersnap Feedback - fix spacing on sub head text (it’s too tight)

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1465]
**Sender**: jesi.carson@gmail.com
**Comment**: fix spacing on sub head text (it’s too tight)
[Open #1147 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1147)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-03/04-14/87ef2034-a290-4aed-a543-4c48d2ae8b50.png'>![Usersnap Feedback - fix spacing on sub head text (it’s too tight)](https://usersnappublic.s3.amazonaws.com/2021-10-03/04-14/79c14d0e-881f-4b00-8d9a-dc910cac2d0c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-03/04-14/87ef2034-a290-4aed-a543-4c48d2ae8b50.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [https://participedia.net/search?selectedCategory=case&openFilters=1](https://participedia.net/search?selectedCategory=case&openFilters=1)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/140849103-0962a4a8-2a0c-4af4-8c75-a5b406531fcd.png)
This was fixed a long while ago. Are you still seeing this on your phone? @jesicarson

**Comment by jesicarson** [comment]
Saw it on desktop today.
