### ISSUE TITLE
Usersnap Feedback - Twice I entered information in the data forms for Links, Video, and severa[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1469]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Twice I entered information in the data forms for Links, Video, and several other categories, but it didn't save the information either time.
[Open #1150 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1150)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-05/18-26/f07c648b-a3f6-4028-b568-92e71751104d.png'>![Usersnap Feedback - Twice I entered information in the data forms for Links, Video, and severa(...)](https://usersnappublic.s3.amazonaws.com/2021-10-05/18-26/4219a789-90fd-414b-9a9a-1e63b3cabb0a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-05/18-26/f07c648b-a3f6-4028-b568-92e71751104d.png'>Download original image</a>

**Browser**: Firefox 92 (Windows 10)
**Referer**: [https://participedia.net/organization/306](https://participedia.net/organization/306)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee please have a look at this, and organize a meeting with @plscully for debugging if needed. thanks!

**Comment by paninee** [comment]
@jesicarson  @plscully Fixed and deployed live. Removed the red banner.
