### ISSUE TITLE
Usersnap Feedback - Error loading map in case narrative

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#147]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Error loading map in case narrative
[Open #161 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/161)

<a href='https://usersnappublic.s3.amazonaws.com/2018-04-13/03-28/540c0cd1-7990-4237-b61d-d29645ecf04a.png'>![Usersnap Feedback - Error loading map in case narrative](https://usersnappublic.s3.amazonaws.com/2018-04-13/03-28/a53fce16-bf60-4972-a7c0-69a9c510811e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-04-13/03-28/540c0cd1-7990-4237-b61d-d29645ecf04a.png'>Download original image</a>

**Browser**: Chrome 65 (Windows 10)
**Referer**: [https://participedia.xyz/case/445](https://participedia.xyz/case/445)
**Screen size**: 1280 x 720 **Browser size**: 1422 x 600

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
See participedia/frontend#317
