### ISSUE TITLE
Usersnap Feedback - Looks like duplicates here

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1472]
**Sender**: jesi.carson@gmail.com
**Comment**: Looks like duplicates here
[Open #1153 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1153)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-07/21-48/e0b6ade1-f788-4e40-a6bc-c66e7ea165c9.png'>![Usersnap Feedback - Looks like duplicates here](https://usersnappublic.s3.amazonaws.com/2021-10-07/21-48/b4133720-554d-4905-889b-6ff0632c0d31.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-07/21-48/e0b6ade1-f788-4e40-a6bc-c66e7ea165c9.png'>Download original image</a>

**Browser**: Chrome 94 (Macintosh)
**Referer**: [https://participedia.net/search](https://participedia.net/search)
**Screen size**: 1920 x 1080 **Browser size**: 1713 x 879

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
@jesicarson this does not look like a duplicate by system error. It looks like the user upload the entry twice. If you notice, on entry has an apostrophe symbol and another doesn't. I think these were the test entries from when I was in the video call with Thorsten. I hid them both.
