### ISSUE TITLE
Usersnap Feedback - I just got an email from a user who said they updated this entry - but obv[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1474]
**Sender**: jesi.carson@gmail.com
**Comment**: I just got an email from a user who said they updated this entry - but obviously their changes are not being reflected in the contributor history - is this related to the publishing bug you're working on Pan? the user's name is Katarzyna (Pliszczyńska) Pawłowska, but it looks here like Alanna was the last person to update this entry (which also seems odd)
[Open #1155 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1155)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-08/01-51/d9229d3e-70d1-4e3f-9227-b2cc2f9d0df5.png'>![Usersnap Feedback - I just got an email from a user who said they updated this entry - but obv(...)](https://usersnappublic.s3.amazonaws.com/2021-10-08/01-51/30877b81-2ea1-422f-b12a-e0f5a3cd6abb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-08/01-51/d9229d3e-70d1-4e3f-9227-b2cc2f9d0df5.png'>Download original image</a>

**Browser**: Chrome 94 (Macintosh)
**Referer**: [https://participedia.net/organization/5961](https://participedia.net/organization/5961)
**Screen size**: 1920 x 1080 **Browser size**: 1777 x 879

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
It must be the same issue, because I just tried to update the entry and my changes were not saved.

**Comment by paninee** [comment]
This is related to https://github.com/participedia/usersnaps/issues/1470

**Comment by paninee** [comment]
@jesicarson  @plscully Fixed. Deployed.

**Comment by plscully** [comment]
> This is the only other problem entry that I checked just now, and it doens't appear to be fixed either. It still lists Alanna as the last person to do an update .
> 
> @jesicarson @plscully Fixed. Deployed.

**Comment by jesicarson** [comment]
@plscully It’s now tracking edits and contributors correctly. I just made an edit and it’s reflected in the drop down.
