### ISSUE TITLE
Usersnap Feedback - On this landing page these and several other entries are noted as having b[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1476]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: On this landing page these and several other entries are noted as having been updated within the last few days, but similar records of updates to not appear in the Contributor History.
[Open #1157 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1157)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-12/14-42/fa6295e9-faf8-4561-b240-2ddd51b42a84.png'>![Usersnap Feedback - On this landing page these and several other entries are noted as having b(...)](https://usersnappublic.s3.amazonaws.com/2021-10-12/14-42/84fbaa0c-35eb-412c-9639-c34174db44e7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-12/14-42/fa6295e9-faf8-4561-b240-2ddd51b42a84.png'>Download original image</a>

**Browser**: Firefox 93 (Windows 10)
**Referer**: [https://participedia.net/search](https://participedia.net/search)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee this isn't actually crazy urgent, but i labeled it P1 because i'm guessing its related to the publishing bug you just worked on, so probably good to get in there and fix the contributor history too.

**Comment by paninee** [comment]
This is related to https://github.com/participedia/usersnaps/issues/1470

**Comment by paninee** [comment]
@jesicarson  @plscully Fixed. Deployed.

**Comment by plscully** [comment]
@paninee @jesicarson  This doesn't appear to be fixed when I view it on my browser. Entry https://participedia.net/organization/7121 
Search results say that it was last updated on Oct 9, 2021, but contributor history says Oct 20, 2020.
Also, I see that there are lots of entries that are marked "test" -- Can someone please fix the titles on these so that users aren't confused?

**Comment by jesicarson** [comment]
Thanks Pat!

@paninee can you check on the results display not matching the contribution history drop down?

I’m hiding the tests now.

**Comment by plscully** [comment]
@jesicarson  Please be careful hiding the cases marked "test".  A lot of them look like Pan might have added :test" to the title of a legitimate entry. Where that's the situation I suppose we just want to edit the entry's title.
