### ISSUE TITLE
Usersnap Feedback - I think that Scott Fletcher first submitted this entry. Why is this say "u[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1477]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I think that Scott Fletcher first submitted this entry. Why is this say "unknown user O"?
[Open #1158 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1158)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-12/14-44/d00dcac9-60f7-4e76-8d79-0b0419c0c070.png'>![Usersnap Feedback - I think that Scott Fletcher first submitted this entry. Why is this say "u(...)](https://usersnappublic.s3.amazonaws.com/2021-10-12/14-44/a77a8211-aae3-4cb8-9104-ee3a163e37ca.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-12/14-44/d00dcac9-60f7-4e76-8d79-0b0419c0c070.png'>Download original image</a>

**Browser**: Firefox 93 (Windows 10)
**Referer**: [https://participedia.net/case/4596](https://participedia.net/case/4596)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
This is a data issue. It may have been added while the website had other bugs. I adjusted the data and now we're displaying Scott as the contributor.
