### ISSUE TITLE
Usersnap Feedback - Trying to set this test to hidden and get this error modal.

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1479]
**Sender**: jesi.carson@gmail.com
**Comment**: Trying to set this test to hidden and get this error modal.
[Open #1160 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1160)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-15/22-02/e6d26513-8f93-49e6-87cd-8914cd9fbf01.png'>![Usersnap Feedback - Trying to set this test to hidden and get this error modal.](https://usersnappublic.s3.amazonaws.com/2021-10-15/22-02/c7cb946c-4f2e-44aa-a943-91c60a6f4979.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-15/22-02/e6d26513-8f93-49e6-87cd-8914cd9fbf01.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [https://participedia.net/case/7746/edit](https://participedia.net/case/7746/edit)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
This is a data issue happened probably because other languages aren't there. It's probably happened when we had issues with localization. Hid now.
