### ISSUE TITLE
Usersnap Feedback - Can’t hide these tests. Pan please have a look thx.

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1480]
**Sender**: jesi.carson@gmail.com
**Comment**: Can’t hide these tests. Pan please have a look thx.
[Open #1161 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1161)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-15/22-04/2c7e6189-987f-4bac-a370-78b2ad8fb6bb.png'>![Usersnap Feedback - Can’t hide these tests. Pan please have a look thx.](https://usersnappublic.s3.amazonaws.com/2021-10-15/22-04/9291ca44-2b8b-425f-aa17-715e05305bfe.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-15/22-04/2c7e6189-987f-4bac-a370-78b2ad8fb6bb.png'>Download original image</a>

**Browser**: Safari 14 (iOS)
**Referer**: [https://participedia.net/case/7743/edit](https://participedia.net/case/7743/edit)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
The entry does have a title. It was already published. I went in to edit, unchecked the featured box and checked the hidden box. This modal seems like a bug

I was able to hide 2 or 3 tests before this started happening. 

@paninee

**Comment by paninee** [comment]
Removed.
