### ISSUE TITLE
Usersnap Feedback - Fix formatting

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1481]
**Sender**: jesi.carson@gmail.com
**Comment**: Fix formatting
[Open #1162 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1162)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-18/17-31/5742e632-6f53-4a21-a765-d2b4266fe04e.png'>![Usersnap Feedback - Fix formatting](https://usersnappublic.s3.amazonaws.com/2021-10-18/17-31/36324a1d-4e10-4e65-87a4-2d9adf935d14.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-18/17-31/5742e632-6f53-4a21-a765-d2b4266fe04e.png'>Download original image</a>

**Browser**: Chrome 94 (Macintosh)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1920 x 1080 **Browser size**: 1280 x 720

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
Fixed and deployed. @jesicarson
