### ISSUE TITLE
Usersnap Feedback - The first four "test" entries that appear on the results for "search all" [...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1484]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: The first four "test" entries that appear on the results for "search all" cannot be hidden. I get this error message when I select "hide" and publish.
[Open #1165 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1165)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-20/15-26/009baa97-eba0-4fec-8d7f-8364049ce80b.png'>![Usersnap Feedback - The first four "test" entries that appear on the results for "search all" (...)](https://usersnappublic.s3.amazonaws.com/2021-10-20/15-26/4e88414c-31cf-460c-9630-e29a13e91e7b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-20/15-26/009baa97-eba0-4fec-8d7f-8364049ce80b.png'>Download original image</a>

**Browser**: Firefox 93 (Windows 10)
**Referer**: [https://participedia.net/case/7743/edit](https://participedia.net/case/7743/edit)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/138829721-9f56dfaa-d542-469b-8a58-bf457f273036.png)

**Comment by paninee** [comment]
Removed.
