### ISSUE TITLE
Usersnap Feedback - I went to Scarborough senior high school

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1485]
**Sender**: adellebarrows12@gmail.com
**Comment**: I went to Scarborough senior high school
[Open #1166 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1166)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-20/15-34/2384a654-1875-41ed-96f3-e155c202a85d.png'>![Usersnap Feedback - I went to Scarborough senior high school](https://usersnappublic.s3.amazonaws.com/2021-10-20/15-34/aed0d2b3-9946-49f0-b8dc-3fcac99db3bf.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-20/15-34/2384a654-1875-41ed-96f3-e155c202a85d.png'>Download original image</a>

**Browser**: Chrome 80 (Android 10)
**Referer**: [https://participedia.net/case/4527](https://participedia.net/case/4527)
**Screen size**: 360 x 720 **Browser size**: 360 x 560

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
@jesicarson what do I do with this?
