### ISSUE TITLE
Usersnap Feedback - Is it OK for us to remove "TEST TITLE" from this case? If so, please do so.

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1486]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Is it OK for us to remove "TEST TITLE" from this case? If so, please do so.
[Open #1167 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1167)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-26/15-07/23d7a557-ec3f-44b2-9836-41cf0206c635.png'>![Usersnap Feedback - Is it OK for us to remove "TEST TITLE" from this case? If so, please do so.](https://usersnappublic.s3.amazonaws.com/2021-10-26/15-07/e3c10108-60c7-412f-8a0e-3a9adb8a0848.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-26/15-07/23d7a557-ec3f-44b2-9836-41cf0206c635.png'>Download original image</a>

**Browser**: Firefox 93 (Windows 10)
**Referer**: [https://participedia.net/case/6044](https://participedia.net/case/6044)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1075

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
Removed.
