### ISSUE TITLE
Usersnap Feedback - Hello. I've been trying to upload an organization entry to the site today [...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1488]
**Sender**: wallaj9@mcmaster.ca
**Comment**: Hello. I've been trying to upload an organization entry to the site today and it will not publish the full entry. When I did the full version entry and hit publish, the "publishing" pop up window with the three loading dots came up but it stayed on that screen for hours before I eventually reloaded the page and lost all the entry data. I then went back and re-did the entry as a quick submit to try to get some of the information up on the site. It successfully published the quick submit, but only when I did not add images or use any of the dropdown lists. I then went back to edit the organization entry to add all the other elements and it successfully published all text fields but would not go past the "publishing" pop up when I try to add images or use any of the drop down lists. The images are less than 5MB. So, essentially the site is allowing me to upload text info, files (pdfs), and links, however, it will not allow me to add images or use the drop down menus for sections such as "Scope of Operations & Activities" and "Focus Area."
[Open #1169 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1169)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-27/01-10/1606b0d6-bd12-491e-a480-2e9908784d07.png'>![Usersnap Feedback - Hello. I've been trying to upload an organization entry to the site today (...)](https://usersnappublic.s3.amazonaws.com/2021-10-27/01-10/c17beb8f-b195-465a-aaaf-8e09ac28b994.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-27/01-10/1606b0d6-bd12-491e-a480-2e9908784d07.png'>Download original image</a>

**Browser**: Chrome 95 (Windows 10)
**Referer**: [https://participedia.net/user/421614](https://participedia.net/user/421614)
**Screen size**: 1280 x 720 **Browser size**: 1600 x 762

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
@jesicarson fixed and deployed, removed red banner.
