### ISSUE TITLE
Usersnap Feedback - I have tried to add this case unsuccessfully to the "Public Participation [...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1489]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I have tried to add this case unsuccessfully to the "Public Participation for Racial Justice" collection, but it won't let me.
[Open #1170 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1170)

<a href='https://usersnappublic.s3.amazonaws.com/2021-10-27/02-00/0304e0eb-a12c-48b7-aaf2-cc152d87706d.png'>![Usersnap Feedback - I have tried to add this case unsuccessfully to the "Public Participation (...)](https://usersnappublic.s3.amazonaws.com/2021-10-27/02-00/1e4a9f9a-6130-402a-8874-0bf09e029151.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-10-27/02-00/0304e0eb-a12c-48b7-aaf2-cc152d87706d.png'>Download original image</a>

**Browser**: Firefox 93 (Windows 10)
**Referer**: [https://participedia.net/case/7705](https://participedia.net/case/7705)
**Screen size**: 1600 x 1000 **Browser size**: 1600 x 896

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
Fixed and moved into "Public Participation for Racial Justice" collection
![image](https://user-images.githubusercontent.com/29439995/139169638-b78d1924-e9d3-41a3-9806-1a7cedaa3f8a.png)

**Comment by plscully** [comment]
@paninee Thank you!
