### ISSUE TITLE
User Issue - Search function only works from home page

### ISSUE THREAD

**Issue by scottofletcher** [participedia/usersnaps#149]
Submitted by Lucy J Parry: 
Search function only works from home page

Details:
Text search from any page but the home page fails to load. URL is changed (eg. "https://participedia.xyz/case/4512" becomes "https://participedia.xyz/case/4512?query=testing") but the page does not load.

Note: 
I (Scott) also experience this problem. I have to constantly navigate back to the homepage (by clicking the logo at the top left-hand corner) and then searching from there.

**Comment by jesicarson** [comment]
known bug. closing via https://github.com/participedia/frontend/issues/836
