### ISSUE TITLE
Usersnap Feedback - LinkedIn social share broken. Flagged by user by email to info@pp.  Please [...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1493]
**Sender**: jesi.carson@gmail.com
**Comment**: LinkedIn social share broken. Flagged by user by email to info@pp.  Please fix. Thanks!
[Open #1174 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1174)

<a href='https://usersnappublic.s3.amazonaws.com/2021-11-08/18-36/b5c33b2c-e63c-4120-a9f3-131f2285c68a.png'>![Usersnap Feedback - LinkedIn social share broken. Flagged by user by email to info@pp.  Please (...)](https://usersnappublic.s3.amazonaws.com/2021-11-08/18-36/56452255-c329-4c1a-9901-8320659c7347.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-11-08/18-36/b5c33b2c-e63c-4120-a9f3-131f2285c68a.png'>Download original image</a>

**Browser**: Chrome 95 (Macintosh)
**Referer**: [https://participedia.net/case/5729](https://participedia.net/case/5729)
**Screen size**: 1920 x 1080 **Browser size**: 1602 x 796

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Here's the error:

![Screen Shot 2021-11-08 at 9 35 28 AM](https://user-images.githubusercontent.com/13560530/140790844-87c70888-e84e-42fa-ac8a-e92ed1aa915c.png)

**Comment by paninee** [comment]
Fixed and deployed live.
![image](https://user-images.githubusercontent.com/29439995/141613189-ef30645d-520d-4eaf-a3a9-10716a4fc085.png)
