### ISSUE TITLE
Usersnap Feedback - When I scroll my mouse over the URL, the entire thing lights up in red (go[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#151]
**Sender**: scottowenfletcher@gmail.com
**Comment**: When I scroll my mouse over the URL, the entire thing lights up in red (good) BUT only part of the hyperlinked text is underlined (bad).
[Open #164 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/164)

<a href='https://usersnappublic.s3.amazonaws.com/2018-04-16/16-47/b73d766c-9065-4a2f-819f-b20d3f47c0ea.png'>![Usersnap Feedback - When I scroll my mouse over the URL, the entire thing lights up in red (go(...)](https://usersnappublic.s3.amazonaws.com/2018-04-16/16-47/e71855c4-75e6-4cd2-bf08-be881d5f7955.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-04-16/16-47/b73d766c-9065-4a2f-819f-b20d3f47c0ea.png'>Download original image</a>

**Browser**: Chrome 65 (Windows 10)
**Referer**: [https://participedia.xyz/case/4225](https://participedia.xyz/case/4225)
**Screen size**: 1280 x 720 **Browser size**: 1422 x 600

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
closing via: https://github.com/participedia/usersnaps/issues/152
