### ISSUE TITLE
Usersnap Feedback - Stage Test: Update this badge to the same one we use on the cards 

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1520]
**Sender**: jesi.carson@gmail.com
**Comment**: Update this badge to the same one we use on the cards (no drop shadow, slightly larger)
[Open #1201 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1201)

<a href='https://usersnappublic.s3.amazonaws.com/2021-11-23/17-35/56724876-b174-4767-9294-58e60e5665d4.png'>![Usersnap Feedback - Update this badge to the same one we use on the cards (no drop shadow, sli(...)](https://usersnappublic.s3.amazonaws.com/2021-11-23/17-35/0aaf6d23-dd1f-42a4-8835-79c028501f61.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-11-23/17-35/56724876-b174-4767-9294-58e60e5665d4.png'>Download original image</a>

**Browser**: Chrome 95 (Macintosh)
**Referer**: [http://ppedia-stage.herokuapp.com/search?query=&selectedCategory=case&openFilters=1](http://ppedia-stage.herokuapp.com/search?query=&selectedCategory=case&openFilters=1)
**Screen size**: 1920 x 1080 **Browser size**: 1408 x 796

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/143720721-880aef9b-3773-4f45-b4a0-02e4ed6d7064.png)
