### ISSUE TITLE
Usersnap Feedback - I received this error message after editing an English language organizati[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1526]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I received this error message after editing an English language organization entry. See this entry 4for "public Agenda" -- https://participedia.net/organization/265
[Open #1207 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1207)

<a href='https://usersnappublic.s3.amazonaws.com/2021-11-30/21-59/9bd0d681-7128-4cd1-a908-fe909bb64c5c.png'>![Usersnap Feedback - I received this error message after editing an English language organizati(...)](https://usersnappublic.s3.amazonaws.com/2021-11-30/21-59/daf67ce2-fb07-493d-80e2-bbc9ce6d0771.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-11-30/21-59/9bd0d681-7128-4cd1-a908-fe909bb64c5c.png'>Download original image</a>

**Browser**: Firefox 94 (Windows 10)
**Referer**: [https://participedia.net/organization/265/edit?full=1](https://participedia.net/organization/265/edit?full=1)
**Screen size**: 1600 x 1000 **Browser size**: 1600 x 896

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by plscully** [comment]
@paninee @jesicarson  This was odd. Unfortunately I had spent a fair amount of time making edits to this entry before I received this "Portuguese: Cannot create a organization without at least a title" message.  When I clicked again it said "internal server error."

**Comment by jesicarson** [comment]
@paninee please have a look at this. Sounds similar to this issue: https://github.com/participedia/usersnaps/issues/1521

**Comment by paninee** [comment]
Reproduced https://www.loom.com/share/bbe3bb57beca45a8b2c0cc6af3f8de02

**Comment by paninee** [comment]
Data issue. Only happens with this entry. Fixed the translation.
