### ISSUE TITLE
Usersnap Feedback - I am trying to publish/create a new special collection but I get an endles[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1533]
**Sender**: emiljapa@mcmaster.ca
**Comment**: I am trying to publish/create a new special collection but I get an endless loop of 'Publishing...'
[Open #1214 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1214)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-06/16-22/241934ad-e119-43af-a475-554e8b57edb1.png'>![Usersnap Feedback - I am trying to publish/create a new special collection but I get an endles(...)](https://usersnappublic.s3.amazonaws.com/2021-12-06/16-22/e7ced056-343f-4fe0-bc97-451a0bd0e655.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-06/16-22/241934ad-e119-43af-a475-554e8b57edb1.png'>Download original image</a>

**Browser**: Chrome 96 (Windows 10)
**Referer**: [https://participedia.net/collection/new](https://participedia.net/collection/new)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 961

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
Fixed. Deployed.
