### ISSUE TITLE
Usersnap Feedback - Formatting bug on the homepage

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1536]
**Sender**: jesi.carson@gmail.com
**Comment**: Formatting bug on the homepage
[Open #1217 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1217)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-06/21-18/7af14483-c4e7-4d74-b5b8-9cb3396128f9.png'>![Usersnap Feedback - Formatting bug on the homepage](https://usersnappublic.s3.amazonaws.com/2021-12-06/21-18/898abd0b-26df-4763-a091-0c233206401c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-06/21-18/7af14483-c4e7-4d74-b5b8-9cb3396128f9.png'>Download original image</a>

**Browser**: Chrome 96 (Macintosh)
**Referer**: [https://participedia.net/#map](https://participedia.net/#map)
**Screen size**: 1920 x 1080 **Browser size**: 1744 x 895

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee please fix today if possible. 

A few more screenshots:

![Screen Shot 2021-12-06 at 12 19 01 PM](https://user-images.githubusercontent.com/13560530/144916442-f3b00a6e-da48-4549-b8e4-6f091e314c87.png)

![Screen Shot 2021-12-06 at 12 19 08 PM](https://user-images.githubusercontent.com/13560530/144916449-0a400632-1a2f-481f-aa82-b240ba72eafd.png)

![Screen Shot 2021-12-06 at 12 19 14 PM](https://user-images.githubusercontent.com/13560530/144916455-0664fc5b-9e03-4fea-8f64-23886bdb9b73.png)

**Comment by paninee** [comment]
Cannot reproduce.
![image](https://user-images.githubusercontent.com/29439995/144926094-e155ec22-3b9a-43e7-8632-dc17777f4dca.png)
