### ISSUE TITLE
Usersnap Feedback - I'm editing this case so most of the sidebar data was already filled out. [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#154]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I'm editing this case so most of the sidebar data was already filled out. It's not immediately obvious that these are the selected values. When going through and doing clean-up, I like to be able to easily see what values have been selected so I can quickly judge whether they are correct. It would be handy if they were indented slightly with an 'X' to the left so I can easily remove one or more of them without having to open the drop-down menu, scroll to the value, and deselect it.
[Open #167 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/167)

<a href='https://usersnappublic.s3.amazonaws.com/2018-04-16/17-21/e4669af4-1200-4d2e-91e3-cda9cea0dc5b.png'>![Usersnap Feedback - I'm editing this case so most of the sidebar data was already filled out. (...)](https://usersnappublic.s3.amazonaws.com/2018-04-16/17-21/5a8ef35f-d14a-4c58-8088-2099598ce6d4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-04-16/17-21/e4669af4-1200-4d2e-91e3-cda9cea0dc5b.png'>Download original image</a>

**Browser**: Chrome 65 (Windows 10)
**Referer**: [https://participedia.xyz/case/445/edit](https://participedia.xyz/case/445/edit)
**Screen size**: 1280 x 720 **Browser size**: 1422 x 600

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
covered by participedia/frontend#716
