### ISSUE TITLE
Usersnap Feedback - This error message also appeared on several other spam organization entrie[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1542]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: This error message also appeared on several other spam organization entries. This messages makes it impossible to save an entry after it has been marked as "hidden," so the spam remains.
[Open #1223 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1223)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-08/16-15/07e799de-d05f-4133-878d-05b3af9b1cf6.png'>![Usersnap Feedback - This error message also appeared on several other spam organization entrie(...)](https://usersnappublic.s3.amazonaws.com/2021-12-08/16-15/ccd6f922-0304-499d-b1e2-5d19ceceab06.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-08/16-15/07e799de-d05f-4133-878d-05b3af9b1cf6.png'>Download original image</a>

**Browser**: Firefox 95 (Windows 10)
**Referer**: [https://participedia.net/organization/7838/edit](https://participedia.net/organization/7838/edit)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 985

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee please have a look asap thank you

**Comment by jesicarson** [comment]
related #1540 and #1541

**Comment by jesicarson** [comment]
I was able to reproduce this bug, and got the same error as Pat. 

But I did block the user, so at least they can't publish any new entries.

**Comment by plscully** [comment]
@jesicarson @paninee  Years ago on the Drupal version of PPedia there was a function where once you blocked a user all their entries were automatically hidden. Is this something we should consider adding to the auth-o and captcha functions?

**Comment by jesicarson** [comment]
@plscully Yes I remember that. Since we use a 3rd party (Auth0) for authentication and blocking sign in, I'm not sure what our options are in terms of linking blocking users to hiding entries (they're different databases managed by separate user interfaces currently). Building our own authentication system is a very big undertaking, which is why we rely on Auth0. Pan and I will discuss asap, as the Auth0 sign up captcha is obviously not as effective as we'd hoped. 

As always we appreciate your eyes on the site Pat! Thank you!

**Comment by paninee** [comment]
This looks like a translation issue. Will look into it.

**Comment by paninee** [comment]
I hid them manually for now until we can sort this out.

**Comment by plscully** [comment]
> I hid them manually for now until we can sort this out.

@paninee @jesicarson I'm sorry to report that the same type of thing appeared this morning. Unfortunately this time its especially bad, with 6 entries advertising call girl services and another 3 for gaming & gambling

**Comment by jesicarson** [comment]
@paninee please hide today's spam as soon as you can, thank you.
