### ISSUE TITLE
Usersnap Feedback - There appears to be a duplication issue going on here as well.

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1543]
**Sender**: jesi.carson@gmail.com
**Comment**: There appears to be a duplication issue going on here as well.
[Open #1224 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1224)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-08/22-43/2a338635-5abd-4caa-a559-98896b0bc825.png'>![Usersnap Feedback - There appears to be a duplication issue going on here as well.](https://usersnappublic.s3.amazonaws.com/2021-12-08/22-43/b1db0367-ac10-47d8-afb9-617a4fdbf6d2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-08/22-43/2a338635-5abd-4caa-a559-98896b0bc825.png'>Download original image</a>

**Browser**: Chrome 96 (Macintosh)
**Referer**: [https://participedia.net/search](https://participedia.net/search)
**Screen size**: 1920 x 1080 **Browser size**: 1440 x 796

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
2 different users trying to publish "idea collection map"

This one worked, they only published it once: https://participedia.net/user/421787

This one appears to have duplicated the entry 4 times: https://participedia.net/user/421691

**Comment by jesicarson** [comment]
Attempted to edit one of the duplicated idea collection map entries, and got the language error message @paninee 

I'm not sure this one is spam though, looks like a legit entry being attempted. 

![Screen Shot 2021-12-08 at 1 46 52 PM](https://user-images.githubusercontent.com/13560530/145289735-b25e0a72-3e7d-455e-88ba-86bb41b57042.png)

**Comment by paninee** [comment]
@jesicarson This is not a spam. I reproduce the issue. Entries are being created even when the form validation failed. https://www.loom.com/share/d47b76a429c14ac88d90b6ba3d92433d

**Comment by jesicarson** [comment]
Right sorry. I added the label to a batch of issues and must have included this one by mistake. We can remove the spam label. 

Glad you can reproduce and fix.

**Comment by jesicarson** [comment]
@paninee there are a bunch of new duplicates today - see #1547

**Comment by paninee** [comment]
I hid these ones already.
