### ISSUE TITLE
Usersnap Feedback - Duplicates to remove

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1547]
**Sender**: jesi.carson@gmail.com
**Comment**: Duplicates to remove
[Open #1228 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1228)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-14/18-13/d98bf412-3f66-43f9-82ce-68655addd8d1.png'>![Usersnap Feedback - Duplicates to remove](https://usersnappublic.s3.amazonaws.com/2021-12-14/18-13/f9573edf-3683-43eb-bf3c-8f8b079b7180.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-14/18-13/d98bf412-3f66-43f9-82ce-68655addd8d1.png'>Download original image</a>

**Browser**: Chrome 96 (Macintosh)
**Referer**: [https://participedia.net/search?page=2](https://participedia.net/search?page=2)
**Screen size**: 1920 x 1080 **Browser size**: 1627 x 904

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Multiple entries from https://participedia.net/case/7911 to https://participedia.net/case/7930 

by user https://participedia.net/user/421900

**Comment by jesicarson** [comment]
Error message when I try to hide the entries:
 
![Screen Shot 2021-12-14 at 9 16 24 AM](https://user-images.githubusercontent.com/13560530/146047257-6c455704-bdbc-47a3-bc6b-32a5434687c7.png)

**Comment by jesicarson** [comment]
@paninee please have a look as soon as you can. thanks.

**Comment by paninee** [comment]
I cannot reproduce the issue. This should not be able to happen anymore since the deployment on December 12. The only reason I can think of that this happens is the user has not refreshed the pages. All the fixes we added applied to the web frontend, including the CAPTCHA and the validation fix. I cleaned up the dupes and block the spam users. Let's see if this still happens.

**Comment by paninee** [comment]
I reproduced it now.

**Comment by paninee** [comment]
Done and fixed the publishing issue as well. They're now live.
