### ISSUE TITLE
Usersnap Feedback - More duplicates

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1548]
**Sender**: jesi.carson@gmail.com
**Comment**: More duplicates
[Open #1229 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1229)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-14/18-17/0632da81-c590-45a5-b4a9-cefe8b792864.png'>![Usersnap Feedback - More duplicates](https://usersnappublic.s3.amazonaws.com/2021-12-14/18-17/dac6e7b0-f0d8-48a5-8eb1-664c09e6a1e3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-14/18-17/0632da81-c590-45a5-b4a9-cefe8b792864.png'>Download original image</a>

**Browser**: Chrome 96 (Macintosh)
**Referer**: [https://participedia.net/search?page=3](https://participedia.net/search?page=3)
**Screen size**: 1920 x 1080 **Browser size**: 1627 x 904

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
related to #1547

**Comment by paninee** [comment]
Hid all of them.
