### ISSUE TITLE
Usersnap Feedback - Hello there, I have trouble publishing content on the website. I get the e[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1549]
**Sender**: foulques.renard@citoyensdedemain.org
**Comment**: Hello there,
I have trouble publishing content on the website. I get the error: "Cannot publish case without at least a title". But I can't find where the problem is...
Thanks a lot :)
[Open #1230 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1230)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-15/09-01/043fe6db-df81-4396-8da1-cdd6bb40e914.png'>![Usersnap Feedback - Hello there, I have trouble publishing content on the website. I get the e(...)](https://usersnappublic.s3.amazonaws.com/2021-12-15/09-01/a3140adf-bbc2-44e6-861f-04afb62bcf17.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-15/09-01/043fe6db-df81-4396-8da1-cdd6bb40e914.png'>Download original image</a>

**Browser**: Chrome 96 (Windows 10)
**Referer**: [https://participedia.net/case/6044/edit](https://participedia.net/case/6044/edit)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 577

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
Fixed. Have them refresh the page and try again. @jesicarson

**Comment by jesicarson** [comment]
emailed them. thanks pan.
