### ISSUE TITLE
Usersnap Feedback - Received this error message when I tried to hide an entry from Spam user. [...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1551]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Received this error message when I tried to hide an entry from Spam user. The first time I saw this I logged out and logged back in so that I could complete captcha. I tried again and still received this error message.
[Open #1232 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1232)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-20/16-06/4a8ee11e-6fd9-4ee1-8968-bd8613b94f54.png'>![Usersnap Feedback - Received this error message when I tried to hide an entry from Spam user. (...)](https://usersnappublic.s3.amazonaws.com/2021-12-20/16-06/56a9f8e8-acbd-4e52-9e4e-a284f6efc0f7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-20/16-06/4a8ee11e-6fd9-4ee1-8968-bd8613b94f54.png'>Download original image</a>

**Browser**: Firefox 95 (Windows 10)
**Referer**: [https://participedia.net/case/7949/edit](https://participedia.net/case/7949/edit)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 985

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
I completed the captcha, but got the language error when trying to publish:

![Screen Shot 2021-12-20 at 9 39 51 AM](https://user-images.githubusercontent.com/13560530/146809252-b74a9e08-390c-4e7f-b858-b90ddbfc29cf.png)

Checking in with @paninee this morning and we'll discuss the plan to address this ongoing issue.

**Comment by paninee** [comment]
Hid
