### ISSUE TITLE
Usersnap Feedback - Spam - Please block user and hide their two entries.

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1552]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block user and hide their two entries.
[Open #1233 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1233)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-20/16-07/7be54546-89eb-4b23-8644-9865517336bb.png'>![Usersnap Feedback - Spam - Please block user and hide their two entries.](https://usersnappublic.s3.amazonaws.com/2021-12-20/16-07/4b1157ec-d950-4ebb-9443-5b1737ba8672.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-20/16-07/7be54546-89eb-4b23-8644-9865517336bb.png'>Download original image</a>

**Browser**: Firefox 95 (Windows 10)
**Referer**: [https://participedia.net/case/7949](https://participedia.net/case/7949)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 985

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
Blocked and hid.
