### ISSUE TITLE
Usersnap Feedback - While trying to do a lengthy editing job on this case I had to re=select t[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1553]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: While trying to do a lengthy editing job on this case I had to re=select the Captca every 60 sconds. Sometimes the Captcha allows me to select it and sometimes it doesn't. When it doesn't I lose work so I gave up on editing this.
[Open #1234 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1234)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-21/16-56/3662ed42-e096-46a9-85fd-b595c45914f0.png'>![Usersnap Feedback - While trying to do a lengthy editing job on this case I had to re=select t(...)](https://usersnappublic.s3.amazonaws.com/2021-12-21/16-56/3ce64e53-7b7f-48bd-9c05-e917915c50bd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-21/16-56/3662ed42-e096-46a9-85fd-b595c45914f0.png'>Download original image</a>

**Browser**: Firefox 95 (Windows 10)
**Referer**: [https://participedia.net/case/7393/edit?full=1](https://participedia.net/case/7393/edit?full=1)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 985

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee did you work on publishing issues after this was flagged by Pat? Maybe this is already resolved. If not, please have a look when you can. Thanks!

**Comment by plscully** [comment]
Hi @jesicarson - Yes, @paninee resolved this.

**Comment by paninee** [comment]
@jesicarson @plscully this does not sound like the publishing issue I fixed, but I cannot reproduce this issue. The recaptcha is always there. I have been editing the entry for 10 minutes.
