### ISSUE TITLE
Usersnap Feedback - Would be great if all selected values showed up like the first (highlighte[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#156]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Would be great if all selected values showed up like the first (highlighted in gray w/an 'X' for easy single-selection removal). "Type of organizer/manager" selection could/should still be below drop-down menu though.
[Open #169 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/169)

<a href='https://usersnappublic.s3.amazonaws.com/2018-04-16/17-31/8d1c15ba-4017-4454-a40f-3d5e6362bb2c.png'>![Usersnap Feedback - Would be great if all selected values showed up like the first (highlighte(...)](https://usersnappublic.s3.amazonaws.com/2018-04-16/17-31/cccd20c3-13ee-4b60-8657-40555fc98ff9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-04-16/17-31/8d1c15ba-4017-4454-a40f-3d5e6362bb2c.png'>Download original image</a>

**Browser**: Chrome 65 (Windows 10)
**Referer**: [https://participedia.xyz/case/445/edit](https://participedia.xyz/case/445/edit)
**Screen size**: 1280 x 720 **Browser size**: 1600 x 737

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
participedia/frontend#716
