### ISSUE TITLE
Usersnap Feedback - Publish button on edit profile not working. Bug

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1563]
**Sender**: jesi.carson@gmail.com
**Comment**: Publish button on edit profile not working. Bug
[Open #1244 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1244)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-31/19-45/da9c19af-de71-4623-8dbd-e05c352955cf.png'>![Usersnap Feedback - Publish button on edit profile not working. Bug](https://usersnappublic.s3.amazonaws.com/2021-12-31/19-45/3debd867-b751-4a1d-a633-a0a4261fc979.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-31/19-45/da9c19af-de71-4623-8dbd-e05c352955cf.png'>Download original image</a>

**Browser**: Safari 15 (iOS)
**Referer**: [https://participedia.net/user/1189/edit](https://participedia.net/user/1189/edit)
**Screen size**: 390 x 844 **Browser size**: 390 x 745

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by paninee** [comment]
@jesicarson  fixed and deployed live
