### ISSUE TITLE
Usersnap Feedback - BUG - Cannot edit this new collection. Attempting to click "hide" after th[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1575]
**Sender**: jesi.carson@gmail.com
**Comment**: BUG - Cannot edit this new collection. Attempting to click "hide" after the test collection was published successfully, and get this error.
[Open #1256 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1256)

<a href='https://usersnappublic.s3.amazonaws.com/2022-01-12/18-53/59d8e651-afcb-450e-817b-d19e5821f5d4.png'>![Usersnap Feedback - BUG - Cannot edit this new collection. Attempting to click "hide" after th(...)](https://usersnappublic.s3.amazonaws.com/2022-01-12/18-53/64ddb9ac-d721-42ed-a887-41ad37d24838.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2022-01-12/18-53/59d8e651-afcb-450e-817b-d19e5821f5d4.png'>Download original image</a>

**Browser**: Chrome 97 (Macintosh)
**Referer**: [https://participedia.net/collection/8010/edit](https://participedia.net/collection/8010/edit)
**Screen size**: 1920 x 1080 **Browser size**: 1440 x 796

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee This needs to be addressed asap, as Bonny has an article coming out in a few weeks that will need to link to a new collection, but we cannot create a new collection because of this bug. Thanks!

**Comment by jesicarson** [comment]
Note - I was able to publish this collection, but not edit it. I had not made any changes to the title when I got the error. 

![Screen Shot 2022-01-12 at 9 53 25 AM](https://user-images.githubusercontent.com/13560530/149195675-17d79234-e9a1-4072-835d-69062e3a7a33.png)

**Comment by paninee** [comment]
@jesicarson  fixed and deployed live
