### ISSUE TITLE
Usersnap Feedback - Filters button should be removed from collections on MOBILE.

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1580]
**Sender**: jesi.carson@gmail.com
**Comment**: Filters button should be removed from collections.
[Open #1261 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1261)

<a href='https://usersnappublic.s3.amazonaws.com/2022-01-26/16-42/f0d17307-80a4-400f-88ec-d187c85a1e37.png'>![Usersnap Feedback - Filters button should be removed from collections.](https://usersnappublic.s3.amazonaws.com/2022-01-26/16-42/845603cc-7f80-45e1-a6f0-19e2218857b3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2022-01-26/16-42/f0d17307-80a4-400f-88ec-d187c85a1e37.png'>Download original image</a>

**Browser**: Safari 15 (iOS)
**Referer**: [https://participedia.net/collection/8015?selectedCategory=case&openFilters=1](https://participedia.net/collection/8015?selectedCategory=case&openFilters=1)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee The filters button is only visible on collections on mobile. Please remove. Thanks!

**Comment by jesicarson** [comment]
![Screen Shot 2022-01-26 at 9 09 37 AM](https://user-images.githubusercontent.com/13560530/151212109-4eda6eb8-968a-4e8a-967a-a921bfeed114.png)

**Comment by paninee** [comment]
@jesicarson why do we remove it from mobile, but not desktop?
At the moment, the filter button on collection takes the user to the case section on both mobile and desktop.

**Comment by paninee** [comment]
@jesicarson never mind, I was looking at the wrong page.
