### ISSUE TITLE
Usersnap Feedback - Remove collections link on MOBILE

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1581]
**Sender**: jesi.carson@gmail.com
**Comment**: The “collections” link below the drop down is odd. 
[Open #1262 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1262)

<a href='https://usersnappublic.s3.amazonaws.com/2022-01-26/16-43/5183f959-e2cb-4c55-8418-57d56c4041da.png'>![Usersnap Feedback - The “collections” link below the drop down is odd. It should be in the dro(...)](https://usersnappublic.s3.amazonaws.com/2022-01-26/16-43/305844c2-4b7b-41cd-b65c-820625f88558.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2022-01-26/16-43/5183f959-e2cb-4c55-8418-57d56c4041da.png'>Download original image</a>

**Browser**: Safari 15 (iOS)
**Referer**: [https://participedia.net/collection/8015](https://participedia.net/collection/8015)
**Screen size**: 390 x 844 **Browser size**: 390 x 664

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
@paninee actually we removed the collections tab on desktop (because it was a different interaction than sorting the collection entries by type). Let's remove it on mobile as well. Thank you.

**Comment by jesicarson** [comment]
![Screen Shot 2022-01-26 at 9 08 43 AM](https://user-images.githubusercontent.com/13560530/151211968-b2a3f647-d992-46fd-8d98-f4a7feb6a859.png)

**Comment by paninee** [comment]
![Uploading image.png…]()
