### ISSUE TITLE
Usersnap Feedback - Broken Images

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#159]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Images from these two case do not display properly in the body of the cases and also a whole in the search display. Here are links to the two cases on .net
https://participedia.net/en/cases/implementation-makueni-county-participatory-budgeting-framework-fy-2015-2016 

https://participedia.net/en/cases/west-pokot-county-participatory-budget-hearings-kenya 
[Open #172 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/172)

<a href='https://usersnappublic.s3.amazonaws.com/2018-04-25/23-43/651611c7-6e43-4df0-8672-460fb74914eb.png'>![Usersnap Feedback - Images from these two case do not display properly in the body of the case(...)](https://usersnappublic.s3.amazonaws.com/2018-04-25/23-43/3d9644a4-8be4-4b14-9a13-65221107a709.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-04-25/23-43/651611c7-6e43-4df0-8672-460fb74914eb.png'>Download original image</a>

**Browser**: Chrome 65 (Windows 10)
**Referer**: [https://participedia.xyz/cases?query=Kenya](https://participedia.xyz/cases?query=Kenya)
**Screen size**: 1920 x 1200 **Browser size**: 1745 x 972

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
also see: https://github.com/participedia/usersnaps/issues/166
