### ISSUE TITLE
[USERSNAP] Can't add organization to collection. Tried twice to publish this change, it doesn't save.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1591]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/organization/7787/edit
**Fields**:
- Add a comment: Can&#39;t add organization to collection. Tried twice to publish this change, it doesn&#39;t save.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/0c1579cf-985e-415c-b464-872aa418321a-annotated_132bfe3f-2374-4479-9c78-38eb5a87b577.png?etag=5ff835dd39c8086552c26d4b9ce6df63)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/0c1579cf-985e-415c-b464-872aa418321a-annotated_132bfe3f-2374-4479-9c78-38eb5a87b577.png?etag=5ff835dd39c8086552c26d4b9ce6df63)*

**Browser**: Chrome 98 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1258x902
**[Open #1274 in Usersnap](https://app.usersnap.com/l/feedback/0712d6b7-e58b-4c38-90fd-1deeca810f7a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee this is fixed right?
