### ISSUE TITLE
Usersnap Feedback - Search results image sizing - Ensure all images remain the same size, allo[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#16]
_From @davidascher on May 11, 2017 21:15_

**Sender**: jesi.carson@gmail.com
**Comment**: Search results image sizing - Ensure all images remain the same size, allow cropping both vertically and horizontally. 

We should also add a note in the edit mode for images of the recommended pixel size, to avoid unfriendly crops in future - but we'll live with them for now. 

(We've noted this in redpen, and I'm assuming this is still in the process of being updated, but I didn't see an issue about it on github yet so adding it here) 

Thanks,
Jesi
[Open #18 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/18)

<a href='https://usersnappublic.s3.amazonaws.com/2017-05-11/23-12/109c2cea-4a0c-45e2-8fed-f648dd342028.png'>![Usersnap Feedback - Search results image sizing - Ensure all images remain the same size, allo(...)](https://usersnappublic.s3.amazonaws.com/2017-05-11/23-12/524c8106-d322-4477-8fa8-230d744057e6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-05-11/23-12/109c2cea-4a0c-45e2-8fed-f648dd342028.png'>Download original image</a>

**Browser**: Chrome 57 (macOS Sierra)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1280 x 800 **Browser size**: 999 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

_Copied from original issue: participedia/frontend#350_

**Comment by andreadelrio** [comment]
I'd think this was referring to the size of the middle image above (Get to know Nuclear...) as it was smaller than the grey images on its sides.

It looks like that's been resolved (I'm guessing that by Sam).

![image](https://user-images.githubusercontent.com/4016496/27257259-729c306e-5384-11e7-81be-b0b6b86a13eb.png)

**Comment by davidascher** [comment]
cool.
