### ISSUE TITLE
[USERSNAP] Spam - Please block user. I hid this entry.  BTW, for a while there after we added Captcha the spam seemed to decrease significantly. Do we need to try something else now?

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1601]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8032
**Fields**:
- Add a comment: Spam - Please block user. I hid this entry. 
BTW, for a while there after we added Captcha the spam seemed to decrease significantly. Do we need to try something else now?

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/3850099a-6a1a-4574-9749-42d84e0b4f38-annotated_f9694ef7-165e-4c3b-a80b-ab9a618971b0.png?etag=744858d790bbf883d463a5e803bdc7dd)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/3850099a-6a1a-4574-9749-42d84e0b4f38-annotated_f9694ef7-165e-4c3b-a80b-ab9a618971b0.png?etag=744858d790bbf883d463a5e803bdc7dd)*

**Browser**: Firefox 97 (Windows 10)
**Screen size**: 1760x1100
**Browser size**: 1760x985
**[Open #1284 in Usersnap](https://app.usersnap.com/l/feedback/b28a4e15-7e24-4a3d-964b-7bd254486e92?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@plscully Pan is looking into whether or not these are bots, but we think they are likely real people (which is why it has slowed down, but not stopped). If that's the case, the only thing we could really do is to not let anyone create an account without being approved by an admin - but I'm not sure there's bandwidth on the project for this. I'll check in with Paul too.

**Comment by jesicarson** [comment]
blocked
