### ISSUE TITLE
[USERSNAP] Spam -- Please block user. I hid this entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1602]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/user/422256
**Fields**:
- Add a comment: Spam -- Please block user. I hid this entry.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/865224ab-779d-46c3-9861-d742f3d9ceb3-annotated_beccee75-4b5c-4966-b2d3-5ac14dcd72f3.png?etag=631e2c404d87eced7f6a5363d7043032)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/865224ab-779d-46c3-9861-d742f3d9ceb3-annotated_beccee75-4b5c-4966-b2d3-5ac14dcd72f3.png?etag=631e2c404d87eced7f6a5363d7043032)*

**Browser**: Firefox 98 (Windows 10)
**Screen size**: 1760x1100
**Browser size**: 1760x985
**[Open #1285 in Usersnap](https://app.usersnap.com/l/feedback/9210c89a-e7d4-41b1-b931-0e75fe1dd086?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
