### ISSUE TITLE
Usersnap Feedback - Brief Description is 280 characters not 140

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#161]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Brief Description is 280 characters not 140 
[Open #174 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/174)

<a href='https://usersnappublic.s3.amazonaws.com/2018-05-02/18-49/234cdc26-aad9-44f0-b919-45262b16b8c8.png'>![Usersnap Feedback - Brief Description is 280 characters not 140](https://usersnappublic.s3.amazonaws.com/2018-05-02/18-49/4fb8b3f8-ba6e-4448-8286-5924b8d33c8d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-05-02/18-49/234cdc26-aad9-44f0-b919-45262b16b8c8.png'>Download original image</a>

**Browser**: Chrome 65 (Windows 10)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 1280 x 720 **Browser size**: 1600 x 737

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
We decided that we would go with 280 because Twitter doubled their limit and the instructional text says 'tweet length'. The instructional text and placeholder just need to be updated to say "280 characters"

**Comment by jesicarson** [comment]
covered by: https://github.com/participedia/frontend/issues/806
