### ISSUE TITLE
[USERSNAP] Spam - Please block user. I hid both this entry and an organization entry with the same title from this user

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1612]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/case/8095
**Fields**:
- Add a comment: Spam - Please block user. I hid both this entry and an organization entry with the same title from this user

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/4d110b72-f563-4884-85e1-e217e86054a1-annotated_dcb7116d-0218-4dd4-b440-08c6f66c77c1.png?etag=7c997d55c590cc7f59bdb82aade2fc2c)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/4d110b72-f563-4884-85e1-e217e86054a1-annotated_dcb7116d-0218-4dd4-b440-08c6f66c77c1.png?etag=7c997d55c590cc7f59bdb82aade2fc2c)*

**Browser**: Firefox 98 (Windows 10)
**Screen size**: 1760x1100
**Browser size**: 1760x985
**[Open #1295 in Usersnap](https://app.usersnap.com/l/feedback/bed3da89-e2b2-43bc-96da-21c4f134465d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
