### ISSUE TITLE
[USERSNAP] Spam - Please block user. I hid this entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1613]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8093
**Fields**:
- Add a comment: Spam - Please block user. I hid this entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b50b6a84-694c-4283-9e28-c8ccc08c6ba9-annotated_e11681d3-bb62-4192-ab67-208f865e357d.png?etag=2145e3cd05f8105a01520248f5d69dc8)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b50b6a84-694c-4283-9e28-c8ccc08c6ba9-annotated_e11681d3-bb62-4192-ab67-208f865e357d.png?etag=2145e3cd05f8105a01520248f5d69dc8)*

**Browser**: Firefox 98 (Windows 10)
**Screen size**: 1760x1100
**Browser size**: 1760x985
**[Open #1296 in Usersnap](https://app.usersnap.com/l/feedback/3141a66c-0163-4d71-ae40-569fd9ef22a9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
