### ISSUE TITLE
[USERSNAP] Spam - please block user. I hid their two identical organization entries.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1614]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8101
**Fields**:
- Add a comment: Spam - please block user. I hid their two identical organization entries.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d3455765-1351-415e-966c-7f4f35fd63c8-annotated_898436b0-68e1-43af-8007-0adc8210ae46.png?etag=72cc0954b96bcba00ee581cc749e7705)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d3455765-1351-415e-966c-7f4f35fd63c8-annotated_898436b0-68e1-43af-8007-0adc8210ae46.png?etag=72cc0954b96bcba00ee581cc749e7705)*

**Browser**: Firefox 98 (Windows 10)
**Screen size**: 1760x1100
**Browser size**: 1760x985
**[Open #1297 in Usersnap](https://app.usersnap.com/l/feedback/cd8a7664-80b5-4e12-832e-63614121bf78?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
