### ISSUE TITLE
[USERSNAP] Switching to spanish (ES) on about page results in "internal server error"

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1619]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/about
**Fields**:
- Add a comment: Switching to spanish (ES) on about page results in &#34;internal server error&#34;

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2c311d01-f604-4d81-a384-35dab7d11398-annotated_62d873f3-c156-44a2-bff3-bf57a0b48047.png?etag=d4a7fdb05b6282dd9e91efd640bc55e1)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2c311d01-f604-4d81-a384-35dab7d11398-annotated_62d873f3-c156-44a2-bff3-bf57a0b48047.png?etag=d4a7fdb05b6282dd9e91efd640bc55e1)*

**Browser**: Chrome 99 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1255x807
**[Open #1302 in Usersnap](https://app.usersnap.com/l/feedback/993e2c48-5d64-41be-9a4a-0aa14de704f3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
![Screen Shot 2022-03-24 at 12 35 04 PM](https://user-images.githubusercontent.com/13560530/159996467-1d660008-2548-4c94-a108-216461fc2857.png)

**Comment by jesicarson** [comment]
was notified by a user email to info@participedia.net
