### ISSUE TITLE
Usersnap Feedback - It seems as though the map wont load when a case designates a country with[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#162]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: It seems as though the map wont load when a case designates a country without a specific city
[Open #175 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/175)

<a href='https://usersnappublic.s3.amazonaws.com/2018-05-04/22-31/4b948ac5-3f4c-4a5a-a5d7-3ff06045a502.png'>![Usersnap Feedback - It seems as though the map wont load when a case designates a country with(...)](https://usersnappublic.s3.amazonaws.com/2018-05-04/22-31/9934940d-a3ed-46f3-923d-d095ac08899d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-05-04/22-31/4b948ac5-3f4c-4a5a-a5d7-3ff06045a502.png'>Download original image</a>

**Browser**: Chrome 66 (Windows 10)
**Referer**: [https://participedia.xyz/case/5283](https://participedia.xyz/case/5283)
**Screen size**: 1920 x 1200 **Browser size**: 1745 x 972

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Good sleuthing!

**Comment by jesicarson** [comment]
@dethe since this is mostly aesthetic, could we hide this feature for now and return to re-implement it once all the other stuff is done?

**Comment by dethe** [comment]
Agreed. I thought I'd figured out a fix, but on examination, we never actually had country maps for all countries, not even for all the ones actually in our database for cases, etc. Going to pull this out until/if we decide to implement it properly, because as far as I can tell it never was fully working and we've wasted way too much time on it already.

**Comment by jesicarson** [comment]
Sounds good, thanks Dethe.
