### ISSUE TITLE
Usersnap Feedback - Duplicate location in sidebar and the map of Rwanda does not display

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#163]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Sidebar data lists the location twice and the map of Rwanda does not display
[Open #176 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/176)

<a href='https://usersnappublic.s3.amazonaws.com/2018-05-12/16-44/57b1457a-6315-4fab-9173-bdb4594228d7.png'>![Usersnap Feedback - Sidebar data lists the location twice and the map of Rwanda does not display](https://usersnappublic.s3.amazonaws.com/2018-05-12/16-44/081b4676-5b98-4ddf-b7f5-aaae7b14a157.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-05-12/16-44/57b1457a-6315-4fab-9173-bdb4594228d7.png'>Download original image</a>

**Browser**: Chrome 66 (Windows 10)
**Referer**: [https://participedia.xyz/case/5232](https://participedia.xyz/case/5232)
**Screen size**: 1920 x 1200 **Browser size**: 1745 x 972

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Fix is on the way, but the map of Rwanda will still not show because we removed the mini maps.

**Comment by jesicarson** [comment]
Yep about the map. Duplication bugs consolidated here: https://github.com/participedia/frontend/issues/855
