### ISSUE TITLE
[USERSNAP] no user info in wiki dropdown. bug? test?

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1631]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/case/7509
**Fields**:
- Add a comment: SPAM entry, please block user

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/22e4476c-4618-4cc0-ad60-d816a987d1ae-annotated_914d3145-933f-49ae-8d82-9b1eee76c952.png?etag=2db2a90db0542d824ccb89ec4e6e19a2)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/22e4476c-4618-4cc0-ad60-d816a987d1ae-annotated_914d3145-933f-49ae-8d82-9b1eee76c952.png?etag=2db2a90db0542d824ccb89ec4e6e19a2)*

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1334x612
**[Open #1314 in Usersnap](https://app.usersnap.com/l/feedback/5fe3ca0c-345a-4355-a0ec-729575cf8c45?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee this isn't spam - I assume you are doing tests, or these are old entries? There's no user showing up in the wiki history dropdown though - so that seems a bit odd. Can you look at this please? thanks.

**Comment by paninee** [comment]
This was a very old data from May 2021. It's a bad data. There's no author on that entry for some reason.

Hid the entry.
![image](https://user-images.githubusercontent.com/29439995/160468306-a0ea9cfe-780e-4b3f-87bd-0b36c6a4f96d.png)
![image](https://user-images.githubusercontent.com/29439995/160468338-c44dc16d-ed07-4fe0-974b-cd6f1b37c063.png)
