### ISSUE TITLE
[USERSNAP] Spam - Please block user. I hid this entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1634]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8121
**Fields**:
- Add a comment: Spam - Please block user. I hid this entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e19ce136-67df-4c01-a050-f83118ce6664-annotated_9310d59c-3df8-42ad-9a2c-5df92dcc9b53.png?etag=939e4a79e4c575ec45e9e800fe25693b)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e19ce136-67df-4c01-a050-f83118ce6664-annotated_9310d59c-3df8-42ad-9a2c-5df92dcc9b53.png?etag=939e4a79e4c575ec45e9e800fe25693b)*

**Browser**: Firefox 98 (Windows 10)
**Screen size**: 1760x1100
**Browser size**: 1760x985
**[Open #1317 in Usersnap](https://app.usersnap.com/l/feedback/c9bc858e-d5ad-485d-b7e7-507020c5a4ce?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
