### ISSUE TITLE
[USERSNAP] Spam. Block this user. Entry is hidden.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1635]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/organization/8128
**Fields**:
- Add a comment: Spam. Block this user. Entry is hidden.

**Browser**: Safari 15 (iOS)
**Screen size**: 390x844
**[Open #1318 in Usersnap](https://app.usersnap.com/l/feedback/25e3b3f3-1ffb-4074-bd95-8a1563864bcc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
