### ISSUE TITLE
[USERSNAP] Spam. Please block user. I hid this entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1636]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8132
**Fields**:
- Add a comment: Spam. Please block user. I hid this entry.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/71fb5871-87e0-4e54-8b16-530168b0d09f-annotated_68a3590d-b999-4204-bfe3-edc5b658e17b.png?etag=f8ce0271889d9600a359cd95453501f9)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/71fb5871-87e0-4e54-8b16-530168b0d09f-annotated_68a3590d-b999-4204-bfe3-edc5b658e17b.png?etag=f8ce0271889d9600a359cd95453501f9)*

**Browser**: Firefox 98 (Windows 10)
**Screen size**: 1760x1100
**Browser size**: 1760x985
**[Open #1319 in Usersnap](https://app.usersnap.com/l/feedback/dffbd130-63ec-43b8-b254-2af785351693?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
