### ISSUE TITLE
[USERSNAP] Spam - Block user - I hid these three entries

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1638]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/user/422406
**Fields**:
- Add a comment: Spam - Block user - I hid these three entries

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b015434d-f1bc-4af8-b3f0-1857cb415262-annotated_45ff81af-fb32-403f-957d-ef453561e324.png?etag=d65ddcf984c2efa3bfeea0cb306008de)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b015434d-f1bc-4af8-b3f0-1857cb415262-annotated_45ff81af-fb32-403f-957d-ef453561e324.png?etag=d65ddcf984c2efa3bfeea0cb306008de)*

**Browser**: Firefox 98 (Windows 10)
**Screen size**: 1760x1100
**Browser size**: 1760x985
**[Open #1321 in Usersnap](https://app.usersnap.com/l/feedback/c1898cca-a598-4040-8d46-569bab1c9a08?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
Blocked
