### ISSUE TITLE
Usersnap Feedback - User Profile - Biography text should be black, not blue.

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#164]
**Sender**: jesi.carson@gmail.com
**Comment**: User Profile - Biography text should be black, not blue.
[Open #177 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/177)

<a href='https://usersnappublic.s3.amazonaws.com/2018-05-15/20-09/0879c1c2-9eb8-4c3d-ae6a-b3b39f4fb83c.png'>![Usersnap Feedback - User Profile - Biography text should be black, not blue.](https://usersnappublic.s3.amazonaws.com/2018-05-15/20-09/d06d6091-e083-4533-b75a-bb7eeb2e9a9a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-05-15/20-09/0879c1c2-9eb8-4c3d-ae6a-b3b39f4fb83c.png'>Download original image</a>

**Browser**: Chrome 66 (Macintosh)
**Referer**: [https://participedia.xyz/users/1189](https://participedia.xyz/users/1189)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@LLPrin - This might be an easy fix? If not, then P2.
