### ISSUE TITLE
[USERSNAP] Spam - Bloc user - I hid their two entries

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1643]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/case/8157
**Fields**:
- Add a comment: Spam - Bloc user - I hid their two entries

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e20ab878-4493-4805-b336-c3db27f2264c-annotated_ada5ffa6-f58c-42e8-8c64-16dca3cda280.png?etag=e92984eb2bca17a4e2660ccd3ce34dda)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e20ab878-4493-4805-b336-c3db27f2264c-annotated_ada5ffa6-f58c-42e8-8c64-16dca3cda280.png?etag=e92984eb2bca17a4e2660ccd3ce34dda)*

**Browser**: Firefox 99 (Windows 10)
**Screen size**: 1760x1100
**Browser size**: 1760x985
**[Open #1326 in Usersnap](https://app.usersnap.com/l/feedback/0b93e0fa-de9f-4ea3-9bea-b1e84d20c426?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
