### ISSUE TITLE
Usersnap Feedback - Relationship to this case field - how is this being used? Knowing the rela[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#165]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Relationship to this case field - how is this being used? Knowing the relationship of the person who first submits the entry is important - is that stored somewhere or do my edits replace that data? What about each person that edits/changes the entry? Is there relationship to this entry stored somewhere?
[Open #178 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/178)

<a href='https://usersnappublic.s3.amazonaws.com/2018-05-15/23-25/fc4b3cbd-b013-4c1f-873d-434c84e5356d.png'>![Usersnap Feedback - Relationship to this case field - how is this being used? Knowing the rela(...)](https://usersnappublic.s3.amazonaws.com/2018-05-15/23-25/cd19eac5-dad2-412c-9ed5-75a5999a4b30.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-05-15/23-25/fc4b3cbd-b013-4c1f-873d-434c84e5356d.png'>Download original image</a>

**Browser**: Chrome 66 (Windows 10)
**Referer**: [https://participedia.xyz/case/4512/edit](https://participedia.xyz/case/4512/edit)
**Screen size**: 1280 x 720 **Browser size**: 1590 x 712

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Good question to be addressed with version control design https://github.com/participedia/frontend/issues/587
