### ISSUE TITLE
[USERSNAP] Spam - Hide user - I hid this entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1651]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/case/8174
**Fields**:
- Add a comment: Spam - Hide user - I hid this entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/957f0ad0-4a9b-42c5-89aa-8b58ca984974-annotated_bf7f0406-7679-49c2-b57d-367560055806.png?etag=9ef49bb9c21de9cefb1934ebdb5b8008)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/957f0ad0-4a9b-42c5-89aa-8b58ca984974-annotated_bf7f0406-7679-49c2-b57d-367560055806.png?etag=9ef49bb9c21de9cefb1934ebdb5b8008)*

**Browser**: Firefox 99 (Windows 10)
**Screen size**: 1760x1100
**Browser size**: 1760x985
**[Open #1334 in Usersnap](https://app.usersnap.com/l/feedback/dbe6e40d-cc29-4dbd-8ed5-7c20d3c9d941?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
