### ISSUE TITLE
[USERSNAP] The image upload for this case isn't working for some reason!

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1653]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/case/7995/edit
**Fields**:
- Add a comment: The image upload for this case isn&#39;t working for some reason!

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/140eaba7-64d0-4474-909b-a011b8d446b3-annotated_38c2d112-f13c-4983-95e8-9bbdb7c0563d.png?etag=94a185b6a1d579a24d2c62bddde7a32a)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/140eaba7-64d0-4474-909b-a011b8d446b3-annotated_38c2d112-f13c-4983-95e8-9bbdb7c0563d.png?etag=94a185b6a1d579a24d2c62bddde7a32a)*

**Browser**: Chrome 100 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1396x678
**[Open #1336 in Usersnap](https://app.usersnap.com/l/feedback/690f7322-a2ca-4afd-84a7-e8aa6d00f505?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee Bug verified. Images can't be added via the "click to select" method. (however, drag and drop does seem to work). Let's look at this when you have some time (adding to project backlog). For now people can use drag and drop. I'll email this user. Here's what I'm seeing when testing: 

I click the "click to select" text and look for an image in my finder (mac os). The finder comes up as normal, and I select an image to test:

![Screen Shot 2022-04-22 at 8 49 36 AM](https://user-images.githubusercontent.com/13560530/164749983-44fcb59f-e1be-4cbe-90cb-8858f760745b.png)


Clicking "open" on the finder to add the image does not work. It removes the selected image and leaves the finder open:

![Screen Shot 2022-04-22 at 8 49 45 AM](https://user-images.githubusercontent.com/13560530/164750115-2a62d29e-4e1c-4a21-bd6d-6f290a1667d9.png)
