### ISSUE TITLE
[USERSNAP] Spam -Block User - I hid this entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1658]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8193
**Fields**:
- Add a comment: Spam -Block User - I hid this entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/72af8c46-e4ce-4e72-b5e1-22e38d1d6574-annotated_e42b8040-9de0-47b5-ba4e-dde1c5820076.png?etag=d5cf49c5c988ae09cf05bfaf0f2a6d94)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/72af8c46-e4ce-4e72-b5e1-22e38d1d6574-annotated_e42b8040-9de0-47b5-ba4e-dde1c5820076.png?etag=d5cf49c5c988ae09cf05bfaf0f2a6d94)*

**Browser**: Chrome 100 (Windows 10)
**Screen size**: 1920x1200
**Browser size**: 1920x1057
**[Open #1341 in Usersnap](https://app.usersnap.com/l/feedback/1f26f045-4a48-47e6-8582-33992e17b6fc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
