### ISSUE TITLE
[USERSNAP] Spam -Block User - I hid this entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1659]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8192
**Fields**:
- Add a comment: Spam -Block User - I hid this entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/8fb91431-0dd1-4bde-8f9a-5256f2d238f7-annotated_5ecc2750-f5f2-4e3c-9d26-6aae467cb29a.png?etag=37a96a2c2c13988858b09475a1c62af4)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/8fb91431-0dd1-4bde-8f9a-5256f2d238f7-annotated_5ecc2750-f5f2-4e3c-9d26-6aae467cb29a.png?etag=37a96a2c2c13988858b09475a1c62af4)*

**Browser**: Chrome 100 (Windows 10)
**Screen size**: 1920x1200
**Browser size**: 1920x1057
**[Open #1342 in Usersnap](https://app.usersnap.com/l/feedback/7e3be769-cb97-4ab0-a2b5-fbddf142e8e0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
