### ISSUE TITLE
[USERSNAP] Bonjour,   La page suivante n'arrive pas à être traduite automatiquement en anglais, est-ce normal?   Voir:https://participedia.net/case/8159   Merci!   François

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1662]
**Sender**: robert.francois@uqam.ca
**Taken at**: https://participedia.net/case/8159
**Fields**:
- Ajoutez un commentaire: Bonjour,

La page suivante n&#39;arrive pas à être traduite automatiquement en anglais, est-ce normal?

Voir:https://participedia.net/case/8159

Merci!

François

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/55fe6ed3-3a83-412d-9f42-100b186f0141-annotated_7ec6aee2-c63e-4ca7-b98e-42ff94b6edf0.png?etag=2b9a3a4305fbcd2bf1867b986eda2dd1)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/55fe6ed3-3a83-412d-9f42-100b186f0141-annotated_7ec6aee2-c63e-4ca7-b98e-42ff94b6edf0.png?etag=2b9a3a4305fbcd2bf1867b986eda2dd1)*

**Browser**: Firefox 99 (macOS Catalina)
**Screen size**: 1366x768
**Browser size**: 1325x632
**[Open #1345 in Usersnap](https://app.usersnap.com/l/feedback/2ee74eeb-b84f-4f5a-b8c8-740563567ce4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
misunderstood the issue here. looks like this user didn't know that after the first publish entries are not translated. i'll email them.
