### ISSUE TITLE
[USERSNAP] Spam. Hide user

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1663]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/8196
**Fields**:
- Add a comment: Spam. Hide user

**Browser**: Safari 15 (iOS)
**Screen size**: 390x844
**[Open #1346 in Usersnap](https://app.usersnap.com/l/feedback/db9a9dcb-59fe-4c78-83c7-8eb6a1651e2b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
