### ISSUE TITLE
[USERSNAP] This user appears to be confused as to how to use the auto-translation. They entered French text into the English template

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1666]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/case/8117
**Fields**:
- Add a comment: This user appears to be confused as to how to use the auto-translation. They entered French text into the English template

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/07c6e4d8-fb01-4c27-91b4-67e361a9f1b0-annotated_dba8ae65-6e22-48b2-a41f-b88ca54e6127.png?etag=6dbc351f1f0a5f9aeea3ab94cb2c9726)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/07c6e4d8-fb01-4c27-91b4-67e361a9f1b0-annotated_dba8ae65-6e22-48b2-a41f-b88ca54e6127.png?etag=6dbc351f1f0a5f9aeea3ab94cb2c9726)*

**Browser**: Firefox 99 (Windows 10)
**Screen size**: 1280x720
**Browser size**: 1280x567
**[Open #1349 in Usersnap](https://app.usersnap.com/l/feedback/f9cc6559-1f01-4568-a1d3-709c5842eedc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee before I let the editing team know that this can be manually fixed - is there a way to know what happened here? Did this person copy french over the EN text? or was this old data that hadn't yet been manually fixed? 

Thanks.

**Comment by jesicarson** [comment]
another issue - same problem with FR / EN - https://github.com/participedia/usersnaps/issues/1662

**Comment by paninee** [comment]
We can't track what happened with the user's input, but it's likely that the user puts in French in English as the original language.

**Comment by jesicarson** [comment]
ok. should we just close this then?

**Comment by jesicarson** [comment]
can pass to editing team to manually fix
