### ISSUE TITLE
[USERSNAP] Spam -Block user - I hid this entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1667]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8195
**Fields**:
- Add a comment: Spam -Block user - I hid this entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/706060c7-97f0-4f4d-a161-4c05156dfc69-annotated_23c62130-3f34-4c13-a5a8-31bd34eca957.png?etag=30609074445e2d82989435f61641d150)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/706060c7-97f0-4f4d-a161-4c05156dfc69-annotated_23c62130-3f34-4c13-a5a8-31bd34eca957.png?etag=30609074445e2d82989435f61641d150)*

**Browser**: Firefox 99 (Windows 10)
**Screen size**: 1280x720
**Browser size**: 1280x567
**[Open #1350 in Usersnap](https://app.usersnap.com/l/feedback/eafd5be2-59c0-4f05-86f0-2dd1457167db?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
