### ISSUE TITLE
[USERSNAP] Span - Block user - I hid this entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1668]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8209
**Fields**:
- Add a comment: Span - Block user - I hid this entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/8a63c175-ce7d-43aa-8fb8-e5b607bcb01e-annotated_2687f041-9fc4-4f5d-af62-b7bb45466c1a.png?etag=ddfde2364e24b7975797a9940b68b70b)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/8a63c175-ce7d-43aa-8fb8-e5b607bcb01e-annotated_2687f041-9fc4-4f5d-af62-b7bb45466c1a.png?etag=ddfde2364e24b7975797a9940b68b70b)*

**Browser**: Firefox 100 (Windows 10)
**Screen size**: 1920x1200
**Browser size**: 1920x1019
**[Open #1351 in Usersnap](https://app.usersnap.com/l/feedback/bff0fbe1-2725-42b2-b2be-1deec0f4860e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
