### ISSUE TITLE
[USERSNAP] Spam - Block User - I hid this entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1669]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8210
**Fields**:
- Add a comment: Spam - Block User - I hid this entry.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d69069cd-a60e-47bc-a5f7-42be684ac66a-annotated_614f3f24-32bc-43fb-b3b7-ddefd5515bca.png?etag=62663a50660290573fac70a846b0acee)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d69069cd-a60e-47bc-a5f7-42be684ac66a-annotated_614f3f24-32bc-43fb-b3b7-ddefd5515bca.png?etag=62663a50660290573fac70a846b0acee)*

**Browser**: Firefox 100 (Windows 10)
**Screen size**: 1920x1200
**Browser size**: 1920x1019
**[Open #1352 in Usersnap](https://app.usersnap.com/l/feedback/4ee15b6f-010e-4c35-83cb-50a0a0117e8d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
