### ISSUE TITLE
[USERSNAP] Spam - Block User - I hid this entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1671]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8212
**Fields**:
- Add a comment: Spam - Block User - I hid this entry.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2ccd1295-7a8b-46ca-ae8d-030ab3ccd5de-annotated_c160a1ad-b249-4a3c-b6e2-4b727c4b5261.png?etag=bd5d7d2c5715b1bdda17e63e6d1d175f)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2ccd1295-7a8b-46ca-ae8d-030ab3ccd5de-annotated_c160a1ad-b249-4a3c-b6e2-4b727c4b5261.png?etag=bd5d7d2c5715b1bdda17e63e6d1d175f)*

**Browser**: Firefox 100 (Windows 10)
**Screen size**: 1920x1200
**Browser size**: 1920x1019
**[Open #1354 in Usersnap](https://app.usersnap.com/l/feedback/fba494ef-b6ed-4eec-ad3f-e50fa41c013e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
