### ISSUE TITLE
[USERSNAP] This entry has been identified as spam, please remove.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1672]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/organization/8208
**Fields**:
- Add a comment: This entry has been identified as spam, please remove.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2fb1a4ec-8c39-454c-8707-94512eba5e3d-annotated_1525d74b-0d92-42b2-bfd3-ec38f90c379a.png?etag=1ddb7cc5c9e1089e86d15b228de0b7fb)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2fb1a4ec-8c39-454c-8707-94512eba5e3d-annotated_1525d74b-0d92-42b2-bfd3-ec38f90c379a.png?etag=1ddb7cc5c9e1089e86d15b228de0b7fb)*

**Browser**: Chrome 100 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1396x678
**[Open #1355 in Usersnap](https://app.usersnap.com/l/feedback/9ec332d8-57cb-413d-9e60-757b3e8e4dea?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
entry hidden and user blocked
