### ISSUE TITLE
[USERSNAP] This entry has been identified as spam, please remove it.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1673]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/organization/8207
**Fields**:
- Add a comment: This entry has been identified as spam, please remove it.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/f532c466-9d9f-4ea5-b241-0d46d2876638-annotated_e3b46728-6f1e-4635-81ae-2104ebdc1edf.png?etag=a3b7a8bb8047bd3308afd71ebc7282dc)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/f532c466-9d9f-4ea5-b241-0d46d2876638-annotated_e3b46728-6f1e-4635-81ae-2104ebdc1edf.png?etag=a3b7a8bb8047bd3308afd71ebc7282dc)*

**Browser**: Chrome 100 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1396x678
**[Open #1356 in Usersnap](https://app.usersnap.com/l/feedback/fc32fc5f-063b-4476-95b0-20cdd85961a3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
entry hidden and user blocked
