### ISSUE TITLE
[USERSNAP] This entry is spam, please remove. I have hidden it. Thanks!

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1677]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/case/8221/edit
**Fields**:
- Add a comment: This entry is spam, please remove. I have hidden it. Thanks!

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d8d80a6a-5e25-4ed0-bb44-6e24d39cd1cf-annotated_c62d3048-190e-4ecf-ba10-0ade07030e43.png?etag=f93ca7a89cf39600a7fbbeab843f92d7)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d8d80a6a-5e25-4ed0-bb44-6e24d39cd1cf-annotated_c62d3048-190e-4ecf-ba10-0ade07030e43.png?etag=f93ca7a89cf39600a7fbbeab843f92d7)*

**Browser**: Chrome 101 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1396x678
**[Open #1360 in Usersnap](https://app.usersnap.com/l/feedback/dd2300c0-bfd7-440b-a2a7-5e7147770d6e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
