### ISSUE TITLE
[USERSNAP] Won't let me tick the CAPTCHA box

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1679]
**Sender**: lucy.parry@canberra.edu.au
**Taken at**: https://participedia.net/method/new?full=1
**Fields**:
- Add a comment: Won&#39;t let me tick the CAPTCHA box

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/898ec71e-139e-46d7-8975-d67f86368463-annotated_7abde94a-bbc0-4758-bf2a-fae623cf6eae.png?etag=481103b1a552ef378a8dd2027387ff1f)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/898ec71e-139e-46d7-8975-d67f86368463-annotated_7abde94a-bbc0-4758-bf2a-fae623cf6eae.png?etag=481103b1a552ef378a8dd2027387ff1f)*

**Browser**: Chrome 101 (Windows 10)
**Screen size**: 2048x1152
**Browser size**: 2048x1002
**[Open #1362 in Usersnap](https://app.usersnap.com/l/feedback/1f375fe8-06eb-483e-bb38-6127d089f060?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
I can't reproduce this. Lucy was eventually able to publish. Temporary glitch. I advised her to reload the site / clear cache.
