### ISSUE TITLE
Usersnap Feedback - Case Form: Add hyperlink to guidelines for narrative

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#168]
**Sender**: jesi.carson@gmail.com
**Comment**: In Case Narrative explanatory text: "guidelines" should be hyperlinked to the guidelines doc.
[Open #181 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/181)

<a href='https://usersnappublic.s3.amazonaws.com/2018-05-18/22-04/89c42891-ebb4-48d8-b13c-bfec3313f7dd.png'>![Usersnap Feedback - In Case Narrative explanatory text: "guidelines" should be hyperlinked to (...)](https://usersnappublic.s3.amazonaws.com/2018-05-18/22-04/faa7664c-8ae0-466a-8b44-1685780214d5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-05-18/22-04/89c42891-ebb4-48d8-b13c-bfec3313f7dd.png'>Download original image</a>

**Browser**: Chrome 66 (Macintosh)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher where's the latest guidelines doc? amber requested that we format it graphically to match the site as well, per: #114

**Comment by scottofletcher** [comment]
@jesicarson all the guidelines are in this folder: https://drive.google.com/open?id=0BwMEfFNchoN8SkNxYUJzdUdvVE0

The Key Considerations doc is the one that we send out the most often and are the bare minimum that we ask all contributors to read. The full and abridged guidelines for case are pretty much up to date for XYZ although I need to change some of the headings (eg. History is now 'Background History and Context'). The guidelines for Sidebar Data haven't been updated for XYZ but we kept most of the fields with some additions and tweeks so it won't be a huge job. The method guidelines are completely out of date for XYZ. The org guidelines are also out of date although Pat but I haven't finished the data fields or narrative headings for XYZ anyways.
