### ISSUE TITLE
[USERSNAP] Formatting of headings is not saving properly - I formatted them as heading 2 in the narrative.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1680]
**Sender**: lucy.parry@canberra.edu.au
**Taken at**: https://participedia.net/method/8250
**Fields**:
- Add a comment: Formatting of headings is not saving properly - I formatted them as heading 2 in the narrative.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d51e2e03-8ab8-43a7-874f-7a634296c473-annotated_3bcd707d-816c-40ab-a411-bff5c34bc95d.png?etag=98e20b786eae1c6801707fdd27368f23)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d51e2e03-8ab8-43a7-874f-7a634296c473-annotated_3bcd707d-816c-40ab-a411-bff5c34bc95d.png?etag=98e20b786eae1c6801707fdd27368f23)*

**Browser**: Chrome 101 (Windows 10)
**Screen size**: 2048x1152
**Browser size**: 2048x1002
**[Open #1363 in Usersnap](https://app.usersnap.com/l/feedback/fd00d38a-7b3a-49be-b99b-bbe9286e250a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
I was able to reproduce this bug by editing the narrative, highlighting and changing the heading text to H2 via the dropdown. the changes are not reflected when published.
