### ISSUE TITLE
[USERSNAP] publish button not working on profile page. bug

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1682]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/user/1189/edit
**Fields**:
- Add a comment: publish button not working on profile page. bug

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/f03f1b4f-55c2-4b3d-9816-3d1b3be2632f-annotated_6e9f3377-d05e-4066-b003-d000f401fa5f.png?etag=93be4c31c6ff0cb4321e47b63f8c2bdb)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/f03f1b4f-55c2-4b3d-9816-3d1b3be2632f-annotated_6e9f3377-d05e-4066-b003-d000f401fa5f.png?etag=93be4c31c6ff0cb4321e47b63f8c2bdb)*

**Browser**: Chrome 101 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1405x898
**[Open #1365 in Usersnap](https://app.usersnap.com/l/feedback/16d12a74-05ce-44cf-b04e-17965b86ed7f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee please prioritize this fix. we've gotten a couple of emails lately about this, plus another usersnap today. Thanks.
