### ISSUE TITLE
Usersnap Feedback - Case Form: Case Narrative field too long, ADD SCROLL BAR

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#169]
**Sender**: jesi.carson@gmail.com
**Comment**: Case Narrative field should have a scroll bar inside it, rather than extending the box very long. Currently you have to highlight text then navigate way, way up to edit any formatting or add hyperlinks. Not user friendly.
[Open #182 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/182)

<a href='https://usersnappublic.s3.amazonaws.com/2018-05-18/22-29/8e52a5bb-52a7-4438-9d05-368c6c5d13d6.png'>![Usersnap Feedback - Case Narrative field should have a scroll bar inside it, rather than exten(...)](https://usersnappublic.s3.amazonaws.com/2018-05-18/22-29/cc294977-2e7e-49c4-a990-2b93cd19220f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-05-18/22-29/8e52a5bb-52a7-4438-9d05-368c6c5d13d6.png'>Download original image</a>

**Browser**: Chrome 66 (Macintosh)
**Referer**: [https://participedia.xyz/case/4558/edit](https://participedia.xyz/case/4558/edit)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
This issue has been seconded by Lucy & Ethan

**Comment by scottofletcher** [comment]
See participedia/frontend#795

**Comment by jesicarson** [comment]
@scottofletcher @dethe i remember (maybe on slack?) a discussion about how many lines of text we will automatically show in the narrative - I think it was 25, can you confirm? This is in addition to a scroll bar, which I'm designing now.

**Comment by scottofletcher** [comment]
It's ~22 on .net but then there's the bottom border which takes up space. I just want the editing buttons to fit on the same screen as the narrative (ie. not have the narrative cut off at the bottom) so whatever you think it best. If you decreased the size of the bottom border, 25 lines would fit no problem
<img width="670" alt="fireshot capture 114 - edit case seeking the meaningfu_ - https___participedia net_en_node_5187_edit" src="https://user-images.githubusercontent.com/29512491/42903837-f0ab874e-8a87-11e8-80a7-8670184a7bd1.png">

**Comment by scottofletcher** [comment]
whoa sorry I didn't realize the case I was ready was such heavy subject matter!

**Comment by ascott** [comment]
this will be fixed with this PR https://github.com/participedia/api/pull/354
