### ISSUE TITLE
[USERSNAP] spam hidden. block pls

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1696]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/organization/8276
**Fields**:
- Add a comment: spam hidden. block pls

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/9bcbde76-2aef-4f9d-a3e1-d1918d81fcdf-annotated_8df51027-f268-4b7d-98c1-eb41e7a2151f.png?etag=23deca9131e57f4ede8ae74f285adbff)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/9bcbde76-2aef-4f9d-a3e1-d1918d81fcdf-annotated_8df51027-f268-4b7d-98c1-eb41e7a2151f.png?etag=23deca9131e57f4ede8ae74f285adbff)*

**Browser**: Chrome 102 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1113x794
**[Open #1379 in Usersnap](https://app.usersnap.com/l/feedback/c8eeff63-fc83-488d-a5e6-ddbe8b803be0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
