### ISSUE TITLE
Usersnap Feedback - Missing Placeholder Images

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#170]
**Sender**: jesi.carson@gmail.com
**Comment**: Missing Placeholder Images
[Open #183 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/183)

<a href='https://usersnappublic.s3.amazonaws.com/2018-05-21/20-54/d81a1152-75da-442b-a45d-f338e12c2935.png'>![Usersnap Feedback - Missing Placeholder Images](https://usersnappublic.s3.amazonaws.com/2018-05-21/20-54/d8ad1548-78bc-41c9-a025-2d626ee15b5e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-05-21/20-54/d81a1152-75da-442b-a45d-f338e12c2935.png'>Download original image</a>

**Browser**: Chrome 66 (Macintosh)
**Referer**: [https://participedia.xyz/?page=2](https://participedia.xyz/?page=2)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
ref: https://github.com/participedia/frontend/issues/364
