### ISSUE TITLE
[USERSNAP] spam - block user - I hid this entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1711]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8298
**Fields**:
- Add a comment: spam - block user - I hid this entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/01f80402-9013-42bb-a3be-251e73d4fc2f-annotated_5123cf31-f137-4a8c-a18f-dacf4489bada.png?etag=5ff9b3dda509a6aa8f8c6cbc73b86884)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/01f80402-9013-42bb-a3be-251e73d4fc2f-annotated_5123cf31-f137-4a8c-a18f-dacf4489bada.png?etag=5ff9b3dda509a6aa8f8c6cbc73b86884)*

**Browser**: Firefox 101 (Windows 10)
**Screen size**: 1280x720
**Browser size**: 1280x567
**[Open #1394 in Usersnap](https://app.usersnap.com/l/feedback/f2d42356-bf37-48a6-8f95-41f2b45c02dd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
