### ISSUE TITLE
[USERSNAP] Spam. Block. Entry is hidden

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1712]
**Sender**: None
**Taken at**: https://participedia.net/case/8307
**Fields**:
- Add a comment: Spam. Block. Entry is hidden

**Browser**: Safari 15 (iOS)
**Screen size**: 390x844
**[Open #1395 in Usersnap](https://app.usersnap.com/l/feedback/0b1e905c-4517-45b6-9985-ac65662177be?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
