### ISSUE TITLE
[USERSNAP] Spam - block user - I hid this entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1714]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/case/8341
**Fields**:
- Add a comment: Spam - block user - I hid this entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2591f0dd-0a41-46f8-bd68-727e1609f502-annotated_423a068d-9085-4a6f-aa41-423f6666ede4.png?etag=416af23f81d022934741d4ec9dd22e27)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2591f0dd-0a41-46f8-bd68-727e1609f502-annotated_423a068d-9085-4a6f-aa41-423f6666ede4.png?etag=416af23f81d022934741d4ec9dd22e27)*

**Browser**: Firefox 101 (Windows 10)
**Screen size**: 1920x1200
**Browser size**: 1920x1019
**[Open #1397 in Usersnap](https://app.usersnap.com/l/feedback/12a14fa5-1034-46c6-b384-5a749e6d251d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
