### ISSUE TITLE
[USERSNAP] Spam - Block user - I hid their two entries

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1719]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/organization/8301
**Fields**:
- Add a comment: Spam - Block user - I hid their two entries

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e55eff64-3829-45eb-b341-f359d6338fe1-annotated_b5905eb7-f257-4ab9-b94d-26eb5271dfda.png?etag=73b988d7b9ea48bab3b5dd0515108bda)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e55eff64-3829-45eb-b341-f359d6338fe1-annotated_b5905eb7-f257-4ab9-b94d-26eb5271dfda.png?etag=73b988d7b9ea48bab3b5dd0515108bda)*

**Browser**: Firefox 101 (Windows 10)
**Screen size**: 1920x1200
**Browser size**: 1920x1019
**[Open #1402 in Usersnap](https://app.usersnap.com/l/feedback/e8fe809e-fe38-4170-87af-d18587c29792?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
