### ISSUE TITLE
[USERSNAP] Hey Jesi - this entry is spam can it be taken down? I've hidden it in the meantime.   Nina

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1739]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/case/8364
**Fields**:
- Add a comment: Hey Jesi - this entry is spam can it be taken down? I&#39;ve hidden it in the meantime.

Nina

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/c7feaae4-979b-47f2-b6cf-c6cdd056b428-annotated_a213a446-0b8a-479b-bd27-5d50b1ae17f4.png?etag=84c0d880b505ac14029c7db8ea51e39b)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/c7feaae4-979b-47f2-b6cf-c6cdd056b428-annotated_a213a446-0b8a-479b-bd27-5d50b1ae17f4.png?etag=84c0d880b505ac14029c7db8ea51e39b)*

**Browser**: Chrome 103 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1396x678
**[Open #1422 in Usersnap](https://app.usersnap.com/l/feedback/18b9276d-7eb5-4736-864c-5617d317e42c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
