### ISSUE TITLE
[USERSNAP] This entry is spam, please remove it. I have hidden it in the meantime.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1740]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/organization/8229
**Fields**:
- Add a comment: This entry is spam, please remove it. I have hidden it in the meantime.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/edb60ed6-4168-4145-af31-3ed2eb0e3139-annotated_a542ebd2-77b0-4ad3-a5ac-742491e0ed64.png?etag=97bfcd5abaab6de32de9155859422c46)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/edb60ed6-4168-4145-af31-3ed2eb0e3139-annotated_a542ebd2-77b0-4ad3-a5ac-742491e0ed64.png?etag=97bfcd5abaab6de32de9155859422c46)*

**Browser**: Chrome 103 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1396x678
**[Open #1423 in Usersnap](https://app.usersnap.com/l/feedback/54149933-d63f-443c-b104-e7106dd01034?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
