### ISSUE TITLE
[USERSNAP] This entry is spam, please take it down. I've hidden it in the meantime.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1741]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/organization/8228
**Fields**:
- Add a comment: This entry is spam, please take it down. I&#39;ve hidden it in the meantime.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/9ae1b476-3d3c-4413-9cc3-3249441efc67-annotated_ab6cec98-645c-4202-b055-f5f8e5416041.png?etag=9b0c5d9d25b732af095c5d9b41aa4309)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/9ae1b476-3d3c-4413-9cc3-3249441efc67-annotated_ab6cec98-645c-4202-b055-f5f8e5416041.png?etag=9b0c5d9d25b732af095c5d9b41aa4309)*

**Browser**: Chrome 103 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1396x678
**[Open #1424 in Usersnap](https://app.usersnap.com/l/feedback/e5f5b759-46f6-4c05-b01d-0322fff1b529?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@NinaSartor FYI "hiding" is the same as taking down an entry. I will block the user. thanks!
