### ISSUE TITLE
[USERSNAP] This entry is spam - Ghlagatin is an entertainment blog. Please take it down

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1743]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/organization/7707
**Fields**:
- Add a comment: This entry is spam - Ghlagatin is an entertainment blog. Please take it down

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/3cfa32f8-affb-47d0-b55b-24c7b2c08c00-annotated_98a41dc4-c5dc-4d7a-8e66-7f0333948cee.png?etag=2f639f0a577eb91ea5d561aae998cbc1)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/3cfa32f8-affb-47d0-b55b-24c7b2c08c00-annotated_98a41dc4-c5dc-4d7a-8e66-7f0333948cee.png?etag=2f639f0a577eb91ea5d561aae998cbc1)*

**Browser**: Chrome 103 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1396x678
**[Open #1426 in Usersnap](https://app.usersnap.com/l/feedback/1439f56b-c7be-42d7-97e3-23de80297e5c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@NinaSartor This entry was not hidden. Please hide all spam entries as you find them (this is how we take them down from the site - they are no longer discoverable by non-admins if they are hidden). Following this I will block the user account via the 3rd party authentication app that we use.

**Comment by jesicarson** [comment]
user blocked and entry hidden
