### ISSUE TITLE
[USERSNAP] This entry is spam please have it removed. I have hidden it in the meantime

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1744]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/organization/6215
**Fields**:
- Add a comment: This entry is spam please have it removed. I have hidden it in the meantime

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6bf0b822-024b-4f5c-b963-0dce17483465-annotated_21a2a7b2-4bbb-4a77-b022-000d96e47f43.png?etag=67ac99b3501152999c79443ed920cfc5)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6bf0b822-024b-4f5c-b963-0dce17483465-annotated_21a2a7b2-4bbb-4a77-b022-000d96e47f43.png?etag=67ac99b3501152999c79443ed920cfc5)*

**Browser**: Chrome 103 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 737x665
**[Open #1427 in Usersnap](https://app.usersnap.com/l/feedback/0f64e67b-eb63-41af-978e-20fcd24cd842?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@NinaSartor FYI - This is not spam. Alex is a longtime participedia contributor. It is a stub. I am un-hiding this.
