### ISSUE TITLE
[USERSNAP] It is not letting me create a special collection.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1749]
**Sender**: emiljapa@mcmaster.ca
**Taken at**: https://participedia.net/collection/new
**Fields**:
- Add a comment: It is not letting me create a special collection.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/7adeddbc-2434-46f2-b72b-7d944d2873e3-annotated_f81b8e1a-e5d9-49d1-a151-58a7cea5dee9.png?etag=fa3dcfcc7bf11582d092041f41ccd66c)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/7adeddbc-2434-46f2-b72b-7d944d2873e3-annotated_f81b8e1a-e5d9-49d1-a151-58a7cea5dee9.png?etag=fa3dcfcc7bf11582d092041f41ccd66c)*

**Browser**: Edge (Chromium) 103 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x961
**[Open #1432 in Usersnap](https://app.usersnap.com/l/feedback/2ec2a174-8b68-4a5d-9149-667ee1dddbe6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
closing this but leaving #1750 open
