### ISSUE TITLE
[USERSNAP] I found the bug: it turns out if you copy and paste information into the title or description box when creating content, it will create an error and not let you publish.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1750]
**Sender**: emiljapa@mcmaster.ca
**Taken at**: https://participedia.net/collection/8376
**Fields**:
- Add a comment: I found the bug: it turns out if you copy and paste information into the title or description box when creating content, it will create an error and not let you publish.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/bfcf7fe9-ca32-4d5d-b28d-96515f946163-annotated_e6a4bccb-2364-4141-832d-ebd7dcdea985.png?etag=75d2bf4504f3b8c664d83cbec5d09eca)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/bfcf7fe9-ca32-4d5d-b28d-96515f946163-annotated_e6a4bccb-2364-4141-832d-ebd7dcdea985.png?etag=75d2bf4504f3b8c664d83cbec5d09eca)*

**Browser**: Edge (Chromium) 103 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x961
**[Open #1433 in Usersnap](https://app.usersnap.com/l/feedback/dfa65d6b-ce2e-4abb-9b93-d31a4f352168?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
ref https://github.com/participedia/usersnaps/issues/1749

**Comment by jesicarson** [comment]
I could not reproduce this... I copy/pasted text in the description and mine published correctly.

@Emiljanowicz where were you copying your text from? an email or word doc or another place? possibly embedded formatting from copy/paste, but i'm also thinking this was maybe a one time glitch. sometimes refreshing the site / clearing your cache can help. 

let me know if you can reproduce this Paul, and we'll go from there.

**Comment by jesicarson** [comment]
here's my test collection (it's now hidden) https://participedia.net/collection/8378

![Screen Shot 2022-07-26 at 10 35 10 AM](https://user-images.githubusercontent.com/13560530/181074220-ca3e4a0c-99bc-4295-9ff1-dc03c577aa85.png)
