### ISSUE TITLE
[USERSNAP] Hey Jesi, this is spam. I've hidden the entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1753]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/organization/8379
**Fields**:
- Add a comment: Hey Jesi, this is spam. I&#39;ve hidden the entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b3191058-a6d2-495f-885a-e9a780666f72-annotated_026fec55-3652-40c4-ab71-0ca16f4f9751.png?etag=c8a43b874b624c8515887f5890e51770)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b3191058-a6d2-495f-885a-e9a780666f72-annotated_026fec55-3652-40c4-ab71-0ca16f4f9751.png?etag=c8a43b874b624c8515887f5890e51770)*

**Browser**: Chrome 103 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1031x670
**[Open #1436 in Usersnap](https://app.usersnap.com/l/feedback/c53aab0b-4e4c-44b9-b200-cff2bb92ca23?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
blocked
