### ISSUE TITLE
[USERSNAP] Hey Jesi this is spam. I've hidden the entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1754]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/organization/349
**Fields**:
- Add a comment: Hey Jesi this is spam. I&#39;ve hidden the entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/418f7cb6-ca34-4e34-bde5-c0a5c19d1d2f-annotated_c955575c-cd3a-4960-b44a-36599352148f.png?etag=65ff2e0e0e8e4cf61604dbd2eb7f7154)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/418f7cb6-ca34-4e34-bde5-c0a5c19d1d2f-annotated_c955575c-cd3a-4960-b44a-36599352148f.png?etag=65ff2e0e0e8e4cf61604dbd2eb7f7154)*

**Browser**: Chrome 103 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1031x670
**[Open #1437 in Usersnap](https://app.usersnap.com/l/feedback/f0f265c5-1c2d-40e6-aac2-9dcca6b175f7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
Paul Nollen has contributed to a lot of entries, i recognize his name. i won't block him but i agree with hiding this entry.
