### ISSUE TITLE
[USERSNAP] Hey Jesi - I am thinking this entry is spam. The link to their site doesn't work and there's no information about "Eidemus" on the internet. I'd say to hide the entry.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1755]
**Sender**: sarton1@mcmaster.ca
**Taken at**: https://participedia.net/organization/370
**Fields**:
- Add a comment: Hey Jesi - I am thinking this entry is spam. The link to their site doesn&#39;t work and there&#39;s no information about &#34;Eidemus&#34; on the internet. I&#39;d say to hide the entry.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/a352ac4d-176c-40d7-87e8-181814560e04-annotated_47ccb2d5-49c3-463f-950a-edd12a80bdaa.png?etag=a65eaed8f2a399a81f9f358036c22cb8)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/a352ac4d-176c-40d7-87e8-181814560e04-annotated_47ccb2d5-49c3-463f-950a-edd12a80bdaa.png?etag=a65eaed8f2a399a81f9f358036c22cb8)*

**Browser**: Chrome 103 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1031x670
**[Open #1438 in Usersnap](https://app.usersnap.com/l/feedback/78655652-1efe-4467-bc9c-e53f1ed003f4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
ive hidden the entry, but for now I won't block the user. the content seems like it was intending to be relevant. we'll keep an eye on them.
