### ISSUE TITLE
[USERSNAP] stage test: I added text in the spanish drop down in the form, and that text is not showing here once it is published (it overwrote my spanish text with the machine translation from english)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1760]
**Sender**: jesi.carson@gmail.com
**Taken at**: http://ppedia-stage.herokuapp.com/case/7381
**Fields**:
- Add a comment: stage test: I added text in the spanish drop down in the form, and that text is not showing here once it is published (it overwrote my spanish text with the machine translation from english)

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6684841c-f0ca-4bd8-bdf4-678ca337a61e-annotated_ec77d908-7a53-4fbe-9e85-6655cda0b536.png?etag=e3ab35cecfa142d1c69c7139d6611d2d)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6684841c-f0ca-4bd8-bdf4-678ca337a61e-annotated_ec77d908-7a53-4fbe-9e85-6655cda0b536.png?etag=e3ab35cecfa142d1c69c7139d6611d2d)*

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1633x910
**[Open #1443 in Usersnap](https://app.usersnap.com/l/feedback/e53c9aad-54c9-4264-a3b5-104072a84bb7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by paninee** [comment]
Fixed and tested on stage

https://www.loom.com/share/a04caaeb7637451e9e945b8511245dd3
https://www.loom.com/share/89ae11f6035443e6bf7565a4f13a44bc

**Comment by jesicarson** [comment]
This bug is still happening for a new entry. @paninee
