### ISSUE TITLE
Usersnap Feedback - Search bar doesn't work from profile page. Typed a search term, hit enter, [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#177]
**Sender**: jesi.carson@gmail.com
**Comment**: Search bar doesn't work from profile page. Typed a search term, hit enter, no result. Stays on profile page. Would expect to be redirected to homepage search results. 
[Open #190 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/190)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-05/23-46/f6043c1c-9360-47ea-8836-d559444ee4aa.png'>![Usersnap Feedback - Search bar doesn't work from profile page. Typed a search term, hit enter, (...)](https://usersnappublic.s3.amazonaws.com/2018-06-05/23-46/678708bd-ec59-4172-a40d-89d1d570d920.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-05/23-46/f6043c1c-9360-47ea-8836-d559444ee4aa.png'>Download original image</a>

**Browser**: Chrome 66 (Macintosh)
**Referer**: [https://participedia.xyz/users/1189?query=democracy](https://participedia.xyz/users/1189?query=democracy)
**Screen size**: 1280 x 800 **Browser size**: 1279 x 703

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Closing via: https://github.com/participedia/frontend/issues/836
