### ISSUE TITLE
Usersnap Feedback - Clicking the home button didn't clear search query.   after conducting a s[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#179]
**Sender**: jesi.carson@gmail.com
**Comment**: Clicking the home button didn't clear search query. 

after conducting a search for (womens rights) and (children), then viewing the results, I clicked the logo/home button - the results from my previous search are still displayed. 
[Open #192 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/192)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-05/23-50/b750ee7e-9342-4561-8bd4-baf90f4f9c44.png'>![Usersnap Feedback - Clicking the home button didn't clear search query.   after conducting a s(...)](https://usersnappublic.s3.amazonaws.com/2018-06-05/23-50/e53c445e-af10-4f3b-85e6-7f1538b7d591.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-05/23-50/b750ee7e-9342-4561-8bd4-baf90f4f9c44.png'>Download original image</a>

**Browser**: Chrome 66 (Macintosh)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1280 x 800 **Browser size**: 1278 x 703

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Closing via: https://github.com/participedia/frontend/issues/836
