### ISSUE TITLE
Usersnap Feedback - Submitting a case: There are 2 submit buttons. The red circle with upload [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#18]
_From @davidascher on May 10, 2017 5:6_

**Sender**: jesi.carson@gmail.com
**Comment**: Submitting a case: There are 2 submit buttons. The red circle with upload icon gets hidden behind the footer. 
- Jesi
[Open #15 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/15)

<a href='https://usersnappublic.s3.amazonaws.com/2017-05-10/07-04/74946972-c023-40cd-a899-2714ec8cc5b6.png'>![Usersnap Feedback - Submitting a case: There are 2 submit buttons. The red circle with upload (...)](https://usersnappublic.s3.amazonaws.com/2017-05-10/07-04/2ef6abb3-b9f7-4a7c-bd64-0ca113eea086.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-05-10/07-04/74946972-c023-40cd-a899-2714ec8cc5b6.png'>Download original image</a>

**Browser**: Chrome 57 (macOS Sierra)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 1280 x 800 **Browser size**: 1279 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

_Copied from original issue: participedia/frontend#342_

**Comment by davidascher** [comment]
Got rid of the red button -- I can easily either bring it back and remove the submit button -- tell me which you prefer @jesicarson  =)

**Comment by jesicarson** [comment]
@davidascher Getting rid of red button is what we want. See issue #407 (want to match button design for Quick Submit to top nav design, and also add a "do full version" button beside it to reveal the rest of the fields) - let me know if I should mock this up.

**Comment by davidascher** [comment]
A quick mock would be great.

**Comment by jesicarson** [comment]
Sure. Here's the other issue: https://github.com/participedia/frontend/issues/407

Here's a screenshot: 
![screen shot 2017-06-05 at 3 01 54 pm](https://cloud.githubusercontent.com/assets/13560530/26805301/2ec6ae9c-4a00-11e7-88cc-8066d751e4be.png)



Here's the .ai file for reference: https://drive.google.com/open?id=0B5j_dGoSFCLJa3NRSTI3bU1wcGc
