### ISSUE TITLE
[USERSNAP] missing placeholder image on search (on prod)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1800]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/search?query=Malawi%20Human%20Rights%20Youth%20Network
**Fields**:
- Add a comment: missing placeholder image on search (on prod)

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/80b08d2c-8e79-46be-b802-c0a0847ff94d-annotated_2caa9a1a-83f4-46ab-b749-393fcf63bd23.png?etag=cdba77314a87e061bf4c753d331e6d3d)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/80b08d2c-8e79-46be-b802-c0a0847ff94d-annotated_2caa9a1a-83f4-46ab-b749-393fcf63bd23.png?etag=cdba77314a87e061bf4c753d331e6d3d)*

**Browser**: Chrome 104 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1849x926
**[Open #1483 in Usersnap](https://app.usersnap.com/l/feedback/73cd0f31-f98c-42c1-a6ac-32cf66b7386f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee eventually the images load, but they're taking much longer than usual. Is there something different?
