### ISSUE TITLE
[USERSNAP] No me deja agregar un nuevo caso, me redirige siempre al login, lo realizo intento crear la entrada y cae en un bucle que nuevamente me lleva al login

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1801]
**Sender**: vianavilla@gmail.com
**Taken at**: https://participedia.net/content-chooser
**Fields**:
- Agrega un comentario: No me deja agregar un nuevo caso, me redirige siempre al login, lo realizo intento crear la entrada y cae en un bucle que nuevamente me lleva al login

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/9d56b0df-710e-4f11-9987-e77433e791c4-annotated_8264ae11-2022-4eb5-ad56-ce20674fe80e.png?etag=cea263ee138c4229e6ee71f5c9b44e4c)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/9d56b0df-710e-4f11-9987-e77433e791c4-annotated_8264ae11-2022-4eb5-ad56-ce20674fe80e.png?etag=cea263ee138c4229e6ee71f5c9b44e4c)*

**Browser**: Chrome 104 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1366x657
**[Open #1484 in Usersnap](https://app.usersnap.com/l/feedback/acdec7bb-2a57-4cb4-90ac-e207711e09d0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
I emailed this user.
