### ISSUE TITLE
[USERSNAP] Search is not working, it's going to some html thing

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1813]
**Sender**: lucy.parry@canberra.edu.au
**Taken at**: https://participedia.net/
**Fields**:
- Add a comment: Search is not working, it&#39;s going to some html thing

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/abb17b46-3730-497e-a3f5-2357fbc74cd5-annotated_48d38e3a-ef4e-42dd-8583-bd15948d4058.png?etag=8d47056877da3b14dfeac6266b2279a8)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/abb17b46-3730-497e-a3f5-2357fbc74cd5-annotated_48d38e3a-ef4e-42dd-8583-bd15948d4058.png?etag=8d47056877da3b14dfeac6266b2279a8)*

**Browser**: Chrome 104 (Windows 10)
**Screen size**: 2048x1152
**Browser size**: 2048x1034
**[Open #1496 in Usersnap](https://app.usersnap.com/l/feedback/7b054796-c8d1-4a81-9b53-e0972b7d03eb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee verified this bug. 

https://participedia.net/search?query=test

typing into the search bar in the header on homepage returns an error page with this text:

{"OK":false,"error":{"length":124,"name":"error","severity":"ERROR","code":"42703","position":"1427","file":"parse_relation.c","line":"3284","routine":"errorMissingColumn"}}
