### ISSUE TITLE
[USERSNAP] This case seems to be a duplicate

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1830]
**Sender**: slasors@mcmaster.ca
**Taken at**: https://participedia.net/case/8483/
**Fields**:
- Add a comment: This case seems to be a duplicate

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/192329e8-cc6e-4fbc-96c3-9bbc4c488579-annotated_84457c26-79a9-4534-be54-f23792a27692.png?etag=b23a57d4698c15667850994488ad32b5)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/192329e8-cc6e-4fbc-96c3-9bbc4c488579-annotated_84457c26-79a9-4534-be54-f23792a27692.png?etag=b23a57d4698c15667850994488ad32b5)*

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1186x689
**[Open #1513 in Usersnap](https://app.usersnap.com/l/feedback/9b6e173b-6c14-47a5-b6a1-d155373fb82b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
ive hidden this one
