### ISSUE TITLE
[USERSNAP] This case seems to be a duplicate

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1831]
**Sender**: slasors@mcmaster.ca
**Taken at**: https://participedia.net/case/8485
**Fields**:
- Add a comment: This case seems to be a duplicate

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/7f892056-e57c-485f-8df5-505c95f77767-annotated_4ffc22f1-da3a-4b4c-a9f6-ea38fabcd011.png?etag=69ea6ef4ef38154bf3dec06d9e0434ee)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/7f892056-e57c-485f-8df5-505c95f77767-annotated_4ffc22f1-da3a-4b4c-a9f6-ea38fabcd011.png?etag=69ea6ef4ef38154bf3dec06d9e0434ee)*

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1186x689
**[Open #1514 in Usersnap](https://app.usersnap.com/l/feedback/65bdd232-7cfe-4932-85c8-56f874252594?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
ive kept this one live and hidden the other: #1830
