### ISSUE TITLE
Usersnap Feedback - About page: Add space between drop down list items

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#184]
**Sender**: jesi.carson@gmail.com
**Comment**: About page: Add space between drop down list items (shown here - add space after "University of British Columbia" before the word "Co-Investigators")
[Open #197 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/197)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-12/22-18/c574db61-82a7-4bc3-a686-b3091d9f13fc.png'>![Usersnap Feedback - About page: Add space between drop down list items (shown here - add space (...)](https://usersnappublic.s3.amazonaws.com/2018-06-12/22-18/7cf57de0-d2b0-48ac-bd34-ece82ff0bccd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-12/22-18/c574db61-82a7-4bc3-a686-b3091d9f13fc.png'>Download original image</a>

**Browser**: Chrome 67 (Macintosh)
**Referer**: [https://participedia.xyz/about](https://participedia.xyz/about)
**Screen size**: 1280 x 800 **Browser size**: 1279 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Closing via https://github.com/participedia/frontend/issues/853
