### ISSUE TITLE
[USERSNAP] I tried to create a draft entry and now I can't see the drafts tab or know where to find it.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1849]
**Sender**: lucy.parry@canberra.edu.au
**Taken at**: https://participedia.net/user/134860
**Fields**:
- Add a comment: I tried to create a draft entry and now I can&#39;t see the drafts tab or know where to find it.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/65eeeda3-ed53-4cae-ae5c-455d27ccd63f-annotated_949281a0-c35f-4e35-8feb-75a8710a0611.png?etag=f1da6445e407105ce86d0a36cf26167e)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/65eeeda3-ed53-4cae-ae5c-455d27ccd63f-annotated_949281a0-c35f-4e35-8feb-75a8710a0611.png?etag=f1da6445e407105ce86d0a36cf26167e)*

**Browser**: Chrome 105 (Windows 10)
**Screen size**: 2048x1152
**Browser size**: 2048x1034
**[Open #1532 in Usersnap](https://app.usersnap.com/l/feedback/82912506-5507-4f85-add7-2e624593d231?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee verified this. I am not seeing a draft after typing info into the form and then navigating to my profile page. please review asap. thank you!

**Comment by paninee** [comment]
@jesicarson I cannot reproduce. What field did you put into the form?
![image](https://user-images.githubusercontent.com/29439995/192041501-c12fd899-78dc-4292-8677-e8315c684378.png)

**Comment by paninee** [comment]
This bug was fixed, but it won't apply backwards, so I'm trying to locate Lucy's entry to fix the data for her.
