### ISSUE TITLE
[USERSNAP] unable to add entries to collection

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1850]
**Sender**: joyceechen1011@gmail.com
**Taken at**: https://participedia.net/case/7259/edit?full=1
**Fields**:
- Add a comment: I’m currently trying to add cases to the Transnational Citizens’ Assembly special collection, but I’m not able to add two of them — https://participedia.net/case/7259/edit?full=1 &amp; https://participedia.net/case/7251/edit — because it says the cases lack a title (they don’t). Is there any way this can be fixed? Thank you so much!

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e03bedb1-e9bb-4bce-883c-9417d4b3cf7f-annotated_eeb18f35-bace-44ca-869e-3c2dae626460.png?etag=e8d47bb39c8741e76eec16e457f3b8f5)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e03bedb1-e9bb-4bce-883c-9417d4b3cf7f-annotated_eeb18f35-bace-44ca-869e-3c2dae626460.png?etag=e8d47bb39c8741e76eec16e457f3b8f5)*

**Browser**: Chrome 105 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1120x665
**[Open #1533 in Usersnap](https://app.usersnap.com/l/feedback/b11fb077-8f2a-488b-a799-0183ed4cd39a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
same issue: [#1851](https://github.com/participedia/usersnaps/issues/1851)

**Comment by jesicarson** [comment]
tested again today and i'm not getting blocked on publish, but the cases don't get added to the collection when published either. so there's still something going on here with collections. perhaps related to #1853 

@paninee
