### ISSUE TITLE
[USERSNAP] Can't open reader view on entries in collections (only edit view opens)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1853]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/case/8127/edit
**Fields**:
- Add a comment: When I open an entry within a collection it takes me immediately to the admin-only edit page. But if I go straight to the entry without accessing it via the collection, it opens in the typical, default view mode. This happened whether or not I was logged in to PPedia.  I discovered this when I was trying to identify the contributor to an entry, but the site kept taking me directly to the admin-only edit page. 

Here is one of the entries that I accessed when this happened.it also happened with several other entries.  https://participedia.net/case/8127

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/bd79072f-5725-4e70-aca4-acfb0cd79229-annotated_4091eec6-a67e-425a-a6d3-a562dd96b2de.png?etag=7ea657e5564a471c6f652288b5cdc3e5)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/bd79072f-5725-4e70-aca4-acfb0cd79229-annotated_4091eec6-a67e-425a-a6d3-a562dd96b2de.png?etag=7ea657e5564a471c6f652288b5cdc3e5)*

**Browser**: Chrome 105 (Windows 10)
**Screen size**: 1280x720
**Browser size**: 1280x577
**[Open #1536 in Usersnap](https://app.usersnap.com/l/feedback/cdf5dfa7-5e62-4d1e-baf0-dbe83150b041?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee please review

**Comment by jesicarson** [comment]
@paninee this is the other time this was flagged - https://github.com/participedia/usersnaps/issues/1826

Please prioritize as soon as you can. thanks

**Comment by paninee** [comment]
@jesicarson @plscully Fixed, and deployed. Please try again.
