### ISSUE TITLE
[USERSNAP] To: "participedia.net". Re: App Store. Dear Madames/Sirs. As we know, people who surf the Internet occasionally download software or applications for various uses. I am a person who survives on a very low income-disability pension from the Na...

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1857]
**Sender**: assaf197254@yahoo.co.il
**Taken at**: https://participedia.net/organization/4427
**Fields**:
- Add a comment: To: &#34;participedia.net&#34;.
Re: App Store.
Dear Madames/Sirs.
As we know, people who surf the Internet occasionally download software or applications for various uses. I am a person who survives on a very low income-disability pension from the National Insurance Institute. For this reason paying for software purchases is very problematic for me.
I am looking for an online app store service, where you can download software for free. Is there such a service on the Internet? Is there an economic or business model that can enable this (for example: a free download app store - which gets its revenue from its users&#39; particularly massive exposure to advertisements)?
Regards,
Assaf Benyamini,
115 Costa Rica Street,
Entrance A-Apartment 4,
Kiryat Menachem,
Jerusalem, ISRAEL, Zip code: 9662592.
Phone numbers: at home-972-2-6427757.
Mobile-972-58-6784040. 
Fax-972-77-2700076.
post Scriptum. 1) My ID number: 029547403.
2) My email addresses: 029547403@walla.co.il or: asb783a@gmail.com or: assaf197254@yahoo.co.il or: ass.benyamini@yandex.com 
Or: assaffff@protonmail.com

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/a3b051c7-519e-47a7-a7a0-9ed551e4880d-annotated_7573dc6b-adad-4a45-9e9d-3a7bca158e90.png?etag=7992c92426b7db89f3e83046d444ea29)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/a3b051c7-519e-47a7-a7a0-9ed551e4880d-annotated_7573dc6b-adad-4a45-9e9d-3a7bca158e90.png?etag=7992c92426b7db89f3e83046d444ea29)*

**Browser**: Chrome 105 (Windows 10)
**Screen size**: 1433x806
**Browser size**: 955x450
**[Open #1540 in Usersnap](https://app.usersnap.com/l/feedback/ef7e7639-0d8c-4b34-8ce1-c655346d3b60?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
emailed user
