### ISSUE TITLE
Usersnap Feedback - When I paste some text in, it always pastes in with one space before the text.

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#186]
**Comment**: When I paste some text in, it always pastes in with one space before the text.
[Open #199 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/199)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-13/14-12/2031c70d-d401-4883-a447-901f30206dbb.png'>![Usersnap Feedback - When I paste some text in, it always pastes in with one space before the text.](https://usersnappublic.s3.amazonaws.com/2018-06-13/14-12/5c04200f-e5e3-4f14-80c1-02b3a9613529.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-13/14-12/2031c70d-d401-4883-a447-901f30206dbb.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/method/387/edit](https://participedia.xyz/method/387/edit)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 635

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
SECOND THIS^^^

**Comment by ascott** [comment]
fixed with this PR https://github.com/participedia/api/pull/354
