### ISSUE TITLE
Usersnap Feedback - The brief description box is only visible when editing an entry, but it do[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#187]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: The brief description box is only visible when editing an entry, but it doesn't appear on either the full entry screen or the home/search page under the pictures and title. Important as this is the only place people can see a brief description - it's no longer included in the narrative headings (for methods at least). 
[Open #200 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/200)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-14/10-30/292c7c3e-09ea-4c5a-ba90-77e9a924b975.png'>![Usersnap Feedback - The brief description box is only visible when editing an entry, but it do(...)](https://usersnappublic.s3.amazonaws.com/2018-06-14/10-30/e1d66069-264a-4c7c-9f02-491f52340487.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-14/10-30/292c7c3e-09ea-4c5a-ba90-77e9a924b975.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/method/4324](https://participedia.xyz/method/4324)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 635

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
covered by https://github.com/participedia/frontend/issues/840
