### ISSUE TITLE
[USERSNAP] HI threre are no submit button.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1877]
**Sender**: None
**Taken at**: https://participedia.net/case/8188/edit?full=1
**Fields**:
- 新增評論: HI threre are no submit button.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/1e767fb0-e798-4c37-b90f-80d59116c43a-annotated_7a1f20d7-1310-430c-9a42-c7ce25536d80.png?etag=11e17ba9746e649344cebd729e07eabc)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/1e767fb0-e798-4c37-b90f-80d59116c43a-annotated_7a1f20d7-1310-430c-9a42-c7ce25536d80.png?etag=11e17ba9746e649344cebd729e07eabc)*

**Browser**: Chrome 107 (Windows 10)
**Screen size**: 1280x800
**Browser size**: 1280x649
**[Open #1560 in Usersnap](https://app.usersnap.com/l/feedback/41bf1605-9a78-4437-bab4-e1e691a45a7a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
user did not leave an email address, so i cant email them. nothing we can do here. closing
