### ISSUE TITLE
[USERSNAP] Hi,  I have found a problem among this page. user cannot publish any content on this website, plz fix it immediately , thank you

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1878]
**Sender**: greener.sh10@nycu.edu.tw
**Taken at**: https://participedia.net/case/8188/edit
**Fields**:
- Add a comment: Hi, 
I have found a problem among this page.
user cannot publish any content on this website, plz fix it immediately , thank you

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/da54681b-3705-49f9-abf1-e456b7a5d4f7-annotated_4f20f31e-ea72-40cd-8432-7f968b17032f.png?etag=d0566a6875e3928e6856ffc3f55f2cc7)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/da54681b-3705-49f9-abf1-e456b7a5d4f7-annotated_4f20f31e-ea72-40cd-8432-7f968b17032f.png?etag=d0566a6875e3928e6856ffc3f55f2cc7)*

**Browser**: ChromeiOS 107 (iOS)
**Screen size**: 390x844
**Browser size**: 390x669
**[Open #1561 in Usersnap](https://app.usersnap.com/l/feedback/81c08fd3-8407-454f-bef2-e7c73623304b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
i emailed this user. closing
