### ISSUE TITLE
Usersnap Feedback - Can only search from the homepage. Just slows things down.

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#188]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: Can only search from the homepage. Just slows things down.
[Open #201 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/201)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-14/10-33/16129675-67d0-402a-b134-bc99855b1f8a.png'>![Usersnap Feedback - Can only search from the homepage. Just slows things down.](https://usersnappublic.s3.amazonaws.com/2018-06-14/10-33/f229547a-5534-46c4-9bd8-4402ffae2ab2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-14/10-33/16129675-67d0-402a-b134-bc99855b1f8a.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/method/4324](https://participedia.xyz/method/4324)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 635

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Known bug: https://github.com/participedia/frontend/issues/836
