### ISSUE TITLE
[USERSNAP] As it has been months, thus here kindly asking:  https://participedia.net/help-faq-contact   1. When the website publishing and editing enable and back? Will be when? Please reply as soon as possible, there’s urgent inquiry and editing of the...

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1880]
**Sender**: haobai9623@gmail.com
**Taken at**: https://participedia.net/
**Fields**:
- Add a comment: As it has been months, thus here kindly asking:  https://participedia.net/help-faq-contact

1. When the website publishing and editing enable and back? Will be when? Please reply as soon as possible, there’s urgent inquiry and editing of the participedia case need to be uploaded.

2. What’s the reason as the disabled happened? Is there anything we customers can help with?

Could the developer Jesi could reply as well?

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/64c25df3-602e-4417-b929-9cadb0067b3e-annotated_636f90cd-574f-4865-99f3-5177519eb8e9.png?etag=e2269bdf5080812b2f88461e13a99c0e)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/64c25df3-602e-4417-b929-9cadb0067b3e-annotated_636f90cd-574f-4865-99f3-5177519eb8e9.png?etag=e2269bdf5080812b2f88461e13a99c0e)*

**Browser**: Chrome 108 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x821
**[Open #1563 in Usersnap](https://app.usersnap.com/l/feedback/ae211e90-28ef-4178-bdb2-a7ecfefddc45?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
this user emailed as well. i have replied. closing.
