### ISSUE TITLE
[USERSNAP] Hello,   Can you give a idea when the option for publishing and editing wil be aviable. Because I'm using this site in my seminar.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1885]
**Sender**: robert.francois@uqam.ca
**Taken at**: https://participedia.net/?utm_source=mailchimp&utm_campaign=03007ec7e1f0&utm_medium=page#
**Fields**:
- Ajoutez un commentaire: Hello,

Can you give a idea when the option for publishing and editing wil be aviable. Because I&#39;m using this site in my seminar.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b283c1ab-a40c-4675-a45a-ed733f3d0a2d-annotated_cd7b11e7-7104-443f-8c74-2015a36a678e.png?etag=c2552799ad17655f202f4dcf0fe408c4)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b283c1ab-a40c-4675-a45a-ed733f3d0a2d-annotated_cd7b11e7-7104-443f-8c74-2015a36a678e.png?etag=c2552799ad17655f202f4dcf0fe408c4)*

**Browser**: Firefox 109 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1393x762
**[Open #1568 in Usersnap](https://app.usersnap.com/l/feedback/5e874e71-6621-43e6-bb18-a27ec1d109bf?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
Emailed this user
