### ISSUE TITLE
[USERSNAP] Application error when clicking the results CSV for cases. Download does not work.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1888]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/search?selectedCategory=case
**Fields**:
- Add a comment: Application error when clicking the results CSV for cases. Download does not work.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/1a7211ff-e3a9-4ad7-9b6a-2e639733d677-annotated_0cd17d5a-9386-4016-bc37-c6b3ddfa7633.png?etag=adebabe73c2d839207cba3625cece81e)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/1a7211ff-e3a9-4ad7-9b6a-2e639733d677-annotated_0cd17d5a-9386-4016-bc37-c6b3ddfa7633.png?etag=adebabe73c2d839207cba3625cece81e)*

**Browser**: Chrome 109 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1375x825
**[Open #1571 in Usersnap](https://app.usersnap.com/l/feedback/a4b4c39c-86fe-4dc7-bae7-e50b62d650d7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
screenshot of the error: 
<img width="871" alt="Screen Shot 2023-01-24 at 11 51 50 AM" src="https://user-images.githubusercontent.com/13560530/214394929-29188e39-b693-40c1-855f-79cd1a3a678b.png">

**Comment by jesicarson** [comment]
@paninee do you have a recent export i can email to the user?

**Comment by jesicarson** [comment]
I found one from April 2022 and emailed it to them for now. but it would be good to have the most up to date one.

**Comment by jesicarson** [comment]
Another user emailed about this today. @paninee Can we move this up the priority list after adding captcha to preview? Thanks!

**Comment by paninee** [comment]
@jesicarson This is caused because we export too many records. We don't have enough memory to do that. We have 2 choices to solve this:

1. Increase our server's capability. Which increases the monthly cost, probably by $25/month. While it's the quickest fix, this might not be a permanent solution as our data keeps growing.
2. Force the user to apply filters, and set a limit of how many records they can download. This may not work for some researchers. Took time to implement, probably about 20-30h.
3. Make the CSV download a background task. We work on packaging up the CSV in the background (maybe use worker dyno in Heroku in the future to prevent the main web dyno from being too busy). Store it in S3. Then the user can check if the CSV is completed and ready to be downloaded. similar to how we backup our database. It takes a long time so Heroku shows the progress, when it's done, the status got updated to "Ready". Then we can download it. More complex feature. Probably takes about 60-80h of work.

**Comment by jesicarson** [comment]
Paul agrees with the decision to pay to upgrade the DB for a month or two, and see how long we can get away with that. 

Next step would be to scale back the feature - only allow users to download the dataset once they've applied a certain number of filters / limit the results + provide the full dataset csv for cases manually every month or so as a hyperlink on the research page. 

(note that methods and orgs probably don't have this issue)

**Comment by jesicarson** [comment]
@paninee please let me know when the DB has been updated so i can test if it works

**Comment by jesicarson** [comment]
@paninee did upgrading the database work? we should chat about this, especially the cost implications. ill put this on the weekly agenda for monday.
