### ISSUE TITLE
Usersnap Feedback - Search does not work when using ordinal numbers.

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#189]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: Search does not work when using ordinal numbers. 
[Open #202 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/202)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-15/10-10/c6f7a627-338b-4f95-8359-7a88bb9dd62d.png'>![Usersnap Feedback - Search does not work when using ordinal numbers.](https://usersnappublic.s3.amazonaws.com/2018-06-15/10-10/e3ed2c5d-c2fb-43db-bc00-c23dd99ae48d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-15/10-10/c6f7a627-338b-4f95-8359-7a88bb9dd62d.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/methods?query=21st%20century%20town%20meeting](https://participedia.xyz/methods?query=21st%20century%20town%20meeting)
**Screen size**: 1366 x 768 **Browser size**: 1517 x 706

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
see participedia/api#300

**Comment by scottofletcher** [comment]
see search indexing Master Issue: participedia/api#453
