### ISSUE TITLE
[USERSNAP] when was this published like a specific date please?

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1892]
**Sender**: None
**Taken at**: https://participedia.net/case/7701#
**Fields**:
- Add a comment: when was this published like a specific date please?

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d7fd0240-4061-4a86-a822-dd20f4f7e080-annotated_d1aa94b8-40a7-4212-8f10-657d9cb7193e.png?etag=64e100d8cbf2e7740b50067d5633a5f6)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d7fd0240-4061-4a86-a822-dd20f4f7e080-annotated_d1aa94b8-40a7-4212-8f10-657d9cb7193e.png?etag=64e100d8cbf2e7740b50067d5633a5f6)*

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x969
**[Open #1575 in Usersnap](https://app.usersnap.com/l/feedback/db284d3b-a025-4b4d-9d23-679ae9adbd95?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
no contact info so cant respond. closing
