### ISSUE TITLE
Usersnap Feedback - Login redirect error still happening. https://participedia.xyz/redirect -Jesi

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#19]
_From @davidascher on May 10, 2017 5:3_

**Sender**: jesi.carson@gmail.com
**Comment**: Login redirect error still happening. https://participedia.xyz/redirect
-Jesi
[Open #14 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/14)

<a href='https://usersnappublic.s3.amazonaws.com/2017-05-10/07-02/13fce470-0c1b-4cc9-8da0-919f06001c5c.png'>![Usersnap Feedback - Login redirect error still happening. https://participedia.xyz/redirect -Jesi](https://usersnappublic.s3.amazonaws.com/2017-05-10/07-02/c4d66b82-b9d9-43c6-88aa-3674f0f4dab8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-05-10/07-02/13fce470-0c1b-4cc9-8da0-919f06001c5c.png'>Download original image</a>

**Browser**: Chrome 57 (macOS Sierra)
**Referer**: [https://participedia.xyz/redirect](https://participedia.xyz/redirect)
**Screen size**: 1280 x 800 **Browser size**: 1279 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

_Copied from original issue: participedia/frontend#341_

**Comment by davidascher** [comment]
_From @dethe on May 31, 2017 20:32_

What's the current status of the login issue(s)?

**Comment by davidascher** [comment]
@jesicarson I need you to do a little thing to "clear" a setting in your browser.

<img width="592" alt="screenshot 2017-06-04 17 42 49" src="https://cloud.githubusercontent.com/assets/51278/26766800/3e04af98-494d-11e7-862f-820151b90109.png">

In the console, type:

```
localStorage.clear()
```

<img width="349" alt="screenshot 2017-06-04 17 43 18" src="https://cloud.githubusercontent.com/assets/51278/26766819/66cc322a-494d-11e7-847e-d040cfe3f379.png">


Then reload, and login should work.

**Comment by jesicarson** [comment]
@davidascher the login seems to be working now. It actually worked before I tried the clear() thing, but I also did that and it just said "undefined" as the next line in the console after I hit enter, so not sure what that means.
