### ISSUE TITLE
Usersnap Feedback - Search does not work with exclamation mark.

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#190]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: Search does not work with exclamation mark.
[Open #203 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/203)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-15/11-33/1d46603c-180d-4a02-8ca5-c52566b9234e.png'>![Usersnap Feedback - Search does not work with exclamation mark.](https://usersnappublic.s3.amazonaws.com/2018-06-15/11-33/cbe8ad76-87c0-431b-89a7-fcddd92ba404.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-15/11-33/1d46603c-180d-4a02-8ca5-c52566b9234e.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/?query=reflect!](https://participedia.xyz/?query=reflect!)
**Screen size**: 1366 x 768 **Browser size**: 1517 x 705

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
see participedia/api#300

**Comment by scottofletcher** [comment]
see search indexing Master Issue: participedia/api#453
