### ISSUE TITLE
[USERSNAP] Dear Participedia,   As you can see from the video in attachment , this page doesn't work .    Thanks

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1902]
**Sender**: greener.sh10@nycu.edu.tw
**Taken at**: https://participedia.net/case/12258
**Fields**:
- 新增評論: Dear Participedia,

As you can see from the video in attachment , this page doesn&#39;t work . 

Thanks

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6865c6d9-f648-47a9-8d46-0faf3285499e-annotated_25af5d48-d02f-4fa6-9094-4c7e9e60c294.png?etag=02db1573afcc681541e3962d7f747f62)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6865c6d9-f648-47a9-8d46-0faf3285499e-annotated_25af5d48-d02f-4fa6-9094-4c7e9e60c294.png?etag=02db1573afcc681541e3962d7f747f62)*

**Browser**: Chrome 108 (Windows 10)
**Screen size**: 1280x800
**Browser size**: 659x648
**[View screen recording](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/screen_recording/f381e295-c55c-4f51-9a49-ab300aa28a0b_screen_recording_28ddb47e-712d-4fb3-968a-82bbd65f8ece.webm?etag=e7c2a86ca406b229252c6a5cf47018cc)**
**[Open #1585 in Usersnap](https://app.usersnap.com/l/feedback/069e27ba-432b-4295-8286-aaaeed9e8d81?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
I emailed this user
