### ISSUE TITLE
[USERSNAP] stuck on popup when clicked approve.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1905]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/entries/review#
**Fields**:
- Add a comment: stuck on popup when clicked approve.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/316f61b5-b37e-4c54-90ce-47fc570a82b5-annotated_72cf15bd-dae6-44a0-b1f1-f8114d9b977d.png?etag=bb183e33b0a9e4f6bccbeb16ab189e0d)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/316f61b5-b37e-4c54-90ce-47fc570a82b5-annotated_72cf15bd-dae6-44a0-b1f1-f8114d9b977d.png?etag=bb183e33b0a9e4f6bccbeb16ab189e0d)*

**Browser**: Chrome 109 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x782
**[Open #1588 in Usersnap](https://app.usersnap.com/l/feedback/f1f10a29-af44-48e7-b6b5-37bd6f10588f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
also this: https://github.com/participedia/usersnaps/issues/1906

**Comment by paninee** [comment]
Which entry were you trying to approve? @jesicarson I can't reproduce.

**Comment by jesicarson** [comment]
@paninee I am getting stuck on the popup every time I click approve on all entries. Also when I make any changes to entries on the live site and try to publish, the popup hangs and I have to click refresh to get it to work. All entries.
