### ISSUE TITLE
[USERSNAP] Unable to login with user account njerunancy@gmail.com (verified bug from user email)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1908]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/
**Fields**:
- Add a comment: Unable to login with user account njerunancy@gmail.com (verified bug from user email)

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/bb4724c7-9e77-4737-b79b-df0df8fded1c-annotated_e26b9a9c-4cbf-48f0-b762-6f41f2fe8d90.png?etag=efc47d4cd94a5fc7334aad70adde4217)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/bb4724c7-9e77-4737-b79b-df0df8fded1c-annotated_e26b9a9c-4cbf-48f0-b762-6f41f2fe8d90.png?etag=efc47d4cd94a5fc7334aad70adde4217)*

**Browser**: Safari 16 (iOS)
**Screen size**: 390x844
**Browser size**: 390x664
**[Open #1591 in Usersnap](https://app.usersnap.com/l/feedback/9cabe2a0-03f0-40c7-9e23-8979b7d49826?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
Seems to only affect this account. I tried generating a new password in Auth0, but that didn’t help. 

Steps to reproduce:

Logout and reload site. Click login, enter user email and temp pw and captcha. Result - returned to homepage not logged in.

I also tried logging in with my non-admin jesi@designnerds account, but I was logged in as expected.

**Comment by jesicarson** [comment]
@paninee please manually verify nancytemp@gmail.com so that she can login with this temp account and publish her entry (which I'll manually assign to her personal account once editing is fixed on the platform).

**Comment by paninee** [comment]
@jesicarson For some reasons, this user is blocked. I manually unblocked the account. Should be able to sign in now.

**Comment by jesicarson** [comment]
Thanks. I emailed her. Unfortunately there's a bug on re-assigning authorship, so I'll need to do this once you address that other issue. But closing this for now. 

https://github.com/participedia/usersnaps/issues/1925
