### ISSUE TITLE
Usersnap Feedback - Photo not appearing properly - seen a few like this.

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#191]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: Photo not appearing properly - seen a few like this.
[Open #204 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/204)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-15/14-41/9290c891-04eb-4c34-9ffb-dc661046fa88.png'>![Usersnap Feedback - Photo not appearing properly - seen a few like this.](https://usersnappublic.s3.amazonaws.com/2018-06-15/14-41/f0078e54-4335-4b80-990f-bae24f3faa79.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-15/14-41/9290c891-04eb-4c34-9ffb-dc661046fa88.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/method/4146](https://participedia.xyz/method/4146)
**Screen size**: 1366 x 768 **Browser size**: 1517 x 706

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Known bug, methods images didn't import. Closed via: https://github.com/participedia/frontend/issues/842
