### ISSUE TITLE
[USERSNAP] spam. how did this get through the review system?

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1912]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/user/423495
**Fields**:
- Add a comment: spam. how did this get through the review system?

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/658efd0e-1be2-4f6a-81eb-9be2bb70d1fd-annotated_d5645d98-fbf6-4323-94b7-26aa2ee34fbd.png?etag=8898389a140e53751979e050de538d76)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/658efd0e-1be2-4f6a-81eb-9be2bb70d1fd-annotated_d5645d98-fbf6-4323-94b7-26aa2ee34fbd.png?etag=8898389a140e53751979e050de538d76)*

**Browser**: Chrome 109 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x795
**[Open #1595 in Usersnap](https://app.usersnap.com/l/feedback/27f8bee1-2d57-4797-bb17-bb3857b3b395?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
spam entry hidden: https://participedia.net/organization/12293

@paninee please look into this asap

**Comment by jesicarson** [comment]
this also got through. both are hidden and users blocked manually via auth0: https://github.com/participedia/usersnaps/issues/1913

**Comment by jesicarson** [comment]
this too: https://github.com/participedia/usersnaps/issues/1914

**Comment by paninee** [comment]
Fixed
