### ISSUE TITLE
[USERSNAP] spam got through review system

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1914]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/user/423492
**Fields**:
- Add a comment: spam got through review system

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/11e87f59-dc60-462c-b72b-290515d041ba-annotated_601e5d32-32fe-4f8c-9b48-b94755b4beb2.png?etag=8d21c370684bd8a5ba8096a207d3da85)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/11e87f59-dc60-462c-b72b-290515d041ba-annotated_601e5d32-32fe-4f8c-9b48-b94755b4beb2.png?etag=8d21c370684bd8a5ba8096a207d3da85)*

**Browser**: Chrome 109 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x795
**[Open #1597 in Usersnap](https://app.usersnap.com/l/feedback/fbb194f0-96e2-40c4-9fff-45a3564109e5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
hidden entry: https://participedia.net/organization/12288

user blocked manually via auth0
