### ISSUE TITLE
[USERSNAP] the entries I approved are still showing up in this list (see previous usersnap - popup did not go away, so I refreshed the page with this result)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1919]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/entries/review
**Fields**:
- Add a comment: the entries I approved are still showing up in this list (see previous usersnap - popup did not go away, so I refreshed the page with this result)

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/4a056427-ac2d-40de-88e0-b1adb00c198f-annotated_93fc57ed-5337-4148-af13-0ec9e5596e5c.png?etag=327bc5b88c105176e6814f6a20c01fba)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/4a056427-ac2d-40de-88e0-b1adb00c198f-annotated_93fc57ed-5337-4148-af13-0ec9e5596e5c.png?etag=327bc5b88c105176e6814f6a20c01fba)*

**Browser**: Chrome 109 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1787x884
**[Open #1602 in Usersnap](https://app.usersnap.com/l/feedback/d1e10dcb-7be5-423d-aa71-6f1ede6594fc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee FYI the approve button didn't work. i am about to try again, but it seems to be the popup issue (however refreshing the page didn't work this time)

**Comment by jesicarson** [comment]
reference: https://github.com/participedia/usersnaps/issues/1918

**Comment by paninee** [comment]
Fixed and deployed. https://github.com/participedia/api/commit/8d3ab5534d6696d795be8f8748bd492c63f0ee75
