### ISSUE TITLE
[USERSNAP] Admin unable to hide entries. (Publishing a new entry works fine, but can't hide existing entries)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1920]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/12308/edit
**Fields**:
- Add a comment: Admin unable to hide entries. (Publishing a new entry works fine, but can&#39;t hide existing entries)

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/74f8b037-1487-4972-be72-2ac6047af998-annotated_a4c1870d-f801-492a-8be8-6f8c02fd730b.png?etag=fa734dd243ed94cacf937f824975fd85)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/74f8b037-1487-4972-be72-2ac6047af998-annotated_a4c1870d-f801-492a-8be8-6f8c02fd730b.png?etag=fa734dd243ed94cacf937f824975fd85)*

**Browser**: Chrome 109 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1584x884
**[Open #1603 in Usersnap](https://app.usersnap.com/l/feedback/2ecfb6d0-6b6c-42aa-9114-bd4ae7a16225?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
was able to hide this today. closing.
