### ISSUE TITLE
[USERSNAP] TODO: hide this duplicate entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1921]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/12301
**Fields**:
- Add a comment: TODO: hide this duplicate entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/50081709-1f14-4bf8-abfa-494ae47aadb4-annotated_d6c115d6-524b-4687-873b-b6f079463cad.png?etag=7889de57929952b2a4bbc72a1049f319)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/50081709-1f14-4bf8-abfa-494ae47aadb4-annotated_d6c115d6-524b-4687-873b-b6f079463cad.png?etag=7889de57929952b2a4bbc72a1049f319)*

**Browser**: Chrome 109 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1584x884
**[Open #1604 in Usersnap](https://app.usersnap.com/l/feedback/1182e7f6-e388-40c2-adbc-420f312014a4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
done
