### ISSUE TITLE
[USERSNAP] TODO: hide this test entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1922]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/12308
**Fields**:
- Add a comment: TODO: hide this test entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6b7b75e6-10ca-45b7-ba65-9651a5411248-annotated_38337938-cab6-4a48-a80a-ec192d8b44fe.png?etag=efe5a274b8846d6403ef66b7decb8171)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6b7b75e6-10ca-45b7-ba65-9651a5411248-annotated_38337938-cab6-4a48-a80a-ec192d8b44fe.png?etag=efe5a274b8846d6403ef66b7decb8171)*

**Browser**: Chrome 109 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1584x884
**[Open #1605 in Usersnap](https://app.usersnap.com/l/feedback/9a158afd-cc8f-41f7-aa54-5c3fede4577c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
done
