### ISSUE TITLE
[USERSNAP] Unable to publish changes to submission details (trying to re-assign authorship to Nancy's actual account)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1924]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/12311/edit
**Fields**:
- Add a comment: Unable to publish changes to submission details (trying to re-assign authorship to Nancy&#39;s actual account)

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/caf7eab1-0827-4c8f-a8f0-35a91afcebc9-annotated_b69d7a02-367d-4955-a3a2-4dd2dda06d5c.png?etag=c1f7f75e88698c3568d3de24567742d4)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/caf7eab1-0827-4c8f-a8f0-35a91afcebc9-annotated_b69d7a02-367d-4955-a3a2-4dd2dda06d5c.png?etag=c1f7f75e88698c3568d3de24567742d4)*

**Browser**: Chrome 110 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1710x893
**[Open #1607 in Usersnap](https://app.usersnap.com/l/feedback/5c3c1080-d14b-4e92-bc2c-a7a7e9c2df4a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
done
