### ISSUE TITLE
[USERSNAP] stuck on publishing while trying to hide this entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1926]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/12301/edit
**Fields**:
- Add a comment: stuck on publishing while trying to hide this entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/a67fa8e5-e9d0-426b-98a8-775eefaf9fec-annotated_5b4d03d1-11ee-494b-bbd6-9deb094f97a2.png?etag=d435e1c6fbac0fc99062775623e89d42)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/a67fa8e5-e9d0-426b-98a8-775eefaf9fec-annotated_5b4d03d1-11ee-494b-bbd6-9deb094f97a2.png?etag=d435e1c6fbac0fc99062775623e89d42)*

**Browser**: Chrome 110 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1140x898
**[Open #1609 in Usersnap](https://app.usersnap.com/l/feedback/cfcf92e3-d084-4675-b528-0413d50f3aef?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
follow up: refreshing the page worked and the entry is hidden. but we should still look into this bug, so we dont get duplicates being published if this popup issue affects new entries.
