### ISSUE TITLE
[USERSNAP] Nine cases like this one that have been submitted by user “romiliogch” since March 9 look suspicious. None of them include narrative content & only three include cover images. And an attempt to look at their profile leads to the user error sh...

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1928]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/case/12413
**Fields**:
- Add a comment: Nine cases like this one that have been submitted by user “romiliogch” since March 9 look suspicious. None of them include narrative content &amp; only three include cover images. And an attempt to look at their profile leads to the user error shown in this screen shot  -- https://capture.dropbox.com/wFQZUO1iPM1z3njl

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/a9d754b6-f7e7-40d2-b35e-6bf20ad325d8-annotated_848dc572-e80b-4f08-85e0-f0ed4ff64339.png?etag=0a7aef28932004cbceaf7efd5aa38581)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/a9d754b6-f7e7-40d2-b35e-6bf20ad325d8-annotated_848dc572-e80b-4f08-85e0-f0ed4ff64339.png?etag=0a7aef28932004cbceaf7efd5aa38581)*

**Browser**: Firefox 111 (Windows 10)
**Screen size**: 1920x1200
**Browser size**: 1882x1035
**[Open #1611 in Usersnap](https://app.usersnap.com/l/feedback/f579477f-aa37-4f44-9413-0dfa793209a9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by paninee** [comment]
I did not approve this person. I will block them. Cannot reproduce any error in blocking/approving logic. Not sure how they got through yet. But will keep an eye on more.

**Comment by jesicarson** [comment]
I'm not sure this person was spam... one of their method entries looked legit. has their content been deleted?

**Comment by jesicarson** [comment]
i dont think they should be blocked.

**Comment by jesicarson** [comment]
see: https://github.com/participedia/usersnaps/issues/1936 (there's a bug happening for this user where entries are duplicating and publishing with no title)

Their method entry looks legitimate to me: https://participedia.net/method/12384

**Comment by jesicarson** [comment]
i was able to view their profile page, and i was able to hide all the duplicates that had no titles. I think i should email them today and see if they reply.
