### ISSUE TITLE
[USERSNAP] Hey... am not sure if its a virus on my laptop but when you click on the External Link it takes you to an escort agency. Just thought I should let you know! Liz :)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1929]
**Sender**: eca311@outlook.com
**Taken at**: https://participedia.net/case/1184
**Fields**:
- Add a comment: Hey... am not sure if its a virus on my laptop but when you click on the External Link it takes you to an escort agency. Just thought I should let you know!
Liz :)

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/dbc470fd-f858-4974-b38f-2ec1c7c00301-annotated_a7b277c7-5f75-4711-ad0e-71f0499f8664.png?etag=72b24ff4a686bfab82c894e9ecebb964)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/dbc470fd-f858-4974-b38f-2ec1c7c00301-annotated_a7b277c7-5f75-4711-ad0e-71f0499f8664.png?etag=72b24ff4a686bfab82c894e9ecebb964)*

**Browser**: Chrome 112 (Windows 10)
**Screen size**: 1280x800
**Browser size**: 1280x681
**[Open #1612 in Usersnap](https://app.usersnap.com/l/feedback/0219c531-552e-44ac-ba74-0defad859d61?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
fixed
