### ISSUE TITLE
Usersnap Feedback - Start Date doesn't go back far enough - some of these cases are from the 1[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#193]
**Sender**: scottowenfletch@gmail.com
**Comment**: Start Date doesn't go back far enough - some of these cases are from the 15thC, is it possible to have the dates go back that far?
[Open #206 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/206)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-18/18-20/d6d7a98c-e120-46db-a94f-a923a945bd74.png'>![Usersnap Feedback - Start Date doesn't go back far enough - some of these cases are from the 1(...)](https://usersnappublic.s3.amazonaws.com/2018-06-18/18-20/d94f17ef-e9e7-48a4-ab6b-e95dafe97f18.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-18/18-20/d6d7a98c-e120-46db-a94f-a923a945bd74.png'>Download original image</a>

**Browser**: Firefox 60 (Windows 10)
**Referer**: [https://participedia.xyz/case/5313/edit](https://participedia.xyz/case/5313/edit)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Haha! Well this is an interesting one... I'm not actually sure how much control we have over the calendar plugin, this might be a special field? Will defer to @dethe, P2 priority unless it's a super easy fix. For now lets use the narrative to note historic dates. How far back should the dates ideally go @scottofletcher?

**Comment by scottofletcher** [comment]
This is actually a really hard one - some of our cases go back for centuries. There are some entered on Indigenous systems of governance which go back to 'time immemorial' (which is obviously unfeasible) but it is possible some (smart alecks most likely) could enter cases on early Athenian democracy which would be problematic. 

Also: wondering if we could have an easier calendar tool? The way Microsoft and Google do it is waaaay easier: you click on the year and it 'zooms out' so you can scroll through the years (like ours does) _but_ then it zooms in to a grid of months to select from (ours just goes straight to the current month of the year you selected and then you have to click through to get the right month). Even if you could click on the month like you can on the year that would be better.

**Comment by jesicarson** [comment]
😂😂😂 can we have a time immemorial check box please!?!

**Comment by scottofletcher** [comment]
@jesicarson @dethe 
RE Calendar design: also see #217

**Comment by jesicarson** [comment]
covered by https://github.com/participedia/frontend/issues/875
