### ISSUE TITLE
[USERSNAP] I've tried filling this "methods, tools & techniques" section, but it won't publish. when I was in the draft stage, this section wouldn't appear in preview - it kept clearing instead of saving

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1930]
**Sender**: None
**Taken at**: https://participedia.net/organization/12416/edit?full=1
**Fields**:
- Add a comment: I&#39;ve tried filling this &#34;methods, tools &amp; techniques&#34; section, but it won&#39;t publish. when I was in the draft stage, this section wouldn&#39;t appear in preview - it kept clearing instead of saving

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e587d764-2eba-4336-a7f6-256cf057e725-annotated_5acf5665-b743-4816-9693-6302f89553c6.png?etag=e72f8ff8355c9ba7453cdbbeb3b4f981)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e587d764-2eba-4336-a7f6-256cf057e725-annotated_5acf5665-b743-4816-9693-6302f89553c6.png?etag=e72f8ff8355c9ba7453cdbbeb3b4f981)*

**Browser**: Chrome 112 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1337x705
**[Open #1613 in Usersnap](https://app.usersnap.com/l/feedback/9ab11054-ccd6-4b33-b48a-f039c025b9ff?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
emailed this user so they can try again. closing for now as this fix has been done i think.

**Comment by paninee** [comment]
This only effect organization. As this field only shows up in org. It was affected by the draft feature. I added a fix and deployed to production. We can have the user try again. @jesicarson

**Comment by jesicarson** [comment]
emailed the user

**Comment by jesicarson** [comment]
the user was able to update their entry successfully.
