### ISSUE TITLE
[USERSNAP] Ça fait 2 fois que je veux des aperçus et que ça marque publier.  SVP ne rien publier sur le Cas du Caribou forestier du Québec .  Merci

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1931]
**Sender**: paquette.marie-chantal@courrier.uqam.ca
**Taken at**: https://participedia.net/case/12459
**Fields**:
- Ajoutez un commentaire: Ça fait 2 fois que je veux des aperçus et que ça marque publier.  SVP ne rien publier sur le Cas du Caribou forestier du Québec .  Merci

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e8104d6d-7db8-4284-9a1c-e5b5b68d1c03-annotated_1868b827-8ec1-4cd8-b24b-15f5c13ca197.png?etag=7e3b18686f6d082b376435cce3d4a329)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e8104d6d-7db8-4284-9a1c-e5b5b68d1c03-annotated_1868b827-8ec1-4cd8-b24b-15f5c13ca197.png?etag=7e3b18686f6d082b376435cce3d4a329)*

**Browser**: Chrome 112 (Windows 10)
**Screen size**: 1280x720
**Browser size**: 1024x455
**[Open #1614 in Usersnap](https://app.usersnap.com/l/feedback/46395c5c-05c1-4a78-b0e6-0025cdee300a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
approved this user today, but entry had no title in approval page, and now i cant find it in search

**Comment by jesicarson** [comment]
https://participedia.net/case/12459 returns "this page cannot be found" on the site

**Comment by paninee** [comment]
Might be related to these 2 black title issues.

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/29439995/236914174-efaaa96a-3704-4174-86e8-2f65a49fa8d9.png">

**Comment by paninee** [comment]
Fixed and deployed live. @jesicarson could you ask the user to try again?

**Comment by jesicarson** [comment]
emailed the user
