### ISSUE TITLE
[USERSNAP] Please hide/remove this double entry, there is a full case by the same name

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1935]
**Sender**: emiljapa@mcmaster.ca
**Taken at**: https://participedia.net/case/12438/edit
**Fields**:
- Add a comment: Please hide/remove this double entry, there is a full case by the same name

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/cdcf9416-34c8-447f-8f4c-f741b91c0cb6-annotated_40514ac6-4e94-40a8-853a-7fc160c9a40d.png?etag=a41b708a99a84f32216b2c6856e0e769)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/cdcf9416-34c8-447f-8f4c-f741b91c0cb6-annotated_40514ac6-4e94-40a8-853a-7fc160c9a40d.png?etag=a41b708a99a84f32216b2c6856e0e769)*

**Browser**: Edge (Chromium) 112 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x961
**[Open #1618 in Usersnap](https://app.usersnap.com/l/feedback/8aa71c6b-9a2d-40df-ab96-d157c3327ce6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
think this is done. dont see the duplicate on search. closing.
