### ISSUE TITLE
[USERSNAP] Unable to hide these new 'case' blank entries, please hide/remove. It seems that 10 or so new entries appeared overnight like this.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1936]
**Sender**: emiljapa@mcmaster.ca
**Taken at**: https://participedia.net/search?selectedCategory=case&page=2
**Fields**:
- Add a comment: Unable to hide these new &#39;case&#39; blank entries, please hide/remove. It seems that 10 or so new entries appeared overnight like this.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b139901d-3446-4252-bdae-15f7aac0c93a-annotated_b4b7b11a-3f4f-4e93-b71a-beae7d778aa6.png?etag=3ee5458b94807d1ae38bf7ea754fe22d)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b139901d-3446-4252-bdae-15f7aac0c93a-annotated_b4b7b11a-3f4f-4e93-b71a-beae7d778aa6.png?etag=3ee5458b94807d1ae38bf7ea754fe22d)*

**Browser**: Edge (Chromium) 112 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x961
**[Open #1619 in Usersnap](https://app.usersnap.com/l/feedback/32f8b2a5-f197-4a25-93d6-178caf647155?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee can you remove these manually? thanks!

**Comment by jesicarson** [comment]
funny, I was able to hide these but only if I typed some text into the title field. was getting the "cannot publish without a title" error modal. 

i'm leaving this open so you can investigate why they showed up in the first place. they were case entries numbers 12375-12381

**Comment by jesicarson** [comment]
this is the user, they have a few entries on their profile with no titles, not sure how that could have happened - https://participedia.net/user/423596

**Comment by jesicarson** [comment]
emailed user to ask which duplicates to keep, and invited editing method with no title. closing
