### ISSUE TITLE
[USERSNAP] unable to reassign authorship via "edit submission details" admin-only section of edit form. i edit the entry, open the field, select the correct user to replace babongile (https://participedia.net/user/423267) and publish, but nothing change...

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1940]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/12320
**Fields**:
- Add a comment: unable to reassign authorship via &#34;edit submission details&#34; admin-only section of edit form. i edit the entry, open the field, select the correct user to replace babongile (https://participedia.net/user/423267) and publish, but nothing changes in the wiki contributor history drop down. I expect to see the user above listed as the first author, but it doesn&#39;t change.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d1a16cb7-9530-4fec-8417-5cbb92817868-annotated_b32104be-208f-47c7-8ed9-c90fcbfd766a.png?etag=2b418ab4e7216ef754ef92951a9636c5)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/d1a16cb7-9530-4fec-8417-5cbb92817868-annotated_b32104be-208f-47c7-8ed9-c90fcbfd766a.png?etag=2b418ab4e7216ef754ef92951a9636c5)*

**Browser**: Chrome 113 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1738x950
**[Open #1623 in Usersnap](https://app.usersnap.com/l/feedback/3d640329-fb35-43b7-a257-a620a865ae8f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
I need to reassign all of these entries to the correct first author: https://docs.google.com/spreadsheets/d/1jn-YvTS18770wBpB34Hea6fv7EIzkvq2iWX6D_Qf6Kc/edit#gid=0

@paninee

**Comment by jesicarson** [comment]
After changing the user and publishing, i go back to the edit form and find that the change has not saved. also note the date is incorrect - it shows today's date  <img width="911" alt="Screenshot 2023-05-09 at 3 51 22 PM" src="https://github.com/participedia/usersnaps/assets/13560530/2cdb166c-39b6-447e-a899-53e522b83473">

**Comment by paninee** [comment]
Fixed and deployed live. @jesicarson

**Comment by jesicarson** [comment]
Great thanks. will test asap.
