### ISSUE TITLE
[USERSNAP] This entry is not in the to be approved list. See email from user. Hi pri.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1944]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/12496
**Fields**:
- Add a comment: This entry is not in the to be approved list. See email from user. Hi pri.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6b5cbfee-5143-4eac-be18-4a996764a59a-annotated_5afe6771-868e-410d-83f0-6abe6d8a0439.png?etag=1cf033bc635a499f6642628d032e95cf)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6b5cbfee-5143-4eac-be18-4a996764a59a-annotated_5afe6771-868e-410d-83f0-6abe6d8a0439.png?etag=1cf033bc635a499f6642628d032e95cf)*

**Browser**: Safari 16 (iOS)
**Screen size**: 390x844
**Browser size**: 390x664
**[Open #1627 in Usersnap](https://app.usersnap.com/l/feedback/f7a861c3-cdee-4c75-b42a-3642aa1d1498?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by paninee** [comment]
@jesicarson did you approve this entry? when I checked it it was already approved and show up on the site.

**Comment by jesicarson** [comment]
i didnt approve it, but it could have been another admin. ill need to re-send the email telling people not to do that. however, i dont see it unless im logged in as an admin - when im not logged in, i cant see the entry. do you not have the same result @paninee ?

**Comment by paninee** [comment]
I see the entry fine without logging in, but it looks empty. @jesicarson 
![image](https://github.com/participedia/usersnaps/assets/29439995/452a9a84-0098-48f9-bebd-8e54ad4d29c8)

**Comment by jesicarson** [comment]
That's strange. I see it now too. Maybe it was just a glitch? Anyway, I've emailed the user. We can close for now and reopen if there are any other things going on .
