### ISSUE TITLE
[USERSNAP] Block button didn't work. Clicked block on the MISOPROSTOL wodare1205@farebus.com entry, the page loaded with the entry still in the list. refreshed the page, the entry is still there.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1945]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/entries/review#
**Fields**:
- Add a comment: Block button didn&#39;t work. Clicked block on the MISOPROSTOL wodare1205@farebus.com entry, the page loaded with the entry still in the list. refreshed the page, the entry is still there.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/0870258c-505d-479d-8c5a-a38ea0a77e99-annotated_9c5ddddc-907c-4095-8080-e4948a9e6eb9.png?etag=121e613d2d11346d281448a141a13927)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/0870258c-505d-479d-8c5a-a38ea0a77e99-annotated_9c5ddddc-907c-4095-8080-e4948a9e6eb9.png?etag=121e613d2d11346d281448a141a13927)*

**Browser**: Chrome 113 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1783x933
**[Open #1628 in Usersnap](https://app.usersnap.com/l/feedback/d5b03b21-a039-4083-8290-1a422b0cd8ca?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
#1946 related?
