### ISSUE TITLE
[USERSNAP] approve button always requires page refresh

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1946]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/entries/review#
**Fields**:
- Add a comment: approve button always requires page refresh

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/a88da179-afd7-41a7-9a0d-33c3677a8124-annotated_c286fff8-9244-4aea-a626-8ce2166f1bc9.png?etag=9de4e0deda0d895f994bdc9bc8a4a013)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/a88da179-afd7-41a7-9a0d-33c3677a8124-annotated_c286fff8-9244-4aea-a626-8ce2166f1bc9.png?etag=9de4e0deda0d895f994bdc9bc8a4a013)*

**Browser**: Chrome 113 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1783x933
**[Open #1629 in Usersnap](https://app.usersnap.com/l/feedback/5f30270c-6af3-4caa-b5c1-8f66c89ce7a4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
The last (many) times that I've approved entries, the approve progress modal/ popup never goes away and I always have to refresh the page. I don't care/mind doing this, but if we want other admins on this at some point it should be working consistently. Thanks!
