### ISSUE TITLE
Usersnap Feedback - Search Requires Symbols to Work - no results returned without using "ó" wh[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#196]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Search Requires Symbols to Work - no results returned without using "ó" which not a lot of people have on their keyboards (note: Google Translate accurately recognizes words even without accents/symbols)
[Open #209 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/209)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-18/19-22/288aaeb5-c12d-4c13-9459-86899f855a0e.png'>![Usersnap Feedback - Search Requires Symbols to Work - no results returned without using "ó" wh(...)](https://usersnappublic.s3.amazonaws.com/2018-06-18/19-22/7003e33a-ce45-4d5a-a48b-8cb1ae2d5f7c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-18/19-22/288aaeb5-c12d-4c13-9459-86899f855a0e.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/?query=redaccion](https://participedia.xyz/?query=redaccion)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 882

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
This issue was moved to participedia/frontend#848
