### ISSUE TITLE
[USERSNAP] can't publish a collection

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1962]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/collection/new
**Fields**:
- Add a comment: can&#39;t publish a collection

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6e7a0d2c-ddfc-4892-bb99-637cc7b956f3-annotated_98f89a3c-f3b8-4930-aa45-650b781c2b41.png?etag=690dd50d857f11e7ba7b9d376453acc4)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/6e7a0d2c-ddfc-4892-bb99-637cc7b956f3-annotated_98f89a3c-f3b8-4930-aa45-650b781c2b41.png?etag=690dd50d857f11e7ba7b9d376453acc4)*

**Browser**: Chrome 114 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1633x759
**[Open #1645 in Usersnap](https://app.usersnap.com/l/feedback/ed8964da-ccb9-43d2-aa96-779963d2ec1d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee 

Not sure why this won't work. I've filled the fields correctly and done the captcha. I'll try without an image and see what happens. 

Also note - the preview button does not work for entering a collection - not sure if this would work anyway? maybe we should remove that button for collections. 

Here's what I have filled in so far:
<img width="823" alt="Screenshot 2023-07-24 at 10 04 59 AM" src="https://github.com/participedia/usersnaps/assets/13560530/dbb1c190-0574-458c-b77b-680db45ae7aa">
<img width="1648" alt="Screenshot 2023-07-24 at 10 05 09 AM" src="https://github.com/participedia/usersnaps/assets/13560530/718c7a71-5a4c-45c4-8f55-2ac35fdfc701">

**Comment by jesicarson** [comment]
I removed the image but I still get this error:

<img width="1639" alt="Screenshot 2023-07-24 at 10 07 28 AM" src="https://github.com/participedia/usersnaps/assets/13560530/22bef87e-c2fa-43d9-84a8-6e42d38f1401">

**Comment by jesicarson** [comment]
@paninee 

Here's the content of the collection we need to publish today/tomorrow (newsletter going out Wednesday, we wanted to include this) -

Title:

University of the Western Cape Students

Description:

With a focus on South Africa, the UWC course 'Contemporary Democratic Theory and Practice,' invites students to conduct their own research on topics such as citizen engagement, deliberative decision-making, inclusive governance, and the intersection of technology and democracy. 

Image:

![UWC Participedia Collection_Cover page](https://github.com/participedia/usersnaps/assets/13560530/d9580141-32dd-4153-8e7c-f2ef495a2085)

**Comment by jesicarson** [comment]
Not sure if collections work with drafts? but there's no draft collection in my drafts section either.

**Comment by jesicarson** [comment]
related maybe: #1963
