### ISSUE TITLE
[USERSNAP] new featured collection (University of the Western Cape (UWC) Students) not showing up on the homepage slider

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1965]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/
**Fields**:
- Add a comment: new featured collection (University of the Western Cape (UWC) Students) not showing up on the homepage slider

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/545b5669-50be-412a-aa58-25d9c85663d3-annotated_22dd69f9-100e-4962-b4c8-e3be45713a7c.png?etag=1d09946d2f5a2f664438fea9bcf0b4cf)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/545b5669-50be-412a-aa58-25d9c85663d3-annotated_22dd69f9-100e-4962-b4c8-e3be45713a7c.png?etag=1d09946d2f5a2f664438fea9bcf0b4cf)*

**Browser**: Chrome 115 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1442x828
**[Open #1648 in Usersnap](https://app.usersnap.com/l/feedback/6dac8a23-dafc-4794-a50e-009f14878c81?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
shows up as featured on search but not home :

<img width="1420" alt="Screenshot 2023-07-28 at 1 31 03 PM" src="https://github.com/participedia/usersnaps/assets/13560530/4f5b5cbd-a4ef-44d7-be9d-136990a176cd">

**Comment by paninee** [comment]
Fxied and deployed.
