### ISSUE TITLE
[USERSNAP] I am trying to change the title of this entry to "Dialogue-to-Change (Study Circles)" but I keep getting this error message '' "Sorry, something went wrong. Please try again."

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1967]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/method/188/edit?full=1
**Fields**:
- Add a comment: I am trying to change the title of this entry to &#34;Dialogue-to-Change (Study Circles)&#34; but I keep getting this error message &#39;&#39; &#34;Sorry, something went wrong. Please try again.&#34;

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/fdd8a000-4c1a-43d9-bd1e-9b6664bccb48-annotated_7a98d4be-dc7a-4c2b-a172-b5f83c66bd93.png?etag=09adfc6272ee215ed60d7380839df36d)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/fdd8a000-4c1a-43d9-bd1e-9b6664bccb48-annotated_7a98d4be-dc7a-4c2b-a172-b5f83c66bd93.png?etag=09adfc6272ee215ed60d7380839df36d)*

**Browser**: Firefox 116 (Windows 10)
**Screen size**: 1920x1200
**Browser size**: 1920x1047
**[Open #1650 in Usersnap](https://app.usersnap.com/l/feedback/fcf0730b-75fb-4b68-8855-6f5a30677b4c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
looks like Pat was able to edit this after all. the title of the entry is updated.

![Screenshot 2023-08-15 at 1 15 34 PM](https://github.com/participedia/usersnaps/assets/13560530/e3836727-9e60-40bb-a62e-e9a601266feb)


closing this
