### ISSUE TITLE
[USERSNAP] Stuck on this modal when approving an entry

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1968]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/entries/review
**Fields**:
- Add a comment: Stuck on this modal when approving an entry

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/118c08a7-5014-4f22-b81a-c1c7831e62e3-annotated_9a07e732-243f-4320-a858-080a4eb41334.png?etag=94002a7b08e2fce4f473da3a76f1f26f)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/118c08a7-5014-4f22-b81a-c1c7831e62e3-annotated_9a07e732-243f-4320-a858-080a4eb41334.png?etag=94002a7b08e2fce4f473da3a76f1f26f)*

**Browser**: Safari 16 (iOS)
**Screen size**: 390x844
**Browser size**: 390x664
**[Open #1651 in Usersnap](https://app.usersnap.com/l/feedback/a02456f1-1d48-4675-a1fe-f513e94917ba?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
the approval went through once i refreshed the page. Closing for now. will let you know if it happens again.
