### ISSUE TITLE
[USERSNAP] Verified bug on method image upload. See Jon Stever email.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1970]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/method/6426/edit
**Fields**:
- Add a comment: Verified bug on method image upload. See Jon Stever email.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2170899e-308a-4c49-9408-f6cfc0382ef7-annotated_743ff565-6a22-431d-b2cf-dae7c4cd3363.png?etag=2572846228c6a7b25bd5a8d268534747)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2170899e-308a-4c49-9408-f6cfc0382ef7-annotated_743ff565-6a22-431d-b2cf-dae7c4cd3363.png?etag=2572846228c6a7b25bd5a8d268534747)*

**Browser**: Chrome 116 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1751x869
**[Open #1653 in Usersnap](https://app.usersnap.com/l/feedback/f5fe225d-3428-4e25-bfef-04d920f1e85a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee please have a look at this when you can, and keep me posted so we can inform Jon when fixed. Thanks!

**Comment by jesicarson** [comment]
![ADDIS Process v5 4](https://github.com/participedia/usersnaps/assets/13560530/8994d4a1-d804-4837-be4f-88727be9b3ca)

Here's the attempted upload image. It's a small png 110KB so size isn't the issue.

**Comment by paninee** [comment]
Duplicate of https://github.com/participedia/api/issues/1144
