### ISSUE TITLE
[USERSNAP] Bug in multi language edit. Scenario: Originally published with French text in EN mode, auto translation did not occur. I copied the french text in the brief description to the french drop down, and added english text in the english drop down...

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1973]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/organization/12701
**Fields**:
- Add a comment: Bug in multi language edit. Scenario: Originally published with French text in EN mode, auto translation did not occur. I copied the french text in the brief description to the french drop down, and added english text in the english drop down. The english shows up in EN mode, but the french text has disappeared when using the site in FR mode.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/47bcfc04-7aef-40db-bb06-914393278f1e-annotated_e299a8ee-94ed-407c-8525-4129a78a42e5.png?etag=8668b55c8c0f6b5dbbbcd8019bfed358)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/47bcfc04-7aef-40db-bb06-914393278f1e-annotated_e299a8ee-94ed-407c-8525-4129a78a42e5.png?etag=8668b55c8c0f6b5dbbbcd8019bfed358)*

**Browser**: Chrome 116 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1535x966
**[Open #1656 in Usersnap](https://app.usersnap.com/l/feedback/1883a4fb-4cb3-4baf-a182-cf07b1415e06?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
I tried using the site in FR mode, adding the title and short description in French, but I got stuck on the publish modal and the changes did not save. 

I also got the error message before that, that the entry couldn't be saved without a title. 

So I think because the french text wasn't translated correctly, the title field is blank in all the other languages, which makes an error occur because it's a required field.
