### ISSUE TITLE
[USERSNAP] Clicked "Results CSV" button on this collection, which opened a new tab with "Internal Server Error"

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1976]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/collection/12702?selectedCategory=case
**Fields**:
- Add a comment: Clicked &#34;Results CSV&#34; button on this collection, which opened a new tab with &#34;Internal Server Error&#34;

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/bc97b09e-4a44-4029-993b-c91a637d6945-annotated_11130fcd-a6de-4bd7-a941-ac9ef1e2755f.png?etag=20d1c0942e8c4cd40eb5947529ffd836)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/bc97b09e-4a44-4029-993b-c91a637d6945-annotated_11130fcd-a6de-4bd7-a941-ac9ef1e2755f.png?etag=20d1c0942e8c4cd40eb5947529ffd836)*

**Browser**: Chrome 117 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1494x859
**[Open #1659 in Usersnap](https://app.usersnap.com/l/feedback/e8ffd08d-90b5-4441-a88b-dd83ba655854?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
i assume CSV download is supposed to work on collections in the same way it would with a set of applied filters
