### ISSUE TITLE
Usersnap Feedback - Component Field BUG - I should not be able to select the current case as a [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#198]
**Sender**: scottowenfletch@gmail.com
**Comment**: Component Field BUG - I should not be able to select the current case as a component or parent. 
[Open #211 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/211)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-19/01-14/3625dc1e-b12b-40ab-a418-3f2096810f4a.png'>![Usersnap Feedback - Component Field BUG - I should not be able to select the current case as a (...)](https://usersnappublic.s3.amazonaws.com/2018-06-19/01-14/fa89c504-6601-4a67-8e1a-2e4a3f12a6da.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-19/01-14/3625dc1e-b12b-40ab-a418-3f2096810f4a.png'>Download original image</a>

**Browser**: Firefox 60 (Windows 10)
**Referer**: [https://participedia.xyz/case/5317/edit](https://participedia.xyz/case/5317/edit)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
This issue was moved to participedia/frontend#846
