### ISSUE TITLE
[USERSNAP] No title on case requiring review

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1990]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/entries/review#
**Fields**:
- Add a comment: No title on case requiring review

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/7018f79f-d92a-4ed1-8d84-c4d6f55837e5-annotated_4c43d599-e63b-4971-a3be-8a25fb6b71ef.png?etag=fb47e986468cfc99e2f179da372d3f1f)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/7018f79f-d92a-4ed1-8d84-c4d6f55837e5-annotated_4c43d599-e63b-4971-a3be-8a25fb6b71ef.png?etag=fb47e986468cfc99e2f179da372d3f1f)*

**Browser**: Chrome 118 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x789
**[Open #1673 in Usersnap](https://app.usersnap.com/l/feedback/a01818ae-bd2c-4236-a0d5-78489ecd523c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee this is still showing up on the review entries page.

**Comment by jesicarson** [comment]
![Screenshot 2024-04-10 at 2 56 06 PM](https://github.com/participedia/usersnaps/assets/13560530/98e08ab0-d14e-4715-93a5-f93b924ca49d)
