### ISSUE TITLE
[USERSNAP] clicked download on full cases dataset and was directed to this page, but my dataset isn't here. if i didn't know that it will take a few minutes, i'd find this confusing. let's add some explanatory text to this page, or a modal that let's pe...

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1991]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/exports/csv
**Fields**:
- Add a comment: clicked download on full cases dataset and was directed to this page, but my dataset isn&#39;t here. if i didn&#39;t know that it will take a few minutes, i&#39;d find this confusing. let&#39;s add some explanatory text to this page, or a modal that let&#39;s people know that this is where their results will be when they&#39;re ready, sometimes this takes a few minutes, and they&#39;ll need to refresh the page to see them. also would be good to know that you can find this page again via the profile drop down menu.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/bd9fbb97-1396-4fe3-91d2-92cd5cada5ab-annotated_9c7b7eb9-3775-41b0-b90a-505a85d37a16.png?etag=5173d30ce5302b428088bab6b4139847)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/bd9fbb97-1396-4fe3-91d2-92cd5cada5ab-annotated_9c7b7eb9-3775-41b0-b90a-505a85d37a16.png?etag=5173d30ce5302b428088bab6b4139847)*

**Browser**: Chrome 118 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x767
**[Open #1674 in Usersnap](https://app.usersnap.com/l/feedback/8e606790-40f1-455b-8b06-7a19eab3765e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee Add the following text below the title:

Your downloaded CSV files will load here when they have exported fully, this may take a few minutes. Please refresh the page to load your most recent downloads. This page is accessible anytime via the "My CSV Downloads" link found on your profile menu.
