### ISSUE TITLE
[USERSNAP] Missing case data in CSV columns: X, Y, Z, AA, AB (components, specific methods)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1992]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/exports/csv
**Fields**:
- Add a comment: Missing case data in CSV columns: X, Y, Z, AA, AB (components, specific methods)

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/4d6f76db-6962-4f38-a21b-ffd3ad4f5789-annotated_d48afdfb-3ccd-42df-af08-f6ec5fc102df.png?etag=7cb788523a5fad305b13e8cac92f4a9d)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/4d6f76db-6962-4f38-a21b-ffd3ad4f5789-annotated_d48afdfb-3ccd-42df-af08-f6ec5fc102df.png?etag=7cb788523a5fad305b13e8cac92f4a9d)*

**Browser**: Chrome 118 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x767
**[Open #1675 in Usersnap](https://app.usersnap.com/l/feedback/0813f82b-4093-48ad-bf3d-80ae85e567ca?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
Follow up for Jesi: 

Bernd Schlipphak, bschl_04@uni-muenster.de
victoria.herbig@gess.ethz.ch 
Christoph.Niessen@uantwerpen.be 

- [x] inform user of plan and timing for bug fix

> - [x] Victoria
> - [x] Christoph
> - [x] Bernd

- [ ] inform user when testing is possible TBC

> - [ ] Victoria
> - [ ] Christoph
> - [ ] Bernd

- [ ] inform user when fix implemented 

> - [ ] Victoria
> - [ ] Christoph
> - [ ] Bernd

**Comment by jesicarson** [comment]
There seem to be a bunch of other empty columns in the latest export as well. 

@paninee here are a couple screenshots of fully empty columns:

<img width="1514" alt="Screenshot 2023-11-05 at 9 36 57 AM" src="https://github.com/participedia/usersnaps/assets/13560530/2444ac1d-cd3c-4cd9-8627-400ad00060de">

<img width="1514" alt="Screenshot 2023-11-05 at 9 57 55 AM" src="https://github.com/participedia/usersnaps/assets/13560530/26b12371-fd00-4bec-bf42-3f57c85a9aea">

**Comment by paninee** [comment]
User reported

```
I tried to download the CSV files on Cases and on Methods, but both 
files seem to lack some indicators. What I am searching for is a 
database linking the cases also to the methods used within the cases 
(indicatpors: Types of Methods, Types of specific methods / tools) as 
well as to all the other indicators mentioned in the Codebook on cases 
(https://docs.google.com/spreadsheets/d/1UnczVqn3U9L1Y8vLTQ2pv6rYI0qMMFEM8f8xXlNz4KA/edit#gid=0). 
```

**Comment by jesicarson** [comment]
User reported today:

Hi there,
I was trying to download a CSV file that contains organizations that are active in the climate sector.
However, it seems to me that the file only contains one row with all the column titles and no other information.

What am I doing wrong in the download or reading process?

Your feedback would be greatly appreciated!

Thanks and all the best,

Victoria Herbig

**Comment by jesicarson** [comment]
user reported yesterday:

Dear colleagues

 

I hope this message finds you well.

 

As researcher in political science at the University of Antwerp, I contact you with a question regarding the Participedia database. After accessing the ‘Cases’ part on your website, I tried to download data for all cases via the Results-CSV button. However, I realized that the downloaded data table is empty if no filters are applied. When applying filters, however, I can never obtain all 2168 currently registered cases – even if I tick all boxes in one of the different categories.

 

When downloaded data based on filters, I also realize that much case information is missing in the spreadsheet for cases where the information is included on the website.


Would you have a complete XLSX or CSV sheet that you could share directly via e-mail?

 

Needless to say that any usage will be cited properly.

 

Many thanks in advance and

kind regards,

 

Christoph Niessen
