### ISSUE TITLE
[USERSNAP] Stage review of Participedia School page, a few small edits. 

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1997]
**Sender**: jesi.carson@gmail.com
**Taken at**: http://ppedia-stage.herokuapp.com/school#
**Fields**:
- Add a comment: Stage review of Participedia School page, a few small edits. Will add in github. 

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/9276a550-becf-426f-95f7-1781232a96f7-annotated_a286e0ae-a1e9-4213-8124-3c0a352d3e74.png?etag=726d85a81c27f518fd4628efae7c1a70)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/9276a550-becf-426f-95f7-1781232a96f7-annotated_a286e0ae-a1e9-4213-8124-3c0a352d3e74.png?etag=726d85a81c27f518fd4628efae7c1a70)*

**Browser**: Chrome 118 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1479x860
**[Open #1680 in Usersnap](https://app.usersnap.com/l/feedback/6f93bb95-0c71-4baf-b94b-f10be5589251?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
- [x] Use updated image for transnational school graphic [available here](https://drive.google.com/file/d/10Q1uFnyEbrtrxlBIeh2q9WFekUiyGrFW/view?usp=drive_link)
- [x] add space **below** the transnational school graphic (30px)
- [x] add space **above and below** the horizontal line between sections (30px)
