### ISSUE TITLE
Usersnap Feedback - Case data BUG - Duplicate methods appear in sidebar and edit view

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#200]
**Sender**: jesi.carson@gmail.com
**Comment**: Case data BUG - Duplicate methods appear in sidebar and edit view
[Open #213 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/213)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-19/18-39/3f584e38-39e3-405e-a5de-8893a63962eb.png'>![Usersnap Feedback - Case data BUG - Duplicate methods appear in sidebar and edit view](https://usersnappublic.s3.amazonaws.com/2018-06-19/18-39/d9498665-01a9-4447-80bf-8744f5c680fd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-19/18-39/3f584e38-39e3-405e-a5de-8893a63962eb.png'>Download original image</a>

**Browser**: Chrome 67 (Macintosh)
**Referer**: [https://participedia.xyz/case/4512](https://participedia.xyz/case/4512)
**Screen size**: 1280 x 800 **Browser size**: 1258 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Ah, this is happening because of an interaction with the versioning system I didn't think about. Working on a fix. Also will prevent adding a case as a component of itself.

**Comment by jesicarson** [comment]
Thanks @dethe - I consolidated all the usersnaps about duplicated content here: https://github.com/participedia/frontend/issues/855

**Comment by dethe** [comment]
Yes, I'm working my way through the list there.
