### ISSUE TITLE
[USERSNAP] Typed an "h" into the primary organizer field, displayed a big list of spam organizations. 

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#2005]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/new?source=new?full=1
**Fields**:
- Add a comment: Typed an &#34;h&#34; into the primary organizer field, displayed a big list of spam organizations. 

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/8375cfda-c6de-4e8d-8ef8-89b458582e8f-annotated_5ec24caa-1ed6-4777-a3c2-58b2c8d3c6db.png?etag=ad93db78fbfaf2a21ab970e949638eae)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/8375cfda-c6de-4e8d-8ef8-89b458582e8f-annotated_5ec24caa-1ed6-4777-a3c2-58b2c8d3c6db.png?etag=ad93db78fbfaf2a21ab970e949638eae)*

**Browser**: Chrome 119 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1561x907
**[Open #1688 in Usersnap](https://app.usersnap.com/l/feedback/7d5fe293-0e14-4a77-8cee-ae6199901516?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
![Screenshot 2023-12-04 at 3 15 31 PM](https://github.com/participedia/usersnaps/assets/13560530/855cdbcc-b94c-471b-a3cb-04e9e0c3b67a)

**Comment by jesicarson** [comment]
I went to the users page and deleted the user who published this entry. I don't know why there are so many abortion organizations showing up in the database, but not in search. 

Can we make sure not to display hidden or un-approved entries in the entry form type to search fields? @paninee

**Comment by jesicarson** [comment]
The abortion organizations are not showing up in search, so they must be un-approved spam entries or something.
