### ISSUE TITLE
Usersnap Feedback - Data field bug: Cannot Deselect Value I can't remove this selection. It wa[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#201]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Data field bug: Cannot Deselect Value
I can't remove this selection. It was ported from the .net entry. 
[Open #214 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/214)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-19/18-57/63a212e5-e785-49d9-98f0-4464ca28d8dd.png'>![Usersnap Feedback - Data field bug: Cannot Deselect Value I can't remove this selection. It wa(...)](https://usersnappublic.s3.amazonaws.com/2018-06-19/18-57/c7f3ab71-4a03-477f-b028-9aaaada5dcfc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-19/18-57/63a212e5-e785-49d9-98f0-4464ca28d8dd.png'>Download original image</a>

**Browser**: Firefox 60 (Windows 10)
**Referer**: [https://participedia.xyz/case/4524/edit](https://participedia.xyz/case/4524/edit)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
closing. known bug: https://github.com/participedia/usersnaps/issues/199
