### ISSUE TITLE
[USERSNAP] High Pri - Run Phrase translation on Participedia School page so it shows up in supported languages

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#2010]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/participediaschool
**Fields**:
- Add a comment: High Pri - Run Phrase translation on Participedia School page so it shows up in supported languages

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2a92bae0-f8cd-49e6-9760-4785e2915293-annotated_ef40eca1-6c07-424d-a476-8abdd1173978.png?etag=eb60011fef768c774f2cf9da571edebb)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/2a92bae0-f8cd-49e6-9760-4785e2915293-annotated_ef40eca1-6c07-424d-a476-8abdd1173978.png?etag=eb60011fef768c774f2cf9da571edebb)*

**Browser**: Chrome 120 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1796x906
**[Open #1693 in Usersnap](https://app.usersnap.com/l/feedback/17d1a4f0-3f8e-44a8-bd1d-2139cee7d6d0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee  [Portuguese promo image here.](https://drive.google.com/file/d/1K0vSjhE0zkVaOerWfcOF_wl3JqfO2nhZ/view?usp=drive_link)
