### ISSUE TITLE
[USERSNAP] Cleaning up DB revealed legit entries among spam. Check if these users still need approval. (more below in list as well)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#2013]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/entries/review#
**Fields**:
- Add a comment: Cleaning up DB revealed legit entries among spam. Check if these users still need approval. (more below in list as well)

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/396959c9-6ee1-48da-bbc3-9a3d6e9d721b-annotated_d4e19289-cb9f-4ff0-ba4d-bdf0ba168300.png?etag=ac4c177e3cf644f0923146bd4addd6b1)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/396959c9-6ee1-48da-bbc3-9a3d6e9d721b-annotated_d4e19289-cb9f-4ff0-ba4d-bdf0ba168300.png?etag=ac4c177e3cf644f0923146bd4addd6b1)*

**Browser**: Chrome 120 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1577x883
**[Open #1696 in Usersnap](https://app.usersnap.com/l/feedback/03f800d7-a08b-4b51-b8ad-a52fcd0cad7a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
FYI: Just noticed that a bunch of the non-spam ones are duplicate entries, not multiple edits to the same entry.

**Comment by jesicarson** [comment]
We discussed potentially letting me finish blocking the spam, then just not showing anything in the table before Oct 2022. 

Not sure what the result of approving the duplicates would be.
