### ISSUE TITLE
[USERSNAP] Translation not working

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#2015]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/13046
**Fields**:
- Add a comment: Entry Missing Title - how did this publish if title is a required field?

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/02de9db7-1610-4b6a-b7a1-b9c676feff41-annotated_61815d2a-1dee-4134-a5f8-814b6e613f51.png?etag=a62b8fbd9b34e382abf88dbf0056bc77)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/02de9db7-1610-4b6a-b7a1-b9c676feff41-annotated_61815d2a-1dee-4134-a5f8-814b6e613f51.png?etag=a62b8fbd9b34e382abf88dbf0056bc77)*

**Browser**: Chrome 120 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1489x932
**[Open #1698 in Usersnap](https://app.usersnap.com/l/feedback/e94f6d2c-16cc-4eff-b271-75923402267c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
this entry is on the live site, not awaiting approval 

title is blank in all languages except original language of entry (FR)

**Comment by jesicarson** [comment]
Could this issue be related? https://github.com/participedia/usersnaps/issues/1990

**Comment by jesicarson** [comment]
this entry was approved today (after Pan updated translation key) but there is no text in any languages other than EN (original language) https://participedia.net/organization/13050

**Comment by jesicarson** [comment]
see #2017 - on search results page - if you change the language to french, the entries with missing titles now have titles.

**Comment by jesicarson** [comment]
Viewing search results page in FR reveals many entries that have not been translated from EN:

![Screenshot 2024-01-15 at 11 24 50 AM](https://github.com/participedia/usersnaps/assets/13560530/bd9a1847-974b-4ec8-9e2e-23c14ff056a3)
