### ISSUE TITLE
[USERSNAP] Clicking the title link for the 'Greenway' entry on the approval list leads to "this page cannot be found"

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#2016]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/entries/review
**Fields**:
- Add a comment: Clicking the title link for the &#39;Greenway&#39; entry on the approval list leads to &#34;this page cannot be found&#34;

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/009387a3-87d9-4539-856d-2f93c3feb4f2-annotated_ce8f4316-fee1-4a75-80a9-4c426704d653.png?etag=7d0093a801da6ba8c7f86e3e52a7925e)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/009387a3-87d9-4539-856d-2f93c3feb4f2-annotated_ce8f4316-fee1-4a75-80a9-4c426704d653.png?etag=7d0093a801da6ba8c7f86e3e52a7925e)*

**Browser**: Chrome 120 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1460x932
**[Open #1699 in Usersnap](https://app.usersnap.com/l/feedback/f34a20a4-1b5f-4451-92f2-754affb7a82a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
![Screenshot 2024-01-12 at 11 11 09 AM](https://github.com/participedia/usersnaps/assets/13560530/482c58e9-52d9-420e-8664-af99c4299983)

**Comment by jesicarson** [comment]
@paninee this is still happening. See #2025 (which is very likely spam, but I can't be 100% sure until I see the entry).

I had gone in and approved these legit entries already, despite this error message. Approving them works, they appear on the site. But we do need to fix this bug. 

Thanks!
