### ISSUE TITLE
Usersnap Feedback - Hyperlink Does Not Recognize Symbols.  NOTE: the exact same URL was entere[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#202]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Hyperlink Does Not Recognize Symbols. 
NOTE: the exact same URL was entered as in the Link data field and works in the sidebar
[Open #215 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/215)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-19/19-02/5b413139-9331-429a-ab58-9e944b71f648.png'>![Usersnap Feedback - Hyperlink Does Not Recognize Symbols.  NOTE: the exact same URL was entere(...)](https://usersnappublic.s3.amazonaws.com/2018-06-19/19-02/1a5e8f49-5ee2-4bf8-ac6e-117fb3609ef9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-19/19-02/5b413139-9331-429a-ab58-9e944b71f648.png'>Download original image</a>

**Browser**: Firefox 60 (Windows 10)
**Referer**: [https://participedia.xyz/case/4524](https://participedia.xyz/case/4524)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Connected to :https://github.com/participedia/usersnaps/issues/152 - not 100% sure its the same so leaving this open.
