### ISSUE TITLE
[USERSNAP] Update Registration & Scholarships text. High Pri. 

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#2028]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/participediaschool
**Fields**:
- Add a comment: Update Registration &amp; Scholarships text. High Pri. 

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/112e7c77-edf7-4ce8-a41c-831b9544dd5f-annotated_56a0b746-272d-4292-9c7f-94bd953c2463.png?etag=384151e76d5e606fdbd661c9d9f4e746)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/112e7c77-edf7-4ce8-a41c-831b9544dd5f-annotated_56a0b746-272d-4292-9c7f-94bd953c2463.png?etag=384151e76d5e606fdbd661c9d9f4e746)*

**Browser**: Chrome 121 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1684x915
**[Open #1711 in Usersnap](https://app.usersnap.com/l/feedback/bccf1a89-132b-414d-9c9d-e4966b34a134?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
Registration & Scholarships:

Participants can register to attend in person at all locations until spots are filled (50 spaces per campus). All food and drink during the program will be provided to attendees.

Travel and housing scholarship applications are now closed. Limited registration waiver scholarships are available on a ‘needs basis’ and can be indicated in the registration form. 

[Register Here](https://www.surveymonkey.com/r/participediaschool2024)

Once registered, you will be emailed a secure payment processing link and further information regarding next steps. Please note that our registration cap is 50 people per location, sign up early to secure your spot.

If you have any questions please contact [info@participedia.net](mailto:info@participedia.net)

**Comment by jesicarson** [comment]
@paninee  updated text above

**Comment by jesicarson** [comment]
Oh shoot we also have to remove all reference to Portuguese / Spanish language.. I will provide a few more edits.

**Comment by jesicarson** [comment]
@paninee all edits now reflected in this google doc using suggested edits: https://docs.google.com/document/d/1PB3RMayJsgkQpBQxpMZHt2hUeUhoX3jyq2WAKSjoPIo/edit?usp=sharing

**Comment by jesicarson** [comment]
TODO for me:

- [x] let ricardo know when the edits are live on the site
