### ISSUE TITLE
[USERSNAP] This entry has an image. Not showing up.

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#2032]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/search
**Fields**:
- Add a comment: This entry has an image. Not showing up.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/45a15c4e-cef4-4b9e-9e32-b86f3e59c044-annotated_a640a24b-e9c9-4dac-b226-5cab81375d3d.png?etag=7e464cea0bcdb67ed65a50f49b5561b5)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/45a15c4e-cef4-4b9e-9e32-b86f3e59c044-annotated_a640a24b-e9c9-4dac-b226-5cab81375d3d.png?etag=7e464cea0bcdb67ed65a50f49b5561b5)*

**Browser**: Chrome 122 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1576x849
**[Open #1715 in Usersnap](https://app.usersnap.com/l/feedback/9a939ad9-0cf9-4e8b-a644-10ce5b4eb21c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
all of them have images actually. there's a bug.

**Comment by jesicarson** [comment]
#2031 related

**Comment by jesicarson** [comment]
- [ ] email Oyin and Paul when this is fixed
