### ISSUE TITLE
[USERSNAP] Bug - Entry not visible to non-admins

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#2039]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/8361
**Fields**:
- Add a comment: Bug - Entry not visible to non-admins

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/3389c8e4-2b48-462e-9ccf-53c9f6f35692-annotated_555b16ed-7fbd-4218-b40f-2992cc7ad712.png?etag=237e5a095dc909370b882113adf24799)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/3389c8e4-2b48-462e-9ccf-53c9f6f35692-annotated_555b16ed-7fbd-4218-b40f-2992cc7ad712.png?etag=237e5a095dc909370b882113adf24799)*

**Browser**: Chrome 124 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1398x788
**[Open #1722 in Usersnap](https://app.usersnap.com/l/feedback/3dda735a-7c17-41f6-8c34-9c021c496b04?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
Entry originally published in 2022, shouldn't require admin review.

When not logged in: 

<img width="1225" alt="Screenshot 2024-05-04 at 9 04 32 AM" src="https://github.com/participedia/usersnaps/assets/13560530/d307bae6-5849-4743-b196-5819163042b1">

**Comment by jesicarson** [comment]
- [ ] let user know when this is addressed (see Paolo and Katherine email thread - Re: Final Project Query)

**Comment by jesicarson** [comment]
entry is hidden... not sure why maybe a duplicate.

**Comment by jesicarson** [comment]
not a duplicate, un-hiding and will email paolo and katherine. closing
