### ISSUE TITLE
Usersnap Feedback - "Your Relationship to This Case" should not be visible in sidebar (and sho[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#204]
**Sender**: scottowenfletcher@gmail.com
**Comment**: "Your Relationship to This Case" should not be visible in sidebar (and should not be editable) 
[Open #217 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/217)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-20/01-12/f7c2443b-5d10-468e-8b7b-011beed8f71f.png'>![Usersnap Feedback - "Your Relationship to This Case" should not be visible in sidebar (and sho(...)](https://usersnappublic.s3.amazonaws.com/2018-06-20/01-12/5353d99f-c508-4cd1-83dd-9d01a3a3013e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-20/01-12/f7c2443b-5d10-468e-8b7b-011beed8f71f.png'>Download original image</a>

**Browser**: Firefox 60 (Windows 10)
**Referer**: [https://participedia.xyz/case/5320](https://participedia.xyz/case/5320)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
This issue was moved to participedia/frontend#864
