### ISSUE TITLE
[USERSNAP] It looks like the app that powers the example of data visualization on this page isn't responding

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#2049]
**Sender**: pscully@clearviewconsultingllc.com
**Taken at**: https://participedia.net/research
**Fields**:
- Add a comment: It looks like the app that powers the example of data visualization on this page isn&#39;t responding

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/fc016dc3-b05f-4ec3-98ed-f033555062c6-annotated_05e73c61-b931-4cfd-93f7-96aa4aa73aac.png?etag=79c245433eb6fe0872272163d17f42db)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/fc016dc3-b05f-4ec3-98ed-f033555062c6-annotated_05e73c61-b931-4cfd-93f7-96aa4aa73aac.png?etag=79c245433eb6fe0872272163d17f42db)*

**Browser**: Firefox 128 (Windows 10)
**Screen size**: 1920x1200
**Browser size**: 1920x1039
**[View screen recording](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/screen_recording/451f4514-beb7-4841-ba75-bc972aea8bc1_screen_recording_8f9b52be-86d7-480a-a770-c53c9bb958c5.webm?etag=5fa917e70ef622b9afc6d8de02eabcb4)**
**[Open #1732 in Usersnap](https://app.usersnap.com/l/feedback/3581ae73-a98d-4728-86e2-87415cbae91f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
There's already an issue for this but not sure if it's in the project. adding this as well. let's remove the visualization. we don't have graphcommons anymore, it was legacied ad some point.

**Comment by jesicarson** [comment]
duplicate issue covered by [#2044](https://github.com/participedia/usersnaps/issues/2044) closing
