### ISSUE TITLE
Usersnap Feedback - On .net it was possible to hyperlink to users, which doesn't seem to be po[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#208]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: On .net it was possible to hyperlink to users, which doesn't seem to be possible now.
[Open #221 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/221)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-25/11-06/ca87a577-0584-4716-839f-581b1ec65977.png'>![Usersnap Feedback - On .net it was possible to hyperlink to users, which doesn't seem to be po(...)](https://usersnappublic.s3.amazonaws.com/2018-06-25/11-06/8773bebb-6d6c-403f-ae54-06a068f825a9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-25/11-06/ca87a577-0584-4716-839f-581b1ec65977.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/method/4327/edit](https://participedia.xyz/method/4327/edit)
**Screen size**: 1366 x 768 **Browser size**: 1517 x 706

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Yep it is possible, just let lucy know that you have to visit a users profile page and grab urls that way. she was specifically wondering where the users listing is, so I let her know thats coming in a future update. Closing this.
