### ISSUE TITLE
Usersnap Feedback - Duplication of Methods Entry after Changing Title - the only thing we (Luc[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#210]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Duplication of Methods Entry after Changing Title - the only thing we (Lucy and I) did was change the title and for some reason it was published as a new entry and the original was kept as well
[Open #223 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/223)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-26/23-44/d7f63b24-8837-42d4-87da-e42fbbdf709c.png'>![Usersnap Feedback - Duplication of Methods Entry after Changing Title - the only thing we (Luc(...)](https://usersnappublic.s3.amazonaws.com/2018-06-26/23-44/38096cad-ace6-4f28-8c76-6ca6b90e4911.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-26/23-44/d7f63b24-8837-42d4-87da-e42fbbdf709c.png'>Download original image</a>

**Browser**: Firefox 60 (Windows 10)
**Referer**: [https://participedia.xyz/method/4983](https://participedia.xyz/method/4983)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
see usersnap #211 
Lucy also says you only get the updated title ("CARE Community Score Cards") when doing a regular search

**Comment by ascott** [comment]
same as this issue https://github.com/participedia/frontend/issues/865
