### ISSUE TITLE
Usersnap Feedback - Able to Select the Same Method From Different Tiles. Clicking 'CARE Commun[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#211]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Able to Select the Same Method From Different Tiles. Clicking 'CARE Community Score Card' brings you to the same page as clicking 'Community Score Card' does - the former is more up-to-date (changed the title), the latter shouldn't appear at all. Same thing with 'Community Forestry' and 'Community Forestry Groups'
[Open #224 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/224)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-26/23-46/2a086b68-20be-4aa0-8e32-84e17e0168ff.png'>![Usersnap Feedback - Able to Select the Same Method From Different Tiles. Clicking 'CARE Commun(...)](https://usersnappublic.s3.amazonaws.com/2018-06-26/23-46/a4bfd909-84cc-453f-9472-5028cbca43d0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-26/23-46/2a086b68-20be-4aa0-8e32-84e17e0168ff.png'>Download original image</a>

**Browser**: Firefox 60 (Windows 10)
**Referer**: [https://participedia.xyz/users/417712](https://participedia.xyz/users/417712)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
NOTE: the duplicates don't show up on regular search - only when you're looking through Robert's entries from his profile page

**Comment by scottofletcher** [comment]
This issue was moved to participedia/frontend#865
