### ISSUE TITLE
Usersnap Feedback - Change copyright date in footer to 2018

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#212]
**Sender**: jesi.carson@gmail.com
**Comment**: Change copyright date in footer to 2018
[Open #225 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/225)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-27/18-35/54870ad5-5f04-4a7b-bea3-fe4a394ea8f6.png'>![Usersnap Feedback - Change copyright date in footer to 2018](https://usersnappublic.s3.amazonaws.com/2018-06-27/18-35/14c889f9-7a11-4eca-b7a7-8f78a2d0a180.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-27/18-35/54870ad5-5f04-4a7b-bea3-fe4a394ea8f6.png'>Download original image</a>

**Browser**: Chrome 67 (Macintosh)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 703

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Also, make "CC Participedia 2018" link to our creative commons license: https://creativecommons.org/licenses/by-nc-sa/3.0/
