### ISSUE TITLE
Usersnap Feedback - National Government not listed as option in organizing entity

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#219]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: National Government not listed as option in organizing entity
[Open #232 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/232)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-05/14-36/feb699ee-421a-4569-9cdd-d2d93913210b.png'>![Usersnap Feedback - National Government not listed as option in organizing entity](https://usersnappublic.s3.amazonaws.com/2018-07-05/14-36/fd2801f0-c171-44fd-8ab5-a875f88844fd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-05/14-36/feb699ee-421a-4569-9cdd-d2d93913210b.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 635

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
already noted. closing.
