### ISSUE TITLE
Usersnap Feedback - Mobile quick sub button in hamburger not working. Leads to blank page.  - Jesi

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#22]
**Sender**: jesi.carson@gmail.com
**Comment**: Mobile quick sub button in hamburger not working. Leads to blank page. 
- Jesi

[Open #36 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/36)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-06/00-08/6deb02a9-f200-45e8-8e91-3e1461a076a3.png'>![Usersnap Feedback - Mobile quick sub button in hamburger not working. Leads to blank page.  - Jesi](https://usersnappublic.s3.amazonaws.com/2017-06-06/00-08/205194b3-867e-48cb-927d-c11d967ef8f2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-06/00-08/6deb02a9-f200-45e8-8e91-3e1461a076a3.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/new](https://participedia.xyz/new)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by davidascher** [comment]
@andreadelrio can you take a look?

**Comment by andreadelrio** [comment]
It's broken in the navbar too. It seems like the redirect after login is no longer working.

**Comment by davidascher** [comment]
Ah, ok.  i'll take a look on desktop.
