### ISSUE TITLE
Usersnap Feedback - The "name" on my profile should be my username, but it doesn't work to log [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#220]
**Sender**: jesi.carson@gmail.com
**Comment**: The "name" on my profile should be my username, but it doesn't work to log in. 

Also, our button says "Login" and Autho says "Log In" this should be consistent.
[Open #233 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/233)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-05/20-03/5c1e64cb-0999-4965-8ee1-0866e1a55b6a.png'>![Usersnap Feedback - The "name" on my profile should be my username, but it doesn't work to log (...)](https://usersnappublic.s3.amazonaws.com/2018-07-05/20-03/23951084-0ee9-4ec9-97a4-a0ac8b7746ec.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-05/20-03/5c1e64cb-0999-4965-8ee1-0866e1a55b6a.png'>Download original image</a>

**Browser**: Chrome 67 (Macintosh)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 703

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
This issue was moved to participedia/frontend#873
