### ISSUE TITLE
Usersnap Feedback - The first 'voting' has been transferred from .net. But this does not match [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#223]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: The first 'voting' has been transferred from .net. But this does not match the wording of the option 'voting' in xyz. It's also not possible to then edit that data that has transferred from .net.
[Open #236 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/236)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-06/11-40/8216daaf-f36b-4912-aaf7-af53780b6e87.png'>![Usersnap Feedback - The first 'voting' has been transferred from .net. But this does not match (...)](https://usersnappublic.s3.amazonaws.com/2018-07-06/11-40/c4cf209f-ced8-4f57-801b-54f499242846.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-06/11-40/8216daaf-f36b-4912-aaf7-af53780b6e87.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/case/5115/edit](https://participedia.xyz/case/5115/edit)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 635

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
Merged with participedia/frontend#876
