### ISSUE TITLE
Usersnap Feedback - Multi-select Facilitator Training

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#225]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: Can I suggest that this field be multi-select? Some cases use both.
[Open #238 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/238)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-06/17-40/cc217e81-aecd-45d1-a1da-799e92061def.png'>![Usersnap Feedback - Can I suggest that this field be multi-select? Some cases use both.](https://usersnappublic.s3.amazonaws.com/2018-07-06/17-40/8b8c1191-4da4-4a3d-a050-355c6e6a2cbf.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-06/17-40/cc217e81-aecd-45d1-a1da-799e92061def.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/case/2197/edit](https://participedia.xyz/case/2197/edit)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 635

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully @scottofletcher this is a data model question. Thoughts?

**Comment by plscully** [comment]
@scottofletcher Let's discuss this on Slack and get back to @jesicarson ASAP

**Comment by scottofletcher** [comment]
@jesicarson @dethe new instructional "What level of training did facilitators have?"

Changed in all documents:
https://docs.google.com/document/d/1CzpPBn-E7t4JxSPQ4vkSnzD5eyRuoi7sFltTNT6oTPw/edit
https://docs.google.com/document/d/1sovR-RCilKwWN2XKxQH7xVo8XDEnh6BSgz7JfNqFy4g/edit#heading=h.g8pnwksg916o
https://docs.google.com/document/d/1z1X2xLXaVf1xfvM0Sk3E2jP6_nBjskemrL7s7L2vyv4/edit#
