### ISSUE TITLE
Usersnap Feedback - Video field is yellow?

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#228]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Video field is yellow?
[Open #241 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/241)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-15/23-28/fe22d38d-ac60-4cd8-aeef-3a875ee60489.png'>![Usersnap Feedback - Video field is yellow?](https://usersnappublic.s3.amazonaws.com/2018-07-15/23-28/f7c209ac-b7d1-4473-9bcf-a77ffcc36df0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-15/23-28/fe22d38d-ac60-4cd8-aeef-3a875ee60489.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/case/13/edit](https://participedia.xyz/case/13/edit)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 809

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher I don't see any yellow, is it just me? I also checked the site, and I don't see what yellow you mean. If this is still happening for you, could you provide more details about whats happening and submit your own screenshot? Sometimes usersnaps screenshots are inaccurate. Thanks!

**Comment by scottofletcher** [comment]
oh weird! yeah I'll for sure use my own screenshot app if/when I come across the weird yellow again (that was the first time it happened - maybe it was just my browser having a fit)

**Comment by scottofletcher** [comment]
@jesicarson It happened again and I got a screenshot!
<img width="355" alt="screenshot 2018-07-22 15 54 19" src="https://user-images.githubusercontent.com/29512491/43051049-aa0f5cb4-8dc7-11e8-9721-7df78759a133.png">
It seems to happen when I select from the options suggested by my browser based on past entries. In this case, I have entered 'Comune di Milano [Milan City Council]' as a Funder in another case so when I started typing "Com", I then selected the entry suggested by my browser (in a drop-down menu - other options included "Comune di Olbia" etc.) and the auto-fill turned the field yellow.

**Comment by jesicarson** [comment]
Good info thanks Scott. Does it prevent you from saving the entry or anything?

**Comment by scottofletcher** [comment]
nope, it's just yellow :P

**Comment by jesicarson** [comment]
Ok thanks.
