### ISSUE TITLE
Usersnap Feedback - Test cases marked by admin as "hidden" still show up on my profile page.

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#233]
**Sender**: jesi.carson@gmail.com
**Comment**: Test cases marked by admin as "hidden" still show up on my profile page. 
[Open #246 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/246)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-24/19-37/69da885c-952f-4546-ba00-824145791684.png'>![Usersnap Feedback - Test cases marked by admin as "hidden" still show up on my profile page.](https://usersnappublic.s3.amazonaws.com/2018-07-24/19-37/a4d95b77-1635-41b1-8aa7-bddc1709aa72.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-24/19-37/69da885c-952f-4546-ba00-824145791684.png'>Download original image</a>

**Browser**: Chrome 67 (Macintosh)
**Referer**: [https://participedia.xyz/users/1189](https://participedia.xyz/users/1189)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 703

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
This is also true when logged out. thought it might be an admin view thing (ie admins can still see hidden content), but its not.
