### ISSUE TITLE
Usersnap Feedback - Profile names update question - will it change to the First and Last Name [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#234]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Profile names update question - will it change to the First and Last Name users entered on .net or the username? I don't think Dr. Ashworth wants her email made public like this. 
[Open #247 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/247)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-27/18-46/fd6867e6-cf1d-4854-b2c8-e83df3643d50.png'>![Usersnap Feedback - Profile names update question - will it change to the First and Last Name (...)](https://usersnappublic.s3.amazonaws.com/2018-07-27/18-46/110223d4-4fc6-4082-b1ab-834af998c8c2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-27/18-46/fd6867e6-cf1d-4854-b2c8-e83df3643d50.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/organization/5247](https://participedia.xyz/organization/5247)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 809

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher there is only a field for "full name" on .net (not split into first/ last) so this should remain the same on .xyz. 

Regarding public email addresses, this is a problematic bug that @dethe should prioritize if it hasn't been done already.  Thanks!

**Comment by scottofletcher** [comment]
@jesicarson Ok, so right now what's appearing on XYZ is their username and not their 'Full Name'? And with the updates it will display their Full Name? on .net, Dr. Ashworth's 'Full Name' is "Joanna Ashworth" which I assume is what she (and other users) wanted to have publicly displayed

**Comment by jesicarson** [comment]
Yes thats right. We should show 'name' not 'username' for authorship on public facing pages.

**Comment by dethe** [comment]
This seems to be happening when they create a login with Auth0. Auth0 doesn't have a `name` only a username, which is their email, and is then passed to us as their name. I will patch up those names in the database as best I can, and try to intercept them when they create an account through Auth0. This could also be part of why folks are getting user ids that don't actually match up with their contributions. It's not the quick fix it would be if we could just switch from using `name` field vs. using `username` field, but I can look at it as soon as Auth0 is working again.

**Comment by jesicarson** [comment]
We are also displaying usernames (not names) from .net as .xyz authorship (I have checked with accounts who aren't active yet on xyz, so shouldn't have used Auth0 yet), so maybe both fixes need to happen?
