### ISSUE TITLE
Usersnap Feedback - Search doesn't recognize individual words separated by a slash  The entry [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#235]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Search doesn't recognize individual words separated by a slash 
The entry I'm looking for is "Carcross/Tagish First Nation" but a search for just "Carcross" or "Tagish" doesn't return anything
[Open #248 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/248)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-28/19-01/632dd173-1dce-4185-989a-6ca268afe303.png'>![Usersnap Feedback - Search doesn't recognize individual words separated by a slash  The entry (...)](https://usersnappublic.s3.amazonaws.com/2018-07-28/19-01/3398d2d9-e8e6-4991-86d6-376d3529cb65.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-28/19-01/632dd173-1dce-4185-989a-6ca268afe303.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/?query=carcross](https://participedia.xyz/?query=carcross)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 882

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by participedia/api#300
