### ISSUE TITLE
Usersnap Feedback - FOLLOW UP TO PREVIOUS USERSNAP: Search doesn't recognize two words separat[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#236]
**Sender**: scottowenfletcher@gmail.com
**Comment**: FOLLOW UP TO PREVIOUS USERSNAP: Search doesn't recognize two words separated with a slash at all. Haven't tried capitalizing the words but I assume that won't make a difference. 
[Open #249 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/249)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-28/19-03/2625bcff-1b0f-4eac-8d52-3e8813a75412.png'>![Usersnap Feedback - FOLLOW UP TO PREVIOUS USERSNAP: Search doesn't recognize two words separat(...)](https://usersnappublic.s3.amazonaws.com/2018-07-28/19-03/c7e37413-f91b-4d84-b28b-92a607daa051.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-28/19-03/2625bcff-1b0f-4eac-8d52-3e8813a75412.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/?query=carcross/tagish](https://participedia.xyz/?query=carcross/tagish)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 882

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by participedia/api#300
