### ISSUE TITLE
Usersnap Feedback - Location continues to revert to a less accurate selection. I have entered [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#237]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Location continues to revert to a less accurate selection. I have entered 'Carcross/Tagish First Nation' and selected it from the drop-down numerous times but each time, it either immediately goes to a less accurate location (eg. Yukon, Canada; Carcross, Yukon, Canada; Canada) or it saves and then reverts when I go to edit it. 
[Open #250 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/250)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-31/18-31/16c9502d-5e2d-48a9-97b8-d51ecf374560.png'>![Usersnap Feedback - Location continues to revert to a less accurate selection. I have entered (...)](https://usersnappublic.s3.amazonaws.com/2018-07-31/18-31/fd045730-38a9-4561-97ff-897a5d131864.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-31/18-31/16c9502d-5e2d-48a9-97b8-d51ecf374560.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/organization/5096/edit](https://participedia.xyz/organization/5096/edit)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 882

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
known bug: https://github.com/participedia/usersnaps/issues/229
referencing and closing this one
