### ISSUE TITLE
Usersnap Feedback - This is from an iPad. Note lack of  narrative & lead photo at top of page. [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#238]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: This is from an iPad. Note lack of  narrative & lead photo at top of page. You have to scroll down a long way to see it. But it displays properly on desktop & iPhone 
[Open #251 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/251)

<a href='https://usersnappublic.s3.amazonaws.com/2018-08-01/17-38/4f22e559-7c8c-44d3-9e31-fbb6b595cd03.png'>![Usersnap Feedback - This is from an iPad. Note lack of  narrative & lead photo at top of page. (...)](https://usersnappublic.s3.amazonaws.com/2018-08-01/17-38/a47a0795-15a4-48f0-a4bc-9d01bee18dd5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-08-01/17-38/4f22e559-7c8c-44d3-9e31-fbb6b595cd03.png'>Download original image</a>

**Browser**: ChromeiOS 67 (iOS)
**Referer**: [https://participedia.xyz/case/5101](https://participedia.xyz/case/5101)
**Screen size**: 768 x 1024 **Browser size**: 768 x 1024

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully can you take a manual screenshot with your iPad to show the problem. Not seeing what you mean with this usersnap. Thank you!

**Comment by plscully** [comment]
@jesicarson Verticle screenshot from my ipad  ![ipad case display problem] (https://user-images.githubusercontent.com/29512657/43533791-ae68ae64-9583-11e8-9c26-0d8768484732.PNG)

This is the case it refers to https://participedia.xyz/case/5101

**Comment by jesicarson** [comment]
That is strange. I'm seeing other cases showing up as normal on my iPad, and the case you mention (5101) showing up too wide for the vertical ipad screen. @dethe any ideas?

https://participedia.xyz/case/5228 (working normally)
![image](https://user-images.githubusercontent.com/13560530/43534824-243b70de-956d-11e8-95cb-c04b403e2fbd.png)

https://participedia.xyz/case/5101 (too wide for vertical ipad screen)
![image](https://user-images.githubusercontent.com/13560530/43534849-32c5a25a-956d-11e8-94cc-5d740645f871.png)

**Comment by jesicarson** [comment]
Breakpoint issue maybe? On desktop I see the same problem of the image and narrative getting stacked below the data when I resize my screen below roughly 945px wide. 
ie: https://participedia.xyz/case/5101
![screen shot 2018-08-16 at 11 57 51 am](https://user-images.githubusercontent.com/13560530/44229048-b7055800-a14b-11e8-854b-470284ba75b7.png)
