### ISSUE TITLE
Usersnap Feedback - When I select this case the page it goes to won't load

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#240]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: When I select this case the page it goes to won't load
[Open #253 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/253)

<a href='https://usersnappublic.s3.amazonaws.com/2018-08-10/18-03/1fb5a8c6-337c-455b-93ac-9e4ac3dfe113.png'>![Usersnap Feedback - When I select this case the page it goes to won't load](https://usersnappublic.s3.amazonaws.com/2018-08-10/18-03/2c75fc01-7e4b-41b2-8c9d-96db43d559c9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-08-10/18-03/1fb5a8c6-337c-455b-93ac-9e4ac3dfe113.png'>Download original image</a>

**Browser**: Chrome 68 (Windows 10)
**Referer**: [https://participedia.xyz/cases?query=Grama%20Sabhas%20Kerala](https://participedia.xyz/cases?query=Grama%20Sabhas%20Kerala)
**Screen size**: 1920 x 1200 **Browser size**: 1745 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Thanks Pat.
This is the case https://participedia.xyz/case/35, and a screenshot:

![screen shot 2018-08-10 at 9 05 41 am](https://user-images.githubusercontent.com/13560530/43968684-b833f160-9c7c-11e8-8c8a-f8d22d78849e.png)

**Comment by jesicarson** [comment]
Some other pages that won't load: https://github.com/participedia/usersnaps/issues/231

**Comment by dethe** [comment]
Weird, I can load those pages just fine over the API, but they don't load in the app. The app asks if there is data (OPTIONS request), which comes back saying "No data" (HTTP 204 response). I'm not sending an HTTP 204 anywhere I can find, and there definitely *is* data, so I'm puzzled. On the other hand, this won't be a problem once I rejigger the templating, so I'm going to ignore it for now and concentrate on that.

**Comment by ascott** [comment]
this case loads for me, must have been fixed at some point. closing.
