### ISSUE TITLE
Usersnap Feedback - I don't have admin tools anymore

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#242]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I don't have admin tools anymore
[Open #255 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/255)

<a href='https://usersnappublic.s3.amazonaws.com/2018-08-12/23-47/c0dc6ae9-4fb4-4b11-8465-37a5c78b0af9.png'>![Usersnap Feedback - I don't have admin tools anymore](https://usersnappublic.s3.amazonaws.com/2018-08-12/23-47/ae6f8a6a-425d-4a8a-88ca-d8fed5770a2d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-08-12/23-47/c0dc6ae9-4fb4-4b11-8465-37a5c78b0af9.png'>Download original image</a>

**Browser**: Chrome 68 (Windows 10)
**Referer**: [https://participedia.xyz/method/5188](https://participedia.xyz/method/5188)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher can you refresh and try again? mine seem to be working:

![screen shot 2018-08-13 at 11 27 43 am](https://user-images.githubusercontent.com/13560530/44050504-f9305520-9eeb-11e8-8bf5-52efaf5b8a74.png)

**Comment by scottofletcher** [comment]
@jesicarson refreshed, cleared cache, etc. and still don't have admin tools
