### ISSUE TITLE
Usersnap Feedback - This case is missing social links. Think it has something to do with the s[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#243]
**Sender**: jesi.carson@gmail.com
**Comment**: This case is missing social links. Think it has something to do with the size of the image but not sure. 
[Open #256 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/256)

<a href='https://usersnappublic.s3.amazonaws.com/2018-08-15/21-43/ca712f89-336d-4ecf-b541-4106f40263b0.png'>![Usersnap Feedback - This case is missing social links. Think it has something to do with the s(...)](https://usersnappublic.s3.amazonaws.com/2018-08-15/21-43/ab9b9d69-cedf-4c2a-b0e3-d0672210f694.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-08-15/21-43/ca712f89-336d-4ecf-b541-4106f40263b0.png'>Download original image</a>

**Browser**: Chrome 68 (Macintosh)
**Referer**: [https://participedia.xyz/case/5101](https://participedia.xyz/case/5101)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 703

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Here's what I actually see on my desktop (usersnap image is not accurate):

![screen shot 2018-08-16 at 9 49 42 am](https://user-images.githubusercontent.com/13560530/44222570-cf6c7700-a139-11e8-9260-f62f3e75b10b.png)
