### ISSUE TITLE
Usersnap Feedback - Search for Roundtable Discussions returns only 'Magic Roundtables'

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#248]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Search for Roundtable Discussions returns only 'Magic Roundtables' 
[Open #261 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/261)

<a href='https://usersnappublic.s3.amazonaws.com/2018-08-22/00-10/75357706-5789-4320-a98b-f84b69670a0e.png'>![Usersnap Feedback - Search for Roundtable Discussions returns only 'Magic Roundtables'](https://usersnappublic.s3.amazonaws.com/2018-08-22/00-10/cb02fda8-9ab9-40a7-b05b-9cc857a123b2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-08-22/00-10/75357706-5789-4320-a98b-f84b69670a0e.png'>Download original image</a>

**Browser**: Chrome 68 (Windows 10)
**Referer**: [https://participedia.xyz/method/5309](https://participedia.xyz/method/5309)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by participedia/api#300
