### ISSUE TITLE
Usersnap Feedback - Another case that doesn't come up in search (I tried Los Angeles, Los Ange[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#250]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Another case that doesn't come up in search (I tried Los Angeles, Los Angeles Metro, Metro Purple. etc.)
[Open #263 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/263)

<a href='https://usersnappublic.s3.amazonaws.com/2018-08-24/19-36/d6746d5c-3055-4e2f-8de4-ad09a05bea6a.png'>![Usersnap Feedback - Another case that doesn't come up in search (I tried Los Angeles, Los Ange(...)](https://usersnappublic.s3.amazonaws.com/2018-08-24/19-36/aa93bc5d-076e-4d60-87fb-f0d674570a46.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-08-24/19-36/d6746d5c-3055-4e2f-8de4-ad09a05bea6a.png'>Download original image</a>

**Browser**: Chrome 68 (Windows 10)
**Referer**: [https://participedia.xyz/case/5281](https://participedia.xyz/case/5281)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by participedia/api#300
