### ISSUE TITLE
Usersnap Feedback - another page that doesn't show up on search

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#253]
**Sender**: scottowenfletcher@gmail.com
**Comment**: another page that doesn't show up on search
[Open #266 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/266)

<a href='https://usersnappublic.s3.amazonaws.com/2018-09-03/00-20/fe7df4ba-7b62-4e3d-b606-e132f896263d.png'>![Usersnap Feedback - another page that doesn't show up on search](https://usersnappublic.s3.amazonaws.com/2018-09-03/00-20/e7e81010-32ce-4da5-b32b-b690af3d5895.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-09-03/00-20/fe7df4ba-7b62-4e3d-b606-e132f896263d.png'>Download original image</a>

**Browser**: Chrome 68 (Windows 10)
**Referer**: [https://participedia.xyz/organization/5247](https://participedia.xyz/organization/5247)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 803

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by participedia/api#300
