### ISSUE TITLE
Usersnap Feedback - Clicking edit on an organization entry wipes out all fields. I was also al[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#255]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Clicking edit on an organization entry wipes out all fields. I was also alerted to this by Claire Buchanan at SFU
[Open #268 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/268)

<a href='https://usersnappublic.s3.amazonaws.com/2018-09-06/18-14/e6eb49f2-ad28-45b7-a5e2-f9a4b46a9811.png'>![Usersnap Feedback - Clicking edit on an organization entry wipes out all fields. I was also al(...)](https://usersnappublic.s3.amazonaws.com/2018-09-06/18-14/bba4bdfa-b515-4945-ab99-338885fe8ed8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-09-06/18-14/e6eb49f2-ad28-45b7-a5e2-f9a4b46a9811.png'>Download original image</a>

**Browser**: Chrome 68 (Windows 10)
**Referer**: [https://participedia.xyz/organization/310/edit](https://participedia.xyz/organization/310/edit)
**Screen size**: 1280 x 720 **Browser size**: 2560 x 1071

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Ooh thats not good. 
Although I just made a test org and tried to edit it and it didn't wipe out all the fields, they remained. https://participedia.xyz/organization/5429/edit
So @scottofletcher you have had this bug happen to you? Does it happen on every org you try to edit?
@dethe any clue as to why this would happen to one org and not another? Maybe its only on orgs that were transferred from .net and not new ones created on .xyz?

**Comment by scottofletcher** [comment]
@jesicarson yes, this seems to happen sporadically and, in fact the screenshot shows the blank edit form of a complete organization (see [here](https://participedia.xyz/organization/310)).  So far I've been able to solve the problem by pressing the browser's back button and then clicking edit again (although one time I actually had to log out and log back in before I could make it stop wiping out the org forms!). I haven't experienced this with the case or methods forms although Lucy's done most of the method editing thus far (but I'm sure she'd tell me if the forms were being wiped out)

**Comment by dethe** [comment]
When I hear that something happens sporadically, my first suspicion is that the login timed out but the UI hadn't been updated to reflect that yet. I tried simulating login timeouts, but was unable to re-create this issue. The other possibility would be if there was some kind of content that breaks the page, but I can't see how off-hand.

**Comment by scottofletcher** [comment]
I don't think it's a login/logout issue because the only thing that gets wiped is the narrative (ie. whatever's been entered up till that point is cleared and replaced with the placeholder - ie. the narrative headings)

**Comment by dethe** [comment]
I guess what I'm saying is, for problems that are occasional and hard to replicate consistently, if you notice any patterns when it happens, that will help.

**Comment by scottofletcher** [comment]
@dethe Sounds good! Unfortunately there haven't been any patterns... In fact, quite the opposite actually - this problem seems to afflict new (created on XYZ) and old (transferred from .net) entries. This won't be a problem once we have versioning up and running though b/c then we can just revert to an earlier version if someone accidentally freaks out when the edit form comes up empty and presses 'publish'. I'm just worried that that'll happen sooner rather than later and we'll lose a bunch of work. Is there any way of retrieving an earlier version right now just in case?
