### ISSUE TITLE
Usersnap Feedback - Search does not recognize ordinal numbers

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#256]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Search does not recognize ordinal numbers
[Open #269 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/269)

<a href='https://usersnappublic.s3.amazonaws.com/2018-09-06/18-48/39a3144f-5246-4974-b5e7-2f226d8feb97.png'>![Usersnap Feedback - Search does not recognize ordinal numbers](https://usersnappublic.s3.amazonaws.com/2018-09-06/18-48/38633aae-0278-4062-8d97-6ee1de4eed94.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-09-06/18-48/39a3144f-5246-4974-b5e7-2f226d8feb97.png'>Download original image</a>

**Browser**: Chrome 68 (Windows 10)
**Referer**: [https://participedia.xyz/?query=21st%20century](https://participedia.xyz/?query=21st%20century)
**Screen size**: 1280 x 720 **Browser size**: 2560 x 1071

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
See participedia/api#300

**Comment by scottofletcher** [comment]
see search indexing Master Issue: participedia/api#453
