### ISSUE TITLE
Usersnap Feedback - Missing case on search  Searching for "Winnipeg Budget Consultations" does [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#257]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Missing case on search 
Searching for "Winnipeg Budget Consultations" does not return an entry with that name yet it's listed (and linked to) as the parent of several other entries (see my comment below)
[Open #270 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/270)

<a href='https://usersnappublic.s3.amazonaws.com/2018-09-24/00-38/e0ae7443-105d-4791-ad40-38e7376b388b.png'>![Usersnap Feedback - Missing case on search  Searching for "Winnipeg Budget Consultations" does (...)](https://usersnappublic.s3.amazonaws.com/2018-09-24/00-38/57ffa943-520c-4297-a4ff-872dfa96ef90.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-09-24/00-38/e0ae7443-105d-4791-ad40-38e7376b388b.png'>Download original image</a>

**Browser**: Chrome 69 (Windows 10)
**Referer**: [https://participedia.xyz/?query=winnipeg](https://participedia.xyz/?query=winnipeg)
**Screen size**: 1280 x 720 **Browser size**: 2560 x 1159

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
<img width="960" alt="fireshot capture 167 - participedia - https___participedia xyz_case_5442" src="https://user-images.githubusercontent.com/29512491/45933714-3524fd80-bf47-11e8-94a7-1fd33440c537.png">

**Comment by scottofletcher** [comment]
see search indexing Master Issue: participedia/api#453
