### ISSUE TITLE
Usersnap Feedback - Entering description of a case on mobile, the text editor is glitchy, I ca[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#26]
**Sender**: jesi.carson@gmail.com
**Comment**: Entering description of a case on mobile, the text editor is glitchy, I can't see what I'm typing. Going to post a screenshot of that on slack, because you can't use the feedback button with text editor open. I also can't see this text anymore because the text editor is covering the feedback window. - jesi 
[Open #40 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/40)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/00-58/2bfd3dd8-d7c5-4b0a-aad1-268bcd091423.png'>![Usersnap Feedback - Entering description of a case on mobile, the text editor is glitchy, I ca(...)](https://usersnappublic.s3.amazonaws.com/2017-06-17/00-58/5eb8d4bf-fe5e-43dc-827a-71cb94eb699f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/00-58/2bfd3dd8-d7c5-4b0a-aad1-268bcd091423.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 320 x 568 **Browser size**: 260 x 374

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by andreadelrio** [comment]
Covered with new body editor.
