### ISSUE TITLE
Usersnap Feedback - New organization entry not showing up on search - 'Electronic Frontier Fou[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#269]
**Sender**: scottowenfletcher@gmail.com
**Comment**: New organization entry not showing up on search - 'Electronic Frontier Foundation' creation 10/10/2018; searches for 'Electronic', 'Frontier', etc. do not return it
[Open #282 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/282)

<a href='https://usersnappublic.s3.amazonaws.com/2018-10-14/18-46/1d468ec5-0f9e-46ce-9534-7db7b5f76f3f.png'>![Usersnap Feedback - New organization entry not showing up on search - 'Electronic Frontier Fou(...)](https://usersnappublic.s3.amazonaws.com/2018-10-14/18-46/72673057-4c28-4039-891f-032703d3b42e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-10-14/18-46/1d468ec5-0f9e-46ce-9534-7db7b5f76f3f.png'>Download original image</a>

**Browser**: Chrome 69 (Windows 10)
**Referer**: [https://participedia.xyz/organizations?query=frontier](https://participedia.xyz/organizations?query=frontier)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 795

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
see search indexing Master Issue: participedia/api#453
