### ISSUE TITLE
Usersnap Feedback - Entry not searchable! This entry doesn't show up on searches for 'Boston', [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#270]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Entry not searchable! This entry doesn't show up on searches for 'Boston', 'Green Links', etc.
[Open #283 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/283)

<a href='https://usersnappublic.s3.amazonaws.com/2018-11-07/17-31/5885d0e9-f960-433e-9463-becc503b1d5f.png'>![Usersnap Feedback - Entry not searchable! This entry doesn't show up on searches for 'Boston', (...)](https://usersnappublic.s3.amazonaws.com/2018-11-07/17-31/8b3e1dd6-9bf7-4308-af0e-c47d7187946e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-11-07/17-31/5885d0e9-f960-433e-9463-becc503b1d5f.png'>Download original image</a>

**Browser**: Chrome 70 (Windows 10)
**Referer**: [https://participedia.xyz/case/5392](https://participedia.xyz/case/5392)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 869

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
see search indexing Master Issue: participedia/api#453
