### ISSUE TITLE
Usersnap Feedback - Quick sub didn't work. Clicked submit case and got an error message. - jesi

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#28]
**Sender**: jesi.carson@gmail.com
**Comment**: Quick sub didn't work. Clicked submit case and got an error message. - jesi
[Open #42 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/42)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/01-02/2fc12718-0709-47bb-a6cc-02ee9460b2ff.png'>![Usersnap Feedback - Quick sub didn't work. Clicked submit case and got an error message. - jesi](https://usersnappublic.s3.amazonaws.com/2017-06-17/01-02/cf3dfd24-701e-4ff2-830d-be1d97139415.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/01-02/2fc12718-0709-47bb-a6cc-02ee9460b2ff.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Working these days.
