### ISSUE TITLE
Usersnap Feedback - Case not search indexed (tried 'recovered' 'enterprise' 'worker recovered' [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#280]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Case not search indexed (tried 'recovered' 'enterprise' 'worker recovered' etc. etc. nothing returned.)
[Open #292 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/292)

<a href='https://usersnappublic.s3.amazonaws.com/2019-01-01/01-28/42275633-9a49-4ca3-8c85-95660ce4a2b8.png'>![Usersnap Feedback - Case not search indexed (tried 'recovered' 'enterprise' 'worker recovered' (...)](https://usersnappublic.s3.amazonaws.com/2019-01-01/01-28/b07e8634-7a9f-42b2-aacc-643399535272.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-01-01/01-28/42275633-9a49-4ca3-8c85-95660ce4a2b8.png'>Download original image</a>

**Browser**: Chrome 71 (Windows 10)
**Referer**: [https://participedia.xyz/case/5530](https://participedia.xyz/case/5530)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 869

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
see search indexing Master Issue: participedia/api#453
