### ISSUE TITLE
Usersnap Feedback - entry not search indexed

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#281]
**Sender**: scottowenfletcher@gmail.com
**Comment**: entry not search indexed
[Open #293 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/293)

<a href='https://usersnappublic.s3.amazonaws.com/2019-01-05/17-55/b348f2fb-17e7-4d6f-8da3-46e45eccad6c.png'>![Usersnap Feedback - entry not search indexed](https://usersnappublic.s3.amazonaws.com/2019-01-05/17-55/caa2ff91-6a1e-4e47-8f76-de06951e29d8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-01-05/17-55/b348f2fb-17e7-4d6f-8da3-46e45eccad6c.png'>Download original image</a>

**Browser**: Chrome 71 (Windows 10)
**Referer**: [https://participedia.xyz/case/5533](https://participedia.xyz/case/5533)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 869

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
see search indexing Master Issue: participedia/api#453
