### ISSUE TITLE
Usersnap Feedback - Case won't load

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#283]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Case won't load
[Open #295 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/295)

<a href='https://usersnappublic.s3.amazonaws.com/2019-01-23/01-11/df87872d-8d5b-4832-983d-671df2c4f95a.png'>![Usersnap Feedback - Case won't load](https://usersnappublic.s3.amazonaws.com/2019-01-23/01-11/8af0ae2d-1925-4375-9f4d-83f7dbf0eed5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-01-23/01-11/df87872d-8d5b-4832-983d-671df2c4f95a.png'>Download original image</a>

**Browser**: Chrome 71 (Windows 10)
**Referer**: [https://participedia.xyz/case/551](https://participedia.xyz/case/551)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 869

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
throwing a 500 error
<img width="1117" alt="Screenshot 2019-03-13 17 55 07" src="https://user-images.githubusercontent.com/130878/54324053-357a8900-45b9-11e9-8573-a698cc1e82f9.png">
