### ISSUE TITLE
Usersnap Feedback - Page not indexed in search  (sorry if I already Usersnapped this entry - I [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#285]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Page not indexed in search 
(sorry if I already Usersnapped this entry - I lose track of which ones I do and don't post...)
[Open #297 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/297)

<a href='https://usersnappublic.s3.amazonaws.com/2019-01-29/23-48/70d49009-0e49-4601-b2a9-0fac1424b884.png'>![Usersnap Feedback - Page not indexed in search  (sorry if I already Usersnapped this entry - I (...)](https://usersnappublic.s3.amazonaws.com/2019-01-29/23-48/d948b0af-b0db-4b5e-ab9e-3d6d47e8044a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-01-29/23-48/70d49009-0e49-4601-b2a9-0fac1424b884.png'>Download original image</a>

**Browser**: Chrome 71 (Windows 10)
**Referer**: [https://participedia.xyz/method/5309](https://participedia.xyz/method/5309)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 869

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
see search indexing Master Issue: participedia/api#453
