### ISSUE TITLE
Usersnap Feedback - Site error message is telling me that title and body are not entered but t[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#29]
**Sender**: jesi.carson@gmail.com
**Comment**: Site error message is telling me that title and body are not entered but they were definitely entered before I clicked submit. The Photo i selected also disappeared following the previous error message. 
- jesi
[Open #43 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/43)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/01-04/354dd57a-5978-4ab3-8db1-b56d3d456def.png'>![Usersnap Feedback - Site error message is telling me that title and body are not entered but t(...)](https://usersnappublic.s3.amazonaws.com/2017-06-17/01-04/7eb4106c-3032-45f5-800a-9e798b0d814b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/01-04/354dd57a-5978-4ab3-8db1-b56d3d456def.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
This should be working now. Not sure what was up with the photo, but it may be related to the issue we're having with lists, will deal with it there.
