### ISSUE TITLE
Usersnap Feedback - Entry not search indexed

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#290]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Entry not search indexed
[Open #302 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/302)

<a href='https://usersnappublic.s3.amazonaws.com/2019-02-16/01-04/725ba18f-2e78-4f2a-b15d-a94e4f6e58eb.png'>![Usersnap Feedback - Entry not search indexed](https://usersnappublic.s3.amazonaws.com/2019-02-16/01-04/bf4bd98d-5418-40c1-a898-f08d7e0bd187.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-02-16/01-04/725ba18f-2e78-4f2a-b15d-a94e4f6e58eb.png'>Download original image</a>

**Browser**: Chrome 72 (Windows 10)
**Referer**: [https://participedia.xyz/organization/310](https://participedia.xyz/organization/310)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
see search indexing Master Issue: participedia/api#453
