### ISSUE TITLE
Usersnap Feedback - Border of brief description text box shouldn't turn blue when typing in it [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#294]
**Sender**: jesi.carson@gmail.com
**Comment**: Border of brief description text box shouldn't turn blue when typing in it (but its not a big deal and can be ignored if this is annoying to remove for some reason).
[Open #38 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/38)

<a href='https://usersnappublic.s3.amazonaws.com/2019-02-22/18-32/188a901b-007d-48b4-8416-115e97520e84.png'>![Usersnap Feedback - Border of brief description text box shouldn't turn blue when typing in it (...)](https://usersnappublic.s3.amazonaws.com/2019-02-22/18-32/c104a4c1-2e16-4829-82e6-1dd671e0fba7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-02-22/18-32/188a901b-007d-48b4-8416-115e97520e84.png'>Download original image</a>

**Browser**: Chrome 72 (macOS Mojave)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5239/edit](https://ppedia-stage.herokuapp.com/case/5239/edit)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
the blue outline shows that the field is focused and the user can input text. it is especially useful for users who navigate the page with their keyboard, using tab to navigate between form elements. with the focus styling, they can easily see what element is in focus.

is there another colour you would prefer to use to show that the field is in focus? i think it is generally best practice in terms of accessibility (ref: https://www.deque.com/blog/give-site-focus-tips-designing-usable-focus-indicators/) to keep a specific focus style.

**Comment by jesicarson** [comment]
@ascott good feedback, thanks! i'm ok with the blue as is for now. Is it easy to change the colour if we decide to down the line? thinking we may define a "participedia blue" (or other accent colour) at some point and want to use that. 
also, does every field turn blue when it is "in focus", including drop down/other types of fields?

**Comment by ascott** [comment]
yes, the outline/focus colour is easily changeable with CSS.  here's a gif showing clicking and tabbing through the edit form. you can see the outline in focused form fields as well as buttons/links.
![form-focus](https://user-images.githubusercontent.com/130878/53537971-b5382c00-3ac0-11e9-92ed-cbdf419b4a50.gif)

**Comment by jesicarson** [comment]
I think that's fine, but the only small thing that looks odd is when the blue box goes around "add another link", can it be a blue underline? not a train smash if not. 

do you have the hex code for the current blue you're using? its a pretty standard web blue, yes?

**Comment by ascott** [comment]
the hex code for the current blue is #3b99fc which is the default for Chrome browsers focus outline style. we could change the treatment for the links, but in my opinion keeping the standard treatment is better since it is a recognizable, standard treatment for accessibility across the web. if you tab through this github issue, you'll see that it has the same styling.

**Comment by jesicarson** [comment]
ok sounds good, thanks!
