### ISSUE TITLE
Usersnap Feedback - Too much space between Primary Location and Links, keep to standard spacin[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#295]
**Sender**: jesi.carson@gmail.com
**Comment**: Too much space between Primary Location and Links, keep to standard spacing between questions. 
[Open #39 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/39)

<a href='https://usersnappublic.s3.amazonaws.com/2019-02-22/18-34/904c3966-16a1-447a-918e-f4ff3321d744.png'>![Usersnap Feedback - Too much space between Primary Location and Links, keep to standard spacin(...)](https://usersnappublic.s3.amazonaws.com/2019-02-22/18-34/afaf02ac-e4ca-45bb-b348-f82ad782d8bf.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-02-22/18-34/904c3966-16a1-447a-918e-f4ff3321d744.png'>Download original image</a>

**Browser**: Chrome 72 (macOS Mojave)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5239/edit](https://ppedia-stage.herokuapp.com/case/5239/edit)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Note, this is in quick submit view

**Comment by ascott** [comment]
i think this just looks like too much space because it is missing the horizontal divider line. here it is with the line and the spacing matches the specs here: https://github.com/participedia/frontend/issues/853#issuecomment-400779201
<img width="780" alt="screenshot 2019-02-25 17 06 09" src="https://user-images.githubusercontent.com/130878/53379842-0f4dbb80-3920-11e9-9890-1ac655f53532.png">

**Comment by jesicarson** [comment]
No horizontal spacers on quick sub, thx!

**Comment by ascott** [comment]
oops, will fix!
