### ISSUE TITLE
Usersnap Feedback - Can check box button be dark grey or or even black instead of blue?

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#298]
**Sender**: jesi.carson@gmail.com
**Comment**: Can check box button be dark grey or or even black instead of blue? 
[Open #42 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/42)

<a href='https://usersnappublic.s3.amazonaws.com/2019-02-22/18-40/5b1a4d20-fc74-4a76-9d67-7b8c7fe82974.png'>![Usersnap Feedback - Can check box button be dark grey or or even black instead of blue?](https://usersnappublic.s3.amazonaws.com/2019-02-22/18-40/0242b6f2-385b-487b-b16f-a36d338a968f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-02-22/18-40/5b1a4d20-fc74-4a76-9d67-7b8c7fe82974.png'>Download original image</a>

**Browser**: Chrome 72 (macOS Mojave)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5239/edit](https://ppedia-stage.herokuapp.com/case/5239/edit)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson we were using the default browser checkbox, which cannot be styled differently, so i created a custom checkbox so we can get the dark grey background. let me know what you think of this:
<img width="307" alt="screenshot 2019-02-28 23 21 27" src="https://user-images.githubusercontent.com/130878/53659453-75805a00-3c10-11e9-98d1-d1a29543ef39.png">
<img width="309" alt="screenshot 2019-02-28 23 21 20" src="https://user-images.githubusercontent.com/130878/53659454-75805a00-3c10-11e9-830b-75fa892781c2.png">

**Comment by jesicarson** [comment]
love it. thank you! details, details :P
