### ISSUE TITLE
Usersnap Feedback - Fix to standard spacing between Audio and Start Date questions.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#299]
**Sender**: jesi.carson@gmail.com
**Comment**: Fix to standard spacing between Audio and Start Date questions. 
[Open #43 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/43)

<a href='https://usersnappublic.s3.amazonaws.com/2019-02-22/18-38/14855c48-2172-4e68-90de-185195b6cd34.png'>![Usersnap Feedback - Fix to standard spacing between Audio and Start Date questions.](https://usersnappublic.s3.amazonaws.com/2019-02-22/18-38/3b62e64f-d5f5-4b10-a7d3-251d0d553ad7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-02-22/18-38/14855c48-2172-4e68-90de-185195b6cd34.png'>Download original image</a>

**Browser**: Chrome 72 (macOS Mojave)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5239/edit](https://ppedia-stage.herokuapp.com/case/5239/edit)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson this is the standard spacing afaik (30px below section + horizontal line + 60px space, then next section), but it's missing the horizontal divider line, which has since been added. 
<img width="969" alt="screenshot 2019-02-26 19 32 05" src="https://user-images.githubusercontent.com/130878/53463925-48a82900-39fd-11e9-8f00-5bdd4e045bb8.png">

**Comment by jesicarson** [comment]
If this is quick submit, there should be no horizontal spacer bars at all, just regularly spaced questions with no delineation of different sections.

If this is the full version, the section header is missing above Start Date - should be "Date & Duration"

(next time I will note if my snap is quick sub or full, sorry about that)

**Comment by ascott** [comment]
ah, i see! thanks for the clarification!
