### ISSUE TITLE
Usersnap Feedback - Gravatar is excessively confusing and doesn't seem to work! I've gone from [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#313]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Gravatar is excessively confusing and doesn't seem to work! I've gone from my PPedia profile to my WordPress/Gravatar and back like 5 times now and it just doesn't seem to work
[Open #32 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/32)

<a href='https://usersnappublic.s3.amazonaws.com/2019-02-20/23-02/fbfbec0e-751a-448d-8156-0ab460d76217.png'>![Usersnap Feedback - Gravatar is excessively confusing and doesn't seem to work! I've gone from (...)](https://usersnappublic.s3.amazonaws.com/2019-02-20/23-02/c769135c-5a26-4dfb-b9d8-705e0edd7984.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-02-20/23-02/fbfbec0e-751a-448d-8156-0ab460d76217.png'>Download original image</a>

**Browser**: Firefox 65 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/user/110904](https://ppedia-stage.herokuapp.com/user/110904)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 585

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher what is gravatar? i must have missed something :P is this for your wordpress testing?

**Comment by ascott** [comment]
@jesicarson Gravatar is the service we are using for profile pictures. It is a profile picture that is associated with your email address so it can be used on multiple services. https://en.gravatar.com/

**Comment by jesicarson** [comment]
Oh right, thanks! 
Is it supposed to be working yet?

**Comment by ascott** [comment]
yes, it should be working. it's working for me, but there are some bugs with user login currently so problems with gravatar could be related to that, i'm not sure. i haven't dug into this yet, so i'm not sure why it's not working for scott. does it work for you @jesicarson?

**Comment by jesicarson** [comment]
Actually I haven't tried it yet. At the moment I'm staying away from any testing outside of visual review until you give the go ahead, so that you can keep focused. So no rush on this specifically.
