### ISSUE TITLE
Usersnap Feedback - Editing feedback: now that I read it, 'The initial vision..." paragraph do[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#316]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Editing feedback: now that I read it, 'The initial vision..." paragraph doesn't make sense as written. There should be two separate objects: the initial vision and the ongoing project. IE the initial vision was developed by Archon and Mark, but it's not guided by a set of standing committees, the [ongoing] project is. It's also unclear what we mean by PPedia being guided by a set of standing committees - what part of it is guided? It kind of contradicts our message of 'community-driven', or at least complicates/confuses that message.
[Open #28 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/28)

<a href='https://usersnappublic.s3.amazonaws.com/2019-02-20/22-34/d2e722a5-9b55-4e07-bfc1-d3a7a311c6ca.png'>![Usersnap Feedback - Editing feedback: now that I read it, 'The initial vision..." paragraph do(...)](https://usersnappublic.s3.amazonaws.com/2019-02-20/22-34/60a2e5f5-fd20-45b2-811a-83617a796a8b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-02-20/22-34/d2e722a5-9b55-4e07-bfc1-d3a7a311c6ca.png'>Download original image</a>

**Browser**: Firefox 65 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/about](https://ppedia-stage.herokuapp.com/about)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 585

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
