### ISSUE TITLE
Usersnap Feedback - Error when I clicked "submit case" after editing an existing case. - Jesi

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#32]
**Sender**: jesi.carson@gmail.com
**Comment**: Error when I clicked "submit case" after editing an existing case.
- Jesi
[Open #46 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/46)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/01-20/d4411fbd-10da-4d2b-b7b8-4d67ef9ec039.png'>![Usersnap Feedback - Error when I clicked "submit case" after editing an existing case. - Jesi](https://usersnappublic.s3.amazonaws.com/2017-06-17/01-20/5487f10c-6f3b-45d1-ab19-2907fca5ff32.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/01-20/d4411fbd-10da-4d2b-b7b8-4d67ef9ec039.png'>Download original image</a>

**Browser**: Chrome 58 (macOS Sierra)
**Referer**: [https://participedia.xyz/case/4565/edit](https://participedia.xyz/case/4565/edit)
**Screen size**: 1280 x 800 **Browser size**: 1276 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Working now.
