### ISSUE TITLE
Usersnap Feedback - All content that I just added when editing has been deleted following the [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#33]
**Sender**: jesi.carson@gmail.com
**Comment**: All content that I just added when editing has been deleted following the last error message. This is desktop now, by the way. 
- Jesi
[Open #47 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/47)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/01-21/fbfb9b63-3018-4bb5-a83d-569699f11d22.png'>![Usersnap Feedback - All content that I just added when editing has been deleted following the (...)](https://usersnappublic.s3.amazonaws.com/2017-06-17/01-21/23d929c7-5304-4fc6-a053-d9af0c05c662.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/01-21/fbfb9b63-3018-4bb5-a83d-569699f11d22.png'>Download original image</a>

**Browser**: Chrome 58 (macOS Sierra)
**Referer**: [https://participedia.xyz/case/4565/edit](https://participedia.xyz/case/4565/edit)
**Screen size**: 1280 x 800 **Browser size**: 1276 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
@jesicarson Is this still replicable or can I close it?
