### ISSUE TITLE
Usersnap Feedback - "Hidden" content should not show up on user profiles (or anywhere, for tha[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#330]
**Sender**: scottowenfletcher@gmail.com
**Comment**: "Hidden" content should not show up on user profiles (or anywhere, for that matter)
[Open #304 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/304)

<a href='https://usersnappublic.s3.amazonaws.com/2019-03-10/22-34/46bfe11d-3776-451d-952d-31c64d1e630b.png'>![Usersnap Feedback - "Hidden" content should not show up on user profiles (or anywhere, for tha(...)](https://usersnappublic.s3.amazonaws.com/2019-03-10/22-34/fda0f078-381d-4443-9e1f-6ba9c49024f3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-03-10/22-34/46bfe11d-3776-451d-952d-31c64d1e630b.png'>Download original image</a>

**Browser**: Chrome 72 (Windows 10)
**Referer**: [https://participedia.xyz/users/199797](https://participedia.xyz/users/199797)
**Screen size**: 1280 x 720 **Browser size**: 1707 x 771

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher which of this content is supposed to be hidden? and is all hidden content currently visible or just certain items? thanks

**Comment by scottofletcher** [comment]
@jesicarson oh sorry, I used the highlight/select function of Usersnaps but it doesn't seem to display here. It was the one on the bottom right, "Medialab Prado's ParticipaLAB (Madrid)" was converted to a case and 'hidden'. 
RE is all hidden content visible: yes, but just on user profiles, if you follow a hyperlink to a hidden page, and if you type in the exact URL (ie. if you know the ID)

**Comment by jesicarson** [comment]
Reproduced by Scott with test account: As a non-admin user you can access hidden content from case ID urls, AND hidden items are showing up on people's user profiles.

Note: Dethe said it would be possible to re-route all non-admin traffic from hidden pages to a page that says 'This entry has been removed' (but shouldn't be necessary if the above problem is addressed and hidden content doesn't show up on the site to be clicked)
