### ISSUE TITLE
Usersnap Feedback - User profile text is blue?

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#332]
**Sender**: scottowenfletcher@gmail.com
**Comment**: User profile text is blue?
[Open #306 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/306)

<a href='https://usersnappublic.s3.amazonaws.com/2019-03-13/23-56/8efc4a4d-1460-43da-94dc-5ab89983171c.png'>![Usersnap Feedback - User profile text is blue?](https://usersnappublic.s3.amazonaws.com/2019-03-13/23-56/bd2d0d42-b1d4-4f6d-b0d2-f2464a3efecc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-03-13/23-56/8efc4a4d-1460-43da-94dc-5ab89983171c.png'>Download original image</a>

**Browser**: Chrome 72 (Windows 10)
**Referer**: [https://participedia.xyz/users/417806](https://participedia.xyz/users/417806)
**Screen size**: 1280 x 720 **Browser size**: 1707 x 771

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
known bug. on to do list for @ascott

**Comment by ascott** [comment]
fixed
