### ISSUE TITLE
Usersnap Feedback - @jesi should we be using the creative commons icon here, or the copyright icon?

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#339]
**Sender**: alannascott@gmail.com
**Comment**: @jesicarson  should we be using the creative commons icon here, or the copyright icon?
[Open #58 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/58)

<a href='https://usersnappublic.s3.amazonaws.com/2019-03-22/21-33/c4c692c2-8950-4916-abaa-911c35416175.png'>![Usersnap Feedback - @jesi should we be using the creative commons icon here, or the copyright icon?](https://usersnappublic.s3.amazonaws.com/2019-03-22/21-33/dbfea95c-c8b9-4e37-8add-f350b407ec80.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-03-22/21-33/c4c692c2-8950-4916-abaa-911c35416175.png'>Download original image</a>

**Browser**: Chrome 73 (macOS High Sierra)
**Referer**: [https://ppedia-stage.herokuapp.com/](https://ppedia-stage.herokuapp.com/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson quick q about the copyright symbol in the footer...

**Comment by jesicarson** [comment]
Creative Commons with Hyperlink to cc license. https://creativecommons.org/licenses/by-nc-sa/3.0/
