### ISSUE TITLE
Usersnap Feedback - Need tiered bullet points.  Will the new text editor allow for indented/su[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#349]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Need tiered bullet points. 
Will the new text editor allow for indented/sub-bullet points? There are a lot of cases like this
[Open #317 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/317)

<a href='https://usersnappublic.s3.amazonaws.com/2019-04-01/17-25/34362963-3fae-4ea8-b15c-68ba51d4883b.png'>![Usersnap Feedback - Need tiered bullet points.  Will the new text editor allow for indented/su(...)](https://usersnappublic.s3.amazonaws.com/2019-04-01/17-25/815411d0-54a9-408f-9c89-270fac6b0df9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-04-01/17-25/34362963-3fae-4ea8-b15c-68ba51d4883b.png'>Download original image</a>

**Browser**: Chrome 73 (Windows 10)
**Referer**: [https://participedia.xyz/case/5706/edit](https://participedia.xyz/case/5706/edit)
**Screen size**: 1280 x 720 **Browser size**: 1451 x 754

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher yes, the new editor supports nested bullets 👍 

<img width="698" alt="Screenshot 2019-04-16 13 15 03" src="https://user-images.githubusercontent.com/130878/56241033-ac3bf380-6049-11e9-9d3e-e34ce79c054f.png">
