### ISSUE TITLE
Usersnap Feedback - So, when I choose to see only "cases" (or any other options) it only chang[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#35]
**Sender**: kalincacopello@gmail.com
**Comment**: So, when I choose to see only "cases" (or any other options) it only changes the content grid, but not in the map (this stays static with all entries)
[Open #49 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/49)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/01-48/b7ec8a99-d92d-4bc6-a6e2-0e8b0b03bab1.png'>![Usersnap Feedback - So, when I choose to see only "cases" (or any other options) it only chang(...)](https://usersnappublic.s3.amazonaws.com/2017-06-17/01-48/b25cd9d4-ae45-43c1-91fc-5f71b713dc08.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/01-48/b7ec8a99-d92d-4bc6-a6e2-0e8b0b03bab1.png'>Download original image</a>

**Browser**: Firefox 53 (macOS Sierra)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 633

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Will be tracked and fixed here: https://github.com/participedia/frontend/issues/478
