### ISSUE TITLE
Usersnap Feedback - Case, General Issues (editing an existing case): The existing case had one [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#355]
**Sender**: jesi.carson@gmail.com
**Comment**: Case, General Issues (editing an existing case): The existing case had one general issue already selected. I added two more and tried to re-order them, but re-ordering doesn't work.
[Open #67 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/67)

<a href='https://usersnappublic.s3.amazonaws.com/2019-04-09/01-17/f0662d46-c80c-4a4c-b3e4-9a9ef7990275.png'>![Usersnap Feedback - Case, General Issues (editing an existing case): The existing case had one (...)](https://usersnappublic.s3.amazonaws.com/2019-04-09/01-17/3c9ece3e-5bea-45ea-997b-cd00358e92d6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-04-09/01-17/f0662d46-c80c-4a4c-b3e4-9a9ef7990275.png'>Download original image</a>

**Browser**: Chrome 73 (macOS Mojave)
**Referer**: [http://ppedia-stage.herokuapp.com/case/5196/edit](http://ppedia-stage.herokuapp.com/case/5196/edit)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson i just tested this and it's working for me. here's a screen grab gif of the interaction: 

![participedia-adding-re-ordering-list](https://user-images.githubusercontent.com/130878/55763620-919bc600-5a1c-11e9-83b8-c0e322657039.gif)

can you give me more details about what happens when you try or what you are expecting to happen?

**Comment by jesicarson** [comment]
It doesn't work like that for me. When I drag and drop the items, they don't re-order.

**Comment by jesicarson** [comment]
Ah! Sorry, I lied it does work. I was dragging the items in between the space between the other items, not right on top of them. It only works when you drop an item right on top of another item. Anyway, good that it works.
