### ISSUE TITLE
Usersnap Feedback - Clicking + Case doesn't work. Seems to time out. Will upload screenshot of [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#358]
**Sender**: jesi.carson@gmail.com
**Comment**: Clicking + Case doesn't work. Seems to time out. Will upload screenshot of error message to this snap.
[Open #70 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/70)

<a href='https://usersnappublic.s3.amazonaws.com/2019-04-09/02-48/41fbf055-f7d1-45c2-9deb-950ff06ee31f.png'>![Usersnap Feedback - Clicking + Case doesn't work. Seems to time out. Will upload screenshot of (...)](https://usersnappublic.s3.amazonaws.com/2019-04-09/02-48/a2e64635-91af-4e6d-b0c8-5cf5749925c3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-04-09/02-48/41fbf055-f7d1-45c2-9deb-950ff06ee31f.png'>Download original image</a>

**Browser**: Chrome 73 (macOS Mojave)
**Referer**: [http://ppedia-stage.herokuapp.com/content-chooser](http://ppedia-stage.herokuapp.com/content-chooser)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
![Screen Shot 2019-04-08 at 5 48 11 PM](https://user-images.githubusercontent.com/13560530/55765871-a5e4c080-5a26-11e9-9792-1b064875f630.png)

**Comment by ascott** [comment]
this is a known issue and we have an issue in the api repo to track this.
