### ISSUE TITLE
Usersnap Feedback - Tried to submit a method on the quick submit and got a "Something went wro[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#36]
**Sender**: kalincacopello@gmail.com
**Comment**: Tried to submit a method on the quick submit and got a "Something went wrong" message.
[Open #50 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/50)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/02-06/3f3d570a-3294-482f-94a4-83b36d6c33ae.png'>![Usersnap Feedback - Tried to submit a method on the quick submit and got a "Something went wro(...)](https://usersnappublic.s3.amazonaws.com/2017-06-17/02-06/d5f7e34d-06bc-4808-a3b8-92a592ba15d5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-17/02-06/3f3d570a-3294-482f-94a4-83b36d6c33ae.png'>Download original image</a>

**Browser**: Firefox 53 (macOS Sierra)
**Referer**: [https://participedia.xyz/new/method](https://participedia.xyz/new/method)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 633

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
This is fixed now.
