### ISSUE TITLE
Usersnap Feedback - Red/pink text?

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#360]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Red/pink text?
[Open #319 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/319)

<a href='https://usersnappublic.s3.amazonaws.com/2019-04-20/19-11/63fb8bd5-cbbe-4066-a5c1-b8950aed7c02.png'>![Usersnap Feedback - Red/pink text?](https://usersnappublic.s3.amazonaws.com/2019-04-20/19-11/919d5e81-4754-4497-b445-617c24dd79fe.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-04-20/19-11/63fb8bd5-cbbe-4066-a5c1-b8950aed7c02.png'>Download original image</a>

**Browser**: Chrome 73 (Windows 10)
**Referer**: [https://participedia.xyz/organization/265](https://participedia.xyz/organization/265)
**Screen size**: 1280 x 720 **Browser size**: 2560 x 1156

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher looks like this text is formatted as a code block (using `{}` icon rich text editor), which is formatting the text as red/pink. you can fix this in the editor by selecting the affected text and deselecting the `{}` icon.

**Comment by scottofletcher** [comment]
thanks @ascott! I have no idea why that was selected in the first place (wasn't me!)
