### ISSUE TITLE
Usersnap Feedback - Changing my profile image with gravatar has a few problems. 1. it navigate[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#378]
**Sender**: jesi.carson@gmail.com
**Comment**: Changing my profile image with gravatar has a few problems. 1. it navigates me away from participedia with no way to get back. 2. when i return to participedia I am logged out. 3. because my gravatar account had a different email address associated with it, I added the email address associated with this participedia account - then when i returned to participedia and logged in, my other email gravatar is the top right icon and the correct image is my profile. 

I would recommend removing gravatar and not offering an edit profile image option until we can solve this with less bugs.
[Open #323 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/323)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-01/00-20/703d85ca-f5c8-4f67-8826-ac1defb364e9.png'>![Usersnap Feedback - Changing my profile image with gravatar has a few problems. 1. it navigate(...)](https://usersnappublic.s3.amazonaws.com/2019-05-01/00-20/d8f8f186-bd73-4bda-9f82-fb8d019c4f57.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-01/00-20/703d85ca-f5c8-4f67-8826-ac1defb364e9.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://participedia.xyz/users/1189](https://participedia.xyz/users/1189)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Oops I just realized I logged back into xyz instead of staging for this test. Still buggy but will try staging now and see.

**Comment by ascott** [comment]
yeah it is buggy. i just tested on staging and went to gravatar to change the image, and when i came back to my participedia profile it didn't update the image. the same issue happens on the gravatar site, it doesn't update the gravatar profile image in real time. the profile pic in the top right is still the old one even though i've added a new one. 

<img width="1280" alt="Screenshot 2019-05-06 21 43 50" src="https://user-images.githubusercontent.com/130878/57272387-5d7dea00-7048-11e9-9de1-77e8d66e800a.png">

we could use the user initials as the profile image for now until we can implement our own profile image upload.

**Comment by ascott** [comment]
i reloaded my profile, and my new image is there now. so looks like a 5-6 minute lag from the gravatar servers when you add/change your image.

**Comment by ascott** [comment]
created an issue: https://github.com/participedia/api/issues/537
