### ISSUE TITLE
Usersnap Feedback - Edit profile button missing on my profile (post-gravatar use)

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#379]
**Sender**: jesi.carson@gmail.com
**Comment**: Edit profile button missing on my profile (post-gravatar use)
[Open #324 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/324)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-01/00-21/3b1a97e0-837e-452a-a40d-e9c3fa92af92.png'>![Usersnap Feedback - Edit profile button missing on my profile (post-gravatar use)](https://usersnappublic.s3.amazonaws.com/2019-05-01/00-21/f3036470-5b44-413e-9675-9873ac3d6470.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-01/00-21/3b1a97e0-837e-452a-a40d-e9c3fa92af92.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://participedia.xyz/users/1189](https://participedia.xyz/users/1189)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
can't reproduce this on the staging site, must just be an issue with .xyz
