### ISSUE TITLE
Usersnap Feedback - Missing hyperlink to guidelines in narrative explanatory text (this applie[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#389]
**Sender**: jesi.carson@gmail.com
**Comment**: Missing hyperlink to guidelines in narrative explanatory text (this applies to cases, methods and orgs forms)
[Open #94 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/94)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-11/00-59/b31ccc43-eb0c-4d3c-9388-06fd230ee212.png'>![Usersnap Feedback - Missing hyperlink to guidelines in narrative explanatory text (this applie(...)](https://usersnappublic.s3.amazonaws.com/2019-05-11/00-59/fcf2e16b-2e62-41ca-86fa-df22c9cdd405.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-11/00-59/b31ccc43-eb0c-4d3c-9388-06fd230ee212.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://ppedia-stage.herokuapp.com/method/new?full=1](https://ppedia-stage.herokuapp.com/method/new?full=1)
**Screen size**: 1280 x 800 **Browser size**: 1279 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson do you have the link to the guidelines doc? and is it the same doc for the methods and orgs?

**Comment by jesicarson** [comment]
Yes same doc for all: https://docs.google.com/document/d/1lzhV6aoslzqaj9XhOtVUOHbSJYOPK0tiXg0ALzIkN-w/edit?usp=sharing
