### ISSUE TITLE
Usersnap Feedback - Missing info popups on forms. See spec spreadsheets for copy.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#390]
**Sender**: jesi.carson@gmail.com
**Comment**: Missing info popups on forms. See spec spreadsheets for copy.
[Open #95 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/95)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-13/21-49/1e222b70-432f-4c8a-8b22-b09c714e136e.png'>![Usersnap Feedback - Missing info popups on forms. See spec spreadsheets for copy.](https://usersnappublic.s3.amazonaws.com/2019-05-13/21-49/b2e024b7-63bc-47c6-b68d-11a266f6f1fb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-13/21-49/1e222b70-432f-4c8a-8b22-b09c714e136e.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://ppedia-stage.herokuapp.com/case/new?full=1](https://ppedia-stage.herokuapp.com/case/new?full=1)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson is there a git issue for the design of these popups?

**Comment by jesicarson** [comment]
@ascott see xyz, ie: components section of the forms, for the modal functionality. However, on xyz the info icon isn't correct. Below is a screenshot from the design guidelines for placement and here's [the info icon as a vector](https://drive.google.com/open?id=1Q54tklaaeXuCEO_dnJzcBsIlooLz0Cx-). 

![Screen Shot 2019-05-13 at 3 19 00 PM](https://user-images.githubusercontent.com/13560530/57658185-d58d6800-7592-11e9-80f2-e436362329d7.png)

**Comment by ascott** [comment]
@jesicarson thanks!
