### ISSUE TITLE
Usersnap Feedback - Is it possible to display the 'Brief Description' text under the titles li[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#392]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Is it possible to display the 'Brief Description' text under the titles like on .net? It also needs to be included in the narrative (about 'Problems and Purpose') for those who come to the entry from an outside source (eg. Google)
[Open #97 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/97)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-22/65fa1ee8-52c6-4ac8-a4cb-2a6f523d726d.png'>![Usersnap Feedback - Is it possible to display the 'Brief Description' text under the titles li(...)](https://usersnappublic.s3.amazonaws.com/2019-05-14/19-22/54d220f3-4d6c-4f61-ad03-4961ee0af508.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-22/65fa1ee8-52c6-4ac8-a4cb-2a6f523d726d.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/?selectedCategory=case&page=3&layout=list](https://ppedia-stage.herokuapp.com/?selectedCategory=case&page=3&layout=list)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 731

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher if an article has brief description text, it will show up in this view. looks like the cases you've highlighted don't have brief description text saved.
<img width="1280" alt="Screenshot 2019-05-14 12 53 02" src="https://user-images.githubusercontent.com/130878/57727814-455d2a80-7647-11e9-8963-e76baad21f5d.png">

**Comment by scottofletcher** [comment]
@ascott great! that's actually super helpful to know for editing purposes - thanks!
