### ISSUE TITLE
Usersnap Feedback - Wrong user listed under 'first submitted by'. I submitted this - see https[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#395]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Wrong user listed under 'first submitted by'. I submitted this - see https://participedia.net/en/cases/use-montreals-right-initiative-public-consultations-state-urban-agriculture and https://participedia.xyz/case/4850
[Open #100 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/100)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-31/0754cf6f-2b59-43f5-8259-927c905c2439.png'>![Usersnap Feedback - Wrong user listed under 'first submitted by'. I submitted this - see https(...)](https://usersnappublic.s3.amazonaws.com/2019-05-14/19-31/68e0e5b8-f9a2-4a35-ba4c-097022a90c4c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-31/0754cf6f-2b59-43f5-8259-927c905c2439.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/4850](https://ppedia-stage.herokuapp.com/case/4850)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 731

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher disregard the incorrect user data. we anonymized the data for local use, so they are all fake names. in retrospect since the data is all public anyway, we probably didn't need to do this.

**Comment by scottofletcher** [comment]
Sorry, my bad! Although Loy Bashirian is kind of a cool name. Has a Star Wars ring to it :P
