### ISSUE TITLE
Usersnap Feedback - Change to "Cases are specific events and instances of participatory politi[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#398]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Change to "Cases are specific events and instances of participatory politics and governance. Cases can be contemporary or historical, completed or ongoing."
[Open #103 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/103)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-34/02a5dc33-1675-44d7-ab48-f70706193f02.png'>![Usersnap Feedback - Change to "Cases are specific events and instances of participatory politi(...)](https://usersnappublic.s3.amazonaws.com/2019-05-14/19-34/28ad37b3-0548-467a-9e13-3deb9fba2a37.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-34/02a5dc33-1675-44d7-ab48-f70706193f02.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/content-chooser](https://ppedia-stage.herokuapp.com/content-chooser)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 731

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #460
