### ISSUE TITLE
Usersnap Feedback - Change to "Organizations are formal and informal groups that design, imple[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#399]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Change to "Organizations are formal and informal groups that design, implement, and support innovations in participatory politics and governance."
[Open #104 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/104)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-35/b92b94d9-6a8c-4adb-ba53-d603120453dc.png'>![Usersnap Feedback - Change to "Organizations are formal and informal groups that design, imple(...)](https://usersnappublic.s3.amazonaws.com/2019-05-14/19-35/b4901000-5779-43a4-8be1-0d6d8aa8205f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-35/b92b94d9-6a8c-4adb-ba53-d603120453dc.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/content-chooser](https://ppedia-stage.herokuapp.com/content-chooser)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 731

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #460
