### ISSUE TITLE
Usersnap Feedback - Can't enter text

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#406]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Can't enter text
[Open #111 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/111)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-48/270e24c3-f161-4f89-8ddf-48605c4d3a59.png'>![Usersnap Feedback - Can't enter text](https://usersnappublic.s3.amazonaws.com/2019-05-14/19-48/b73c6d05-d81a-43a5-8efe-6dc8f3eac614.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-48/270e24c3-f161-4f89-8ddf-48605c4d3a59.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/new?full=1](https://ppedia-stage.herokuapp.com/case/new?full=1)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 731

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
@ascott I don't know why, but the position of my Usersnap arrow is off - I think this is happening with all my Usersnaps...

**Comment by ascott** [comment]
duplicate
