### ISSUE TITLE
Usersnap Feedback - Cannot enter text in Primary Organizer/Manager field

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#411]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Cannot enter text in Primary Organizer/Manager field
[Open #116 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/116)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-57/6f6037ac-03c1-4272-b048-0b81f06f86c2.png'>![Usersnap Feedback - Cannot enter text in Primary Organizer/Manager field](https://usersnappublic.s3.amazonaws.com/2019-05-14/19-57/ab8b3965-1292-4367-bd21-69bc4ba5ec2f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-14/19-57/6f6037ac-03c1-4272-b048-0b81f06f86c2.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/new?full=1](https://ppedia-stage.herokuapp.com/case/new?full=1)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 731

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher two options for this field, can you let us know which you prefer?
1. leave as is (update the placeholder text to "Select organizer from the database"), and users can see a complete list of all organizations in the database with the dropdown menu, but cannot type to search for one
2. change this to an autocomplete/type to search field, but then users cannot see the complete list.

**Comment by scottofletcher** [comment]
@jesicarson I think all the fields that were designed to be autocomplete/type to search should be implemented as such. we currently have close to 600 organization in the database which is far too many to scroll through. I like how it works on XYZ currently: I can type in one or two letters and get a shortened list of possible options

**Comment by jesicarson** [comment]
Ok sounds good, we will implement type to search where specified in the spreadsheet. 
@ascott is this a big change requiring a lot of dev time? 
@scottofletcher can it wait until after launch? and, can you help by highlighting the fields in the spreadsheet that this change applies to?
thanks!

**Comment by ascott** [comment]
probably 1/2 - 1 day to implement. i believe it should only be for lists of cases, methods and orgs.

**Comment by scottofletcher** [comment]
@jesicarson unfortunately this can't wait until after launch because these are some of our most crucial fields (they tie the datasets together - something Mark, Edana, and Sule requested). also, the current drop-down doesn't actually contain any items; it seems to be blank or have the items listed in white on a white background. my entries also failed to save when I selected anything from these menus (yes, I could select blank items...)

**Comment by jesicarson** [comment]
Yep this is actually a bug on my side. I don't even see the orgs in the list, its a blank drop down. I've filed another issue for this. screenshot:
![Screen Shot 2019-05-16 at 8 54 26 AM](https://user-images.githubusercontent.com/13560530/57868720-5e391d80-77b8-11e9-82e6-6f6f61ba8acc.png)

**Comment by scottofletcher** [comment]
here's what it looks like on mobile: 
![Screenshot_20190516-085319_Chrome](https://user-images.githubusercontent.com/29512491/57869923-e91b1780-77ba-11e9-9e23-ee4bad507302.jpg)

**Comment by jesicarson** [comment]
Yep. Bad bug. @ascott this should be high on the list.

**Comment by jesicarson** [comment]
@ascott that is - at least get the values visible and the field functioning. If it makes sense to make it type to search at the same time, great. If not, that can wait.

**Comment by scottofletcher** [comment]
@jesicarson this needs to be type to search by launch, though

**Comment by jesicarson** [comment]
@scottofletcher it needs to be functional by launch, at least.

**Comment by ascott** [comment]
yes, hi pri to get this functional. it's document in the api project here: https://github.com/participedia/api/issues/574

will get the autocomplete happening asap as well, but focusing on functionality bugs first.
