### ISSUE TITLE
Usersnap Feedback - I seem to remember that Amber asked us to make all headings 'Heading 2' by [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#413]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I seem to remember that Amber asked us to make all headings 'Heading 2' by default
[Open #118 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/118)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/00-05/9b6d05a3-b440-47e1-9550-4932a77a20b1.png'>![Usersnap Feedback - I seem to remember that Amber asked us to make all headings 'Heading 2' by (...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/00-05/f6a91d28-251b-41aa-96fa-cd52501035e1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/00-05/9b6d05a3-b440-47e1-9550-4932a77a20b1.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/new?full=1](https://ppedia-stage.herokuapp.com/case/new?full=1)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 731

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
the current body headings use h3, so if we want to move to h2, it would require a data migration to change all existing headings from h3 to h2 in order to be consistent.

**Comment by jesicarson** [comment]
@scottofletcher is correct, the design guidelines specify H2 for narrative headings. That should be the default.

**Comment by scottofletcher** [comment]
@ascott Jaskiran and I have gone through and changed most entry's headings to H2 by now, so it's nbd if they don't update automatically. just as long as they're in H2 in the new narrative editor so new entries will be consistent going forward

**Comment by jesicarson** [comment]
Great. Hopefully we can just switch it to be the default from now on.
