### ISSUE TITLE
Usersnap Feedback - I really like the new brief description field that allows you to go over 2[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#417]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I really like the new brief description field that allows you to go over 280 characters BUT I think we should cap it at 500 characters. I got into the 700s which is a bit much
[Open #122 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/122)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/00-27/8ddc573d-8d97-4671-b13e-3fd111069c4e.png'>![Usersnap Feedback - I really like the new brief description field that allows you to go over 2(...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/00-27/c46a20ec-a61d-4617-aacf-e82f0636dd58.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/00-27/8ddc573d-8d97-4671-b13e-3fd111069c4e.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/new?full=1](https://ppedia-stage.herokuapp.com/case/new?full=1)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 731

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott is this a bug?

**Comment by ascott** [comment]
i don't think this is a bug. the field allows you paste as many characters as you want, but shows how far over the limit you are. i don't think we need to limit the amount of characters allowed over the limit. 
<img width="641" alt="Screenshot 2019-05-15 14 01 08" src="https://user-images.githubusercontent.com/130878/57809232-e5838400-7719-11e9-8e5e-76618942e50e.png">
i would say we could close this one.

**Comment by jesicarson** [comment]
Oh I get it. I thought he was able to publish more than 280 characters. Yes i agree we don't need to limit it, and allowing people to see what they want to paste in here and then edit it down using the counter seems like a friendlier interface. Closing.
