### ISSUE TITLE
Usersnap Feedback - Clicking 'Do Full Version' wiped out everything I'd entered in Quick Submit...

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#429]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Clicking 'Do Full Version' wiped out everything I'd entered in Quick Submit...
[Open #134 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/134)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/01-12/e7a0d60d-e2ac-4a90-a14b-5eeca607a9ac.png'>![Usersnap Feedback - Clicking 'Do Full Version' wiped out everything I'd entered in Quick Submit...](https://usersnappublic.s3.amazonaws.com/2019-05-15/01-12/b617243f-7d18-4912-a4a5-4df3fc7caa57.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/01-12/e7a0d60d-e2ac-4a90-a14b-5eeca607a9ac.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/new?full=1](https://ppedia-stage.herokuapp.com/case/new?full=1)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 685

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher did you see the warning message first? 
<img width="1280" alt="Screenshot 2019-05-14 16 31 09" src="https://user-images.githubusercontent.com/130878/57738782-c0353e00-7665-11e9-9159-c45caa992944.png">

**Comment by scottofletcher** [comment]
nope. I was also able to hit refresh, back, and close the browser window without seeing that message

**Comment by ascott** [comment]
ok thanks, i thought this was working in FF. I will look into it.
