### ISSUE TITLE
Usersnap Feedback - Neither of the publish buttons are working

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#430]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Neither of the publish buttons are working
[Open #135 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/135)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/01-25/ecdeaf5b-8435-43c6-bb51-18ec70a2dd75.png'>![Usersnap Feedback - Neither of the publish buttons are working](https://usersnappublic.s3.amazonaws.com/2019-05-15/01-25/8aab111c-d2ea-47b4-a6cd-8434b6070b0c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/01-25/ecdeaf5b-8435-43c6-bb51-18ec70a2dd75.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5251/edit?full=1](https://ppedia-stage.herokuapp.com/case/5251/edit?full=1)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 685

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher do you have any other context here? is there a particular field you are trying to save?  if you open the web console do you see any errors? (you can open the console via the menu Tools > Web Developer > Web Console)

**Comment by scottofletcher** [comment]
@ascott Sorry, I got frustrated and gave up. I'll try it again tomorrow

**Comment by ascott** [comment]
@scottofletcher no problem, thanks for all of your testing work! i'll see if i can reproduce this.

**Comment by scottofletcher** [comment]
@ascott having the same problem this morning - here's the Web Console read out: 
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-132033152-2”. edit:6:1
Use of Mutation Events is deprecated. Use MutationObserver instead. edit-view.bundle.js:8129:10
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]

**Comment by scottofletcher** [comment]
Oh now it says 
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More] edit-view.bundle.js:18187:24
    onreadystatechange https://ppedia-stage.herokuapp.com/build/js/edit-view.bundle.js:18187
    onreadystatechange https://cdn.usersnap.com/classic/frontend/assets/js/entries/setup/22e4a578ff652caf3795.js:78

**Comment by scottofletcher** [comment]
oh, and this was when I was editing a case, not submitting one. and I changed the title.

**Comment by ascott** [comment]
thanks @scottofletcher

**Comment by ascott** [comment]
closing to consolidate into 1 issues: https://github.com/participedia/usersnaps/issues/607
