### ISSUE TITLE
Usersnap Feedback - Changing profile pic goes to another site - Gravatar - but I guess this is [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#442]
**Sender**: lucyjparry@gmail.com
**Comment**: Changing profile pic goes to another site - Gravatar - but I guess this is intentional? I'm not if users will be bothered to create another profile for another site though just to upload their photo.
[Open #147 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/147)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/11-25/1e3afba3-5bc5-49c3-9994-31a605dfdbec.png'>![Usersnap Feedback - Changing profile pic goes to another site - Gravatar - but I guess this is (...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/11-25/88f3ed20-f7d4-4282-be56-8cb94784fe47.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/11-25/1e3afba3-5bc5-49c3-9994-31a605dfdbec.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/user/417694/edit](https://ppedia-stage.herokuapp.com/user/417694/edit)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 625

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott we're addressing this with explanatory text below the profile image on edit profile view, isn't that right? If there's an issue for that in api this can be closed.
