### ISSUE TITLE
Usersnap Feedback - I think I should not be able to see another person bookmark. If you want t[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#447]
**Sender**: spadayale@gmail.com
**Comment**: I think I should not be able to see another person bookmark. If you want to add a sort of favorite playlist that is public that should have another name. Bookmark=private.
[Open #152 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/152)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/11-39/db24a520-6448-4e80-89a5-9475be642787.png'>![Usersnap Feedback - I think I should not be able to see another person bookmark. If you want t(...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/11-39/c43b1f42-9453-4cc7-8663-92023faa6b4b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/11-39/db24a520-6448-4e80-89a5-9475be642787.png'>Download original image</a>

**Browser**: Edge 17 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/user/1361?selectedCategory=bookmarks](https://ppedia-stage.herokuapp.com/user/1361?selectedCategory=bookmarks)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 934

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott this is correct, you shouldn't be able to see other users bookmarks.

**Comment by ascott** [comment]
@jesicarson ah ok, so the public profile should only show the contributions tab?

**Comment by jesicarson** [comment]
@ascott yes
