### ISSUE TITLE
Usersnap Feedback - not immediately clear how to create a new case. Can't we use "create conte[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#452]
**Sender**: spadayale@gmail.com
**Comment**: not immediately clear how to create a new case. Can't we use "create content" or "contribute:" instead of quick submit? Can't we have a redundant placement of "create" also in the tabs? After organizations? There it becomes quite easy to understand.
[Open #157 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/157)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/11-56/f6350a7a-9c3f-475c-8bba-fcf76618ecf2.png'>![Usersnap Feedback - not immediately clear how to create a new case. Can't we use "create conte(...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/11-56/faedf47a-4016-487c-bf50-7514b955fce5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/11-56/f6350a7a-9c3f-475c-8bba-fcf76618ecf2.png'>Download original image</a>

**Browser**: Edge 17 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/?selectedCategory=case](https://ppedia-stage.herokuapp.com/?selectedCategory=case)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 934

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
We can return to this idea after launch if further feedback comes in about people not understanding quick submit. Closing for now.
