### ISSUE TITLE
Usersnap Feedback - This is how the brief description + editing prompt is going to appear. not [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#468]
**Sender**: scottowenfletcher@gmail.com
**Comment**: This is how the brief description + editing prompt is going to appear. not the best.
[Open #173 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/173)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/18-23/19b258fb-2425-41cc-b547-7008b01bd82f.png'>![Usersnap Feedback - This is how the brief description + editing prompt is going to appear. not (...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/18-23/5cbb0ddf-be77-4e7b-95cd-df570464dbba.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/18-23/19b258fb-2425-41cc-b547-7008b01bd82f.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/1394](https://ppedia-stage.herokuapp.com/case/1394)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott Low priority, return to this after launch.
