### ISSUE TITLE
Usersnap Feedback - Should this just be 'Deliberation'?

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#47]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Should this just be 'Deliberation'?
[Open #61 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/61)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/00-36/2e1f3ee7-7bc9-453e-b381-5dfdc1ee4aae.png'>![Usersnap Feedback - Should this just be 'Deliberation'?](https://usersnappublic.s3.amazonaws.com/2017-06-18/00-36/057a4947-5da7-497d-91e5-3ccbc1bb9afc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/00-36/2e1f3ee7-7bc9-453e-b381-5dfdc1ee4aae.png'>Download original image</a>

**Browser**: Chrome 58 (Windows 10)
**Referer**: [https://participedia.xyz/case/4557/edit](https://participedia.xyz/case/4557/edit)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 590

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by andreadelrio** [comment]
Fixing it to be "Discussion, Dialogue, or Deliberation" as  per
![image](https://user-images.githubusercontent.com/4016496/30503910-f920c09a-9a20-11e7-9acf-7b3020fe6cb0.png)
