### ISSUE TITLE
Usersnap Feedback - I don't think we need a comma between 'relevant' and 'specific topics' sin[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#470]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I don't think we need a comma between 'relevant' and 'specific topics' since specific topics is a quasi-proper noun in this case
[Open #175 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/175)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/18-30/92fc9e7b-5a2f-42e0-81cb-cc45a0f53ffe.png'>![Usersnap Feedback - I don't think we need a comma between 'relevant' and 'specific topics' sin(...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/18-30/7fd9d81b-fca3-48be-a638-d06389f934d1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/18-30/92fc9e7b-5a2f-42e0-81cb-cc45a0f53ffe.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/organization/new?full=1](https://ppedia-stage.herokuapp.com/organization/new?full=1)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
