### ISSUE TITLE
Usersnap Feedback - Not sure that we need to display longitude and latitude in the sidebar. it [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#473]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Not sure that we need to display longitude and latitude in the sidebar. it takes up valuable space
[Open #178 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/178)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/18-36/946d2ca3-512d-4f4c-8e17-336a1c075f4f.png'>![Usersnap Feedback - Not sure that we need to display longitude and latitude in the sidebar. it (...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/18-36/4ad9cce7-c579-4feb-9a48-58fe3d858255.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/18-36/946d2ca3-512d-4f4c-8e17-336a1c075f4f.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/organization/5262](https://ppedia-stage.herokuapp.com/organization/5262)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott I agree with this feedback. How should I re-label?

**Comment by ascott** [comment]
we can use the `design-changes` label for things that should be done.
