### ISSUE TITLE
Usersnap Feedback - Update D&T in about page. Add all past team members, remove David from sta[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#477]
**Sender**: jesi.carson@gmail.com
**Comment**: Update D&T in about page. Add all past team members, remove David from staff section.
[Open #325 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/325)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/20-29/717c21b4-e3da-4cba-bb7c-3ac31a091b12.png'>![Usersnap Feedback - Update D&T in about page. Add all past team members, remove David from sta(...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/20-29/3540e1aa-745e-494a-9284-63897364ab6e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/20-29/717c21b4-e3da-4cba-bb7c-3ac31a091b12.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://participedia.xyz/about](https://participedia.xyz/about)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson this is from .xyz. are the same updates needed on staging?
