### ISSUE TITLE
Usersnap Feedback - Clicking 'login' just logs me in, doesn't open the pop-up to ask me for my [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#482]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Clicking 'login' just logs me in, doesn't open the pop-up to ask me for my username/email and password. that's fine, but what if I wanted to sign-in using a different account or if I'm not the same person that used this computer last (thinking about students here although I guess everyone has their own laptop these days)
[Open #185 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/185)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/23-29/b3f67199-f9e5-49ed-8429-98e83e7ca173.png'>![Usersnap Feedback - Clicking 'login' just logs me in, doesn't open the pop-up to ask me for my (...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/23-29/879a8fa6-ee41-47ee-9024-de06f719c354.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/23-29/b3f67199-f9e5-49ed-8429-98e83e7ca173.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/?page=97](https://ppedia-stage.herokuapp.com/?page=97)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Agreed, we should allow a way to switch accounts. If not how it works on xyz, then adding "Switch Accounts" to the profile dropdown could work.

**Comment by ascott** [comment]
if you use the sign out link in the profile dropdown,  it will log you out and require that you go to the login page again. i think the situation scott is referring to is basically keeping the account in session storage so you don't have to enter your login details again.
