### ISSUE TITLE
Usersnap Feedback - Location changed once I hit edit. I entered the World Bank, and the locati[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#487]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Location changed once I hit edit. I entered the World Bank, and the location used to be 'Work Bank I', now it's just the street address
[Open #190 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/190)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/23-43/2b6f4640-c5c7-47b3-9cec-9838754e1873.png'>![Usersnap Feedback - Location changed once I hit edit. I entered the World Bank, and the locati(...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/23-43/75bae905-e43e-42e2-81bd-a43f5d67e930.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/23-43/2b6f4640-c5c7-47b3-9cec-9838754e1873.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5801/edit?full=1](https://ppedia-stage.herokuapp.com/case/5801/edit?full=1)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
#488
