### ISSUE TITLE
Usersnap Feedback - Title and creator I added to the image do not show up when I mouse over it

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#493]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Title and creator I added to the image do not show up when I mouse over it
[Open #196 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/196)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/23-51/cb564900-c48a-43e0-b405-684bafdc006d.png'>![Usersnap Feedback - Title and creator I added to the image do not show up when I mouse over it](https://usersnappublic.s3.amazonaws.com/2019-05-15/23-51/290ab323-2786-4bf7-ac82-00675d59bde4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/23-51/cb564900-c48a-43e0-b405-684bafdc006d.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/method/5644](https://ppedia-stage.herokuapp.com/method/5644)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott is this a bug or not yet implemented? thx.

**Comment by ascott** [comment]
looks like there was no title saved for this entry, and the pop over only shows up if there is a title saved. 
I added a title and it shows up. <img width="636" alt="Screenshot 2019-05-16 14 05 20" src="https://user-images.githubusercontent.com/130878/57887183-be918480-77e3-11e9-907a-1a24c0e90a56.png">
