### ISSUE TITLE
Usersnap Feedback - Audio title/description I entered does not appear in sidebar

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#498]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Audio title/description I entered does not appear in sidebar
[Open #201 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/201)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/00-12/5df623cb-74bf-4dc5-94e3-5c70875e671f.png'>![Usersnap Feedback - Audio title/description I entered does not appear in sidebar](https://usersnappublic.s3.amazonaws.com/2019-05-16/00-12/3dcb2723-1b4e-4a9d-97ac-1026538b6f30.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/00-12/5df623cb-74bf-4dc5-94e3-5c70875e671f.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/method/5802](https://ppedia-stage.herokuapp.com/method/5802)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
disregard! I'm an idiot.
