### ISSUE TITLE
Usersnap Feedback - Would be nice if we could centre logos in the image display, especially if [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#504]
**Sender**: jesi.carson@gmail.com
**Comment**: Would be nice if we could centre logos in the image display, especially if on a white background. But understand this may not be possible.
[Open #207 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/207)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/00-28/cace0c83-0243-47a5-9730-9f1b1435f96c.png'>![Usersnap Feedback - Would be nice if we could centre logos in the image display, especially if (...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/00-28/74d0eac3-9f24-4f7e-934f-996b1e45cc72.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/00-28/cace0c83-0243-47a5-9730-9f1b1435f96c.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [http://ppedia-stage.herokuapp.com/?selectedCategory=organizations](http://ppedia-stage.herokuapp.com/?selectedCategory=organizations)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson currently the images are set to cover the entire image area, so it appears that they are all the same size image, so they stretch to fill the space. the alternative is to scale them down so their longest side fits in the available area and looks like this: 

<img width="1280" alt="Screenshot 2019-05-16 21 51 43" src="https://user-images.githubusercontent.com/130878/57903871-02f14480-7825-11e9-8389-4c8a585db8dd.png">
<img width="1280" alt="Screenshot 2019-05-16 21 50 20" src="https://user-images.githubusercontent.com/130878/57903878-0b497f80-7825-11e9-9ae5-91732d747db3.png">

let me know if you prefer this and i will make the change.

**Comment by jesicarson** [comment]
No we don’t want to do that. That’s why I thought it probably isn’t possible to scale only certain images.
