### ISSUE TITLE
Usersnap Feedback - Quick sub still not working for me. Error message.   - jesi

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#52]
**Sender**: jesi.carson@gmail.com
**Comment**: Quick sub still not working for me. Error message.  
- jesi
[Open #66 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/66)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/05-08/8c2c3e4c-c7f4-4352-b1a6-820a7b3d13e8.png'>![Usersnap Feedback - Quick sub still not working for me. Error message.   - jesi](https://usersnappublic.s3.amazonaws.com/2017-06-18/05-08/82f42bca-ea49-4204-9be3-1527f38c5d4a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/05-08/8c2c3e4c-c7f4-4352-b1a6-820a7b3d13e8.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Fixed now, and for some time now (for cases and orgs, methods were still having problems until recently).
