### ISSUE TITLE
Usersnap Feedback - Feature/Hide toggles missing for me, an admin account.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#521]
**Sender**: jesi.carson@gmail.com
**Comment**: Feature/Hide toggles missing for me, an admin account.
[Open #224 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/224)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/00-50/374aa1b2-9c23-4729-b391-d2f847a1e42e.png'>![Usersnap Feedback - Feature/Hide toggles missing for me, an admin account.](https://usersnappublic.s3.amazonaws.com/2019-05-16/00-50/fc978735-6af8-4927-ab6c-f7dad45473db.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/00-50/374aa1b2-9c23-4729-b391-d2f847a1e42e.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [http://ppedia-stage.herokuapp.com/case/4524](http://ppedia-stage.herokuapp.com/case/4524)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson the featured/hidden toggles are on the edit view, not the reader view. also this is the staging site. can you check if you can see the toggles on the prod site on the edit view?

**Comment by jesicarson** [comment]
Oh ya! I forgot we moved that to the edit view. Yes they are there, just checked. Thank you!
