### ISSUE TITLE
Usersnap Feedback - Will the links field auto generate a url if i just type jesicarson.com rat[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#523]
**Sender**: jesi.carson@gmail.com
**Comment**: Will the links field auto generate a url if i just type jesicarson.com rather than http://jesicarson.com? it probably should. 
design backlog
[Open #226 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/226)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/00-56/b512cd33-8dc1-499f-8968-8c9c847689f6.png'>![Usersnap Feedback - Will the links field auto generate a url if i just type jesicarson.com rat(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/00-56/737e20f0-147b-4902-85e3-51dac3c03c13.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/00-56/b512cd33-8dc1-499f-8968-8c9c847689f6.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [http://ppedia-stage.herokuapp.com/case/new](http://ppedia-stage.herokuapp.com/case/new)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Apparently this is also a bug. 

The site did generate a url: https://s3.amazonaws.com/uploads.participedia.xyz/jesicarson.com which takes you to a strange error page showing: 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>jesicarson.com</Key>
<RequestId>6F0B828F1663A620</RequestId>
<HostId>
Rokd9gsjXwf7pR5bCCc9bQdUsFVo6eDGa4iGcSCzes/9R34EPe2wFMI1zHvWSKqhjAWMv1cUrSI=
</HostId>
</Error>

![Screen Shot 2019-05-15 at 4 16 57 PM](https://user-images.githubusercontent.com/13560530/57815597-e376f080-772c-11e9-8b3e-7699bd1529b0.png)
