### ISSUE TITLE
Usersnap Feedback - The error messsge in the attached screen shot is from "Pat's second test c[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#53]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: The error messsge in the attached screen shot is from "Pat's second test case." All went well until I hit submit
[Open #67 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/67)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/05-14/7c235036-1308-4a5a-af2f-cbd20dab1c1e.png'>![Usersnap Feedback - The error messsge in the attached screen shot is from "Pat's second test c(...)](https://usersnappublic.s3.amazonaws.com/2017-06-18/05-14/aeb01985-22c3-4131-8f30-51752ba05c09.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/05-14/7c235036-1308-4a5a-af2f-cbd20dab1c1e.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
This was related to an authentication problem which has been fixed.
