### ISSUE TITLE
Usersnap Feedback - Update all 'what is a(n)' help menu definitions using the wording in the g[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#531]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Update all 'what is a(n)' help menu definitions using the wording in the guidelines: 
Cases are specific examples of how various methods of participatory politics and governance are implemented. Cases can be contemporary or historical, completed or ongoing.
Methods are the overarching processes used to guide public participation such as citizens' juries, deliberative polling, and participatory budgeting. 
Organizations are formal and informal groups that design, implement, and support innovations in participatory politics and governance.
[Open #234 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/234)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-11/80b66f81-cb48-4a29-bc8b-5b550290c71f.png'>![Usersnap Feedback - Update all 'what is a(n)' help menu definitions using the wording in the g(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-11/090a3cfd-8163-41f1-bf68-5e34a74f0038.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-11/80b66f81-cb48-4a29-bc8b-5b550290c71f.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
