### ISSUE TITLE
Usersnap Feedback - Please link to entry-specific guidelines in help menu Cases: https://docs.[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#532]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Please link to entry-specific guidelines in help menu
Cases: https://docs.google.com/document/d/1FuBBhVoKi-KzXQXDSU8DzoRFArLNsur40Q1NvnfmPrA/edit?usp=sharing

Orgs: https://docs.google.com/document/d/12QmZZBupsm2F73RnKNOqTLnaSl3CdzlWEfvv-XW4U34/edit?usp=sharing

Methods: https://docs.google.com/document/d/1Lgw_R5h5dsk-O4WYDBD7feLvRtwtq5wnXysJ6qp8veE/edit?usp=sharing
[Open #235 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/235)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-13/8209c42c-f68c-432d-b0ca-d4c4d129b190.png'>![Usersnap Feedback - Please link to entry-specific guidelines in help menu Cases: https://docs.(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-13/50f0d22c-60da-4874-90d2-fb07d8515078.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-13/8209c42c-f68c-432d-b0ca-d4c4d129b190.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
