### ISSUE TITLE
Usersnap Feedback - I would hyperlink the words 'research page' on the ''What is a survey' pag[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#533]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I would hyperlink the words 'research page' on the ''What is a survey' page of the help menu
[Open #236 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/236)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-14/b3afb05f-4e57-431e-8449-f574cadd1828.png'>![Usersnap Feedback - I would hyperlink the words 'research page' on the ''What is a survey' pag(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-14/0bd0e912-c4be-437e-967f-67b460adc107.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-14/b3afb05f-4e57-431e-8449-f574cadd1828.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
see #610
