### ISSUE TITLE
Usersnap Feedback - 'How do I create a user account' help page edits:  insert comma after addr[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#534]
**Sender**: scottowenfletcher@gmail.com
**Comment**: 'How do I create a user account' help page edits: 
insert comma after address
insert comma after Facebook
[Open #237 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/237)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-15/4014f011-75d8-464d-8639-e73299343e01.png'>![Usersnap Feedback - 'How do I create a user account' help page edits:  insert comma after addr(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-15/313bbaf9-c250-4190-9065-b815d5afa683.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-15/4014f011-75d8-464d-8639-e73299343e01.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
