### ISSUE TITLE
Usersnap Feedback - more edits for 'How do I create content': change 'article' to 'entry'

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#535]
**Sender**: scottowenfletcher@gmail.com
**Comment**: more edits for 'How do I create content': change 'article' to 'entry'
[Open #238 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/238)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-17/ea02dbe9-f5e7-4805-920e-4c7306f07f25.png'>![Usersnap Feedback - more edits for 'How do I create content': change 'article' to 'entry'](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-17/5b4f9fc3-4525-445b-9e7a-c9691f785b13.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-17/ea02dbe9-f5e7-4805-920e-4c7306f07f25.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
