### ISSUE TITLE
Usersnap Feedback - 'How do I create content' help menu page edits:  capitalize 'quick submit'

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#536]
**Sender**: scottowenfletcher@gmail.com
**Comment**: 'How do I create content' help menu page edits: 
capitalize 'quick submit'
[Open #239 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/239)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-16/adb992c9-89c7-4382-8977-da36ac809a9f.png'>![Usersnap Feedback - 'How do I create content' help menu page edits:  capitalize 'quick submit'](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-16/f33f1b35-eaeb-40bf-900b-e77a3c58ef9a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-16/adb992c9-89c7-4382-8977-da36ac809a9f.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
