### ISSUE TITLE
Usersnap Feedback - 'What is Quick Submit' help page edits:  capitalize the words 'quick submi[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#537]
**Sender**: scottowenfletcher@gmail.com
**Comment**: 'What is Quick Submit' help page edits: 
capitalize the words 'quick submit' and put quotation marks around them
no need for the last part of the sentence. it's kind of confusing anyways. quick submit implies limited content anyways as does 'in minutes'
insert comma after the word method
[Open #240 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/240)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-19/ebff3348-78e2-4a46-97ed-8dfe4fb05cde.png'>![Usersnap Feedback - 'What is Quick Submit' help page edits:  capitalize the words 'quick submi(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-19/54ee1dd0-0f0a-4105-8541-e4bd23bab769.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-19/ebff3348-78e2-4a46-97ed-8dfe4fb05cde.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
