### ISSUE TITLE
Usersnap Feedback - 'How do I edit content' help menu edits:  insert comma after the word meth[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#538]
**Sender**: scottowenfletcher@gmail.com
**Comment**: 'How do I edit content' help menu edits: 
insert comma after the word method
change the word article to entry
capitalize the word edit and put quotation marks around it (since it's referring to a button)
get rid of the words 'jump in and'
replace 'the current entry' with 'its content'. 

final copy should read: "While viewing a case, method, or organization, click the "Edit" button to add to or amend its content"
[Open #241 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/241)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-23/73f0233c-82b6-4aee-aa61-f4edf27ad9a3.png'>![Usersnap Feedback - 'How do I edit content' help menu edits:  insert comma after the word meth(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-23/91fe0993-bc22-4986-b7cd-95d86cea860c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-23/73f0233c-82b6-4aee-aa61-f4edf27ad9a3.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
