### ISSUE TITLE
Usersnap Feedback - How do I create content in another language help menu edits:  use square b[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#539]
**Sender**: scottowenfletcher@gmail.com
**Comment**: How do I create content in another language help menu edits: 
use square brackets - this is consistent w/what Alessandro has been doing
[Open #242 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/242)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-25/a1138dfd-ed34-4e1b-99b6-5bd6895d9e1c.png'>![Usersnap Feedback - How do I create content in another language help menu edits:  use square b(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-25/8bf3a8b6-5cdb-4e8e-99d8-ff83b1c88c4a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-25/a1138dfd-ed34-4e1b-99b6-5bd6895d9e1c.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
