### ISSUE TITLE
Usersnap Feedback - This appears to be the same error message I received when resting the syst[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#54]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: This appears to be the same error message I received when resting the system 10 hours ago 
[Open #68 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/68)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/14-02/e1620145-a41b-40a1-a9ab-7f3110204193.png'>![Usersnap Feedback - This appears to be the same error message I received when resting the syst(...)](https://usersnappublic.s3.amazonaws.com/2017-06-18/14-02/b65b3af8-ec44-418a-badf-0acf9ce2bff8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/14-02/e1620145-a41b-40a1-a9ab-7f3110204193.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
This submit bug should be fixed now.
