### ISSUE TITLE
Usersnap Feedback - 'How do I search for content' help menu edits:   insert comma after the wo[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#540]
**Sender**: scottowenfletcher@gmail.com
**Comment**: 'How do I search for content' help menu edits: 

insert comma after the word method
put search terms in bold to distinguish from the rest of the sentence. 
the example for AND is confusing - are you saying "bicycle and rally" will return items matching both words or "bicycle AND rally" will do so?
example for QUOTES doesn't contain any quotation marks
delete extra "will" in the example for PARENTHESES
delete "as a group" in the example for PARENTHESES (its redundant)
final Parentheses copy should read: "(bicycle or rally) and (womens rights and UK) will group logical operations inside the parentheses before applying the operators joining the two search items."
[Open #243 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/243)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-32/d7a17046-c545-436c-a75c-54c17b684c04.png'>![Usersnap Feedback - 'How do I search for content' help menu edits:   insert comma after the wo(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-32/9fde3db3-ebb9-4822-9196-47ed30d6fd7e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-32/d7a17046-c545-436c-a75c-54c17b684c04.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
