### ISSUE TITLE
Usersnap Feedback - we should probably change 'How do I access my bookmarked content' to 'How [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#541]
**Sender**: scottowenfletcher@gmail.com
**Comment**: we should probably change 'How do I access my bookmarked content' to 'How do I create and access bookmarked content?' and include instructions for bookmarking things
[Open #244 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/244)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-34/c0d6dac6-2d14-4039-bf4e-a80c600a2c77.png'>![Usersnap Feedback - we should probably change 'How do I access my bookmarked content' to 'How (...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-34/9f4d4883-8b51-4a6c-b5e7-4c738e74dba9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-34/c0d6dac6-2d14-4039-bf4e-a80c600a2c77.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
