### ISSUE TITLE
Usersnap Feedback - Teaching page: I don't think the 'Participedia in Course Assignments' need[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#542]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Teaching page: I don't think the 'Participedia in Course Assignments' needs to be in an accordion menu. there are only two links, so I think it makes sense to list them right after the last sentence under 'Participedia in the Classroom'
[Open #245 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/245)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-38/8f2dd9f2-313f-4211-b6a5-813b355a24ba.png'>![Usersnap Feedback - Teaching page: I don't think the 'Participedia in Course Assignments' need(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-38/e85fd767-f138-44e4-8a72-c087f28acac9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-38/8f2dd9f2-313f-4211-b6a5-813b355a24ba.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/teaching](https://ppedia-stage.herokuapp.com/teaching)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
