### ISSUE TITLE
Usersnap Feedback - Teaching page: I would split #1 into two items:  1. Improve students’ know[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#543]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Teaching page: I would split #1 into two items: 
1. Improve students’ knowledge of innovations in participatory democracy;
2. Improve students' research and writing skills by publishing cases, methods, and organizations on Participedia;

I'm not sure #3 makes sense - who's doing the focusing and/or what is being focused?
[Open #246 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/246)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-41/6e313046-f349-4aa7-a7f7-74bf8ee39b1d.png'>![Usersnap Feedback - Teaching page: I would split #1 into two items:  1. Improve students’ know(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/01-41/2058ddc1-83df-47a3-9a55-762bc7d0aedf.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/01-41/6e313046-f349-4aa7-a7f7-74bf8ee39b1d.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/teaching](https://ppedia-stage.herokuapp.com/teaching)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
covered by #610
