### ISSUE TITLE
Usersnap Feedback - Quick sub error message on laptop.  - Jesi

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#55]
**Sender**: jesi.carson@gmail.com
**Comment**: Quick sub error message on laptop. 
- Jesi
[Open #69 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/69)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/14-34/da17261b-5466-489a-9838-41f2c23e6203.png'>![Usersnap Feedback - Quick sub error message on laptop.  - Jesi](https://usersnappublic.s3.amazonaws.com/2017-06-18/14-34/8d760fa7-0647-456c-bd44-151865da5b94.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/14-34/da17261b-5466-489a-9838-41f2c23e6203.png'>Download original image</a>

**Browser**: Chrome 58 (macOS Sierra)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 1280 x 800 **Browser size**: 1276 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
should be fixed now
