### ISSUE TITLE
Usersnap Feedback - contributions page is missing images

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#559]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: contributions page is missing images
[Open #262 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/262)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/06-04/687f610f-c64f-4a7b-ada3-abb8ee0384a2.png'>![Usersnap Feedback - contributions page is missing images](https://usersnappublic.s3.amazonaws.com/2019-05-16/06-04/06820f72-e364-40af-81b8-31dfd065188d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/06-04/687f610f-c64f-4a7b-ada3-abb8ee0384a2.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/user/417734?selectedCategory=contributions](https://ppedia-stage.herokuapp.com/user/417734?selectedCategory=contributions)
**Screen size**: 1368 x 912 **Browser size**: 1710 x 1003

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
duplicate
