### ISSUE TITLE
Usersnap Feedback - I got an error message each time I tried to submit, but now there are a wh[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#56]
**Sender**: jesi.carson@gmail.com
**Comment**: I got an error message each time I tried to submit, but now there are a whole bunch of duplicate "Jardin" cases. I didn't try to submit 7 times though, so that's strange. 
- Jesi 
[Open #70 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/70)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/14-36/f9fba6d4-2208-49db-9c4b-d41b861aafdc.png'>![Usersnap Feedback - I got an error message each time I tried to submit, but now there are a wh(...)](https://usersnappublic.s3.amazonaws.com/2017-06-18/14-36/3900538a-1e76-44c0-82c3-57335611da0f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/14-36/f9fba6d4-2208-49db-9c4b-d41b861aafdc.png'>Download original image</a>

**Browser**: Chrome 58 (macOS Sierra)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1280 x 800 **Browser size**: 1276 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
The submit error should be fixed now. If the duplicate entries re-occurs we'll open a separate issue for that.
