### ISSUE TITLE
Usersnap Feedback - Images do not display on my profile page for either contributions or bookmarks

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#561]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Images do not display on my profile page for either contributions or bookmarks
[Open #264 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/264)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/16-01/5a56a934-0570-423d-a192-fdeafeb9fc56.png'>![Usersnap Feedback - Images do not display on my profile page for either contributions or bookmarks](https://usersnappublic.s3.amazonaws.com/2019-05-16/16-01/7a16e595-a7e5-4f3d-9222-b0a20273e423.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/16-01/5a56a934-0570-423d-a192-fdeafeb9fc56.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/user/25?selectedCategory=bookmarks](https://ppedia-stage.herokuapp.com/user/25?selectedCategory=bookmarks)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1089

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
duplicate
