### ISSUE TITLE
Usersnap Feedback - Is the Gravatar app necessary? Seems as though it adds an unnecessary step [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#562]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Is the Gravatar app necessary? Seems as though it adds an unnecessary step  given that most people are used to simply uploading an image from their device
[Open #265 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/265)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/16-08/4bf72110-72f7-4508-a9da-4e81f586abfb.png'>![Usersnap Feedback - Is the Gravatar app necessary? Seems as though it adds an unnecessary step (...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/16-08/ec13889e-8a6a-470d-946a-6392af2a774d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/16-08/4bf72110-72f7-4508-a9da-4e81f586abfb.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/user/25/edit](https://ppedia-stage.herokuapp.com/user/25/edit)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1089

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully I think we all agree Gravatar is less than ideal. It's merely a placeholder so we don't have to build something custom just yet. It will  eventually be replaced but better than nothing for now.
