### ISSUE TITLE
Usersnap Feedback - MOBILE: heading 2 and heading 3 are basically the same size

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#568]
**Sender**: scottowenfletcher@gmail.com
**Comment**: MOBILE: heading 2 and heading 3 are basically the same size
[Open #271 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/271)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/17-22/224c1025-d293-4265-b8d1-f985febff13e.png'>![Usersnap Feedback - MOBILE: heading 2 and heading 3 are basically the same size](https://usersnappublic.s3.amazonaws.com/2019-05-16/17-22/e4c2e723-b245-47a0-a58f-1bb48ae0bab5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/17-22/224c1025-d293-4265-b8d1-f985febff13e.png'>Download original image</a>

**Browser**: Chrome 74 (Android 9)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5166](https://ppedia-stage.herokuapp.com/case/5166)
**Screen size**: 412 x 846 **Browser size**: 442 x 447

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Verified. I changed the second heading in the narrative to H2 from H3. It became larger, correctly, in the edit view, but the change didn't publish. It only removed the space between the first two headings (which it didn't in the edit view)

![image](https://user-images.githubusercontent.com/13560530/57873929-50899500-77c4-11e9-9a41-eb0a81d87641.png)
