### ISSUE TITLE
Usersnap Feedback - hitting 'edit' when not signed in should  1. open sign-in pop-up 2. take y[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#577]
**Sender**: scottowenfletcher@gmail.com
**Comment**: hitting 'edit' when not signed in should 
1. open sign-in pop-up
2. take you to the editing form

right now it
1. signs you in to the last account to use the site on this computer (no prompt)
2. loads the reader view again (then I have to hit 'edit' again)
[Open #280 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/280)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/18-22/5ac605ea-d226-4603-bc1a-934413f23128.png'>![Usersnap Feedback - hitting 'edit' when not signed in should  1. open sign-in pop-up 2. take y(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/18-22/a7ff3a65-c95a-471f-9907-c518edee1ca2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/18-22/5ac605ea-d226-4603-bc1a-934413f23128.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/organization/5805](https://ppedia-stage.herokuapp.com/organization/5805)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
i think this is related to the login session getting timed out, so it would login again with the user session stored in the browser, so it didn't require going to the signin form again. i made a change that will hopefully fix this. @scottofletcher let me know if you are still seeing this issue. thx!

**Comment by scottofletcher** [comment]
@ascott just tried it again and I get the same result. I'm not signed in, I press the red pen icon, and my screen reloads with me logged in but still on reader view (and no sign-in pop-up)

**Comment by ascott** [comment]
@scottofletcher now that you are logged in again, my theory is that is shouldn't log you/time you out again, unless you go through the signout link. if this is true then you shouldn't see this happen again. i haven't see it happen again, but we'll see.

**Comment by scottofletcher** [comment]
ok, thanks! But I'm still wondering if the same thing will happen for first-time users. they should be able to click the edit button (or quick submit), have the sign-up/log-in screen pop-up, sign-in/log-in, and then be taken directly to their desired destination (instead of reloading the same screen they were on)

**Comment by ascott** [comment]
no, with this change once a user is logged in, it shouldn't time them out if their computer goes to sleep and they come back to the page.

**Comment by scottofletcher** [comment]
right, I get that, but what about for new users? one's that have never signed up/in before?

**Comment by ascott** [comment]
yeah, for a new user, they will sign in, and won't be signed-out/timedout, so they won't run into the bug described initially.
