### ISSUE TITLE
Usersnap Feedback - Picture uploaded sideways

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#579]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Picture uploaded sideways
[Open #281 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/281)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/18-23/28177d64-09ac-4cdd-83eb-a2142792dd17.png'>![Usersnap Feedback - Picture uploaded sideways](https://usersnappublic.s3.amazonaws.com/2019-05-16/18-23/979fd48c-e97d-47cb-8dee-575eb301c9fe.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/18-23/28177d64-09ac-4cdd-83eb-a2142792dd17.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/organization/5805/edit](https://ppedia-stage.herokuapp.com/organization/5805/edit)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Sometimes this happens with images from phones. Don't think this is a bug. Images were uploading correctly for me. Closing for now.
