### ISSUE TITLE
Usersnap Feedback - Clicked the participedia logo on the main nav bar after recieving last err[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#58]
**Sender**: jesi.carson@gmail.com
**Comment**: Clicked the participedia logo on the main nav bar after recieving last error message while editing the ruelles vertes case. Instead of the refreshed homepage, I was sent back to my last search for oidp2017. 
- Jesi
[Open #72 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/72)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/17-36/bc583c31-7935-408b-aace-ca69723b6d43.png'>![Usersnap Feedback - Clicked the participedia logo on the main nav bar after recieving last err(...)](https://usersnappublic.s3.amazonaws.com/2017-06-18/17-36/b60b971f-d1a2-4f61-a269-a0a0922b326c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/17-36/bc583c31-7935-408b-aace-ca69723b6d43.png'>Download original image</a>

**Browser**: Chrome 58 (macOS Sierra)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1280 x 800 **Browser size**: 1276 x 632

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Will be tracked and fixed here: https://github.com/participedia/frontend/issues/577
