### ISSUE TITLE
Usersnap Feedback - Publish buttons not working again. Web dev console:  Loading failed for th[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#580]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Publish buttons not working again. Web dev console: 
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-132033152-2”. edit:6:1
Use of Mutation Events is deprecated. Use MutationObserver instead. edit-view.bundle.js:8129:10
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]
edit-view.bundle.js:18189:24
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]
[Open #282 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/282)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/18-25/6928f09b-bede-4c51-9c8a-ed29508aaef3.png'>![Usersnap Feedback - Publish buttons not working again. Web dev console:  Loading failed for th(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/18-25/ba50fc98-60bc-45ed-8a78-89461a1aa3d3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/18-25/6928f09b-bede-4c51-9c8a-ed29508aaef3.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/organization/5805/edit](https://ppedia-stage.herokuapp.com/organization/5805/edit)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 501

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
@ascott @jesicarson 
it appears that I can't add images to organization entries - anyone else have that problem?

**Comment by ascott** [comment]
@scottofletcher i tested this on FF66/windows10 today and wasn't able to reproduce. I was able to upload an image as expected. Could you try deactivating any browser plugins/extensions and trying again? Sometimes those can cause issues...

**Comment by scottofletcher** [comment]
@ascott just disabled all my plugins, extensions, addons, etc. and still no dice. I'll send a usersnap now

**Comment by scottofletcher** [comment]
See #618
