### ISSUE TITLE
Usersnap Feedback - Publish buttons in the wrong place. See design guidelines. Should be ancho[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#581]
**Sender**: jesi.carson@gmail.com
**Comment**: Publish buttons in the wrong place. See design guidelines. Should be anchored to centre column, not far right. Same on reader. I'll post the specs here.
[Open #283 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/283)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/18-30/acc7e1d6-bef6-420e-83a5-67368fdec9b0.png'>![Usersnap Feedback - Publish buttons in the wrong place. See design guidelines. Should be ancho(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/18-30/d87f7def-f864-4040-9791-b0cfa6d05ec8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/18-30/acc7e1d6-bef6-420e-83a5-67368fdec9b0.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [http://ppedia-stage.herokuapp.com/case/new?full=1](http://ppedia-stage.herokuapp.com/case/new?full=1)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
From guidelines:

![Screen Shot 2019-05-16 at 9 28 19 AM](https://user-images.githubusercontent.com/13560530/57871053-57f97000-77bd-11e9-8942-2a4bff80f008.png)

![Screen Shot 2019-05-16 at 9 29 42 AM](https://user-images.githubusercontent.com/13560530/57871054-57f97000-77bd-11e9-85a6-bb2a7b7d463e.png)

**Comment by jesicarson** [comment]
@ascott here are the correct icons as well, in an [.ai file](https://drive.google.com/open?id=1dIMJOTQZLBas6TPZjoBiJs3tNu0sOxma).
