### ISSUE TITLE
Usersnap Feedback - METHOD: 'Complexity' field/values missing from sidebar data (I selected 'v[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#588]
**Sender**: scottowenfletcher@gmail.com
**Comment**: METHOD: 'Complexity' field/values missing from sidebar data (I selected 'very low')
[Open #290 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/290)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/18-45/300baeb5-aeab-4bd5-b9ea-41ed1e9dfafa.png'>![Usersnap Feedback - METHOD: 'Complexity' field/values missing from sidebar data (I selected 'v(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/18-45/d441e084-8187-4988-b910-9da496ec24ab.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/18-45/300baeb5-aeab-4bd5-b9ea-41ed1e9dfafa.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/method/5802](https://ppedia-stage.herokuapp.com/method/5802)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
duplicate
