### ISSUE TITLE
Usersnap Feedback - It keeps bringing me to this screen when I click either of the page naviga[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#59]
**Sender**: scottowenfletcher@gmail.com
**Comment**: It keeps bringing me to this screen when I click either of the page navigation "</>" buttons to go to the next page when browsing through cases. 
[Open #73 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/73)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/17-48/7ad074d1-e9a2-4490-839e-62eb165f98ef.png'>![Usersnap Feedback - It keeps bringing me to this screen when I click either of the page naviga(...)](https://usersnappublic.s3.amazonaws.com/2017-06-18/17-48/4b665a15-781c-4278-8c17-589a46de1d90.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/17-48/7ad074d1-e9a2-4490-839e-62eb165f98ef.png'>Download original image</a>

**Browser**: Chrome 58 (Windows 10)
**Referer**: [https://participedia.xyz/new?page=3](https://participedia.xyz/new?page=3)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 590

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Will be tracked and fixed here: https://github.com/participedia/frontend/issues/556
