### ISSUE TITLE
Usersnap Feedback - Mobile - scrolling is difficult on help and contact menu, it scrolls the s[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#592]
**Sender**: jesi.carson@gmail.com
**Comment**: Mobile - scrolling is difficult on help and contact menu, it scrolls the screen behind it. Should be a full modal on mobile.
[Open #294 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/294)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/19-10/64020146-e45f-409a-b9b6-a63a6e844983.png'>![Usersnap Feedback - Mobile - scrolling is difficult on help and contact menu, it scrolls the s(...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/19-10/200f4761-7034-4f2c-8a51-d93f14ff9359.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/19-10/64020146-e45f-409a-b9b6-a63a6e844983.png'>Download original image</a>

**Browser**: Safari 12 (iOS)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
duplicate
