### ISSUE TITLE
Usersnap Feedback - It seems as though users should be able to select the + to add something, [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#594]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: It seems as though users should be able to select the + to add something, and not only select the words "click ..."
[Open #296 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/296)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/19-15/f6c3eed4-0844-4d48-8196-e75b52d63da9.png'>![Usersnap Feedback - It seems as though users should be able to select the + to add something, (...)](https://usersnappublic.s3.amazonaws.com/2019-05-16/19-15/7deca7cc-735b-4d2d-a4a1-9011aa491555.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-16/19-15/f6c3eed4-0844-4d48-8196-e75b52d63da9.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/new](https://ppedia-stage.herokuapp.com/case/new)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1040

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
duplicate
