### ISSUE TITLE
Usersnap Feedback - When I copy and paste something into the narrative box, it transports me a[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#60]
**Sender**: scottowenfletcher@gmail.com
**Comment**: When I copy and paste something into the narrative box, it transports me all the way to the top of the screen. (I do this a lot when I'm editing a case - especially when authors don't use the correct headings and I have to move stuff from different sections)
[Open #74 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/74)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/17-56/f4e424d7-b9b3-49b0-9ed5-315e0e3473be.png'>![Usersnap Feedback - When I copy and paste something into the narrative box, it transports me a(...)](https://usersnappublic.s3.amazonaws.com/2017-06-18/17-56/7bbdbdf8-04d1-438c-9a0f-ef92fed31eff.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/17-56/f4e424d7-b9b3-49b0-9ed5-315e0e3473be.png'>Download original image</a>

**Browser**: Chrome 58 (Windows 10)
**Referer**: [https://participedia.xyz/case/4553/edit](https://participedia.xyz/case/4553/edit)
**Screen size**: 1280 x 720 **Browser size**: 1707 x 787

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by andreadelrio** [comment]
Covered with new body editor.
