### ISSUE TITLE
Updates/Edits to Fixed/Static Text

### ISSUE THREAD

**Issue by scottofletcher** [participedia/usersnaps#610]
All files stored in this folder: https://drive.google.com/drive/folders/1WhUGf-nWyt1DyeVIz8k4oUqeIMdQoP14

- [x] Help & Contact: https://docs.google.com/document/d/1D9Z6m4oDaoNo_CBH3UH6Ma1icqAqBN7BZtse6M2zZEU/edit#heading=h.z6ym77ilsrv5 --> NOTE: changes were made directly to the text, not using the suggestion function. Please review comments

- [x] About: https://drive.google.com/open?id=1_UNn7fSulGkjlNI8a6KeLYDKW6QTMFf0aBa22NUVSDo

- [x] Research: https://drive.google.com/open?id=1E6LzFZJodUIZH7DKxlha_05N1__DOf8_v-iD5JQPPIg --> NOTE: Please review comments

- [x] COMPLETED WAITING FOR @ascott: Terms of Use: https://docs.google.com/document/d/1SlaCscNaT27ESZw8ng4QBpfA6Fcis89mJA9RtR26umw/edit#heading=h.pe4s7hk6cv0m

**Comment by jesicarson** [comment]
Adding P1 label to this with the caveat that the text needs to be reviewed, and also that we're considering building a full on help page so that the content can be indexed by google (#774)

**Comment by ascott** [comment]
@jesicarson @scottofletcher have these content changes been reviewed/signed-off on?

**Comment by scottofletcher** [comment]
not sure - I see that some of my comments still haven't been addressed (eg. the awkward sentence "Focus on Participedia content and its connection to relevant theoretical material" in the Teach Page copy)

**Comment by scottofletcher** [comment]
yeah, looks like they haven't been looked through yet - for some I used the 'suggesting' feature, but nothing's been signed-off on.

**Comment by jesicarson** [comment]
not ready to go yet @ascott lets hold off for now thx

**Comment by ascott** [comment]
going to remove the p1 label until this is ready to go.

**Comment by scottofletcher** [comment]
sounds good, just waiting for Jesi and Pat, right?

**Comment by jesicarson** [comment]
@scottofletcher TOU is reviewed, all comments resolved. Good to go on Phraseapp!

working on the rest of the pages now. will flag here when good to go.

**Comment by jesicarson** [comment]
@scottofletcher help and contact is good to go, aside from a few comments that @ascott is tagged in related to missing some strings in phraseapp. Thanks!

**Comment by jesicarson** [comment]
@scottofletcher about page is good to go into phraseapp.

**Comment by jesicarson** [comment]
@research page good to go. @ascott can we add a button? it doesn't have to be in the drop down, but maybe below the closed accordion menu? same button as the TLRC to browse the dataverse data repo.

**Comment by scottofletcher** [comment]
Help & contact completed

**Comment by scottofletcher** [comment]
About page is done

**Comment by scottofletcher** [comment]
Research page is done! @ascott here is a list of links to pages that need hyperlinks. I included the links needed as comments: https://docs.google.com/document/d/1Bd2N07FDcIMS-E4xw0cgxRpNvmbyZz3grLr1gUlqkU0/edit# The doc is saved in the same folder as the other copy edits: https://drive.google.com/drive/folders/1WhUGf-nWyt1DyeVIz8k4oUqeIMdQoP14

**Comment by scottofletcher** [comment]
> @scottofletcher TOU is reviewed, all comments resolved. Good to go on Phraseapp!
> 
> working on the rest of the pages now. will flag here when good to go.

Handing this off to @ascott since TOU isn't in PhraseApp

**Comment by ascott** [comment]
> @research page good to go. @ascott can we add a button? it doesn't have to be in the drop down, but maybe below the closed accordion menu? same button as the TLRC to browse the dataverse data repo.

@jesicarson yes, will do
