### ISSUE TITLE
Usersnap Feedback - Creative Commons License is too small - it looks like a copyright symbol. [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#611]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Creative Commons License is too small - it looks like a copyright symbol. We should make this more obvious, like this website: https://civictech.guide/ or this website: https://catalog.crowd.law/index.html
[Open #312 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/312)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-17/00-31/b0b124a6-2660-4b17-b185-5a3495cca8f8.png'>![Usersnap Feedback - Creative Commons License is too small - it looks like a copyright symbol. (...)](https://usersnappublic.s3.amazonaws.com/2019-05-17/00-31/19b3b4d5-9a23-4514-add1-6675b57de684.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-17/00-31/b0b124a6-2660-4b17-b185-5a3495cca8f8.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/](https://ppedia-stage.herokuapp.com/)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
We could even put the CC License logo on the footer maybe? https://creativecommons.org/choose/results-one?license_code=by-nc-sa&amp;jurisdiction=&amp;version=3.0&amp;lang=en

**Comment by scottofletcher** [comment]
The Conversation just updated their CC logo and 'republish this article' notice. I'm not saying we have to go this far, but maybe when we finish the 'cite this entry' tool, we can put something like this and have the option to 'reuse' or 'republish' alongside 'cite' (with the CC license logo of course)
![image](https://user-images.githubusercontent.com/29512491/64727390-995d0c00-d48d-11e9-98f1-eca481d0518d.png)

**Comment by jesicarson** [comment]
I like that, what happens when you click the republish button?

**Comment by scottofletcher** [comment]
it comes up with basic and html versions of the article and instructions on crediting

**Comment by jesicarson** [comment]
cool thanks.

**Comment by jesicarson** [comment]
ok so for the footer at least we have some options... in all cases below, ive removed the "Participedia 2019" part, which is debatable, but doesn't really matter that much probably. 

option 1. shown on desktop. uses the (kinda ugly) specific cc license logo. 
![Footer Desktop 1280x1024](https://user-images.githubusercontent.com/13560530/64741660-2b750c80-d4ae-11e9-8723-0118f412fa3d.jpg)

option 2. shown on larger mobile. uses the (cleaner) general cc logo (which we can link to our specific license)
![Footer Mobile 640x1136](https://user-images.githubusercontent.com/13560530/64741662-2b750c80-d4ae-11e9-9d2d-ffc7f765af25.jpg)

option 3. shown on smaller mobile. adds the cc heart icon to our list of social icons. (in this case we could add the cc Participedia 2019 back in if we wanted to)
![Footer Mobile 480x800](https://user-images.githubusercontent.com/13560530/64741661-2b750c80-d4ae-11e9-8a69-ca0416008f9e.jpg)

**Comment by scottofletcher** [comment]
I like option 2! I've never seen that heart thing before and I doubt many people would recognize it. The 'clean' CC logo fits into our overall aesthetic, and I agree that linking to our specific license is a good idea (and what most other sites do too).

**Comment by jesicarson** [comment]
Cool im into that as well. 
@ascott when you have a moment please swap out the current "cc Participedia 2019" in the footer with the [creative commons logo](https://drive.google.com/open?id=1eOFn4sa55KMhby5K4snM63GQxBLRG3sn) (in white), 20px tall x 86px wide. Also please make that entire logo a clickable link to the specific license - https://creativecommons.org/licenses/by-nc-sa/3.0/. Thanks!
![Screen Shot 2019-09-11 at 5 27 29 PM](https://user-images.githubusercontent.com/13560530/64744727-c8897280-d4b9-11e9-9d31-ff5706f2e0af.png)

**Comment by ascott** [comment]
@jesicarson will do! 👍
