### ISSUE TITLE
No 'Feedback' button on Windows Chrome

### ISSUE THREAD

**Issue by scottofletcher** [participedia/usersnaps#612]
Google Chrome Version 74.0.3729.157 (Official Build) (64-bit)
PC: Windows 10 Home 64-bit operative system

Screenshots: 
<img width="956" alt="Screenshot 2019-05-16 15 50 47" src="https://user-images.githubusercontent.com/29512491/57892113-a4ab6e00-77f2-11e9-9555-02a7fa757a87.png">
<img width="960" alt="Screenshot 2019-05-16 15 50 32" src="https://user-images.githubusercontent.com/29512491/57892114-a4ab6e00-77f2-11e9-8f7b-6c45d4784561.png">

**Comment by ascott** [comment]
very strange. when i use windows 10/chrome 74 i see the feedback tab and was able to send a snap. looks like pat also used it from win10/chrome74 in this snap: https://github.com/participedia/usersnaps/issues/607

**Comment by scottofletcher** [comment]
weird, I'm still not getting a feedback button on chrome even w/all my extensions/plugins etc disabled

**Comment by ascott** [comment]
is there anything different about your windows 10 install? it is pretty weird that you are seeing weird things in chrome and firefox that are not reproducible.

**Comment by jesicarson** [comment]
@scottofletcher have you tried the best IT advice ever: restarting your computer?

**Comment by scottofletcher** [comment]
ok, just forget it, if it's not reproducible, then it's clearly just a problem w/my comp
