### ISSUE TITLE
Usersnap Feedback - Failure on test of organizations upload

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#62]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Failure on test of organizations upload
[Open #76 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/76)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/18-02/0ec6d8a6-ed4a-4a51-b885-70dfcc8b1f45.png'>![Usersnap Feedback - Failure on test of organizations upload](https://usersnappublic.s3.amazonaws.com/2017-06-18/18-02/2770ac44-e3c2-40c2-a9b9-8fb0900751c8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/18-02/0ec6d8a6-ed4a-4a51-b885-70dfcc8b1f45.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/new/organization](https://participedia.xyz/new/organization)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
I believe this was a problem we were having with login validation which is fixed now.
