### ISSUE TITLE
Usersnap Feedback - Chrome-Desktop: Geo Scope, Issue Polar, and Issue Technical Complexity lab[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#621]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Chrome-Desktop: Geo Scope, Issue Polar, and Issue Technical Complexity labels are all incorrect.  Issue Interdependency isn't part of our data  model -- it's a leftover from .net
[Open #327 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/327)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-17/21-15/085a430c-bb26-4f5f-8e75-c38dd99f37b5.png'>![Usersnap Feedback - Chrome-Desktop: Geo Scope, Issue Polar, and Issue Technical Complexity lab(...)](https://usersnappublic.s3.amazonaws.com/2019-05-17/21-15/46d1b54c-ddf4-4fc5-9705-e89fce344083.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-17/21-15/085a430c-bb26-4f5f-8e75-c38dd99f37b5.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/method/5764](https://participedia.xyz/method/5764)
**Screen size**: 1920 x 1200 **Browser size**: 1536 x 871

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@plscully this is .xyz (with old model/data) and we are still testing on https://ppedia-stage.herokuapp.com now

**Comment by plscully** [comment]
> @plscully this is .xyz (with old model/data) and we are still testing on https://ppedia-stage.herokuapp.com now

@ascott Sorry! That was a dopey mistake on my part!
