### ISSUE TITLE
Usersnap Feedback - Are admins able to hide/feature content from mobile? If so, toggles are missing.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#623]
**Sender**: jesi.carson@gmail.com
**Comment**: Are admins able to hide/feature content from mobile? If so, toggles are missing.
[Open #322 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/322)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-21/18-19/d927940c-6774-436b-a586-a48473b552e4.png'>![Usersnap Feedback - Are admins able to hide/feature content from mobile? If so, toggles are missing.](https://usersnappublic.s3.amazonaws.com/2019-05-21/18-19/e0ddf05a-7021-4b86-a4a8-464426933863.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-21/18-19/d927940c-6774-436b-a586-a48473b552e4.png'>Download original image</a>

**Browser**: Safari 12 (iOS)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5825](https://ppedia-stage.herokuapp.com/case/5825)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson this isn't implemented yet on desktop or mobile.

**Comment by jesicarson** [comment]
@ascott we need to be able to feature and hide content. This should be prioritized shortly after faceted search and the map overlay, but we can launch without it if necessary. "hide" will be particularly important for people creating test content on xyz once we push staging there. "featured" will be useful for themed campaigns after launch.
