### ISSUE TITLE
Usersnap Feedback - Mobile - high priority - add floating red circle (+) submit button to homepage

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#624]
**Sender**: jesi.carson@gmail.com
**Comment**: Mobile - high priority - add floating red circle (+) submit button to homepage
[Open #323 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/323)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-21/18-21/b859d485-582a-4af4-8aab-49e28bf3d45e.png'>![Usersnap Feedback - Mobile - high priority - add floating red circle (+) submit button to homepage](https://usersnappublic.s3.amazonaws.com/2019-05-21/18-21/4dc0077b-b5f5-4550-af3b-b75dd08862c7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-21/18-21/b859d485-582a-4af4-8aab-49e28bf3d45e.png'>Download original image</a>

**Browser**: Safari 12 (iOS)
**Referer**: [https://ppedia-stage.herokuapp.com/](https://ppedia-stage.herokuapp.com/)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson do you have a mock up for this? or should it be the same size/position as the publish button on the edit pages? but with a `+` that links to the quick submit page?

**Comment by jesicarson** [comment]
![Screen Shot 2019-05-22 at 1 27 20 PM](https://user-images.githubusercontent.com/13560530/58206363-605a1b00-7c95-11e9-90dd-ee26356a2a54.png)

this floating button is on mobile only because we lose the quick submit button from the header and we want submit to always be visible.

**Comment by jesicarson** [comment]
ai file [here](https://drive.google.com/open?id=1dIMJOTQZLBas6TPZjoBiJs3tNu0sOxma)
@ascott

**Comment by jesicarson** [comment]
see also: https://github.com/participedia/usersnaps/issues/388
