### ISSUE TITLE
Usersnap Feedback - I've been clicking the picture icon in the narrative field - while it allo[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#63]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I've been clicking the picture icon in the narrative field - while it allows me to select a picture from my files, it doesn't actually upload that picture into the text box
[Open #77 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/77)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/18-03/c2d7e15e-ea39-417a-a92d-5f3d29d5e884.png'>![Usersnap Feedback - I've been clicking the picture icon in the narrative field - while it allo(...)](https://usersnappublic.s3.amazonaws.com/2017-06-18/18-03/34d2554d-85da-449a-b27e-2e67ff934e4b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/18-03/c2d7e15e-ea39-417a-a92d-5f3d29d5e884.png'>Download original image</a>

**Browser**: Chrome 58 (Windows 10)
**Referer**: [https://participedia.xyz/method/4597/edit](https://participedia.xyz/method/4597/edit)
**Screen size**: 1280 x 720 **Browser size**: 1600 x 737

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher can you clarify this bug with a better screenshot? Sorry, looks like usersnap is not capturing things accurately sometimes.

**Comment by scottofletcher** [comment]
This was eons ago, I think it's fixed
