### ISSUE TITLE
Usersnap Feedback - Admin tools hide entry & set as featured - will I get those tools back in [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#630]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Admin tools hide entry & set as featured - will I get those tools back in time for launch?
[Open #329 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/329)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-21/19-13/a81b5242-c6f9-44b0-bb01-73638d3a2d6e.png'>![Usersnap Feedback - Admin tools hide entry & set as featured - will I get those tools back in (...)](https://usersnappublic.s3.amazonaws.com/2019-05-21/19-13/0e3702d5-c301-4fef-996c-35adc1d9038e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-21/19-13/a81b5242-c6f9-44b0-bb01-73638d3a2d6e.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/organization/5805](https://ppedia-stage.herokuapp.com/organization/5805)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher @jesicarson this is a pretty quick change on the frontend, and i just confirmed that the backend is done for this already. how does this look for now? 
<img width="1280" alt="Screenshot 2019-05-21 19 51 49" src="https://user-images.githubusercontent.com/130878/58144115-09573600-7c02-11e9-86c1-660fb48ea298.png">

**Comment by scottofletcher** [comment]
is it only available from the edit screen? the current site has the tools right on the narrative/reader view. not a huge issue if they are

**Comment by ascott** [comment]
yes, it will only be available from the edit screen. @jesicarson does this look ok to you? added a PR for this change here: https://github.com/participedia/api/pull/614

**Comment by jesicarson** [comment]
accessing this from edit screen is fine for now. go ahead with your design as-is @ascott. great to have this, thanks!!
