### ISSUE TITLE
Usersnap Feedback - We won't be able to link to these when we archive the Drupal site

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#634]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: We won't be able to link to these when we archive the Drupal site
[Open #333 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/333)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/00-33/7da1165d-596e-4d7e-9560-02d397895391.png'>![Usersnap Feedback - We won't be able to link to these when we archive the Drupal site](https://usersnappublic.s3.amazonaws.com/2019-05-22/00-33/d87693fd-ac05-4117-b806-5f221cfc6b88.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/00-33/7da1165d-596e-4d7e-9560-02d397895391.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/teaching](https://ppedia-stage.herokuapp.com/teaching)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1089

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher @jesicarson  do you have alternative links that we should update these with?

**Comment by scottofletcher** [comment]
@ascott I think these are supposed to be linked to Google Docs or PDFs - @jesicarson do I have that right? Here's the file (we can separate it into two): https://docs.google.com/document/d/1qnDZmIukizEIU6SH9KWdkh1DnI-o17KoRMsi9Vz-QDo/edit

**Comment by jesicarson** [comment]
Thanks for the doc @scottofletcher , we should update the copy on this page as we're not linking to any blog posts. Paolo suggested suggest removing the drop down entirely here, and I agree. Let's do that and, please use this copy @ascott :

Teaching 
**Participedia in the Classroom**
Writing or editing articles for Participedia can be a great assignment for courses that deal with political participation, democratic innovation, or deliberation.
In the course of selecting, researching, and writing up a case, method, or organization, students will learn about the substance of participation in varied contexts. Students may also find it rewarding to have their work showcased on Participedia. [Here is a sample assignment and grading rubric](https://docs.google.com/document/d/1qnDZmIukizEIU6SH9KWdkh1DnI-o17KoRMsi9Vz-QDo/edit?usp=sharing) designed for an upper-division undergraduate course, this can be adapted to suit either graduate seminars or introductory courses.  

**Teaching & Learning Resource Centre**
Coming soon! Like cases, methods and organizations, anyone will be able to publish teaching and learning resources to share with the Participedia community.
Currently, Participedia is collecting tools for educators and learners, including course syllabi, sample assignments and more, to enhance course offerings about public participation as well as participatory teaching practices in other subjects. These resources can be applied in early to post-secondary education settings, as well as professional development for NGOs, civil society organizations, and practitioners.

These resources can be used to:

Improve students’ knowledge of innovations in participatory democracy, while also improving their research and writing skills by publishing cases, methods and organizations on Participedia;
Focus on Participedia content and its connection to relevant theoretical material;
Prepare students to be organizers and researchers of democratic innovations, and;
Shape pedagogy and classroom culture to be more participatory.

**Comment by jesicarson** [comment]
Only the Participedia in the Classroom section changes, the Teaching & Learning section can stay as is.

**Comment by scottofletcher** [comment]
yes, I also suggested getting rid of the accordion (see #542). also, @jesicarson is it ok if we use the edited version of the copy I created? it's all here: https://github.com/participedia/usersnaps/issues/610.

**Comment by jesicarson** [comment]
Sure. @ascott Here's the [new teaching page text](https://docs.google.com/document/d/1trJG6BUHqb2Cdb0ZhO5C2F7X8lvvmCzOc6v-b5gWw7A/edit#) (no drop downs, same main sections)
