### ISSUE TITLE
Usersnap Feedback - After trying to bookmark an article a few times and check on my profile if [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#637]
**Sender**: lucyjparry@gmail.com
**Comment**: After trying to bookmark an article a few times and check on my profile if it had worked, something went wrong and the homepage looked like this - blank. Had to re-open the site in another tab, refresh didn't work
[Open #336 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/336)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/12-31/c509e11b-69e6-4eac-8f45-4ab12a7810b3.png'>![Usersnap Feedback - After trying to bookmark an article a few times and check on my profile if (...)](https://usersnappublic.s3.amazonaws.com/2019-05-22/12-31/2935fe25-b89a-46cb-af11-0a14346fc7e7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/12-31/c509e11b-69e6-4eac-8f45-4ab12a7810b3.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/?selectedCategory=bookmarks](https://ppedia-stage.herokuapp.com/?selectedCategory=bookmarks)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 625

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
I think this is fixed already. We can reopen if not.
