### ISSUE TITLE
Usersnap Feedback - I can't work out how to change the profile image. Created the gravatar acc[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#638]
**Sender**: lucyjparry@gmail.com
**Comment**: I can't work out how to change the profile image. Created the gravatar account thing but still not obvious to me how to add the image to Participedia profile.
[Open #337 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/337)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/12-41/2f961258-d82e-405a-80ae-fcec08912bac.png'>![Usersnap Feedback - I can't work out how to change the profile image. Created the gravatar acc(...)](https://usersnappublic.s3.amazonaws.com/2019-05-22/12-41/10869c3b-d78c-435f-b75a-a89eec496ca0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/12-41/2f961258-d82e-405a-80ae-fcec08912bac.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/user/134860/edit](https://ppedia-stage.herokuapp.com/user/134860/edit)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 625

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Good feedback. Noted. Duplicate.
