### ISSUE TITLE
Usersnap Feedback - I entered this method yesterday using the quick submit feature - now that [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#64]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I entered this method yesterday using the quick submit feature - now that I have time to 'flesh it out', I should be able to see all the section headings in the narrative field (otherwise users are going to edit quick submits without using the proper headings which will not only make things messy, but it will difficult to derive qualitative data from the narrative)
[Open #78 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/78)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/18-10/295f662f-2df9-475e-8273-5159f02ee25b.png'>![Usersnap Feedback - I entered this method yesterday using the quick submit feature - now that (...)](https://usersnappublic.s3.amazonaws.com/2017-06-18/18-10/91b7126d-9ef0-440e-8a4e-cc4bf1ca900e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/18-10/295f662f-2df9-475e-8273-5159f02ee25b.png'>Download original image</a>

**Browser**: Chrome 58 (Windows 10)
**Referer**: [https://participedia.xyz/method/4569/edit](https://participedia.xyz/method/4569/edit)
**Screen size**: 1280 x 720 **Browser size**: 1600 x 737

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Hmm, can't replicate this - @scottofletcher can you provide a better screenshot or can we close this? Thx

**Comment by scottofletcher** [comment]
This was so long ago I have no idea what the heck I meant. Don't worry about it, methods is getting an overhaul anyways
