### ISSUE TITLE
Usersnap Feedback - Owners/Creators not included in sidebar data

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#640]
**Sender**: scottowenfletcher@gmail.com
[Open #339 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/339)
**Notes**:
 - (1) Owners/Creators not included in sidebar data

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/17-56/4fcdcee4-9ffe-4c8a-8213-dcc8005e0670.png'>![Usersnap Feedback - Owners/Creators not included in sidebar data](https://usersnappublic.s3.amazonaws.com/2019-05-22/17-56/ce1391a2-7f1a-4a44-ac3d-c1fd49e0f4c5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/17-56/4fcdcee4-9ffe-4c8a-8213-dcc8005e0670.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5830](https://ppedia-stage.herokuapp.com/case/5830)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
leave as is. closing
