### ISSUE TITLE
Usersnap Feedback - Cannot access calendar - have we changed the date entry format? It's actua[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#642]
**Sender**: scottowenfletcher@gmail.com
[Open #341 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/341)
**Notes**:
 - (1) Cannot access calendar - have we changed the date entry format? It's actually easier now that I can just plug in the numbers

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/18-10/3a062656-8de9-4303-9246-ee9f61efb64d.png'>![Usersnap Feedback - Cannot access calendar - have we changed the date entry format? It's actua(...)](https://usersnappublic.s3.amazonaws.com/2019-05-22/18-10/37dcc390-23ee-4404-8d41-150aa289672e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/18-10/3a062656-8de9-4303-9246-ee9f61efb64d.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5830/edit](https://ppedia-stage.herokuapp.com/case/5830/edit)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
we are currently using the native date input for this field. when you hover or focus the field an arrow appears on the right. 
<img width="609" alt="Screenshot 2019-05-23 13 43 59" src="https://user-images.githubusercontent.com/130878/58285102-f73fd980-7d60-11e9-8b6d-e598f676a16a.png">

when you click the arrow you get the date picker dropdown
<img width="648" alt="Screenshot 2019-05-23 13 44 09" src="https://user-images.githubusercontent.com/130878/58285109-fa3aca00-7d60-11e9-83d3-cfa119f547b5.png">

and you can also input the date directly with your keyboard. 

we will have to design and implement something custom if we want different functionality for this.

**Comment by jesicarson** [comment]
I think there’s a design backlog issue for this, but if not we should reopen. We definitely need to improve the UI.
