### ISSUE TITLE
Usersnap Feedback - Evaluation report docs and links missing owner/creator

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#650]
**Sender**: scottowenfletcher@gmail.com
[Open #349 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/349)
**Notes**:
 - (1) Evaluation report docs and links missing owner/creator

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/18-24/4efd51bc-efe8-469e-a9e0-b1262ea3dcad.png'>![Usersnap Feedback - Evaluation report docs and links missing owner/creator](https://usersnappublic.s3.amazonaws.com/2019-05-22/18-24/4bbf83bf-509a-4b1e-8726-d2174789a4e2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/18-24/4efd51bc-efe8-469e-a9e0-b1262ea3dcad.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5830](https://ppedia-stage.herokuapp.com/case/5830)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully @scottofletcher the decision on slack was to keep this as is. closing.

**Comment by scottofletcher** [comment]
yup, got that message late - sorry!

**Comment by scottofletcher** [comment]
I do want to say that the title+creator on the images looks really good - that's the main place we need to be careful about attributions/credits anyways
