### ISSUE TITLE
Usersnap Feedback - We need to allow people to finish the quick submit form and then hit 'do f[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#651]
**Sender**: scottowenfletcher@gmail.com
**Comment**: We need to allow people to finish the quick submit form and then hit 'do full version' without it wiping out everything they entered before launch.
[Open #350 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/350)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/18-26/1633d14d-cdd9-40bb-97ef-59b9b272d6da.png'>![Usersnap Feedback - We need to allow people to finish the quick submit form and then hit 'do f(...)](https://usersnappublic.s3.amazonaws.com/2019-05-22/18-26/f60a7f53-df73-467c-a1d5-2a191a933aea.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/18-26/1633d14d-cdd9-40bb-97ef-59b9b272d6da.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/5830/edit](https://ppedia-stage.herokuapp.com/case/5830/edit)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
doesn't necessarily have to be before launch, as there's a warning popup before changes are lost. Its not ideal but also not a deal breaker. it is definitely a high priority design change though.
