### ISSUE TITLE
Usersnap Feedback - staff and volunteer fields are not filled out in the edit form so should n[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#657]
**Sender**: scottowenfletcher@gmail.com
[Open #356 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/356)
**Notes**:
 - (1) staff and volunteer fields are not filled out in the edit form so should not have a value in the sidebar

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/19-07/8d7e2143-a825-41e6-b53c-dfa6b5e5e855.png'>![Usersnap Feedback - staff and volunteer fields are not filled out in the edit form so should n(...)](https://usersnappublic.s3.amazonaws.com/2019-05-22/19-07/ad49e7ce-2144-47c6-9648-bbe4877ebba0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/19-07/8d7e2143-a825-41e6-b53c-dfa6b5e5e855.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/61](https://ppedia-stage.herokuapp.com/case/61)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
In the edit form we are using checkboxes for these fields, so if the checkbox is left unchecked then we show that as a `no` value on the reader page, so we should probably change these fields so they are like the Legality field, with a Yes/No dropdown menu. thoughts? @scottofletcher @dethe @jesicarson 

<img width="573" alt="Screenshot 2019-05-24 14 32 22" src="https://user-images.githubusercontent.com/130878/58357744-d646b980-7e30-11e9-9b78-94dbf4d53a22.png">

**Comment by scottofletcher** [comment]
works for me!

**Comment by plscully** [comment]
Me too!

**Comment by dethe** [comment]
Implementation detail: Can we convert all the yes/nos to booleans and just display all booleans as yes/no in the UI?

**Comment by ascott** [comment]
@dethe i don't think we should convert all yes/no fields to booleans, because some yes/no fields also have a "Not Applicable" option (eg: the Facilitators field for cases). in terms of the front end, it would be ideal to treat the yes/no fields the same as other single select fields (eg: Scope of Influence field for cases), where we are just passing the key between server and client.

**Comment by ascott** [comment]
dethe and i discussed offline, and i'm going to build a select to handle these boolean fields on the frontend, so we don't save falsey values if the field hasn't been edited.

**Comment by jesicarson** [comment]
ok sounds good!

**Comment by scottofletcher** [comment]
awesome, thanks!
