### ISSUE TITLE
Usersnap Feedback - there should only be 3 (max) general issues selected. also the first one i[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#659]
**Sender**: scottowenfletcher@gmail.com
[Open #358 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/358)
**Notes**:
 - (1) there should only be 3 (max) general issues selected. also the first one in the list needs to be fixed (I assume it's supposed to be 'Education')

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/19-16/8c5909b9-4c2b-48a7-8879-eaa47d5b0975.png'>![Usersnap Feedback - there should only be 3 (max) general issues selected. also the first one i(...)](https://usersnappublic.s3.amazonaws.com/2019-05-22/19-16/ee905363-aeac-4362-aa38-1d4d380441df.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/19-16/8c5909b9-4c2b-48a7-8879-eaa47d5b0975.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/organization/200](https://ppedia-stage.herokuapp.com/organization/200)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher yes this is a bug to do with migrations, but as a work around this issue can be fixed manually by editing the field. just try to edit them as you find them. thanks!

**Comment by jesicarson** [comment]
@ascott the max 3 should be addressed

**Comment by ascott** [comment]
i'm not sure how this org got into this state exactly, but it's possible it had 4 saved before the migration to limiting it to 3? in any case the work around is to just save the org again and it will only save the 3 listed in the edit form.

<img width="544" alt="Screenshot 2019-05-23 16 56 11" src="https://user-images.githubusercontent.com/130878/58293752-aee1e500-7d7b-11e9-87f6-cfd4219dfd0f.png">
