### ISSUE TITLE
Usersnap Feedback - Other in the surveys should go last

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#66]
**Sender**: spadayale@gmail.com
**Comment**: Other in the surveys should go last
[Open #80 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/80)
**Notes**:
 - (1) Other should always be last and possibly bold

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-22/19-01/a30568e5-02a2-48a5-88d1-660643ff7ff5.png'>![Usersnap Feedback - Other in the surveys should go last](https://usersnappublic.s3.amazonaws.com/2017-06-22/19-01/1aacebaa-a255-4687-89a1-e8bea3890d6b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-22/19-01/a30568e5-02a2-48a5-88d1-660643ff7ff5.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 1536 x 864 **Browser size**: 1536 x 725

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Fixed in PR https://github.com/participedia/frontend/pull/606
