### ISSUE TITLE
Usersnap Feedback - is the media carousel supposed to be centred or right-aligned? would proba[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#660]
**Sender**: scottowenfletcher@gmail.com
**Comment**: is the media carousel supposed to be centred or right-aligned? would probably look better in the centre
[Open #359 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/359)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/19-16/c81e4365-c02a-40ce-a23b-357f24e9fbc6.png'>![Usersnap Feedback - is the media carousel supposed to be centred or right-aligned? would proba(...)](https://usersnappublic.s3.amazonaws.com/2019-05-22/19-16/5117f087-d381-4b89-bc3f-a1a0c3fd3b0b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/19-16/c81e4365-c02a-40ce-a23b-357f24e9fbc6.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/organization/200](https://ppedia-stage.herokuapp.com/organization/200)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
correct, it is supposed to be centered.
