### ISSUE TITLE
Usersnap Feedback - Newsletter name 'Participedia Today' makes it sound like a daily newslette[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#663]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Newsletter name 'Participedia Today' makes it sound like a daily newsletter. suggest changing it to something else. what about 'The Frontline of Participation' or just 'Participedia Community News'
[Open #362 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/362)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/19-30/0cbf69df-2e88-42fc-98c6-03c322750891.png'>![Usersnap Feedback - Newsletter name 'Participedia Today' makes it sound like a daily newslette(...)](https://usersnappublic.s3.amazonaws.com/2019-05-22/19-30/e08925bb-c22c-4a73-ba8f-287d3bfd31db.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/19-30/0cbf69df-2e88-42fc-98c6-03c322750891.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/#sidebar-menu](https://ppedia-stage.herokuapp.com/#sidebar-menu)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
agreed. updated https://mailchi.mp/participedia/subscribe
