### ISSUE TITLE
Usersnap Feedback - remove period at end of tagline at top of homepage (it's done everywhere else)

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#664]
**Sender**: scottowenfletcher@gmail.com
**Comment**: remove period at end of tagline at top of homepage (it's done everywhere else)
[Open #363 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/363)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/19-32/3fde1d7d-b928-4db7-a075-7ed4c3ba1d4e.png'>![Usersnap Feedback - remove period at end of tagline at top of homepage (it's done everywhere else)](https://usersnappublic.s3.amazonaws.com/2019-05-22/19-32/6b5fa471-997e-4461-b4f9-4df28dda7128.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-22/19-32/3fde1d7d-b928-4db7-a075-7ed4c3ba1d4e.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/](https://ppedia-stage.herokuapp.com/)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
This will be gone when we do the map overlay which will be this weekend/early next week. Closing.
