### ISSUE TITLE
Usersnap Feedback - High Pri Design Change (maybe a bug?) - need to be able to enter content i[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#668]
**Sender**: jesi.carson@gmail.com
**Comment**: High Pri Design Change (maybe a bug?) - need to be able to enter content in quick submit, and also click full version without publishing.
[Open #367 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/367)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-23/00-31/3ed04861-239c-4450-a275-5dda05a40b00.png'>![Usersnap Feedback - High Pri Design Change (maybe a bug?) - need to be able to enter content i(...)](https://usersnappublic.s3.amazonaws.com/2019-05-23/00-31/7d273c1e-050a-4a9a-a047-250a94c9a1cd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-23/00-31/3ed04861-239c-4450-a275-5dda05a40b00.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://ppedia-stage.herokuapp.com/case/new](https://ppedia-stage.herokuapp.com/case/new)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
duplicate
