### ISSUE TITLE
Usersnap Feedback - I tried to log in using an account I set up on Jun e 7 and received this e[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#67]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I tried to log in using an account I set up on Jun e 7 and received this error message
https://www.dropbox.com/s/vfzehrznemf7mf6/Screenshot%202017-07-17%2018.17.43.png?dl=0 
[Open #81 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/81)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-18/00-19/3d6fc22d-182c-47d7-b0d8-0af9f2ac222a.png'>![Usersnap Feedback - I tried to log in using an account I set up on Jun e 7 and received this e(...)](https://usersnappublic.s3.amazonaws.com/2017-07-18/00-19/5938e276-18c0-473d-af75-24468ac74575.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-18/00-19/3d6fc22d-182c-47d7-b0d8-0af9f2ac222a.png'>Download original image</a>

**Browser**: Chrome 59 (Windows 10)
**Referer**: [http://participedia.xyz/](http://participedia.xyz/)
**Screen size**: 1920 x 1200 **Browser size**: 2133 x 1215

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
This happens if you visit the site using http: vs. https:, we should automatically redirect to https: before you login. Will be tracked and fixed here: https://github.com/participedia/frontend/issues/580
