### ISSUE TITLE
Usersnap Feedback - Bookmark bug. Clicked the bookmark icon on MEHTOD Scott's Testing Round 2 [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#670]
**Sender**: jesi.carson@gmail.com
**Comment**: Bookmark bug. Clicked the bookmark icon on MEHTOD Scott's Testing Round 2 Method and the homepage reloaded without my bookmark activating (it didn't turn grey). I'm logged in. Tried twice. This is the url that was generated on bookmark click: https://ppedia-stage.herokuapp.com/#
[Open #369 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/369)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-24/20-00/b49a8eb3-fd78-483e-91fa-97f55b7d2df6.png'>![Usersnap Feedback - Bookmark bug. Clicked the bookmark icon on MEHTOD Scott's Testing Round 2 (...)](https://usersnappublic.s3.amazonaws.com/2019-05-24/20-00/4e787491-2087-4a27-9039-329f725dc9f2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-24/20-00/b49a8eb3-fd78-483e-91fa-97f55b7d2df6.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://ppedia-stage.herokuapp.com/#](https://ppedia-stage.herokuapp.com/#)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
this looks like maybe the JS wasn't loaded and executed yet when you clicked on the bookmark icon. I tried to reproduce, but wasn't able to. If you try again, are you still able to reproduce? I will try on a slower connection and see if that is maybe the issue...

**Comment by jesicarson** [comment]
yep its working now. closing.
