### ISSUE TITLE
Usersnap Feedback - There should be red pins on the map for featured cases

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#680]
**Sender**: jesi.carson@gmail.com
**Comment**: There should be red pins on the map for featured cases
[Open #379 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/379)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-26/18-10/e9721e42-64a3-4380-ac9d-6b1e4628b754.png'>![Usersnap Feedback - There should be red pins on the map for featured cases](https://usersnappublic.s3.amazonaws.com/2019-05-26/18-10/78f82ffc-b104-4044-8719-6fdee97bd946.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-26/18-10/e9721e42-64a3-4380-ac9d-6b1e4628b754.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://participedia.xyz/?selectedCategory=case](https://participedia.xyz/?selectedCategory=case)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
of the three featured cases, 2 of them don't have any location data, and 1 of them has some location data, but it does not have lat/lng data saved. only cases/orgs with lat/lng data are displayed on the map. there is a script that needs to be run on production data to populate lat/lng data for cases/orgs that have some location data, like city/state/country. https://github.com/participedia/api/issues/533

**Comment by jesicarson** [comment]
Ok thanks for taking care of that @ascott. I think this should be high pri, will add the P1 label.  

Also @scottofletcher will need to feature more than 3 entries so that more red pins show up on the map, he's now working on identifying featured content that ties in with the all team meeting. I think we should have a minimum of 8 cases and 8 orgs from different places in the world featured at all times so that the map is more interesting.

**Comment by jesicarson** [comment]
@ascott Actually, it doesn't have to be P1 if the work around would be to add lat/long data to the entry form. Is that something @scottofletcher can do?

**Comment by ascott** [comment]
there is a work around: by adding the location again using the location autocomplete in the edit form, the lat/lng will get added/saved correctly. however running this script should be pretty quick. i can test on staging first and if all goes well run on production. i would say it'll take me an hour including testing.

**Comment by jesicarson** [comment]
@ascott this can be placed at the bottom of the P1 pri list outlined in our slack PM

**Comment by scottofletcher** [comment]
@jesicarson I don't think it's a good idea to feature more than 4 entries at once because then the entire page will just be featured entries, even when people use the sort by function (when that's available). I was going to do 4 at a time, but rotate them more often

**Comment by ascott** [comment]
we could make the featured marker pins larger to make them more prominent on the map if we are going to have fewer featured items displayed.

**Comment by scottofletcher** [comment]
I like that idea! and would it be possible to have the little info cards pop-up on mouse-over for featured items or is that too complicated?

**Comment by jesicarson** [comment]
lets keep all the pins the same size please. 
and 4 featured of each type at a time should be fine, so the all tab will have at least 8 red pins (4 cases, 4 orgs).

**Comment by scottofletcher** [comment]
no I was going to do 4 entries max, ie. 2 cases and 2 orgs. otherwise, like I said, the whole page will be featured content and people are going to think the sort by function isn't working because the entries aren't changing

**Comment by jesicarson** [comment]
for launch could we do 4 (or more) of each since sort by isn't available? 

we also don't have to show featured first on sort by.

**Comment by scottofletcher** [comment]
ok, for launch, that's definitely do able

didn't we decide with dethe that we were going to keep featured content in place when users used the sort by filters but not when they did a keyword search or faceted search?

**Comment by jesicarson** [comment]
i think so, but we can change that when we return to implementing sort by. that was part of the reason we took it out - we need to better consider how it functions before launching it as a public feature.

**Comment by scottofletcher** [comment]
ok, good call, let's revisit
