### ISSUE TITLE
Usersnap Feedback - Floating publish button should be anchored to left edge of centre column, [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#684]
**Sender**: jesi.carson@gmail.com
**Comment**: Floating publish button should be anchored to left edge of centre column, not right column.
[Open #383 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/383)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-26/18-23/f0b26427-c26b-48f7-927c-68db3d95fd0e.png'>![Usersnap Feedback - Floating publish button should be anchored to left edge of centre column, (...)](https://usersnappublic.s3.amazonaws.com/2019-05-26/18-23/8a300b9a-c87c-407f-a561-2d2c2546208d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-26/18-23/f0b26427-c26b-48f7-927c-68db3d95fd0e.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://participedia.xyz/case/4279/edit](https://participedia.xyz/case/4279/edit)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
ref - guidelines screenshot in this issue: https://github.com/participedia/usersnaps/issues/581

**Comment by jesicarson** [comment]
https://github.com/participedia/usersnaps/issues/682
