### ISSUE TITLE
Usersnap Feedback - need to address the full version bug - should be able to load the full for[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#685]
**Sender**: jesi.carson@gmail.com
**Comment**: need to address the full version bug - should be able to load the full form without publishing the quick form first.
[Open #384 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/384)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-26/18-26/5d9e696f-dda9-4822-b8ef-3ed9b28d04a0.png'>![Usersnap Feedback - need to address the full version bug - should be able to load the full for(...)](https://usersnappublic.s3.amazonaws.com/2019-05-26/18-26/f896c26f-a06b-4a2f-a93e-9be7a4741b73.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-26/18-26/5d9e696f-dda9-4822-b8ef-3ed9b28d04a0.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://participedia.xyz/case/4279/edit](https://participedia.xyz/case/4279/edit)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
second this

**Comment by jesicarson** [comment]
This might not be a bug, but the way it was built - removing bug label. Alanna will need to confirm tho. Either way lets get it changed to load the full version.

**Comment by ascott** [comment]
yeah, confirmed. it's not a bug, but just the way it currently works. created a new issue to track the new functionality here: https://github.com/participedia/api/issues/627
