### ISSUE TITLE
Usersnap Feedback - Couple of things I noticed after quick submitting a test case: - error loa[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#69]
**Sender**: jesi.carson@gmail.com
**Comment**: Couple of things I noticed after quick submitting a test case:
- error loading map for canada
- relevant links should be actual links, not just text
- my vimeo url media that I added isn't showing up anywhere on the published case (although I think this might be being worked on already)
- also, i almost accidentally added a vimeo url under "relevant links" instead of "media" because a vimeo url popped up when I started typing a different url... this could cause confusion. maybe media should come before relevant links in the submit form?
[Open #83 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/83)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-34/4da8af01-95ae-4134-880d-0a609a54d7e0.png'>![Usersnap Feedback - Couple of things I noticed after quick submitting a test case: - error loa(...)](https://usersnappublic.s3.amazonaws.com/2017-08-04/19-34/5832b26a-335e-4b04-a9c9-ccc26d2277d2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-34/4da8af01-95ae-4134-880d-0a609a54d7e0.png'>Download original image</a>

**Browser**: Chrome 59 (macOS Sierra)
**Referer**: [https://participedia.xyz/case/4606](https://participedia.xyz/case/4606)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@dethe fix first three bullet points before user testing

**Comment by dethe** [comment]
@andreadelrio , I can look at the problems we're having with maps (Canada and Argentina I think are both having problems), but can you look at wrapping `relevant_links` with <a> tags? If you have any ideas about how to fix the submit dropping the last item in a list, that would be awesome, otherwise I'll dig into it.

**Comment by dethe** [comment]
Maps (Canada, Argentina, and others) seem to be loading now.

**Comment by dethe** [comment]
List issues will be handled here: https://github.com/participedia/frontend/issues/570
