### ISSUE TITLE
Usersnap Feedback - Delay of about 30-45 seconds b/w selecting the publish button and when the [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#692]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Delay of about 30-45 seconds b/w selecting the publish button and when the "publishing" message appears. And it has now been at least 10 minutes since this first appeared. I'm going to back out of it, but the work I did will be lost.
[Open #391 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/391)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-26/18-55/cf159c01-4f39-4f08-835d-d1d3f34125b7.png'>![Usersnap Feedback - Delay of about 30-45 seconds b/w selecting the publish button and when the (...)](https://usersnappublic.s3.amazonaws.com/2019-05-26/18-55/691eb867-f354-4cdb-af1b-71485d1be6e2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-26/18-55/cf159c01-4f39-4f08-835d-d1d3f34125b7.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/organization/200/edit?full=1](https://participedia.xyz/organization/200/edit?full=1)
**Screen size**: 1920 x 1200 **Browser size**: 1536 x 871

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by plscully** [comment]
I tried again just now on the same organization entry and the publishing process worked fine https://participedia.xyz/organization/200
