### ISSUE TITLE
Usersnap Feedback - Specific Methods, Tools & Techniques field doesn't not contain all possibl[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#695]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Specific Methods, Tools & Techniques field doesn't not contain all possible selections. there are at least three methods with the word 'cafe' in the title, yet none of them are returned (I'm looking for world cafe and have tried 'world' and 'cafe' with no luck)
[Open #394 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/394)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-27/17-32/9680c899-4736-437a-a64e-aa1487f51605.png'>![Usersnap Feedback - Specific Methods, Tools & Techniques field doesn't not contain all possibl(...)](https://usersnappublic.s3.amazonaws.com/2019-05-27/17-32/0281ee55-eeb9-4145-bc73-091143aa1b74.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-27/17-32/9680c899-4736-437a-a64e-aa1487f51605.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/case/4771/edit?full=1](https://participedia.xyz/case/4771/edit?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
tracking here https://github.com/participedia/usersnaps/issues/728
