### ISSUE TITLE
Usersnap Feedback - Searching for 'planning'  in the Specific Methods, Tools & Techniques fiel[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#697]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Searching for 'planning'  in the Specific Methods, Tools & Techniques field should return any title with the word planning in it. I can only select 'collaborative planning' if I enter 'collaborative' before 'planning'.
[Open #396 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/396)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-27/17-59/86cb0105-1e1f-4eb9-8f3d-4a6d39e44791.png'>![Usersnap Feedback - Searching for 'planning'  in the Specific Methods, Tools & Techniques fiel(...)](https://usersnappublic.s3.amazonaws.com/2019-05-27/17-59/2bbe92ca-e196-46c3-ac5a-b3732610b491.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-27/17-59/86cb0105-1e1f-4eb9-8f3d-4a6d39e44791.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/case/4788/edit?full=1](https://participedia.xyz/case/4788/edit?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 794

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
tracking here https://github.com/participedia/usersnaps/issues/728
