### ISSUE TITLE
Usersnap Feedback - User biographies did not transfer from .net

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#700]
**Sender**: scottowenfletcher@gmail.com
**Comment**: User biographies did not transfer from .net
[Open #399 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/399)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-28/00-04/28f2f9f4-b0b9-4788-8c6b-a7ce2f29e7d8.png'>![Usersnap Feedback - User biographies did not transfer from .net](https://usersnappublic.s3.amazonaws.com/2019-05-28/00-04/da4020e4-40b7-4e9e-abc8-f2abf809577b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-28/00-04/28f2f9f4-b0b9-4788-8c6b-a7ce2f29e7d8.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/user/278156](https://participedia.xyz/user/278156)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
.net profile for comparison: 

![image](https://user-images.githubusercontent.com/29512491/58440703-e4931080-8090-11e9-887c-368d550c1fd7.png)
