### ISSUE TITLE
Usersnap Feedback - Should be able to re-order images and/or select which comes first

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#705]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Should be able to re-order images and/or select which comes first
[Open #404 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/404)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-28/18-47/d61df031-3a52-4e21-8f9d-efa2e7e17222.png'>![Usersnap Feedback - Should be able to re-order images and/or select which comes first](https://usersnappublic.s3.amazonaws.com/2019-05-28/18-47/50171b1c-239a-4c68-b25c-21a742c8bbc0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-28/18-47/d61df031-3a52-4e21-8f9d-efa2e7e17222.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/case/5041/edit](https://participedia.xyz/case/5041/edit)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 794

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
That's true. Design spec'd these fields to be drag to re-order, top image being first to display.

**Comment by ascott** [comment]
@jesicarson with all our work around image resizing and optimization, i've noticed that it would be really helpful if it was possible to reorder images in order to choose what image will be displayed in the search results more easily. what do you think about bumping up the priority on this one?

**Comment by jesicarson** [comment]
Would love that.

**Comment by jesicarson** [comment]
Same visual spec as the other drag-to-reorder fields.

**Comment by ascott** [comment]
@jesicarson ok great 👍

**Comment by ascott** [comment]
@jesicarson this change is on staging now if you want to take a look and test it out.

**Comment by jesicarson** [comment]
looks great!
