### ISSUE TITLE
Usersnap Feedback - Map still missing red pins for featured entries.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#709]
**Sender**: jesi.carson@gmail.com
**Comment**: Map still missing red pins for featured entries.
[Open #408 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/408)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-29/01-34/7bac1ebf-ca0e-41bc-bf76-21166d2eba10.png'>![Usersnap Feedback - Map still missing red pins for featured entries.](https://usersnappublic.s3.amazonaws.com/2019-05-29/01-34/1c155baa-8b99-44a4-b553-f8b4b58c4ba3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-29/01-34/7bac1ebf-ca0e-41bc-bf76-21166d2eba10.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://ppedia-stage.herokuapp.com/](https://ppedia-stage.herokuapp.com/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
duplicate #680
