### ISSUE TITLE
Usersnap Feedback - The tag line will probably look better if we break the sentence after "abo[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#711]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: The tag line will probably look better if we break the sentence after "about" and have a slight indentation on the 2nd line
[Open #410 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/410)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-29/02-24/5f606eb0-fff5-4147-8d80-5e0ece92da2e.png'>![Usersnap Feedback - The tag line will probably look better if we break the sentence after "abo(...)](https://usersnappublic.s3.amazonaws.com/2019-05-29/02-24/bdc60e39-fc03-4e3d-b0c5-c305ee569d8f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-29/02-24/5f606eb0-fff5-4147-8d80-5e0ece92da2e.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/](https://ppedia-stage.herokuapp.com/)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1089

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Needs to be responsive to smaller screen sizes. Not sure if it makes sense to max out the line break at 2 or 3 columns maybe? Might help.
