### ISSUE TITLE
Usersnap Feedback - Admin tools are only accessible for methods when doing the quick submit fo[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#712]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Admin tools are only accessible for methods when doing the quick submit form. Can't access them when editing an already submitted entry
[Open #411 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/411)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-29/22-46/96f92074-8b6b-4124-8b9a-060d556d79be.png'>![Usersnap Feedback - Admin tools are only accessible for methods when doing the quick submit fo(...)](https://usersnappublic.s3.amazonaws.com/2019-05-29/22-46/2d5cc2b5-58f8-48ea-872e-250b3a9987bc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-29/22-46/96f92074-8b6b-4124-8b9a-060d556d79be.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/method/new](https://participedia.xyz/method/new)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 794

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Related to #713
