### ISSUE TITLE
Usersnap Feedback - User getting logged out after ~2hr, then get publish error when try to publish entry

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#714]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Publish button not working. Web dev console readout: 
www.googletagmanager.com/gtag/js?id=UA-132033152-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
edit?full=1:1 Access to XMLHttpRequest at 'https://participedia.auth0.com/authorize?response_type=code&redirect_uri=https%3A%2F%2Fparticipedia.xyz%2Fredirect&scope=offline%20openid%20email%20profile&state=t1ilDRYTbm8CgBfhASz4qHde&client_id=lORPmEONgX2K71SX7fk35X5PNZOCaSfU' (redirected from 'https://participedia.xyz/case/41') from origin 'https://participedia.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
edit:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at o.xhr.onreadystatechange (edit-view.bundle.js:20408)
    at XMLHttpRequest.s.onreadystatechange (cdn.usersnap.com/classic/frontend/assets/js/entries/setup/22e4a578ff652caf3795.js:78)
edit?full=1:1 Access to XMLHttpRequest at 'https://participedia.auth0.com/authorize?response_type=code&redirect_uri=https%3A%2F%2Fparticipedia.xyz%2Fredirect&scope=offline%20openid%20email%20profile&state=uvYZpyAJmT3Oz77MeLbrl7Bq&client_id=lORPmEONgX2K71SX7fk35X5PNZOCaSfU' (redirected from 'https://participedia.xyz/case/41') from origin 'https://participedia.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
edit?full=1:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at o.xhr.onreadystatechange (edit-view.bundle.js:20408)
    at XMLHttpRequest.s.onreadystatechange (22e4a578ff652caf3795.js:78)
edit?full=1:1 Access to XMLHttpRequest at 'https://participedia.auth0.com/authorize?response_type=code&redirect_uri=https%3A%2F%2Fparticipedia.xyz%2Fredirect&scope=offline%20openid%20email%20profile&state=Y3diCi64SVg0EG2lwZYgyyvX&client_id=lORPmEONgX2K71SX7fk35X5PNZOCaSfU' (redirected from 'https://participedia.xyz/case/41') from origin 'https://participedia.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
edit?full=1:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at o.xhr.onreadystatechange (edit-view.bundle.js:20408)
    at XMLHttpRequest.s.onreadystatechange (22e4a578ff652caf3795.js:78)
edit?full=1:1 Access to XMLHttpRequest at 'https://participedia.auth0.com/authorize?response_type=code&redirect_uri=https%3A%2F%2Fparticipedia.xyz%2Fredirect&scope=offline%20openid%20email%20profile&state=cEbx6L20Z612oXsY9FE82on9&client_id=lORPmEONgX2K71SX7fk35X5PNZOCaSfU' (redirected from 'https://participedia.xyz/case/41') from origin 'https://participedia.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
edit?full=1:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at o.xhr.onreadystatechange (edit-view.bundle.js:20408)
    at XMLHttpRequest.s.onreadystatechange (22e4a578ff652caf3795.js:78)
[Open #413 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/413)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-29/23-12/acfda9a9-ba9c-43cc-84c3-201b77910dd7.png'>![Usersnap Feedback - Publish button not working. Web dev console readout:  www.googletagmanager(...)](https://usersnappublic.s3.amazonaws.com/2019-05-29/23-12/77109acb-ca1a-459d-abbe-fdd36f7e53fd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-29/23-12/acfda9a9-ba9c-43cc-84c3-201b77910dd7.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/case/41/edit?full=1](https://participedia.xyz/case/41/edit?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 794

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
this looks like you weren't logged in when hitting publish. is it possible you logged out in another tab and then came back to this edit tab later? i can reproduce this bug if i clear my site data while i'm on the edit page and then try and publish, but i can't reproduce during normal use.

@scottofletcher is there anything else you can remember about what you were doing when you encountered this?

**Comment by scottofletcher** [comment]
@ascott no, there's no way I could have logged out on another tab, this happened during a long stretch of editing (over 2 hours), so I think it was the automatic log-out (which I thought we disabled?)

**Comment by ascott** [comment]
ok, thanks for the details. yeah, i thought this issue was solved as well. i'll look into it.

**Comment by scottofletcher** [comment]
that was just me spit balling though - I've been logged in for close to 2hours now, so I'll let you know if I get booted in the next 30mins!
