### ISSUE TITLE
Usersnap Feedback - stuck on publishing if file upload is too large

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#716]
**Sender**: scottowenfletcher@gmail.com
**Comment**: stuck on publishing screen
[Open #415 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/415)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-29/23-26/7b01c4f9-b5e0-4d24-80dc-2cdce018703a.png'>![Usersnap Feedback - stuck on publishing screen](https://usersnappublic.s3.amazonaws.com/2019-05-29/23-26/f9b0ae4a-1ed4-4c8e-b630-4fff39f031c7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-29/23-26/7b01c4f9-b5e0-4d24-80dc-2cdce018703a.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/case/5809/edit?full=1](https://participedia.xyz/case/5809/edit?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
can't reproduce. @scottofletcher let me know if you are still having this issue on this case.

**Comment by scottofletcher** [comment]
@ascott I figured out the problem for this one: the image I'd attached was too large. We should have a pop-up that tells the user the image needs to be under 5MB rather than the continuous loading screen

**Comment by jesicarson** [comment]
@ascott Yes, it's important than the modal tells people what is wrong in the forms if it can't publish. I think you worked on this already in another issue.
