### ISSUE TITLE
Usersnap Feedback - YO THIS LOOKS TIGHT :D

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#718]
**Sender**: scottowenfletcher@gmail.com
**Comment**: YO THIS LOOKS TIGHT :D
[Open #417 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/417)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-30/01-14/7cbe4996-a95d-40ce-8c4a-eaa0e4a8335a.png'>![Usersnap Feedback - YO THIS LOOKS TIGHT :D](https://usersnappublic.s3.amazonaws.com/2019-05-30/01-14/ab7c4459-8ede-440b-a212-7520051a8898.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-30/01-14/7cbe4996-a95d-40ce-8c4a-eaa0e4a8335a.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
woot woot!

**Comment by ascott** [comment]
🎉
