### ISSUE TITLE
Usersnap Feedback - General Issue not saved

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#72]
**Sender**: jesi.carson@gmail.com
**Comment**: Hmm didn't notice this before, but I had selected the general issue "housing" when I first submitted this case, and it looks like the system didn't register that. I'm looking on desktop and also don't see housing as part of the case data. Could be a bug?
[Open #86 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/86)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-39/6217aa01-92ce-4fbe-b3e6-55fd38e23112.png'>![Usersnap Feedback - Hmm didn't notice this before, but I had selected the general issue "housi(...)](https://usersnappublic.s3.amazonaws.com/2017-08-04/19-39/64184da7-a062-44b9-8295-5862d7c07a4f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-39/6217aa01-92ce-4fbe-b3e6-55fd38e23112.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/case/4606/edit](https://participedia.xyz/case/4606/edit)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@dethe fix before user testing

**Comment by dethe** [comment]
Fixed this awhile ago and forgot to close.
