### ISSUE TITLE
Usersnap Feedback - member since displays NAN

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#720]
**Sender**: alanna.scott@gmail.com
**Comment**: member since displays NAN
[Open #419 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/419)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-30/05-23/58758079-ff4d-4c8f-9d0c-7bd87b39efa1.png'>![Usersnap Feedback - member since displays NAN](https://usersnappublic.s3.amazonaws.com/2019-05-30/05-23/60a7d74a-1e3c-47c5-ab29-44ed520972bf.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-30/05-23/58758079-ff4d-4c8f-9d0c-7bd87b39efa1.png'>Download original image</a>

**Browser**: Chrome 74 (macOS High Sierra)
**Referer**: [https://participedia.xyz/user/417754/edit](https://participedia.xyz/user/417754/edit)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
this bug is happening because there are some user records (1143) where join_date is NULL in the db.

it looks like join_date fields stopped getting set 2018-06-06 and started getting set again 2019-05-31, so we could backfill all the missing join_date fields as 2018-06-06 as a pretty close guess at actual join_date.

@jesicarson @dethe do you think this makes sense? any other ideas?

**Comment by jesicarson** [comment]
That works for me. I don't think anyone will care much.
