### ISSUE TITLE
Usersnap Feedback - "Cannot read property 'split' of undefined" error message (again).  Web de[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#722]
**Sender**: scottowenfletcher@gmail.com
**Comment**: "Cannot read property 'split' of undefined" error message (again). 
Web dev console: www.googletagmanager.com/gtag/js?id=UA-132033152-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/case/597:1 Failed to load resource: the server responded with a status of 400 ()
22e4a578ff652caf3795.js:78 It is not advised to open dialogs from within other dialogs. Instead consider replacing the contents of this dialog with new content. Or providing a stepped, or tabbed interface within this dialog.
[Open #421 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/421)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-30/20-21/08ffe773-3179-4863-b9c2-26b034f6e283.png'>![Usersnap Feedback - "Cannot read property 'split' of undefined" error message (again).  Web de(...)](https://usersnappublic.s3.amazonaws.com/2019-05-30/20-21/ea26f158-0dc4-4a3a-b11d-122b3bac9fbb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-30/20-21/08ffe773-3179-4863-b9c2-26b034f6e283.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/case/597/edit](https://participedia.xyz/case/597/edit)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher did you add the evaluation report files, or did this case already have them? if you delete the files and upload again it should work. i'm still trying to figure out how this field is getting into this state.

**Comment by ascott** [comment]
figured out what is happening here: looks like evaluation report urls were not saved with the aws url appended from .xyz entries.  

<img width="1063" alt="Screenshot 2019-05-30 17 52 06" src="https://user-images.githubusercontent.com/130878/58674238-b5380a00-8303-11e9-960c-ac89397ee4c6.png">

rather then handle these 2 cases in our new code, i think the best solution is to write a one-off script to update the urls that are missing the aws base urls. @dethe what do you think?

**Comment by ascott** [comment]
alternatively we could handle this in the file upload function, and if it's a data uri, upload it, and if it's not, add the aws url. this is probably the quickest solution.

**Comment by dethe** [comment]
If there are only 2 I can just fix directly in the db, no script needed

**Comment by ascott** [comment]
@dethe looks like there are about 50 that need to be updated.

**Comment by ascott** [comment]
i updated these fields in the db so they now include the AWS base url, so we shouldn't see this error anymore.
