### ISSUE TITLE
Usersnap Feedback - Editing submission details doesn't work. Changed this from first submittee[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#723]
**Sender**: jesi.carson@gmail.com
**Comment**: Editing submission details doesn't work. Changed this from first submitteed by Julien to Aklilu but the change wasn't saved.
[Open #422 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/422)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-30/22-01/44b4db1c-a1f5-4529-805c-0c628f2d3683.png'>![Usersnap Feedback - Editing submission details doesn't work. Changed this from first submittee(...)](https://usersnappublic.s3.amazonaws.com/2019-05-30/22-01/f9e1165e-ff29-4a2c-b95d-f39b2e1e9b28.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-30/22-01/44b4db1c-a1f5-4529-805c-0c628f2d3683.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Mojave)
**Referer**: [https://participedia.xyz/case/5809](https://participedia.xyz/case/5809)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
duplicate
tracking this issue here: participedia/api#510
