### ISSUE TITLE
Usersnap Feedback - Awkward cropping of image

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#725]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Awkward cropping of image
[Open #424 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/424)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-31/00-10/859f627d-2169-4166-9566-5b09727fe9fd.png'>![Usersnap Feedback - Awkward cropping of image](https://usersnappublic.s3.amazonaws.com/2019-05-31/00-10/ccdce5c4-f8bb-42d4-a1d8-a042cc9f56b3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-31/00-10/859f627d-2169-4166-9566-5b09727fe9fd.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/organization/5785](https://participedia.xyz/organization/5785)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 794

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
fixed by editing the image and re-uploading it with a better aspect ratio of whitespace around it.
