### ISSUE TITLE
Usersnap Feedback - Searching for specific methods, tools & techniques needs to be fixed for launch

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#728]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Searching for specific methods, tools & techniques needs to be fixed for launch
[Open #427 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/427)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-31/19-06/3f1259f7-d9e5-4a28-bffe-d6fa842801d3.png'>![Usersnap Feedback - Searching for specific methods, tools & techniques needs to be fixed for launch](https://usersnappublic.s3.amazonaws.com/2019-05-31/19-06/f02a524e-95f1-4355-b368-0c906ae86415.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-31/19-06/3f1259f7-d9e5-4a28-bffe-d6fa842801d3.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/case/5811/edit?full=1](https://participedia.xyz/case/5811/edit?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 794

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher this field works for me. what is the issue you're experiencing?

**Comment by scottofletcher** [comment]
there was another usersnap about this - the problem is that the wording has to be exact. on the old site (old as in .net and last week's .xyz), you could type in 'art' and get 'participatory arts'. now, you get nothing. you have to type in 'participatory' in order to see 'participatory art'.

**Comment by scottofletcher** [comment]
see #697 and #695

**Comment by jesicarson** [comment]
Gotcha.

**Comment by scottofletcher** [comment]
same deal with the Primary Organizer/Manager field. I couldn't get 'United Nations' by typing 'Nations', only 'United'
