### ISSUE TITLE
Usersnap Feedback - Users should not be able to select hidden entries from the drop down menus [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#729]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Users should not be able to select hidden entries from the drop down menus (components, methods/tools/techniques, orgs)
[Open #428 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/428)

<a href='https://usersnappublic.s3.amazonaws.com/2019-06-02/17-24/8b1fe0e2-88b7-446e-822e-b4c9b67ef873.png'>![Usersnap Feedback - Users should not be able to select hidden entries from the drop down menus (...)](https://usersnappublic.s3.amazonaws.com/2019-06-02/17-24/eebb50cd-912d-4151-88bb-ab59b2c26db2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-06-02/17-24/8b1fe0e2-88b7-446e-822e-b4c9b67ef873.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/case/4512/edit?full=1](https://participedia.xyz/case/4512/edit?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
I can’t seem to assign labels on mobile, but this should be added to the P1 list form updates after faceted search. Or sooner if it’s an easy one.
