### ISSUE TITLE
Usersnap Feedback - Looks like my uploaded images have duplicated in the edit form. Bug?

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#73]
**Sender**: jesi.carson@gmail.com
**Comment**: Looks like my uploaded images have duplicated in the edit form. Bug?
[Open #87 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/87)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-40/c0e8d4a8-1811-44d0-8317-4a465eff8a54.png'>![Usersnap Feedback - Looks like my uploaded images have duplicated in the edit form. Bug?](https://usersnappublic.s3.amazonaws.com/2017-08-04/19-40/f93f3feb-c07b-43e7-b999-67c7b94b317e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-40/c0e8d4a8-1811-44d0-8317-4a465eff8a54.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/case/4606/edit](https://participedia.xyz/case/4606/edit)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Duplicated images will be handled here: https://github.com/participedia/frontend/issues/579
