### ISSUE TITLE
Usersnap Feedback - Admins need to be able to access 'Hidden' content (I need to 'unhide' this)

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#732]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Admins need to be able to access 'Hidden' content (I need to 'unhide' this)
[Open #431 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/431)

<a href='https://usersnappublic.s3.amazonaws.com/2019-06-03/17-58/335e1531-b6b9-4438-86fe-c63936a5b627.png'>![Usersnap Feedback - Admins need to be able to access 'Hidden' content (I need to 'unhide' this)](https://usersnappublic.s3.amazonaws.com/2019-06-03/17-58/8f7f4412-f080-490b-9908-5e2e6e680dfd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-06-03/17-58/335e1531-b6b9-4438-86fe-c63936a5b627.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.xyz/method/4328](https://participedia.xyz/method/4328)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 794

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher i will unhide this for you while i look into why you aren't able to see this page as an admin.

**Comment by ascott** [comment]
@scottofletcher this is fixed now

**Comment by scottofletcher** [comment]
thanks!
