### ISSUE TITLE
Usersnap Feedback - Chrome / net -- Map overlay is not appearing before or after log in

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#735]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Chrome / net -- Map overlay is not appearing before or after log in
[Open #434 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/434)

<a href='https://usersnappublic.s3.amazonaws.com/2019-06-04/15-44/69461fcc-ebaf-4af1-a06e-5540655ea025.png'>![Usersnap Feedback - Chrome / net -- Map overlay is not appearing before or after log in](https://usersnappublic.s3.amazonaws.com/2019-06-04/15-44/e08367c1-3622-4b06-ab7e-0e0340f772ae.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-06-04/15-44/69461fcc-ebaf-4af1-a06e-5540655ea025.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1089

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott this is High pri please fix ASAP thanks :)
