### ISSUE TITLE
Usersnap Feedback - Hello! I accidentally duplicated a case. Can you take this version down? h[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#737]
**Sender**: apottorff@jefferson-center.org
**Comment**: Hello! I accidentally duplicated a case. Can you take this version down? https://participedia.net/case/5819/edit
[Open #436 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/436)

<a href='https://usersnappublic.s3.amazonaws.com/2019-06-06/22-36/e2f3f297-4c61-4ffc-bcf2-6b17e858ae01.png'>![Usersnap Feedback - Hello! I accidentally duplicated a case. Can you take this version down? h(...)](https://usersnappublic.s3.amazonaws.com/2019-06-06/22-36/87ae40fd-5491-4b1c-98b5-ece993d0bf3a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-06-06/22-36/e2f3f297-4c61-4ffc-bcf2-6b17e858ae01.png'>Download original image</a>

**Browser**: Chrome 74 (macOS Sierra)
**Referer**: [https://participedia.net/case/5819/edit](https://participedia.net/case/5819/edit)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 920

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
marked as hidden

**Comment by jesicarson** [comment]
thanks @ascott did you email the sender and let them know? if not I can do that from the info@ email.

**Comment by ascott** [comment]
@jesicarson no, i didn't email the sender.

**Comment by jesicarson** [comment]
ok thanks. on it.
