### ISSUE TITLE
Usersnap Feedback - And my Vimeo URL also didn't get saved by the system, but I definitely ent[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#74]
**Sender**: jesi.carson@gmail.com
**Comment**: And my Vimeo URL also didn't get saved by the system, but I definitely entered it in the form when I first submitted this case. 
[Open #88 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/88)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-41/d2b0a0e5-aead-4bbe-897b-1bc14b644413.png'>![Usersnap Feedback - And my Vimeo URL also didn't get saved by the system, but I definitely ent(...)](https://usersnappublic.s3.amazonaws.com/2017-08-04/19-41/2762ce71-cac6-4f8a-a9e9-47931928ac8e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-41/d2b0a0e5-aead-4bbe-897b-1bc14b644413.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/case/4606/edit](https://participedia.xyz/case/4606/edit)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Will be fixed here: https://github.com/participedia/frontend/issues/570
