### ISSUE TITLE
Usersnap Feedback - There's no "save" or update case button. I have to scroll all the way to t[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#75]
**Sender**: jesi.carson@gmail.com
**Comment**: There's no "save" or update case button. I have to scroll all the way to the bottom past all the form fields that I have never seen before because I used quick submit last time. This feels wrong, we should rethink the way this works. 
[Open #89 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/89)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-43/ac47d7e4-fad0-45b7-8158-2c242fdfce9e.png'>![Usersnap Feedback - There's no "save" or update case button. I have to scroll all the way to t(...)](https://usersnappublic.s3.amazonaws.com/2017-08-04/19-43/9e7865c1-7e21-4495-ae29-d10af5844157.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-43/ac47d7e4-fad0-45b7-8158-2c242fdfce9e.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/case/4606/edit](https://participedia.xyz/case/4606/edit)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@dethe not needed before user testing

**Comment by andreadelrio** [comment]
Should be covered by this https://github.com/participedia/frontend/issues/549 ?

**Comment by jesicarson** [comment]
https://github.com/participedia/frontend/issues/808
