### ISSUE TITLE
Usersnap Feedback - Images duplicated.   And where is the case data accessible on mobile? Does [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#76]
**Sender**: jesi.carson@gmail.com
**Comment**: Images duplicated. 

And where is the case data accessible on mobile? Does this need to be designed?
[Open #90 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/90)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-45/6415493d-1d6b-468a-b17a-a236b3c851bc.png'>![Usersnap Feedback - Images duplicated.   And where is the case data accessible on mobile? Does (...)](https://usersnappublic.s3.amazonaws.com/2017-08-04/19-45/17c7ae44-b715-4d5e-b033-d0683db76efc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-04/19-45/6415493d-1d6b-468a-b17a-a236b3c851bc.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/case/4606](https://participedia.xyz/case/4606)
**Screen size**: 320 x 568 **Browser size**: 320 x 460

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
@jesicarson Was this a case of images being added multiple times while testing or did the images get duplicated simply by editing/saving?

**Comment by jesicarson** [comment]
@dethe I only added them once, and they appeared multiple times when viewing a little while later (I think the duplication happened after attempting to edit the case - perhaps it saves the images again when you save an edit?).

**Comment by dethe** [comment]
Showing case data on mobile will be handled here: https://github.com/participedia/frontend/issues/573

Duplicated images will be handled here: https://github.com/participedia/frontend/issues/579
