### ISSUE TITLE
Usersnap Feedback - Just created this stub and for some reason the case has been created twice[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#760]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: Just created this stub and for some reason the case has been created twice. No idea how. Will need deleting.
[Open #459 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/459)

<a href='https://usersnappublic.s3.amazonaws.com/2019-06-22/09-50/a6c05003-ac68-402e-a794-b73c5c3028be.png'>![Usersnap Feedback - Just created this stub and for some reason the case has been created twice(...)](https://usersnappublic.s3.amazonaws.com/2019-06-22/09-50/02f8a4c9-6939-4b9f-bd2d-c250751072ba.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-06-22/09-50/a6c05003-ac68-402e-a794-b73c5c3028be.png'>Download original image</a>

**Browser**: Chrome 74 (Windows 10)
**Referer**: [https://participedia.net/?query=yarra](https://participedia.net/?query=yarra)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 657

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott is the duplication bug back?

**Comment by ascott** [comment]
@jesicarson this isn't the same duplication bug, but two different entries with different id's. not sure how this would happen either. i will mark one as hidden.
