### ISSUE TITLE
Usersnap Feedback - Another couple cases w/images not displaying in card view

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#764]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Another couple cases w/images not displaying in card view
[Open #463 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/463)

<a href='https://usersnappublic.s3.amazonaws.com/2019-06-30/19-50/30696dd4-6abe-429e-8a6d-d2d581498af4.png'>![Usersnap Feedback - Another couple cases w/images not displaying in card view](https://usersnappublic.s3.amazonaws.com/2019-06-30/19-50/ded03fcd-9e01-4787-9c4c-5ee8c8955a70.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-06-30/19-50/30696dd4-6abe-429e-8a6d-d2d581498af4.png'>Download original image</a>

**Browser**: Chrome 75 (Windows 10)
**Referer**: [https://participedia.net/?page=2](https://participedia.net/?page=2)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
one of these is related to this bug: https://github.com/participedia/api/issues/621

and the other, https://participedia.net/organization/4592, is a corrupt/broken image. if you click through to the reader view the image doesn't display there either, and if you visit the image url directly you get an error https://s3.amazonaws.com/uploads.participedia.xyz/c3e52a66-557d-4e10-a54a-e1a99104ff2d-YourSAy%20logo

**Comment by ascott** [comment]
oh, actually it's an image of a white rectangle, so it looks like nothing!


<img width="1280" alt="Screenshot 2019-07-09 20 35 52" src="https://user-images.githubusercontent.com/130878/60938531-2b2b7b80-a289-11e9-87e6-ab7644c3fa47.png">

**Comment by jesicarson** [comment]
What the??? Is someone messing with us? lol
