### ISSUE TITLE
Usersnap Feedback - One of our partners requested that this case be featured but the lead imag[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#765]
**Sender**: scottowenfletcher@gmail.com
**Comment**: One of our partners requested that this case be featured but the lead image isn't optimal. However, there's currently no way of changing the lead image short of removing all images and then uploading in the exact order I want them displayed.
[Open #464 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/464)

<a href='https://usersnappublic.s3.amazonaws.com/2019-06-30/19-51/0e5f256d-f22e-402a-8086-83382878cc62.png'>![Usersnap Feedback - One of our partners requested that this case be featured but the lead imag(...)](https://usersnappublic.s3.amazonaws.com/2019-06-30/19-51/28abf0af-5042-4941-b61b-d5fe05ce4e6c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-06-30/19-51/0e5f256d-f22e-402a-8086-83382878cc62.png'>Download original image</a>

**Browser**: Chrome 75 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
we need to implement sorting/ranking on media fields to solve this issue. in the short term i can manually update the first image for this case if it's urgent/important. just let me know what image they would like to make the first image @scottofletcher

**Comment by scottofletcher** [comment]
oh sure, how bout we go with the 4th image (a woman standing up w/a microphone + two seated ppl with their hands up). 
thanks!

**Comment by ascott** [comment]
@scottofletcher updated!
