### ISSUE TITLE
Usersnap Feedback - articles that were submitted on the old site in German don't have english [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#773]
**Sender**: alanna.scott@gmail.com
**Comment**: articles that were submitted on the old site in German don't have english translations/versions so no title or body are displayed
[Open #472 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/472)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-05/18-50/0f7f35a1-a89a-4e92-843f-ae5ebf2f740b.png'>![Usersnap Feedback - articles that were submitted on the old site in German don't have english (...)](https://usersnappublic.s3.amazonaws.com/2019-07-05/18-50/04254cfe-e885-46e5-8cca-f4a8a9dc2eaa.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-05/18-50/0f7f35a1-a89a-4e92-843f-ae5ebf2f740b.png'>Download original image</a>

**Browser**: Chrome 74 (macOS High Sierra)
**Referer**: [https://participedia.net/case/3193](https://participedia.net/case/3193)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/
https://participedia.net/case/

**Comment by scottofletcher** [comment]
https://participedia.net/case/728
https://participedia.net/case/755
https://participedia.net/case/766
https://participedia.net/case/767
https://participedia.net/case/769
https://participedia.net/case/773
https://participedia.net/case/774
https://participedia.net/case/777
https://participedia.net/case/781
https://participedia.net/case/787
https://participedia.net/case/792
https://participedia.net/case/796
https://participedia.net/case/808
https://participedia.net/case/825
https://participedia.net/case/852
https://participedia.net/case/929
https://participedia.net/case/935
https://participedia.net/case/967
https://participedia.net/case/980
https://participedia.net/case/1122
https://participedia.net/case/1244
https://participedia.net/case/1250
https://participedia.net/case/1255
https://participedia.net/case/1431
https://participedia.net/case/1459
https://participedia.net/case/2218
https://participedia.net/case/2315
https://participedia.net/case/2360
https://participedia.net/case/2444
https://participedia.net/case/2453
https://participedia.net/case/2454
https://participedia.net/case/2697
https://participedia.net/case/3079
https://participedia.net/case/3193
https://participedia.net/case/4160
https://participedia.net/case/4163
https://participedia.net/case/4166
https://participedia.net/case/4167
https://participedia.net/case/4168
https://participedia.net/case/4169
https://participedia.net/case/4171
https://participedia.net/case/4172
https://participedia.net/case/4284
https://participedia.net/case/4285
https://participedia.net/case/4973
https://participedia.net/case/5061
https://participedia.net/case/5062
https://participedia.net/case/5070
https://participedia.net/case/5071
https://participedia.net/case/5072
https://participedia.net/case/5073
https://participedia.net/case/5074
https://participedia.net/case/5075

I think that's all of them! I'll check the orgs and methods now

**Comment by scottofletcher** [comment]
https://participedia.net/organization/771
https://participedia.net/organization/776
https://participedia.net/organization/4560
https://participedia.net/organization/5060
https://participedia.net/organization/5062
https://participedia.net/organization/5064
https://participedia.net/organization/5065
https://participedia.net/organization/5066
And this one has a title that ends up as #NAME? in the JSON>CSV convert https://participedia.net/organization/778

**Comment by scottofletcher** [comment]
all methods have titles :)

**Comment by ascott** [comment]
@dethe as discussed, when fetching articles we should fall back to the article's original_language if translations in the viewers language don't exist.
