### ISSUE TITLE
Usersnap Feedback - How can I delete one or multiple of the redundant 'contributions' MH

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#776]
**Sender**: marholzhauer@aol.com
**Comment**: How can I delete one or multiple of the redundant 'contributions' MH
[Open #474 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/474)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-09/12-17/38bd71aa-0e58-4cbc-8355-2fa96dbe39bf.png'>![Usersnap Feedback - How can I delete one or multiple of the redundant 'contributions' MH](https://usersnappublic.s3.amazonaws.com/2019-07-09/12-17/d2493db6-eb85-4110-92d2-c567703861f1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-09/12-17/38bd71aa-0e58-4cbc-8355-2fa96dbe39bf.png'>Download original image</a>

**Browser**: Chrome 57 (macOS Mojave)
**Referer**: [https://participedia.net/user/418029?selectedCategory=contributions](https://participedia.net/user/418029?selectedCategory=contributions)
**Screen size**: 2560 x 1440 **Browser size**: 2514 x 1218

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
this looks like that bug we've seen before where duplicate entries are being displayed on the user profile.

**Comment by jesicarson** [comment]
i would say this is a priority, adding p1 label

**Comment by ascott** [comment]
i'm not sure what was happening here. checking now, i can't reproduce the error. there aren't any duplicate entries on her contributions page or other pages i checked.
