### ISSUE TITLE
Usersnap Feedback - This was a duplicate I didn't know I created until Pat pointed it out to m[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#779]
**Sender**: scottowenfletcher@gmail.com
**Comment**: This was a duplicate I didn't know I created until Pat pointed it out to me. I really think there's a problem with the publishing system - I only created one entry which I may have edited a couple times, but never went through the steps that _should_ be needed to create a duplicate (ie. quick submit -> new form -> filling out all the fields again).
[Open #477 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/477)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-12/19-17/9cc63e49-d57f-48e6-932a-5e27ebedbc20.png'>![Usersnap Feedback - This was a duplicate I didn't know I created until Pat pointed it out to m(...)](https://usersnappublic.s3.amazonaws.com/2019-07-12/19-17/30fb7dbb-f0da-4239-9f88-86bf3136db6c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-12/19-17/9cc63e49-d57f-48e6-932a-5e27ebedbc20.png'>Download original image</a>

**Browser**: Chrome 75 (Windows 10)
**Referer**: [https://participedia.net/case/5967](https://participedia.net/case/5967)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher if this is a duplicate, have you already hidden it? i'm not sure what the bug was here, but let's just hide the duplicate for now.

**Comment by scottofletcher** [comment]
oh I have no idea - this was back in July so I think we were doing user testing. there's only one version published and recorded in the dataset now, so I think we can close this
