### ISSUE TITLE
Usersnap Feedback - I entered irrelevant search terms about lawn care & it appeared to stall t[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#78]
**Sender**: None
**Comment**: I entered irrelevant search terms about lawn care & it appeared to stall the app. Even an attempt to return to the home page stalled on this screen.
[Open #92 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/92)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-06/21-52/0af03d85-27b8-44b0-bf81-1cd5b7b9d302.png'>![Usersnap Feedback - I entered irrelevant search terms about lawn care & it appeared to stall t(...)](https://usersnappublic.s3.amazonaws.com/2017-08-06/21-52/88a461a1-3192-4c3a-9cfb-cc92c7926546.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-06/21-52/0af03d85-27b8-44b0-bf81-1cd5b7b9d302.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 768 x 1024 **Browser size**: 768 x 928

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Not sure what happened, but may have been some unrelated breakage at the time. I can't replicate, searching for lawn care or other irrelevant terms returns 0 results quickly (`page 1 of 0 pages`).
