### ISSUE TITLE
Usersnap Feedback - We may have already logged this on Github, but it would be more useful to [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#780]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: We may have already logged this on Github, but it would be more useful to label this either "General Issues", or if we also add the 'specific topics' values, to label this "Issues & Topics". My guess is that these will be popular searches
[Open #478 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/478)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-12/21-21/146dd25d-7db1-4e31-a978-996f482e2f16.png'>![Usersnap Feedback - We may have already logged this on Github, but it would be more useful to (...)](https://usersnappublic.s3.amazonaws.com/2019-07-12/21-21/57b218ff-3277-47dd-9b4a-19112bac33d9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-12/21-21/146dd25d-7db1-4e31-a978-996f482e2f16.png'>Download original image</a>

**Browser**: Chrome 75 (Windows 10)
**Referer**: [https://participedia.net/?selectedCategory=case](https://participedia.net/?selectedCategory=case)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1089

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Good point. @ascott before you start code work on faceted search for methods and orgs, lets review the naming of the main chips and see if we can make them clearer / catchier. I agree with Pat and like "Issues & Topics" way better than "Overview".

**Comment by jesicarson** [comment]
https://github.com/participedia/api/issues/675
