### ISSUE TITLE
Usersnap Feedback - When I try to access these files, it asks me to save them before I can vie[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#781]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: When I try to access these files, it asks me to save them before I can view them. Shouldn't be a way for users to view the file contents w/out first having to save them?
[Open #479 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/479)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-13/17-48/326aa37c-cc3f-4fdf-ad6c-4b0c61db8480.png'>![Usersnap Feedback - When I try to access these files, it asks me to save them before I can vie(...)](https://usersnappublic.s3.amazonaws.com/2019-07-13/17-48/f95d36df-1fcb-4fb8-a7c1-81c01e2facdc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-13/17-48/326aa37c-cc3f-4fdf-ad6c-4b0c61db8480.png'>Download original image</a>

**Browser**: Chrome 75 (Windows 10)
**Referer**: [https://participedia.net/case/5692](https://participedia.net/case/5692)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1089

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
i think this is related to an incorrect Content-Type getting set on the file when we save it to s3. we should be saving it as `Content-Type=application/pdf` so it can be viewed in the browser, rather than being downloaded.  https://stackoverflow.com/questions/46690640/force-s3-pdf-to-be-viewed-in-browser-instead-of-download

**Comment by ascott** [comment]
we should do 2 things: 
- [x] change the upload code on the backend to set the correct Content-Type for files before saving to s3. 
- [ ] batch process existing files saved to s3 and set the appropriate Content-Type

**Comment by jesicarson** [comment]
Lets fix for sure, but since people do at least have a way to access files by saving them, while not ideal, its not P1

**Comment by paninee** [comment]
the content-type is already set, but we also need to change all existing file to the proper content-type, using something like this script

`aws s3 cp --exclude * --include *.pdf  s3://{{bucket}} s3://{{bucket}} --recursive --metadata
-directive REPLACE --content-disposition inline`

**Comment by ascott** [comment]
@paninee thanks for looking into this! did you take care of running the script to set the proper content-type for existing files as well?
