### ISSUE TITLE
Usersnap Feedback - changing/saving first submitted by field doesn't work (admin only). needs [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#788]
**Sender**: alanna.scott@gmail.com
**Comment**: changing/saving first submitted by field doesn't work (admin only). needs backend work.
[Open #486 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/486)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-17/01-32/2425763c-8ac8-4e67-8b40-86159cd01e53.png'>![Usersnap Feedback - changing/saving first submitted by field doesn't work (admin only). needs (...)](https://usersnappublic.s3.amazonaws.com/2019-07-17/01-32/c5dd74df-da4d-4432-b5f2-d0501a829892.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-17/01-32/2425763c-8ac8-4e67-8b40-86159cd01e53.png'>Download original image</a>

**Browser**: Chrome 74 (macOS High Sierra)
**Referer**: [https://participedia.net/case/5529/edit](https://participedia.net/case/5529/edit)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Recently heard from @scottofletcher that having this feature working would improve the editing team's workflow. If possible, @ascott / @dethe  can you assess whether this can be done easily and prior to @paninee starting work? Or let us know if we should sit tight and pass this issue to Pan. Thanks!

**Comment by scottofletcher** [comment]
not a huge deal - we just have a backlog of entries that need their submission info changed. we don't have to make this p1 if you folks don't mind me asking you to change submission details in an emergency (like this morning)

**Comment by ascott** [comment]
@scottofletcher yeah, for articles that really need this done, we can do it on an ad-hoc basis until we get this fixed. feel free to ask in the d&t channel and we can get it done.

**Comment by scottofletcher** [comment]
Thanks! It's rarely ever urgent; today was an exceptional case
