### ISSUE TITLE
Usersnap Feedback - Why all the white space above "get involved"

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#80]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Why all the white space above "get involved"
[Open #94 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/94)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-06/22-12/59631b1e-b561-4102-890d-c2f79768ba92.png'>![Usersnap Feedback - Why all the white space above "get involved"](https://usersnappublic.s3.amazonaws.com/2017-08-06/22-12/6843a70d-1763-48df-87a5-e41f90bcc2b3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-06/22-12/59631b1e-b561-4102-890d-c2f79768ba92.png'>Download original image</a>

**Browser**: Safari 10 (iOS)
**Referer**: [https://participedia.xyz/about](https://participedia.xyz/about)
**Screen size**: 768 x 1024 **Browser size**: 768 x 960

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by andreadelrio** [comment]
We are trying to load this video https://vimeo.com/219546454 and since it appears to have been taken down it's showing a white space where the video player would be. @jesicarson can you please provide a new video link for this page?

**Comment by jesicarson** [comment]
@andreadelrio 
So weird. Not sure why it was taken down, but I've re-uploaded it. Here's the new link: https://vimeo.com/228741848

**Comment by jesicarson** [comment]
@andreadelrio 
Noooope, I take it back. Someone had changed the privacy settings to "visible to only me". I just updated the settings so the original link should work now.

**Comment by andreadelrio** [comment]
@jesicarson great! closing this issue then.

**Comment by jesicarson** [comment]
@andreadelrio One sec, can you fix the viewer so there are no black bars on each side of the video? Like adjust the aspect ratio of the viewer so that the whole video fills the box (make it taller). 
![screen shot 2017-08-07 at 4 47 16 pm](https://user-images.githubusercontent.com/13560530/29050350-3147b73a-7b90-11e7-9f6c-38b66a08de2b.png)
