### ISSUE TITLE
Usersnap Feedback - Country still not displaying (I had entered and selected 'Venezuela')

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#800]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Country still not displaying (I had entered and selected 'Venezuela')
[Open #498 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/498)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-21/02-09/556d4f47-6114-4ed0-97e5-84fdcd04bec4.png'>![Usersnap Feedback - Country still not displaying (I had entered and selected 'Venezuela')](https://usersnappublic.s3.amazonaws.com/2019-07-21/02-09/a47f5eeb-0c25-4e3c-b385-4ac885b8df1c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-21/02-09/556d4f47-6114-4ed0-97e5-84fdcd04bec4.png'>Download original image</a>

**Browser**: Chrome 75 (Windows 10)
**Referer**: [https://participedia.net/organization/5976](https://participedia.net/organization/5976)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 774

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher i haven't pushed this fix to production yet, so that makes sense. will let you know when the change is live.

**Comment by scottofletcher** [comment]
Oh sorry! Jumped the gun!

**Comment by ascott** [comment]
@scottofletcher this is on prod now! :)
