### ISSUE TITLE
Usersnap Feedback - Reader language dropdown not working - changed to french, but it reloaded [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#802]
**Sender**: jesi.carson@gmail.com
**Comment**: Reader language dropdown not working - changed to french, but it reloaded english. (tried twice)
[Open #500 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/500)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-22/20-13/9dcfe674-0b5f-4316-a206-fde6999dd419.png'>![Usersnap Feedback - Reader language dropdown not working - changed to french, but it reloaded (...)](https://usersnappublic.s3.amazonaws.com/2019-07-22/20-13/ebfcf73a-f623-41ef-ab10-d55d7b0afae7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-22/20-13/9dcfe674-0b5f-4316-a206-fde6999dd419.png'>Download original image</a>

**Browser**: Chrome 75 (macOS Mojave)
**Referer**: [https://participedia.net/case/5529](https://participedia.net/case/5529)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 978

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson hmm strange... if you clear your cookies and try again, does it work?

**Comment by jesicarson** [comment]
yes that worked. and also signed me out of everything :P

**Comment by ascott** [comment]
ok, i'll see if i can fix this without requiring people to clear their cookies. 🤦‍♀

**Comment by jesicarson** [comment]
I didn't reload the site first, maybe that would have worked?

**Comment by ascott** [comment]
i checked with Scott and he's not seeing this error, and I cannot reproduce either. let's open another issue if we see this again.
