### ISSUE TITLE
Usersnap Feedback - Stuck on publishing screen. Dev console readout: Failed to load resource: [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#805]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Stuck on publishing screen. Dev console readout: Failed to load resource: the server responded with a status of 503 ()
VM126:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at o.xhr.onreadystatechange (edit-view.bundle.js?cacheKey=1563852930000:20447)
    at XMLHttpRequest.s.onreadystatechange (efa8a6aadd34fb1aa58e.js:78)
xhr.onreadystatechange @ edit-view.bundle.js?cacheKey=1563852930000:20447
s.onreadystatechange @ efa8a6aadd34fb1aa58e.js:78
5823:1 Failed to load resource: the server responded with a status of 503 ()
VM127:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at o.xhr.onreadystatechange (edit-view.bundle.js?cacheKey=1563852930000:20447)
    at XMLHttpRequest.s.onreadystatechange (efa8a6aadd34fb1aa58e.js:78)
[Open #503 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/503)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-25/19-12/b20836ec-7f55-4036-83f2-9cc48efa90c8.png'>![Usersnap Feedback - Stuck on publishing screen. Dev console readout: Failed to load resource: (...)](https://usersnappublic.s3.amazonaws.com/2019-07-25/19-12/70a2be21-1a05-4982-96da-efcbfbbd27c6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-25/19-12/b20836ec-7f55-4036-83f2-9cc48efa90c8.png'>Download original image</a>

**Browser**: Chrome 75 (Windows 10)
**Referer**: [https://participedia.net/case/5823/edit?full=1](https://participedia.net/case/5823/edit?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@dethe looks like the server is returning a 503 error here. any ideas?

**Comment by ascott** [comment]
@scottofletcher were you saving any files or photos with this edit? trying to figure out what is causing the request to time out and throw a 503 error.

**Comment by scottofletcher** [comment]
nope, I was just updating regular (drop-down/select) fields. I might have edited the funders field which I think is the only open text field aside from title, brief description, and narrative

**Comment by ascott** [comment]
i've added some additional error logging so i can get more info about this error when it happens again.

**Comment by ascott** [comment]
we have a better ux flow when this happens now and are still investigating the route cause of the 503's, tracking issue here: https://github.com/participedia/api/issues/730
