### ISSUE TITLE
Usersnap Feedback - SPAM - How should admins deal with spam? Can we block users? Can we delete [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#807]
**Sender**: jesi.carson@gmail.com
**Comment**: SPAM - How should admins deal with spam? Can we block users? Can we delete (not just hide) all the content from a particular user?
[Open #505 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/505)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-26/19-45/1640c716-fe12-4351-9ca6-6b7aae814a3b.png'>![Usersnap Feedback - SPAM - How should admins deal with spam? Can we block users? Can we delete (...)](https://usersnappublic.s3.amazonaws.com/2019-07-26/19-45/b27098b6-74a7-456f-aa69-b6ec7d2a5379.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-26/19-45/1640c716-fe12-4351-9ca6-6b7aae814a3b.png'>Download original image</a>

**Browser**: Chrome 75 (macOS Mojave)
**Referer**: [https://participedia.net/organization/5980](https://participedia.net/organization/5980)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
from Scott on slack -- 
here are their other posts: 
https://participedia.net/organization/5981 
https://participedia.net/organization/5983 
https://participedia.net/organization/5984 
https://participedia.net/organization/5982

**Comment by ascott** [comment]
blocked these users
