### ISSUE TITLE
Usersnap Feedback - Extra sidebar?

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#808]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Extra sidebar?
[Open #506 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/506)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-27/01-11/910b7565-2485-46ac-9de0-6b673e30dd7f.png'>![Usersnap Feedback - Extra sidebar?](https://usersnappublic.s3.amazonaws.com/2019-07-27/01-11/2e420492-da9f-4a7d-999e-cfcc4f93e9f1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-27/01-11/910b7565-2485-46ac-9de0-6b673e30dd7f.png'>Download original image</a>

**Browser**: Chrome 75 (Windows 10)
**Referer**: [https://participedia.net/case/5832](https://participedia.net/case/5832)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher i'm not sure if this screenshot didn't come through properly, but i don't see an extra sidebar here. i just see a red outline with white space.

**Comment by scottofletcher** [comment]
oh weird! ok, if I see it again I'll do a screenshot w/my browser extension and post it here
