### ISSUE TITLE
Usersnap Feedback - I haven't seen the map on the site for the last five days or so. -  pat

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#81]
**Comment**: I haven't seen the map on the site for the last five days or so.
-  pat
[Open #95 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/95)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-15/01-13/64bb6260-2f54-465a-9a87-37a1f701bc5a.png'>![Usersnap Feedback - I haven't seen the map on the site for the last five days or so. -  pat](https://usersnappublic.s3.amazonaws.com/2017-08-15/01-13/cf642bea-88a0-49c3-8134-c9360fb31bdc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-15/01-13/64bb6260-2f54-465a-9a87-37a1f701bc5a.png'>Download original image</a>

**Browser**: Chrome 60 (Windows 10)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1920 x 1200 **Browser size**: 2400 x 1337

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Fixed. Was due to updating a React component, backed the update out.
