### ISSUE TITLE
Usersnap Feedback - I link verso il sito laboratorio-puc-olbia.it non funzionano più

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#812]
**Sender**: giacomo.calvisi@gmail.com
**Comment**: I link verso il sito laboratorio-puc-olbia.it non funzionano più
[Open #510 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/510)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-29/22-32/91cec121-6ffa-4746-a618-cdbf6db3627f.png'>![Usersnap Feedback - I link verso il sito laboratorio-puc-olbia.it non funzionano più](https://usersnappublic.s3.amazonaws.com/2019-07-29/22-32/64e1340a-9c99-419e-bb35-bda992bf8ace.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-29/22-32/91cec121-6ffa-4746-a618-cdbf6db3627f.png'>Download original image</a>

**Browser**: Safari 12 (iOS)
**Referer**: [https://participedia.net/case/5236#](https://participedia.net/case/5236#)
**Screen size**: 768 x 1024 **Browser size**: 768 x 985

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher all the reference links for this article on this domain, laboratorio-puc-olbia.it, are no longer working.

**Comment by scottofletcher** [comment]
thanks! there are approx. 1 billion dead links... I had to use the Wayback Machine for this one
