### ISSUE TITLE
Usersnap Feedback - Grey font?

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#814]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Grey font?
[Open #511 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/511)

<a href='https://usersnappublic.s3.amazonaws.com/2019-08-07/18-16/aab8ec3e-6887-4228-abf1-d5a9c5fb8892.png'>![Usersnap Feedback - Grey font?](https://usersnappublic.s3.amazonaws.com/2019-08-07/18-16/ffd77ed0-181e-4a82-ad06-6e5a49c5a5d0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-08-07/18-16/aab8ec3e-6887-4228-abf1-d5a9c5fb8892.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/case/5988](https://participedia.net/case/5988)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 774

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
The colouring only affects the editing prompt. Here's another case for comparison: 

![image](https://user-images.githubusercontent.com/29512491/62639388-41624100-b8f4-11e9-9931-95722be60f4d.png)

**Comment by jesicarson** [comment]
@scottofletcher i am looking at these snaps and also at the live site, but i can't see what you mean about a grey font anywhere...  can you clarify?

**Comment by scottofletcher** [comment]
It's really really hard to tell, but the editing prompt ('Note: the following entry is a stub. Please help us complete it') is a shade lighter in the Usersnap
