### ISSUE TITLE
Usersnap Feedback - The drop down menu cuts off long values (ie: purpose/goal, will upload a s[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#819]
**Sender**: jesi.carson@gmail.com
**Comment**: The drop down menu cuts off long values (ie: purpose/goal, will upload a screenshot if i can, its not showing here)
[Open #516 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/516)

<a href='https://usersnappublic.s3.amazonaws.com/2019-08-15/18-01/b3c23976-58ce-42ec-aea1-9ff699a58534.png'>![Usersnap Feedback - The drop down menu cuts off long values (ie: purpose/goal, will upload a s(...)](https://usersnappublic.s3.amazonaws.com/2019-08-15/18-01/5970177f-6458-429d-95f8-af48768e8551.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-08-15/18-01/b3c23976-58ce-42ec-aea1-9ff699a58534.png'>Download original image</a>

**Browser**: Chrome 76 (macOS Mojave)
**Referer**: [https://participedia.net/case/6023/edit?full=1](https://participedia.net/case/6023/edit?full=1)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
This is probably a known issue, but just in case:

![Screen Shot 2019-08-15 at 9 01 15 AM](https://user-images.githubusercontent.com/13560530/63109521-4a7b8f80-bf3e-11e9-9e10-88d8860bb58b.png)

**Comment by ascott** [comment]
i'm not sure what the solution should be here. 

on very large screens (1680px+) the options get cut off when the select is as wide as it can get. 
![Screenshot 2019-08-17 21 29 54](https://user-images.githubusercontent.com/130878/63220154-c6402c80-c136-11e9-9888-514f316e79e4.png)

also, when the browser window is less wide but the screen is larger, the select will stretch out past the edge of the browser window and there is still not enough space to show all of the option text. 
![Screenshot 2019-08-17 21 33 35](https://user-images.githubusercontent.com/130878/63220152-c17b7880-c136-11e9-83a7-db700c955133.png)

a couple possible solutions could be:
- set a limit on number of characters for option text and edit all values to fit this length
-- this could be hard to enforce across languages
- design & built a custom select element so we can customize the way options are displayed, and wrap long option texts on to multiple lines.

@jesicarson  do you have other ideas of how to fix this?

**Comment by jesicarson** [comment]
Do we have a custom select element built for the user profile drop down?

Too bad there’s no text wrapping option in the one we’re using for forms. 

It is actually really necessary for all that text because it explains what the values mean and gives examples. The cut off part that was missing helped me to find the right option in the case I was entering (I checked the spreadsheet). 
I guess we could make a glossary page for the values and other terms? But this would be a process in itself. 

I’m honestly not sure what the best solution is. How complex would the custom text wrapping element be? It seems like it will add up to a lot of work for all those drop downs?

**Comment by ascott** [comment]
the element we use for the profile dropdown menu is similar but can't be swapped in for this use case.

the native HTML select element is unfortunately not very style-able which is why we don't have text wrapping capabilities with it. 

here's an open-source standalone autocomplete/select component that looks like it would work well for us. it's written in vanilla js and doesn't have any other dependencies.

I edited the first option to show how it would work with multi-line options, and I can edit the styling to match our form design.

![Screenshot 2019-08-20 16 24 42](https://user-images.githubusercontent.com/130878/63391385-130a4a00-c367-11e9-8377-e99612b75fbd.png)


https://nostyle.herokuapp.com/examples/autocomplete

**Comment by jesicarson** [comment]
@ascott This option looks good to me, and does the job. Can we style the arrow so its not so huge? No big deal if not :P Would it be a big undertaking to update all our drop down menus to this new component style?

**Comment by ascott** [comment]
yep, i can change the style of the arrow to match our current select
design. it shouldn’t take too long to replace our current selects with this
one.

**Comment by jesicarson** [comment]
Great! looks like a good fix to me!

**Comment by ascott** [comment]
fixed with https://github.com/participedia/api/pull/734

**Comment by scottofletcher** [comment]
Is this closed? I'm really struggling with these new menus - much preferred the old ones

**Comment by ascott** [comment]
@scottofletcher what difficulties are you having?

**Comment by scottofletcher** [comment]
it's kind of hard to explain - can we schedule a super quick zoom call and I can share my screen?

**Comment by ascott** [comment]
let’s sync when @jesicarson is back next week so she can hear your feedback too

**Comment by jesicarson** [comment]
Hi @scottofletcher I will slack you about this.

**Comment by ascott** [comment]
discussion from this issue: https://github.com/participedia/usersnaps/issues/847
i will adjust the height of the drop down to show ~8 items at a time.

**Comment by ascott** [comment]
pr here for that change: https://github.com/participedia/api/pull/754

**Comment by scottofletcher** [comment]
> discussion from this issue: #847
> i will adjust the height of the drop down to show ~8 items at a time.

can we do 10? it used to be significantly more

**Comment by ascott** [comment]
@scottofletcher it's between 8-10 but is dependant on if the option text is really long and wraps on to multiple lines.
