### ISSUE TITLE
Usersnap Feedback - Location listed twice. And in the second location field the text is cut off.

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#82]
**Sender**: jesi.carson@gmail.com
**Comment**: Location listed twice. And in the second location field the text is cut off.
[Open #96 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/96)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-18/23-54/f0a40e46-a1c3-4eeb-ac0e-f7fe3f96fa0c.png'>![Usersnap Feedback - Location listed twice. And in the second location field the text is cut off.](https://usersnappublic.s3.amazonaws.com/2017-08-18/23-54/8fe80597-5b97-4974-a531-b550e1cc55d4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-18/23-54/f0a40e46-a1c3-4eeb-ac0e-f7fe3f96fa0c.png'>Download original image</a>

**Browser**: Chrome 59 (macOS Sierra)
**Referer**: [https://participedia.xyz/profile/edit](https://participedia.xyz/profile/edit)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@dethe if possible fix before user testing
