### ISSUE TITLE
Usersnap Feedback - got logged out while editing a case. i was online no more than 20 minutes [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#820]
**Sender**: jesi.carson@gmail.com
**Comment**: got logged out while editing a case. i was online no more than 20 minutes though... booooo this does suck. lol. i feel your pain scott.
[Open #517 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/517)

<a href='https://usersnappublic.s3.amazonaws.com/2019-08-15/18-10/85e79019-31fe-48ee-8637-f5c2d9710450.png'>![Usersnap Feedback - got logged out while editing a case. i was online no more than 20 minutes (...)](https://usersnappublic.s3.amazonaws.com/2019-08-15/18-10/72b153da-7dea-41f1-ab89-c1079e2fde05.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-08-15/18-10/85e79019-31fe-48ee-8637-f5c2d9710450.png'>Download original image</a>

**Browser**: Chrome 76 (macOS Mojave)
**Referer**: [https://participedia.net/case/6023/edit?full=1](https://participedia.net/case/6023/edit?full=1)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
luckily when you click refresh session, it logs you back in and your form inputs are still there. so its not as bad as i thought at first. whew! thanks for that backup alanna!

**Comment by jesicarson** [comment]
obviously i dont enter cases very often (meep)

**Comment by ascott** [comment]
i think we are seeing automatic logouts happening more often because we are having some memory issues which is causing the app to stop and restart. Once we iron out the memory issues, we should see this happen less often. Will post here when I know more.

**Comment by ascott** [comment]
fixed with https://github.com/participedia/api/pull/723
