### ISSUE TITLE
Usersnap Feedback - There's no value under types of interaction for "creative or art-based" in[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#821]
**Sender**: jesi.carson@gmail.com
**Comment**: There's no value under types of interaction for "creative or art-based" interaction.
[Open #518 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/518)

<a href='https://usersnappublic.s3.amazonaws.com/2019-08-15/18-14/a0109926-6e02-46cb-9f55-992917728b5b.png'>![Usersnap Feedback - There's no value under types of interaction for "creative or art-based" in(...)](https://usersnappublic.s3.amazonaws.com/2019-08-15/18-14/8377a7c5-5f92-4e77-be91-27a6787b9287.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-08-15/18-14/a0109926-6e02-46cb-9f55-992917728b5b.png'>Download original image</a>

**Browser**: Chrome 76 (macOS Mojave)
**Referer**: [https://participedia.net/case/6023/edit?full=1](https://participedia.net/case/6023/edit?full=1)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson is there supposed to be an option for this already, or is this a new option that you want to add?

**Comment by jesicarson** [comment]
no, this was just form feedback, but we won't be doing model changes anytime soon so we can probably close this. there's also the general types of methods value: 'participatory arts', which probably covers this well enough.
