### ISSUE TITLE
Usersnap Feedback - Not sure why this location is displaying like this. It would be better if [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#823]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Not sure why this location is displaying like this. It would be better if it had the name of the municipality (Deep Cove) as entered in the location field rather than the postal code
[Open #520 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/520)

<a href='https://usersnappublic.s3.amazonaws.com/2019-08-15/20-15/f4ac14da-909a-4fc1-b40a-b4985c6ef627.png'>![Usersnap Feedback - Not sure why this location is displaying like this. It would be better if (...)](https://usersnappublic.s3.amazonaws.com/2019-08-15/20-15/92355c59-557a-4932-bcb2-01746b3a83d0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-08-15/20-15/f4ac14da-909a-4fc1-b40a-b4985c6ef627.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/case/6019](https://participedia.net/case/6019)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher This looks like an issue with the data returned from Google Maps. It looks like deep cove is a neighborhood and not a city, and so when you select Deep Cove, it only saves the province, country and postal code. If you use North Vancouver instead of Deep Cove, it will save/display the name of the city as well.

**Comment by scottofletcher** [comment]
ok, I'm not quite understanding this - why can I select it from the drop down if it's not going to display in the sidebar? shouldn't we only give people options that work in both the editing field and the reader view?

**Comment by ascott** [comment]
@scottofletcher yeah, ideally the google suggestions would only show options that we will display in the reader view. In this case I would expect the reader view to display the city name of North Vancouver if you were to select Deep Cove, North Vancouver, BC, etc from the dropdown. This is the behaviour we see if we use a different neighborhood. For example if you search and select Mount Pleasant, the city is displayed as Vancouver in the side bar.

**Comment by scottofletcher** [comment]
ok, is there a way to standardize that behaviour? as a reader, I wouldn't have a clue where this was based on the postal code and the province

**Comment by ascott** [comment]
@scottofletcher do you have examples of other locations/address' where you are seeing this behaviour? 

i would have to do some research to see what other address' this is happening with and figure out why this is happening with some neighborhood names and not with others. akaict this is not related to how i have implemented the location input, but has to do with the data being sent back from the Google Maps api/service.  if we are not seeing this issue very often, and since there is a quick work around via the UI, i would suggest we not prioritize debugging this right now. @jesicarson what do you think?

**Comment by jesicarson** [comment]
Agree this is not a priority, but lets leave it in the queue for consideration after some other issues are taken care of. Thanks both!

**Comment by scottofletcher** [comment]
yeah defs not a priority, but probably something to consider. is this affecting the data we collect in the csv? that would make it worth looking into (but not necessarily a higher priority)

@ascott I'll keep my eyes peeled for more examples! I know in the past we've had some addresses change from a street address or a building (eg. Vancouver Int'l Airport) to a city, but this case was more extreme (and - in my opinion - diminishes the user experience more)

**Comment by ascott** [comment]
related issue: https://github.com/participedia/usersnaps/issues/858
