### ISSUE TITLE
Usersnap Feedback - FB chat in groups will no longer function after aug 22. We need to adjust [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#829]
**Sender**: jesi.carson@gmail.com
**Comment**: FB chat in groups will no longer function after aug 22. We need to adjust or delete this copy to point to a new system, or delete this section. https://www.facebook.com/community/education/blog/facebook-group-chat-removal
[Open #526 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/526)

<a href='https://usersnappublic.s3.amazonaws.com/2019-08-20/17-17/2397884f-9353-408a-b3d6-050c9f8b24d3.png'>![Usersnap Feedback - FB chat in groups will no longer function after aug 22. We need to adjust (...)](https://usersnappublic.s3.amazonaws.com/2019-08-20/17-17/b8630087-fb08-49eb-bfec-085be09dfa50.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-08-20/17-17/2397884f-9353-408a-b3d6-050c9f8b24d3.png'>Download original image</a>

**Browser**: Safari 12 (iOS)
**Referer**: [https://participedia.net/teaching](https://participedia.net/teaching)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott whatever we decide has to happen before thursday so adding p1 label (wish we had listened to you and avoided facebook to begin with!! lol)

**Comment by ascott** [comment]
@jesicarson what would do you like to do here? do you want to change this section or delete it?
