### ISSUE TITLE
Usersnap Feedback - There's no option to enter an organization that might not belong on partic[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#83]
**Sender**: jesi.carson@gmail.com
**Comment**: There's no option to enter an organization that might not belong on participedia. We need a field for this. 
[Open #97 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/97)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-18/23-56/e3884040-f285-41eb-a6e1-8a03fca7d000.png'>![Usersnap Feedback - There's no option to enter an organization that might not belong on partic(...)](https://usersnappublic.s3.amazonaws.com/2017-08-18/23-56/daa1b6e4-7a76-4f85-a389-45fb9495254e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-18/23-56/e3884040-f285-41eb-a6e1-8a03fca7d000.png'>Download original image</a>

**Browser**: Chrome 59 (macOS Sierra)
**Referer**: [https://participedia.xyz/profile/edit](https://participedia.xyz/profile/edit)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@dethe would be good to have prior to user testing (particularly as we'll be asking ppedia folks to create user accounts AND Participedia is not currently published as an Org on participedia)

**Comment by jesicarson** [comment]
@dethe if possible, allow the user to enter an org name that isn't in the database in the same form field.

**Comment by dethe** [comment]
Dev: Determine if we can use the existing widget as an input field for text if no matching text is found.

**Comment by andreadelrio** [comment]
We decided to simplify the profile page.
