### ISSUE TITLE
Usersnap Feedback - I did a filtered search for "process/online" -- that was the only filter I [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#835]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I did a filtered search for "process/online" -- that was the only filter I used -- and the result was all 1210 cases. That can't be right
[Open #532 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/532)

<a href='https://usersnappublic.s3.amazonaws.com/2019-08-23/20-42/770c50e8-22b8-4eed-be46-79e77c7824a3.png'>![Usersnap Feedback - I did a filtered search for "process/online" -- that was the only filter I (...)](https://usersnappublic.s3.amazonaws.com/2019-08-23/20-42/92183972-3398-46a3-a88d-0ba2a879e9f9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-08-23/20-42/770c50e8-22b8-4eed-be46-79e77c7824a3.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/?selectedCategory=case&page=1&facetoface_online_or_both=online](https://participedia.net/?selectedCategory=case&page=1&facetoface_online_or_both=online)
**Screen size**: 1920 x 1200 **Browser size**: 1536 x 832

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
verified this bug and just filed another one related to "clear all" not working correctly.
