### ISSUE TITLE
Usersnap Feedback - Am I right in thinking that I can only click on the sidebar data that's av[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#837]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Am I right in thinking that I can only click on the sidebar data that's available in the card-view faceted search menu? shouldn't we expand it? that way people have even more ways to sort entries
[Open #534 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/534)

<a href='https://usersnappublic.s3.amazonaws.com/2019-08-23/21-33/660e2c81-ee7d-4654-95ba-443ef141292e.png'>![Usersnap Feedback - Am I right in thinking that I can only click on the sidebar data that's av(...)](https://usersnappublic.s3.amazonaws.com/2019-08-23/21-33/898b6458-265c-4f4c-98a2-acad7d817623.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-08-23/21-33/660e2c81-ee7d-4654-95ba-443ef141292e.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/case/5730](https://participedia.net/case/5730)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Basically we were able to do this linking easily because the work was already done to make these particular fields available as search filters. Adding new fields is possible, but for now we are working with the fields that you identified as the most important to filter results by.
