### ISSUE TITLE
Usersnap Feedback - What happened to the menus? I used to be able to see at least 10-15 items, [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#847]
**Sender**: scottowenfletcher@gmail.com
**Comment**: What happened to the menus? I used to be able to see at least 10-15 items, now I have to perform some precision-scrolling to find the right one
[Open #544 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/544)

<a href='https://usersnappublic.s3.amazonaws.com/2019-09-04/02-19/0647f389-3850-4000-b420-ed286710bbdd.png'>![Usersnap Feedback - What happened to the menus? I used to be able to see at least 10-15 items, (...)](https://usersnappublic.s3.amazonaws.com/2019-09-04/02-19/11202b77-c7e1-4267-a27d-cc97614051e6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-09-04/02-19/0647f389-3850-4000-b420-ed286710bbdd.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/case/5925/edit?full=1](https://participedia.net/case/5925/edit?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 774

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
there is a discussion about this change here: https://github.com/participedia/usersnaps/issues/819

**Comment by jesicarson** [comment]
@ascott can the default height of the drop down menu be customized? if this is complicated, no worries, but scott has a point that scrolling really zipps you though the list of values quickly, and they're kinda hard to see with only 5 of them visible at a time. Having 8-10 values visible vertically in the drop down should improve this, if possible/easy.

**Comment by ascott** [comment]
@jesicarson yeah, i can adjust the height of the drop down menu to show 8-10 options
