### ISSUE TITLE
Usersnap Feedback - Another thing about the new menu: I use to be able to skip down to a selec[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#848]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Another thing about the new menu: I use to be able to skip down to a selection by typing the first letter in its name. doesn't work any more
[Open #545 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/545)

<a href='https://usersnappublic.s3.amazonaws.com/2019-09-04/02-20/10873c7a-5940-4510-a2ad-a3417e94327a.png'>![Usersnap Feedback - Another thing about the new menu: I use to be able to skip down to a selec(...)](https://usersnappublic.s3.amazonaws.com/2019-09-04/02-20/b6ff1757-f82e-4596-b3ee-f4d239c07330.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-09-04/02-20/10873c7a-5940-4510-a2ad-a3417e94327a.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/case/5925/edit?full=1](https://participedia.net/case/5925/edit?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 774

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher This component still has that functionality. You can filter and navigate to a selection by typing in the search input at the top of the drop-down and then either use your arrow keys and press enter or your mouse to select the item you want.

![participedia-new-select-windows10-chrome76](https://user-images.githubusercontent.com/130878/64226672-2522d700-ce95-11e9-9d10-4995587c15f3.gif)

**Comment by scottofletcher** [comment]
ah ok thanks!
