### ISSUE TITLE
Usersnap Feedback - Used quick submit to enter this org.  After I added the main website in th[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#85]
**Sender**: jesi.carson@gmail.com
**Comment**: Used quick submit to enter this org. 
After I added the main website in the relevant links section, I clicked add another link, and added a link to a podcast on soundcloud (https://soundcloud.com/ncddpodcast/talking-politics-with-bring-it-to-the-table), but it doesn't show up on the org reader page - maybe it's too long?? 
Also the vimeo video from the url I added in the media section doesn't show up on the reader page (i think there's already an issue for this). 
[Open #99 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/99)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-19/00-24/8dd9ef70-dc16-45f8-bd58-bf10289bf94e.png'>![Usersnap Feedback - Used quick submit to enter this org.  After I added the main website in th(...)](https://usersnappublic.s3.amazonaws.com/2017-08-19/00-24/81c5a891-e1cd-4b4f-8a05-2240d9743278.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-19/00-24/8dd9ef70-dc16-45f8-bd58-bf10289bf94e.png'>Download original image</a>

**Browser**: Chrome 59 (macOS Sierra)
**Referer**: [https://participedia.xyz/organization/4611](https://participedia.xyz/organization/4611)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@dethe would be good to fix before user testing, **at least for cases** if the same problem arises there (which i believe it does, at least for video)

**Comment by dethe** [comment]
Looks like the problem is with how we send lists of items to the server, tracking this here: https://github.com/participedia/frontend/pull/186
