### ISSUE TITLE
Usersnap Feedback - Was this entry created using the German interface? if so, the headings are [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#854]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Was this entry created using the German interface? if so, the headings are super outdated and they're also not in the right format (should be H2, not H3)
[Open #551 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/551)

<a href='https://usersnappublic.s3.amazonaws.com/2019-09-06/18-29/f8fbca50-222d-4c5e-8cf4-a70c6a880db2.png'>![Usersnap Feedback - Was this entry created using the German interface? if so, the headings are (...)](https://usersnappublic.s3.amazonaws.com/2019-09-06/18-29/a1fe2951-7e37-4eb6-9c6c-25c3405c2715.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-09-06/18-29/f8fbca50-222d-4c5e-8cf4-a70c6a880db2.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/organization/4560](https://participedia.net/organization/4560)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
IGNORE I'm an id
