### ISSUE TITLE
Usersnap Feedback - Limit year in date-entry form (YYYY-mm-dd) to 4 digits (it's currently set to 7)

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#856]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Limit year in date-entry form (YYYY-mm-dd) to 4 digits (it's currently set to 7)
[Open #553 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/553)

<a href='https://usersnappublic.s3.amazonaws.com/2019-09-10/01-17/a3c9a98c-bafb-4eb9-a8f6-8e4c38bc1209.png'>![Usersnap Feedback - Limit year in date-entry form (YYYY-mm-dd) to 4 digits (it's currently set to 7)](https://usersnappublic.s3.amazonaws.com/2019-09-10/01-17/39318678-20f4-4bfe-8c6a-ab1c7e0fce0a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-09-10/01-17/a3c9a98c-bafb-4eb9-a8f6-8e4c38bc1209.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/case/135](https://participedia.net/case/135)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher what date should this be?

**Comment by ascott** [comment]
the start date and end date fields are limited to yyyy-mm-dd currently. 

<img width="845" alt="Screenshot 2019-09-09 16 21 13" src="https://user-images.githubusercontent.com/130878/64572853-d904e600-d31d-11e9-892a-7e65b247a601.png">

**Comment by jesicarson** [comment]
actually, the form field allows you to enter more digits, and then if you publish that it shows "invalid date" on the sidebar: 
![Screen Shot 2019-09-09 at 4 32 14 PM](https://user-images.githubusercontent.com/13560530/64573220-6c8ae680-d31f-11e9-9ed3-788a6c5f8a0d.png)

**Comment by jesicarson** [comment]
Not that many people will likely do that, but still.
