### ISSUE TITLE
Usersnap Feedback - Wrong dates? I'm pretty sure it's still the 10th

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#859]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Wrong dates? I'm pretty sure it's still the 10th
[Open #556 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/556)

<a href='https://usersnappublic.s3.amazonaws.com/2019-09-11/02-49/47562a0e-4c92-4e8e-8c57-86b640185605.png'>![Usersnap Feedback - Wrong dates? I'm pretty sure it's still the 10th](https://usersnappublic.s3.amazonaws.com/2019-09-11/02-49/c676d94b-1321-4ea8-8b0f-891a8260e0d6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-09-11/02-49/47562a0e-4c92-4e8e-8c57-86b640185605.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/case/6077](https://participedia.net/case/6077)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
via @scottofletcher  on slack:
the cases I entered yesterday all say sept 11
and there's no time stamps for post date
which messes up my sorting

**Comment by jesicarson** [comment]
via @dethe  on slack: If dates are off by about 7 hours it's because they're in UTC. Converting to local time would be do-able, but we'd have to know what local time is for the user requesting the CSV.

note: main problem might be the time stamps for post date, not the delay in post date. @scottofletcher - can you still sort by date, even if the time is 0000?

**Comment by scottofletcher** [comment]
@jesicarson yes but it's not as accurate (tends to default to alphabetical if they all have the same date) which causes problems when I'm transferring info from the csv export to the [edit-tracking Google Sheet](https://docs.google.com/spreadsheets/d/1uiSNHVzTWByC9ZgawKLcE7WTVyiKELQFxn_lthQDgFI/edit#gid=0)
