### ISSUE TITLE
Usersnap Feedback - BUG: I can't click "quick submit", and it says "method needs a name" howev[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#86]
**Sender**: jesi.carson@gmail.com
**Comment**: BUG: I can't click "quick submit", and it says "method needs a name" however, there is a name entered in the title field above. 

Also note that in tags, there are 3 instances of the tag "protest" - we need to remove any duplicates. 
[Open #100 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/100)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-19/00-32/0523448c-757b-4fa2-a4fa-21bf72926a96.png'>![Usersnap Feedback - BUG: I can't click "quick submit", and it says "method needs a name" howev(...)](https://usersnappublic.s3.amazonaws.com/2017-08-19/00-32/99de0c3a-ab61-41fa-9929-27926cd2d4fc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-19/00-32/0523448c-757b-4fa2-a4fa-21bf72926a96.png'>Download original image</a>

**Browser**: Chrome 59 (macOS Sierra)
**Referer**: [https://participedia.xyz/new/method](https://participedia.xyz/new/method)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Fixed in Frontend PR https://github.com/participedia/frontend/pull/569
