### ISSUE TITLE
Usersnap Feedback - Image shows up on reader view but not card view (see https://participedia.[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#860]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Image shows up on reader view but not card view (see https://participedia.net/method/6082)
[Open #557 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/557)

<a href='https://usersnappublic.s3.amazonaws.com/2019-09-13/02-22/a10e94ba-0123-481b-ac05-f29e2f692ced.png'>![Usersnap Feedback - Image shows up on reader view but not card view (see https://participedia.(...)](https://usersnappublic.s3.amazonaws.com/2019-09-13/02-22/3fe90ebf-2b24-4b97-a5e4-94652812fc58.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-09-13/02-22/a10e94ba-0123-481b-ac05-f29e2f692ced.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
i cannot replicate it in my local and live, but i assume its the image url is invalid, on example,
the image url is https://s3.amazonaws.com/uploads.participedia.xyz/871bc7ec-0963-4b99-a45f-817e619ceb86-"Creek Show" SXSW Place by Design 2019 Finalist. It is invalid property value
because of the quotation mark found as part of the url, since on the list page we used background-image to render the image, but on the details page, it uses <img>. I suggest we fix this image manually, but we should filter these special characters, and remove them.

**Comment by jesicarson** [comment]
@paninee looks like “creek show” shouldn’t be part of the URL. It’s actually the first part of the image title...

**Comment by jesicarson** [comment]
But the URL is correct in the form, and the image shows up in some places but not others. ?? Or are you saying we can’t use quotation marks in image titles?

![98ACB09F-8F58-4E81-A9C0-A152EBB617D2](https://user-images.githubusercontent.com/13560530/68693075-78677480-052b-11ea-955c-dd6211ca5caf.png)

**Comment by ascott** [comment]
@jesicarson @paninee i believe this is a remnant of an old bug, where we were using the image title in the file name, but have since stopped doing that since certain characters cause issues in the file name if they are rendered as a background-image rather than in an image tag. so i think @paninee you are right that we should fix these images manually on a one-off basis. to fix them manually via the ui, we would save the affected image (in the place where it is displayed), then delete the image from the entry, and reupload it again and save.

**Comment by jesicarson** [comment]
Ok will do! Thanks!
