### ISSUE TITLE
Usersnap Feedback - I thought there was an option to leave this blank, but it seems to only be [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#865]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: I thought there was an option to leave this blank, but it seems to only be yes/no? If I don't see evidence of it, I prefer not to fill it in.
[Open #562 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/562)

<a href='https://usersnappublic.s3.amazonaws.com/2019-09-14/11-49/556f15f1-d46b-42db-af33-d15a44632510.png'>![Usersnap Feedback - I thought there was an option to leave this blank, but it seems to only be (...)](https://usersnappublic.s3.amazonaws.com/2019-09-14/11-49/7ae1f8d4-9ddc-4a74-bda9-83e2cffd9aa6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-09-14/11-49/556f15f1-d46b-42db-af33-d15a44632510.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/case/5872/edit?full=1](https://participedia.net/case/5872/edit?full=1)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 608

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Good point. Can you deselect your choice? If not we’ll need to add a way to do that. @ascott

**Comment by ascott** [comment]
@jesicarson the choice can be deselected by clicking it again. 

if that is not clear though, we could add an x icon to clear/deselect the option like this:
![Screenshot 2019-09-16 11 54 10](https://user-images.githubusercontent.com/130878/64985051-e0297800-d878-11e9-80c4-7b8cc56cd2e8.png)

**Comment by jesicarson** [comment]
@ascott the x works. although the red makes it look like I might have done something wrong by entering that vaue.. Could we use the same/similar X used in other fields to align with our existing visual system for deselecting values? 
Or, another option, sometimes in drop downs the placeholder text remains as the top item in the list of values, and you can just select that (sort of feels like, ok im intentionally leaving this blank).  Is that a possibility?

**Comment by ascott** [comment]
@jesicarson yes, i can style the X to match the X in other form elements. afaict, there isn't way to show the placeholder at the top and select that to deselect the field.

**Comment by jesicarson** [comment]
@ascott ok lets try the more subtle X (no rush tho)
