### ISSUE TITLE
Usersnap Feedback - I can't select both 'Informal participation' and 'informal conversation sp[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#869]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I can't select both 'Informal participation' and 'informal conversation spaces'. every time I try to select the other one, it replaces my current selection
[Open #566 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/566)

<a href='https://usersnappublic.s3.amazonaws.com/2019-09-18/19-40/84e49476-ead0-473d-ac6d-04283ba7aaba.png'>![Usersnap Feedback - I can't select both 'Informal participation' and 'informal conversation sp(...)](https://usersnappublic.s3.amazonaws.com/2019-09-18/19-40/346df96d-afdd-41fe-abde-dc41091e2f39.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-09-18/19-40/84e49476-ead0-473d-ac6d-04283ba7aaba.png'>Download original image</a>

**Browser**: Chrome 77 (Windows 10)
**Referer**: [https://participedia.net/case/5560/edit?full=1](https://participedia.net/case/5560/edit?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher i took a look and this case is saved with both of the items you listed, so it looks like it was working in the end? i also tested this field locally and wasn't able to reproduce it. let me know if you see something like this again.

**Comment by scottofletcher** [comment]
yeah, eventually I got it to work by publishing and then returning to the edit screen. and this is the first time anything like this happened to me, so I'll be sure to usersnap if it happens again
