### ISSUE TITLE
Usersnap Feedback - The Login button is not working for me. amberfj@gmail.com

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#87]
**Sender**: amberfj@gmail.com
**Comment**: The Login button is not working for me. amberfj@gmail.com
[Open #101 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/101)
**Notes**:
 - (1) The Login button is not working for me. amberfj@gmail.com

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-29/03-16/9295bc6f-e190-4fa1-942c-2b6cd66a616c.png'>![Usersnap Feedback - The Login button is not working for me. amberfj@gmail.com](https://usersnappublic.s3.amazonaws.com/2017-08-29/03-16/bbc950ff-4728-4f9f-8a6c-75221f9f7d63.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-29/03-16/9295bc6f-e190-4fa1-942c-2b6cd66a616c.png'>Download original image</a>

**Browser**: Chrome 60 (macOS Sierra)
**Referer**: [http://participedia.xyz/](http://participedia.xyz/)
**Screen size**: 2560 x 1440 **Browser size**: 2310 x 1219

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
I'm seeing that on my local version now too, which was working earlier.

**Comment by dethe** [comment]
Fixed in PR https://github.com/participedia/frontend/pull/594
