### ISSUE TITLE
Usersnap Feedback - strange formatting on select type page for submit. something up with colum[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#88]
**Sender**: jesi.carson@gmail.com
**Comment**: strange formatting on select type page for submit. something up with columns? should be centered on the page with "select type" above the option buttons. 
[Open #102 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/102)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/18-50/fd77f459-17b8-40ec-bd59-ceb8f4b0c62d.png'>![Usersnap Feedback - strange formatting on select type page for submit. something up with colum(...)](https://usersnappublic.s3.amazonaws.com/2017-08-30/18-50/5b4df9d8-547d-41b1-95ee-63ab31420a67.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/18-50/fd77f459-17b8-40ec-bd59-ceb8f4b0c62d.png'>Download original image</a>

**Browser**: Chrome 60 (macOS Sierra)
**Referer**: [https://participedia.xyz/new](https://participedia.xyz/new)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by andreadelrio** [comment]
This broke when we updated Bootstrap. It's fixed now.
