### ISSUE TITLE
Usersnap Feedback - It is not clear to us what further information is required for this case s[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#881]
**Sender**: Claire.bynner@glasgow.ac.uk
**Comment**: It is not clear to us what further information is required for this case study. you have asked us to verify its content.  How can we verify?  we have added as much information as we can
[Open #577 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/577)

<a href='https://usersnappublic.s3.amazonaws.com/2019-09-30/23-57/1a751eb0-18ad-49da-8f05-78e725d21114.png'>![Usersnap Feedback - It is not clear to us what further information is required for this case s(...)](https://usersnappublic.s3.amazonaws.com/2019-09-30/23-57/9d09de15-e00f-41f5-bf0c-31b121702edb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-09-30/23-57/1a751eb0-18ad-49da-8f05-78e725d21114.png'>Download original image</a>

**Browser**: Safari 13 (macOS Mojave)
**Referer**: [https://participedia.net/case/5640/edit](https://participedia.net/case/5640/edit)
**Screen size**: 1366 x 768 **Browser size**: 1264 x 609

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
ok just emailed Claire and cc'd you
