### ISSUE TITLE
Usersnap Feedback - It's doing that weird thing again where I can't select more than one optio[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#885]
**Sender**: scottowenfletcher@gmail.com
**Comment**: It's doing that weird thing again where I can't select more than one option. I'll upload the GIF right now
[Open #581 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/581)

<a href='https://usersnappublic.s3.amazonaws.com/2019-10-04/02-08/d1a96419-5ba0-4a18-a30c-ce805d98f3ef.png'>![Usersnap Feedback - It's doing that weird thing again where I can't select more than one optio(...)](https://usersnappublic.s3.amazonaws.com/2019-10-04/02-08/8adc94c2-543f-493c-82ec-2ec34feff650.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-10-04/02-08/d1a96419-5ba0-4a18-a30c-ce805d98f3ef.png'>Download original image</a>

**Browser**: Chrome 77 (Windows 10)
**Referer**: [https://participedia.net/case/6110/edit?full=1](https://participedia.net/case/6110/edit?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 774

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment]
![Selection bug again](https://user-images.githubusercontent.com/29512491/66172370-6aefce00-e600-11e9-8af2-9cdb460b318f.gif)
