### ISSUE TITLE
Usersnap Feedback - size of form fields is too short, should match the length of the longer fi[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#89]
**Sender**: jesi.carson@gmail.com
**Comment**: size of form fields is too short, should match the length of the longer field shown here for media. column issue?
[Open #103 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/103)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/18-59/8b179637-9032-4b43-8bb3-fba027c4891c.png'>![Usersnap Feedback - size of form fields is too short, should match the length of the longer fi(...)](https://usersnappublic.s3.amazonaws.com/2017-08-30/18-59/c2ecef14-5a41-44bb-9bab-42386c910267.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/18-59/8b179637-9032-4b43-8bb3-fba027c4891c.png'>Download original image</a>

**Browser**: Chrome 60 (macOS Sierra)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Fixed in PR https://github.com/participedia/frontend/pull/606
