### ISSUE TITLE
Usersnap Feedback - For Jesi - I was looking for info on Hollie and noticed that part of this [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#898]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: For Jesi - I was looking for info on Hollie and noticed that part of this is incorrect. Instead of 'U of Southampton'  it should read 'New America' -- Please fix this asap b/c she is helping me make contacts related to fundraising. Thanks!
[Open #593 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/593)

<a href='https://usersnappublic.s3.amazonaws.com/2019-10-14/20-59/0329b316-fc93-44df-89cb-8ca527ca1e73.png'>![Usersnap Feedback - For Jesi - I was looking for info on Hollie and noticed that part of this (...)](https://usersnappublic.s3.amazonaws.com/2019-10-14/20-59/c14e696c-6860-4d3d-bbaf-7f69669cb120.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-10-14/20-59/0329b316-fc93-44df-89cb-8ca527ca1e73.png'>Download original image</a>

**Browser**: Chrome 77 (Windows 10)
**Referer**: [https://participedia.net/about](https://participedia.net/about)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1040

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully is the following correct? Once you confirm I'll get Alanna to prioritize this edit. Thx!
 
**Hollie Russon-Gilman**
Open Technology Institute
New America

**Comment by plscully** [comment]
@jesicarson Yes, this is correct. ... BTW, do we have to change the French translation when this happens, or will PhraseApp perform an auto-correct?

**Comment by jesicarson** [comment]
Oh that reminds me that we may be able to make this change directly in phraseapp (in which case we’d know that the strings need to be reverified for French). Unless the job titles and institutions are not localizable, I can’t remember if we included them in phraseapp or not. Signing off for today but I’ll check this tomorrow and get back to you.

**Comment by ascott** [comment]
@jesicarson @plscully sorry i missed this back in October. I will update today. The department names and institution names are not localizable.

**Comment by plscully** [comment]
Thanks!

**Comment by ascott** [comment]
this is on staging, along with some other changes that are being tested. Will likely be on prod by the end of the week.
