### ISSUE TITLE
Can't print reader view with data

### ISSUE THREAD

**Issue by scottofletcher** [participedia/usersnaps#899]
Couldn't Usersnap this so here's a screenshot: 

<img width="958" alt="screenshot 2019-10-14 12 05 40" src="https://user-images.githubusercontent.com/29512491/66776715-de54d380-ee7b-11e9-8a34-4642b4246e85.png">

*Note that I've hidden this entry for now until we contact GovLab for permission to run it with the 'reference statement' (long story).

**Comment by scottofletcher** [comment]
sorry if the screenshot isn't clear - that's the pop-up print screen with the case reader view behind it. you can see that the print view is the same as the mobile phone view where the data is collapsed into an accordion (except, in this case, I can't unfold it)

**Comment by jesicarson** [comment]
hmm, i'm not sure how to label this. don't think its a bug, and also probably not super high priority. but if it is something simple on our end to not default to the mobile view for printing, maybe worth doing - @ascott when you have a minute can you assess the complexity of this ask? thx!

**Comment by scottofletcher** [comment]
yeah this is 100% not urgent. I quickly realized that I could just use my screenshot extension to grab the whole page and then save as a PDF ([result](http://bit.ly/2INVIJp))

**Comment by ascott** [comment]
it's an easy fix in the css to use the desktop size styling for printing. i'll make that change.
