### ISSUE TITLE
Usersnap Feedback - We may want to move the ‘scope of influence’ above the list of countries b[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#902]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: We may want to move the ‘scope of influence’ above the list of countries because mobile users may not realize we’re also asking for the scope of influence
[Open #596 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/596)

<a href='https://usersnappublic.s3.amazonaws.com/2019-10-18/00-09/1d4ae65b-c1ad-48a9-857d-1f226d1286f4.png'>![Usersnap Feedback - We may want to move the ‘scope of influence’ above the list of countries b(...)](https://usersnappublic.s3.amazonaws.com/2019-10-18/00-09/7c33b5fa-9b81-437a-b351-2b26b5cef6f3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-10-18/00-09/1d4ae65b-c1ad-48a9-857d-1f226d1286f4.png'>Download original image</a>

**Browser**: ChromeiOS 77 (iOS)
**Referer**: [https://participedia.net/?selectedCategory=case&scope_of_influence=national](https://participedia.net/?selectedCategory=case&scope_of_influence=national)
**Screen size**: 320 x 568 **Browser size**: 320 x 448

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
this is a good suggestion. @ascott could you add this to your search filters workflow if it is a fairly easy switch?

**Comment by ascott** [comment]
@jesicarson i can do this in a different PR. it's a quick change.

**Comment by jesicarson** [comment]
@ascott Yes please! thanks!
