### ISSUE TITLE
Usersnap Feedback - My recent changes are saving, but its not updating my username. I don't kn[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#907]
**Sender**: scottowenfletcher@gmail.com
**Comment**: My recent changes are saving, but its not updating my username. I don't know how long this has been going on for - it could affect numerous cases
[Open #601 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/601)

<a href='https://usersnappublic.s3.amazonaws.com/2019-10-24/21-07/3c8cb7fe-a2c1-4694-afc6-ba7078b61355.png'>![Usersnap Feedback - My recent changes are saving, but its not updating my username. I don't kn(...)](https://usersnappublic.s3.amazonaws.com/2019-10-24/21-07/0bae568e-56c3-4d06-8a0a-e74db0ad34c9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-10-24/21-07/3c8cb7fe-a2c1-4694-afc6-ba7078b61355.png'>Download original image</a>

**Browser**: Chrome 78 (Windows 10)
**Referer**: [https://participedia.net/method/4644](https://participedia.net/method/4644)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
verified. i published an edit to this case https://participedia.net/case/5321 and the most recent updated person is still scott. 
i labelled this as p1 because it is likely connected to the recent work on editing submission details.  @paninee @ascott

**Comment by ascott** [comment]
@jesicarson @scottofletcher taking a look now
