### ISSUE TITLE
Usersnap Feedback - Edit submission details not working. Changed the first submitted by author [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#908]
**Sender**: jesi.carson@gmail.com
**Comment**: Edit submission details not working. Changed the first submitted by author in the form to Scott (non admin) and it still shows me as the first author. Related to the most recent changes not showing up on reader bug just filed by scott.
[Open #602 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/602)

<a href='https://usersnappublic.s3.amazonaws.com/2019-10-24/21-21/531934e1-ad75-4ce2-ad40-476c59f2f655.png'>![Usersnap Feedback - Edit submission details not working. Changed the first submitted by author (...)](https://usersnappublic.s3.amazonaws.com/2019-10-24/21-21/8fdbadf9-8317-4380-b27c-84d0330e7219.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-10-24/21-21/531934e1-ad75-4ce2-ad40-476c59f2f655.png'>Download original image</a>

**Browser**: Chrome 77 (Macintosh)
**Referer**: [https://participedia.net/case/5321](https://participedia.net/case/5321)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
related to https://github.com/participedia/usersnaps/issues/907
