### ISSUE TITLE
Usersnap Feedback - Missing placeholder images on profile page.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#916]
**Sender**: jesi.carson@gmail.com
**Comment**: Missing placeholder images on profile page.
[Open #610 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/610)

<a href='https://usersnappublic.s3.amazonaws.com/2019-10-31/01-04/5051c733-90f1-4f78-b88a-8ba830879e25.png'>![Usersnap Feedback - Missing placeholder images on profile page.](https://usersnappublic.s3.amazonaws.com/2019-10-31/01-04/66dadd8a-9f33-4281-8ece-c1c266689f14.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-10-31/01-04/5051c733-90f1-4f78-b88a-8ba830879e25.png'>Download original image</a>

**Browser**: Chrome 78 (Macintosh)
**Referer**: [https://participedia.net/user/1189](https://participedia.net/user/1189)
**Screen size**: 1680 x 1050 **Browser size**: 1192 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@paninee i think this may be related to this issue: https://github.com/participedia/api/issues/612

**Comment by paninee** [comment]
Fixed in https://github.com/participedia/api/tree/pan-916
