### ISSUE TITLE
Usersnap Feedback - Org entry link doesn't work when published

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#918]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Org entry link doesn't work when published
[Open #612 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/612)

<a href='https://usersnappublic.s3.amazonaws.com/2019-10-31/19-43/dc3fdea0-fe43-4c12-a92d-68d41383235a.png'>![Usersnap Feedback - Org entry link doesn't work when published](https://usersnappublic.s3.amazonaws.com/2019-10-31/19-43/f9bc4770-c32b-4ec7-b48b-0ac0347eb535.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-10-31/19-43/dc3fdea0-fe43-4c12-a92d-68d41383235a.png'>Download original image</a>

**Browser**: Chrome 78 (Windows 10)
**Referer**: [https://participedia.net/organization/6232](https://participedia.net/organization/6232)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
I was able to fix this by re-copying the link url including the http:// part. Not sure if this is supposed to automatically generate a url if anysite.com is added? But at any rate i was able to fix this particular instance manually. @ascott should we keep this open? is it a bug?

**Comment by ascott** [comment]
@jesicarson yes, this is a bug. we should check when a link is added that it includes the https part, and add it if it doesn't. But like you said there is a work around, but just adding it via the form for now, but we can't assume every user knows to include this part.

**Comment by jesicarson** [comment]
Good point. Let's fix this when we have time.

**Comment by ascott** [comment]
@paninee could you please add some validation on the backend to require that all links include either http:// or https:// when submitted. we should return an error like we do when the title field is not complete if you want to take a look at how we are handling validation errors currently.

**Comment by ascott** [comment]
after discussion, we've decided that if the url doesn't have http or https we will set it to http to cover most use cases, since most websites should be redirecting from http to https anyway, and if they don't have https, then http will work.

**Comment by paninee** [comment]
@ascott on second thought. I think it might be better for us to add a URL validation and let the user fix it, because missing `http` is one thing, but the URL could be invalid for other ways. I'm trying to add both, basically, detects if it's missing the `http`, if so add it, but if it still isn't valid after we add the `http`, we should return with an error and let the user fix it.
