### ISSUE TITLE
Usersnap Feedback - This link doesn't work, it should take me to the edit screen for this case [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#925]
**Sender**: scottowenfletcher@gmail.com
**Comment**: This link doesn't work, it should take me to the edit screen for this case but it just takes me to the top of the page
[Open #619 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/619)

<a href='https://usersnappublic.s3.amazonaws.com/2019-11-06/04-37/03bbc3ac-ca36-421b-be9c-9d741a7d43b2.png'>![Usersnap Feedback - This link doesn't work, it should take me to the edit screen for this case (...)](https://usersnappublic.s3.amazonaws.com/2019-11-06/04-37/3cf86c52-e2c0-40ae-ae0a-9372b3af6801.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-11-06/04-37/03bbc3ac-ca36-421b-be9c-9d741a7d43b2.png'>Download original image</a>

**Browser**: Chrome 78 (Windows 10)
**Referer**: [https://participedia.net/case/634#](https://participedia.net/case/634#)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Good Catch! The link in the prompt just adds a hash tag to the end of the case URL. ie: https://participedia.net/case/6239#

**Comment by ascott** [comment]
@scottofletcher @jesicarson thanks for the catch! this is fixed on prod now.
