### ISSUE TITLE
Usersnap Feedback - These links should go to the full edit page, not the quick submit. I think [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#926]
**Sender**: scottowenfletcher@gmail.com
**Comment**: These links should go to the full edit page, not the quick submit. I think we can safely assume that someone clicking on an icon that's asking them to add footnotes or otherwise edit its narrative is looking for the full edit screen
[Open #620 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/620)

<a href='https://usersnappublic.s3.amazonaws.com/2019-11-07/02-19/64098703-aa11-4cc7-b3a3-b0132107a728.png'>![Usersnap Feedback - These links should go to the full edit page, not the quick submit. I think (...)](https://usersnappublic.s3.amazonaws.com/2019-11-07/02-19/e976a4c9-e187-4b67-b658-2e8d7a33660b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-11-07/02-19/64098703-aa11-4cc7-b3a3-b0132107a728.png'>Download original image</a>

**Browser**: Chrome 78 (Windows 10)
**Referer**: [https://participedia.net/case/5411](https://participedia.net/case/5411)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 774

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Ah sorry I didn’t think of that in the specs for this. Alanna, do you have time to make this change?

**Comment by ascott** [comment]
@jesicarson @scottofletcher no problem, i can update that tomorrow.

**Comment by scottofletcher** [comment]
Thanks!
