### ISSUE TITLE
Usersnap Feedback - I'm a bit confused as to why on my profile pages, it has all these entries [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#932]
**Sender**: lucy.parry@canberra.edu.au
**Comment**: I'm a bit confused as to why on my profile pages, it has all these entries as contributions I've done when I'm not sure I've ever even edited some of them! I don't want to take credit for others work!
[Open #626 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/626)

<a href='https://usersnappublic.s3.amazonaws.com/2019-11-16/14-53/37839ce1-3e46-47a4-8b84-f881b9824c72.png'>![Usersnap Feedback - I'm a bit confused as to why on my profile pages, it has all these entries (...)](https://usersnappublic.s3.amazonaws.com/2019-11-16/14-53/e0f589b7-9f7e-493e-a7fc-42a3e989e79b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-11-16/14-53/37839ce1-3e46-47a4-8b84-f881b9824c72.png'>Download original image</a>

**Browser**: Chrome 78 (Windows 10)
**Referer**: [https://participedia.net/user/134860](https://participedia.net/user/134860)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 657

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@paninee can you please confirm that all entries that are passed to the user profile view from the server are indeed entries that have been edited by the user?

**Comment by paninee** [comment]
@ascott it is showing all data, the the user created and updated (cases,things,methods,organizations)

**Comment by ascott** [comment]
@paninee ok, thanks for checking. 

@jesicarson i think the issue here is that likely Lucy doesn't remember when she may have edited some of these entries, and perhaps it's not clear that even if she didn't make changes, but saved the entry, she would still be counted as an author. we've talked about adding some transparency to entries to show all previous authors of the entry, do you have a design in mind/in progress for how this might look on an entry page? what do you think about using an accordion to show/hide the entry author history like this?

![image](https://user-images.githubusercontent.com/130878/69168313-73bf3500-0ac4-11ea-9ee9-975500aa32e0.png)

**Comment by jesicarson** [comment]
@ascott amazing! let's go with the accordion, and make live as soon as possible. BOOM! Checking boxes. Go team!

**Comment by ascott** [comment]
@jesicarson great! i'll create a dev issue in the other repo to track this

**Comment by ascott** [comment]
created an issue for this work here: https://github.com/participedia/api/issues/789
