### ISSUE TITLE
Usersnap Feedback - Collections Staging Test - Need to update the names of the university coll[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#933]
**Sender**: jesi.carson@gmail.com
**Comment**: Collections Staging Test - Need to update the names of the university collections to the following:
- U Arkansas Students should be: "University of Arkansas Clinton School of Public Service"
- Coady Students should be: "Coady Institute Graduates"
- USoton Students should be: "University of Southampton Students"
[Open #627 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/627)

<a href='https://usersnappublic.s3.amazonaws.com/2019-11-18/23-11/397ff756-e2c2-4c03-9ce3-c88cf650286d.png'>![Usersnap Feedback - Collections Staging Test - Need to update the names of the university coll(...)](https://usersnappublic.s3.amazonaws.com/2019-11-18/23-11/85e5ecb7-2bcf-4e69-9c1d-22e684639077.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-11-18/23-11/397ff756-e2c2-4c03-9ce3-c88cf650286d.png'>Download original image</a>

**Browser**: Chrome 78 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/?selectedCategory=case](https://ppedia-stage.herokuapp.com/?selectedCategory=case)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Update: Arkansas should be: “UA Clinton School of Public Service Students”
