### ISSUE TITLE
Usersnap Feedback - Search for actual name of case doesn’t bring up that case in results

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#939]
**Sender**: jesi.carson@gmail.com
**Comment**: Search for actual name of case doesn’t bring up that case in results
[Open #633 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/633)

<a href='https://usersnappublic.s3.amazonaws.com/2019-11-26/02-09/74250ebd-bf48-40f7-9ff3-579171208f11.png'>![Usersnap Feedback - Search for actual name of case doesn’t bring up that case in results](https://usersnappublic.s3.amazonaws.com/2019-11-26/02-09/b9d68956-f39b-4107-9fe7-f3afb19f428b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-11-26/02-09/74250ebd-bf48-40f7-9ff3-579171208f11.png'>Download original image</a>

**Browser**: Safari 13 (iOS)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
@ascott cannot reproduce 
![image](https://user-images.githubusercontent.com/29439995/69819538-068e5c80-11b4-11ea-9ff5-5c45f7eda7ca.png)

**Comment by ascott** [comment]
@jesicarson i also was not able to repro. are you still seeing this issue?

**Comment by jesicarson** [comment]
nope, very strange. ill let you know if it happens again, but all seems well. we can keep this closed.
