### ISSUE TITLE
Usersnap Feedback - BEFORE USER TESTING: "Participant Selection" is listed twice. Delete one o[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#94]
**Sender**: jesi.carson@gmail.com
**Comment**: BEFORE USER TESTING:
"Participant Selection" is listed twice. Delete one of them.
[Open #108 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/108)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/19-13/f0056fe6-610a-4a1c-a16c-37ab61d016f9.png'>![Usersnap Feedback - BEFORE USER TESTING: "Participant Selection" is listed twice. Delete one o(...)](https://usersnappublic.s3.amazonaws.com/2017-08-30/19-13/2e2380f8-4116-42a3-8994-c0b3af798fb2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/19-13/f0056fe6-610a-4a1c-a16c-37ab61d016f9.png'>Download original image</a>

**Browser**: Chrome 60 (macOS Sierra)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 1280 x 800 **Browser size**: 1600 x 845

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Fixed in PR https://github.com/participedia/frontend/pull/606
