### ISSUE TITLE
Usersnap Feedback - Contributor history doesn't need to show the exact time/time zone, I don't [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#940]
**Sender**: jesi.carson@gmail.com
**Comment**: Contributor history doesn't need to show the exact time/time zone, I don't think. Also looks like there may be errors in the display, how can there be multiple publish entries at the exact same time? And, if its not too difficult, we could show only the latest date&name if that person published multiple times on the same date. Thoughts?
[Open #634 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/634)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-02/19-23/34b29f21-e472-4b77-b513-f38a3fd27b93.png'>![Usersnap Feedback - Contributor history doesn't need to show the exact time/time zone, I don't (...)](https://usersnappublic.s3.amazonaws.com/2019-12-02/19-23/ab4dc0e2-f022-4a69-811c-e69c2b3d02a2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-02/19-23/34b29f21-e472-4b77-b513-f38a3fd27b93.png'>Download original image</a>

**Browser**: Chrome 78 (Macintosh)
**Referer**: [https://participedia.net/case/634](https://participedia.net/case/634)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson do you mean that we should remove the time and timezone or just the timezone? i think both are important especially if there have been multiple edits in a day, and the timezone is important since our editors are located all over the world. if an editor makes a change and then sees the timestamp for their change, without a timezone, i could see it looking like a bug if the time is not displayed in their timezone. An alternative to showing the timezone next to all of the timestamps could be to add a note under the table that says "All times are displayed in UTC"

I feel like we should show all edits on the entry, including if there are multiple from the same person in the same day. The reason for this apart from true transparency into the editing history, is if another editor made an edit in between the other editors edits, we would want to see that history. 

In this case where there are multiple edits on the same day at the same time, it could be that the editor was making quick changes and then publishing and checking them, and publishing again. I've tested this again, and the changes are getting saved and displayed correctly.

**Comment by jesicarson** [comment]
Right, just wanting to find a balance that is transparent but not too much info (ie: multiple saves in a row). Let’s chat weds about this one. :)

**Comment by jesicarson** [comment]
covered by #941 , closing this one.
