### ISSUE TITLE
Usersnap Feedback - Repeating contributions (same date, time, contributor) under history

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#941]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: Repeating contributions (same date, time, contributor) under history
[Open #635 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/635)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-04/04-36/fb2e13f8-04d4-4cf8-a957-26a1a5627174.png'>![Usersnap Feedback - Repeating contributions (same date, time, contributor) under history](https://usersnappublic.s3.amazonaws.com/2019-12-04/04-36/e90a7493-c70c-4339-a090-0633d5aecf2a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-04/04-36/fb2e13f8-04d4-4cf8-a957-26a1a5627174.png'>Download original image</a>

**Browser**: Chrome 78 (Windows 10)
**Referer**: [https://participedia.net/case/5578](https://participedia.net/case/5578)
**Screen size**: 1368 x 912 **Browser size**: 1710 x 1003

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott this is reading like an error for users. Maybe worth considering streamlining the display. Or is it actually an error?

**Comment by ascott** [comment]
@jesicarson ok, i'll take a closer look into this.

**Comment by jesicarson** [comment]
@ascott as per our chat today:
- only show all the authors who contributed each day, once, in the order of most recent edit (do not show multiple edits by the same author on the same day, or time stamps)

**Comment by ascott** [comment]
@jesicarson this fix is on prod now :)

**Comment by ascott** [comment]
@jesicarson just noticed that we are missing the very first edit with this fix 🤦‍♀. i created a new issue and will fix! https://github.com/participedia/usersnaps/issues/949
