### ISSUE TITLE
Usersnap Feedback - Can the language drop down in the header show the full word for each langu[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#942]
**Sender**: jesi.carson@gmail.com
**Comment**: Can the language drop down in the header show the full word for each language, in addition to the abbreviated initials? ie: EN - English, FR - French, etc. (see this site for example: https://commonfare.net/)
[Open #636 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/636)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-04/19-59/26583dff-6905-4d16-be6c-89558a73e06b.png'>![Usersnap Feedback - Can the language drop down in the header show the full word for each langu(...)](https://usersnappublic.s3.amazonaws.com/2019-12-04/19-59/45cf4f23-ecaf-495c-8097-e00abb399c4b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-04/19-59/26583dff-6905-4d16-be6c-89558a73e06b.png'>Download original image</a>

**Browser**: Chrome 78 (Macintosh)
**Referer**: [https://participedia.net/case/5725](https://participedia.net/case/5725)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@ascott this would be p1 if possible

**Comment by ascott** [comment]
@jesicarson sounds good 👍

**Comment by ascott** [comment]
@jesicarson i took a look into this and since we are using a native html select it's not possible to show different values in the list when it's open and when it's closed.

**Comment by jesicarson** [comment]
So we'd have to do a custom drop down to fix?

**Comment by ascott** [comment]
@jesicarson yes.

**Comment by jesicarson** [comment]
Ok. Let's add a custom drop down to the list of housekeeping, not a huge priority, and Pan can do it if she needs something to do over the break. Sound ok? 
I do think it would be nice to have the full language names at some point, but great that we have this for now anyway.

**Comment by ascott** [comment]
@paninee do you want to take this one? we are using custom selects on the edit form page using this library: https://github.com/brianvoe/slim-select. Can you use this lib and change out the native select in the header to achieve the design @jesicarson has referenced above?

**Comment by paninee** [comment]
Here's how it looks now. 
![image](https://user-images.githubusercontent.com/29439995/77341158-8dc78900-6ceb-11ea-9c50-eb5c67c1365c.png)

Merged branch `pan-942` into `master` and deployed to stage.

**Comment by jesicarson** [comment]
Sorry that request wasn't clear. I meant, when the drop down menu is open, it would be nice to have the full word. I don't want the white box on the header, I'd like to leave it as-is with the short form of the language, to save space on the header. Does that make sense?

**Comment by jesicarson** [comment]
exactly like the commonfare.net example: 
![Screen Shot 2020-03-23 at 10 06 44 AM](https://user-images.githubusercontent.com/13560530/77342850-10514800-6cee-11ea-9f78-e2d5e672c6c5.png)

**Comment by paninee** [comment]
Tested on stage, just realized the old dropdown UI design has a grey background and white text. Working on CSS to make it looks the same.

**Comment by jesicarson** [comment]
So ya, we don't need the full languages on the header, only when the drop down is open. Thanks!

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/77397984-dd499b80-6d63-11ea-9a42-7b3a7882c7fd.png)

Deployed on stage.

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/77398067-00744b00-6d64-11ea-817a-5c824dd8a5e8.png)

**Comment by jesicarson** [comment]
Nice, just tested on stage, looks good! Thanks @paninee

**Comment by paninee** [comment]
Deployed to production.
