### ISSUE TITLE
Usersnap Feedback - Some most recently updated cases don't appear on the home page

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#946]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: Some most recently updated cases don't appear on the home page
[Open #640 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/640)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-08/01-40/d5bccd68-8ada-40d0-83d7-adb34e054c1c.png'>![Usersnap Feedback - Some most recently updated cases don't appear on the home page](https://usersnappublic.s3.amazonaws.com/2019-12-08/01-40/4d9a098a-0cf5-43a5-8459-a3cc77f3658e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-08/01-40/d5bccd68-8ada-40d0-83d7-adb34e054c1c.png'>Download original image</a>

**Browser**: Chrome 78 (Windows 10)
**Referer**: [https://participedia.net/case/4818](https://participedia.net/case/4818)
**Screen size**: 1368 x 912 **Browser size**: 1710 x 1003

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
upon checking the data on stage it seems our data is correct, it's getting all your edited article

this is the data I'm getting on the SQL function I created

![image](https://user-images.githubusercontent.com/29439995/70809239-3756c000-1d76-11ea-86ea-7f66151f4b62.png)

but upon seeing the front-end code, @ascott are you intended to show only the specific date (same dates) instead of showing all of it.

![image](https://user-images.githubusercontent.com/29439995/70809253-3cb40a80-1d76-11ea-811c-3b2f79d1ac98.png)

**Comment by ascott** [comment]
@paninee looks like you may have mixed up this issue with something else. we need to look into why recently updated cases are not showing up on the home page.

**Comment by paninee** [comment]
@ascott do you know how to reproduce this? I just updated this case, and it updates fine.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/29439995/70906774-11226180-1fbc-11ea-8c39-b7fdad8df77f.png">

**Comment by jesicarson** [comment]
@paninee if you look at the case that Jaskiran usersnapped (https://participedia.net/case/4818) then compare that to the homepage results for Dec 8 (https://participedia.net/?page=6) you will see that it is not appearing as updated on the homepage. Is it appearing as updated in the database? If so, why wouldn't it show up on the homepage?
Perhaps try to update that particular case again and see if you can reproduce? If not, and it correctly logs on the homepage, maybe this isn't a bug? Could it be a one time error of some kind?

**Comment by paninee** [comment]
@jesicarson it seems like it's a one-off thing. I updated the case again, and it now shows up after the featured case.
