### ISSUE TITLE
Usersnap Feedback - This is not a big deal, but shouldn't this read '21-28 results of 28' ? Th[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#947]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: This is not a big deal, but shouldn't this read '21-28 results of 28' ? This is from the U of Southampton cases collection
[Open #641 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/641)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-08/18-16/16b8f92c-2620-4ee6-bf7c-674df3262856.png'>![Usersnap Feedback - This is not a big deal, but shouldn't this read '21-28 results of 28' ? Th(...)](https://usersnappublic.s3.amazonaws.com/2019-12-08/18-16/c4477a72-9a04-43d1-8b11-7bdeeeb30d32.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-08/18-16/16b8f92c-2620-4ee6-bf7c-674df3262856.png'>Download original image</a>

**Browser**: Firefox 71 (Windows 10)
**Referer**: [https://participedia.net/?selectedCategory=case&page=2&collections=usoton_students](https://participedia.net/?selectedCategory=case&page=2&collections=usoton_students)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1064

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
thanks for flagging @plscully, i'll take a look 🤔

**Comment by paninee** [comment]
Fixed in https://github.com/participedia/api/tree/pan-947

**Comment by paninee** [comment]
Deployed on production
