### ISSUE TITLE
Usersnap Feedback - edit history is missing the first edit/first submitted by entry

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#949]
**Sender**: alanna.scott@gmail.com
**Comment**: edit history is missing the first edit/first submitted by entry
[Open #643 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/643)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-10/20-44/73bcd57c-6a5f-451e-80b0-00d4f1a23706.png'>![Usersnap Feedback - edit history is missing the first edit/first submitted by entry](https://usersnappublic.s3.amazonaws.com/2019-12-10/20-44/e6e50b69-2282-485c-bdae-c41d9ff0f20c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-10/20-44/73bcd57c-6a5f-451e-80b0-00d4f1a23706.png'>Download original image</a>

**Browser**: Chrome 78 (macOS High Sierra)
**Referer**: [https://participedia.net/case/5578](https://participedia.net/case/5578)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
This is related to https://github.com/participedia/usersnaps/issues/968. Already fixed in the branch `pan-968`
