### ISSUE TITLE
Usersnap Feedback - This image is not displaying correctly. I also opened the full screen and [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#950]
**Sender**: jesi.carson@gmail.com
**Comment**: This image is not displaying correctly. I also opened the full screen and nothing shows up. There is, however, an image in the form - it's a logo.
[Open #644 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/644)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-11/19-52/dc2b0bce-580a-4393-94b6-360b31d1b690.png'>![Usersnap Feedback - This image is not displaying correctly. I also opened the full screen and (...)](https://usersnappublic.s3.amazonaws.com/2019-12-11/19-52/0aa8a8d0-6a7e-4c1f-9071-2358c8571b03.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-11/19-52/dc2b0bce-580a-4393-94b6-360b31d1b690.png'>Download original image</a>

**Browser**: Chrome 78 (Macintosh)
**Referer**: [https://participedia.net/organization/5976](https://participedia.net/organization/5976)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
this particular image includes a url in the attribution field of the form, not sure if that affects anything.

**Comment by ascott** [comment]
this is the result of an old bug where we weren't escaping the filename if it had spaces in it. to solve this on a one-off basis, when we see the issue on an entry, we can download the image, and the reupload it. since the bug has been fixed, once it's uploaded again the image displays properly. A url in the attribution field is not a problem. I just manually fixed this case.
