### ISSUE TITLE
Usersnap Feedback - The language selector looks fine after it changes to 'EN', but there is th[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#951]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: The language selector looks fine after it changes to 'EN', but there is this glitch when it first appears. This is on Firefox, but the same thing happens with Chrome
[Open #645 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/645)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-12/17-30/b4d98d25-c4c8-49ed-bc05-c7f1f486c1ed.png'>![Usersnap Feedback - The language selector looks fine after it changes to 'EN', but there is th(...)](https://usersnappublic.s3.amazonaws.com/2019-12-12/17-30/f77e19ac-6fa7-4b26-b2a4-49517f1c90fb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-12/17-30/b4d98d25-c4c8-49ed-bc05-c7f1f486c1ed.png'>Download original image</a>

**Browser**: Firefox 71 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1064

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully i can’t see the screenshot properly as it is cut off (not sure if its just me, I’m on my phone) if possible could you take a manual screenshot of the glitch you’re seeing and post it here? Thanks!

**Comment by plscully** [comment]
@jesicarson Here you go ...
https://www.dropbox.com/s/vqw671z823xkrar/Screenshot%202019-12-12%2012.46.47.png?dl=0

**Comment by ascott** [comment]
pasting the image here for ease. i'll look in to this.
![image](https://user-images.githubusercontent.com/130878/70757342-08980580-1cf4-11ea-96d5-dc23c031e4db.png)
