### ISSUE TITLE
Usersnap Feedback - Alanna / Pan - please double check these French versions entered by Zaria [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#952]
**Sender**: jesi.carson@gmail.com
**Comment**: Alanna / Pan - please double check these French versions entered by Zaria Channer are being correctly assigned as FR in the database. Want to ensure seamless transition to the next phase of localization. Thanks!
[Open #646 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/646)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-12/22-13/254e2592-9fb7-4958-adb6-671c8a9533ae.png'>![Usersnap Feedback - Alanna / Pan - please double check these French versions entered by Zaria (...)](https://usersnappublic.s3.amazonaws.com/2019-12-12/22-13/8115bb48-4eb9-4199-8f6c-a8468fe7d8e0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-12/22-13/254e2592-9fb7-4958-adb6-671c8a9533ae.png'>Download original image</a>

**Browser**: Safari 13 (iOS)
**Referer**: [https://participedia.net/user/417703](https://participedia.net/user/417703)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson I can confirm that the latest/verified French translations are on the production site. Are there any phrases that don't look correct?

**Comment by jesicarson** [comment]
Sorry, I meant, were these cases by Zaria entered with French selected in the drop down, and logged as such in the database?

**Comment by ascott** [comment]
@jesicarson ah i see, yes, I checked and the entries added in French have been added with the original language set to FR in the database.

**Comment by jesicarson** [comment]
Great, thanks! Closing.
