### ISSUE TITLE
Usersnap Feedback - Edit view on iPhone 6s is off center

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#953]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Edit view on iPhone 6s is off center
[Open #647 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/647)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-14/22-23/01087e94-fd77-40da-bdd5-999261ecd96c.png'>![Usersnap Feedback - Edit view on iPhone 6s is off center](https://usersnappublic.s3.amazonaws.com/2019-12-14/22-23/7ca6bde8-b76b-42ff-a046-6a8a0bd5197c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-14/22-23/01087e94-fd77-40da-bdd5-999261ecd96c.png'>Download original image</a>

**Browser**: ChromeiOS 78 (iOS)
**Referer**: [https://participedia.net/case/634/edit](https://participedia.net/case/634/edit)
**Screen size**: 320 x 568 **Browser size**: 320 x 448

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Yep I’m seeing this bug too 

![936AB9F0-5EBF-4CEA-8989-82FEF56CD720](https://user-images.githubusercontent.com/13560530/70855178-2e034b80-1e7b-11ea-89c2-74df3d4115a3.png)
