### ISSUE TITLE
Usersnap Feedback - Search filters should allow for multiple locations to be selected. ie: Can[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#955]
**Sender**: jesi.carson@gmail.com
**Comment**: Search filters should allow for multiple locations to be selected. ie: Canada and China both have multiple cases, but when both filters are clicked, there are zero results. I'm wondering if the settings are specifying that results must have ALL the filters that are checked? If so we need to change this so results must contain ANY of the selected filters, not ALL of them.
[Open #649 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/649)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-17/20-24/de563ff7-cab4-422b-afb2-6475ca8a8e8f.png'>![Usersnap Feedback - Search filters should allow for multiple locations to be selected. ie: Can(...)](https://usersnappublic.s3.amazonaws.com/2019-12-17/20-24/e2a1e341-a08b-4dc7-aea4-c526b475ef33.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-17/20-24/de563ff7-cab4-422b-afb2-6475ca8a8e8f.png'>Download original image</a>

**Browser**: Chrome 78 (Macintosh)
**Referer**: [https://participedia.net/?selectedCategory=case&country=Canada,China](https://participedia.net/?selectedCategory=case&country=Canada,China)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 948

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment]
@ascott Fixed, it's on staging https://ppedia-stage.herokuapp.com.
