### ISSUE TITLE
Usersnap Feedback - Completeness prompt - Can we try the grey box filled, rather than outlined?

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#957]
**Sender**: jesi.carson@gmail.com
**Comment**: Completeness prompt - Can we try the grey box filled, rather than outlined?
[Open #651 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/651)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-20/23-44/8be4e377-1f49-42c2-9e3d-893c915dfe44.png'>![Usersnap Feedback - Completeness prompt - Can we try the grey box filled, rather than outlined?](https://usersnappublic.s3.amazonaws.com/2019-12-20/23-44/65c4a2e0-2c6a-4f92-8826-f2716b075233.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-20/23-44/8be4e377-1f49-42c2-9e3d-893c915dfe44.png'>Download original image</a>

**Browser**: Chrome 79 (Macintosh)
**Referer**: [https://participedia.net/method/4620](https://participedia.net/method/4620)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 899

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@jesicarson here is the alert with a background color of `#f1f1f1` with black text.

<img width="1316" alt="Screenshot 2020-01-03 16 39 30" src="https://user-images.githubusercontent.com/130878/71756935-557c8100-2e47-11ea-8453-97ee97dcdb36.png">

**Comment by jesicarson** [comment]
Looks good to me!

**Comment by ascott** [comment]
@jesicarson this is on prod now.
