### ISSUE TITLE
Usersnap Feedback - Staging test for filter results text - “Arts” has been shortened from “Art[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#959]
**Sender**: jesi.carson@gmail.com
**Comment**: Staging test for filter results text - “Arts” has been shortened from “Arts, culture, and recreation” ... I see why this makes sense, but we may want to include the full text for the filters. Pan - are you just taking the first word from each filter to display?
[Open #653 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/653)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-28/18-46/fbc000d8-f700-444a-afd1-6ed147481bd5.png'>![Usersnap Feedback - Staging test for filter results text - “Arts” has been shortened from “Art(...)](https://usersnappublic.s3.amazonaws.com/2019-12-28/18-46/7ef69612-9380-4bad-aee7-ed4c63deeaf1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-28/18-46/fbc000d8-f700-444a-afd1-6ed147481bd5.png'>Download original image</a>

**Browser**: Safari 13 (iOS)
**Referer**: [https://ppedia-stage.herokuapp.com/?selectedCategory=case&query=Women&general_issues=arts](https://ppedia-stage.herokuapp.com/?selectedCategory=case&query=Women&general_issues=arts)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by zphingphong** [comment]
Close, in regards of https://github.com/participedia/api/issues/821
