### ISSUE TITLE
Usersnap Feedback - BEFORE USER TESTING: Error message when submitting a full case form. Every [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#96]
**Sender**: jesi.carson@gmail.com
**Comment**: BEFORE USER TESTING:
Error message when submitting a full case form. Every single field was filled out. Case was called "Aug 30 Jesi Test" (or similar).
[Open #110 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/110)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/19-16/cd1e72e1-8047-4bce-bc24-aaee8c5717c4.png'>![Usersnap Feedback - BEFORE USER TESTING: Error message when submitting a full case form. Every (...)](https://usersnappublic.s3.amazonaws.com/2017-08-30/19-16/aadadd50-2fd8-490c-8217-3f226863b978.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/19-16/cd1e72e1-8047-4bce-bc24-aaee8c5717c4.png'>Download original image</a>

**Browser**: Chrome 60 (macOS Sierra)
**Referer**: [https://participedia.xyz/new/case](https://participedia.xyz/new/case)
**Screen size**: 1280 x 800 **Browser size**: 1600 x 845

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
This case can videos and we had missed a migration (changes to the videos schema in the database) on xyx. Fixed for now, avoiding this issue in the future will come under https://github.com/participedia/api/issues/93.
