### ISSUE TITLE
Usersnap Feedback - Staging test for filter results text - Seeing this, I do think we need to [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#962]
**Sender**: jesi.carson@gmail.com
**Comment**: Staging test for filter results text - Seeing this, I do think we need to add the full filter label to the text, could separate them with semicolons. There also needs to be proper spacing between words and punctuation.
[Open #656 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/656)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-28/18-52/ac2403ab-300a-4e68-8da1-b5c1283096b1.png'>![Usersnap Feedback - Staging test for filter results text - Seeing this, I do think we need to (...)](https://usersnappublic.s3.amazonaws.com/2019-12-28/18-52/4befb922-d22a-433c-8eb1-bbc5c7a6536e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-28/18-52/ac2403ab-300a-4e68-8da1-b5c1283096b1.png'>Download original image</a>

**Browser**: Safari 13 (iOS)
**Referer**: [https://ppedia-stage.herokuapp.com/?selectedCategory=case&method_types=collaborative,deliberative](https://ppedia-stage.herokuapp.com/?selectedCategory=case&method_types=collaborative,deliberative)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@paninee the text for this filter should read: 
`1 - 4 results of 4 where Method Types include Collaborative, Deliberative (page 1 of 1)`

and if filters are selected for multiple fields it should read like: 
https://ppedia-stage.herokuapp.com/?selectedCategory=case&general_issues=arts,education&scope_of_influence=organization
`1 - 1 results of 1 where General Issues include Arts or Education and Scope of Influence includes Organization (page 1 of 1)`

@jesicarson does that sound right to you?

**Comment by jesicarson** [comment]
Looks good. This seems clear enough to me, and we can test it with a few other folks once it’s live too.

**Comment by paninee** [comment]
@ascott @jesicarson instead of `Method type` can we use the word `General Types of Methods` to show on the filter? So that we don't have to add more translation too new keywords, and also if it's the same thing, they both should be consistently using the same wording.

**Comment by paninee** [comment]
@ascott @jesicarson I assume we want to localize this as well right? how does comma and the word `and` work in other languages we support?

**Comment by zphingphong** [comment]
Close, in regarding to https://github.com/participedia/api/issues/821
