### ISSUE TITLE
Usersnap Feedback - staging test for selected search filters - the X looks like the padding ne[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#969]
**Sender**: jesi.carson@gmail.com
**Comment**: staging test for selected search filters - the X looks like the padding needs to be adjusted. could make the X a tiny bit smaller to fit better if needed.
[Open #663 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/663)

<a href='https://usersnappublic.s3.amazonaws.com/2020-01-22/20-04/488ea4dc-00ae-4be2-a0c1-d90d16e08bd0.png'>![Usersnap Feedback - staging test for selected search filters - the X looks like the padding ne(...)](https://usersnappublic.s3.amazonaws.com/2020-01-22/20-04/2c77d294-ffc8-4a3b-99e6-46aa7a8587a7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-01-22/20-04/488ea4dc-00ae-4be2-a0c1-d90d16e08bd0.png'>Download original image</a>

**Browser**: Chrome 79 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/?selectedCategory=case&purposes=make,make_influence,deliver&method_types=community,deliberative,direct&change_types=changes,changes_civic,changes_public](https://ppedia-stage.herokuapp.com/?selectedCategory=case&purposes=make,make_influence,deliver&method_types=community,deliberative,direct&change_types=changes,changes_civic,changes_public)
**Screen size**: 1920 x 1080 **Browser size**: 916 x 854

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by zphingphong** [comment]
Closed. Fixed as part of https://github.com/participedia/api/issues/825.

![image](https://user-images.githubusercontent.com/558198/72948674-b9a1af00-3d3a-11ea-8238-a6403aa42bfb.png)
