### ISSUE TITLE
Usersnap Feedback - Formatting bug? Column issue? All cases on my profile page show up below o[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#97]
**Sender**: jesi.carson@gmail.com
**Comment**: Formatting bug? Column issue?
All cases on my profile page show up below one another in one line in the left column, rather than across the screen in a grid. 
[Open #111 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/111)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/19-19/9bbe08e6-880f-4f18-aec6-680d357a9bcf.png'>![Usersnap Feedback - Formatting bug? Column issue? All cases on my profile page show up below o(...)](https://usersnappublic.s3.amazonaws.com/2017-08-30/19-19/f3b4901f-0ecb-4636-941e-105b1fc871ee.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/19-19/9bbe08e6-880f-4f18-aec6-680d357a9bcf.png'>Download original image</a>

**Browser**: Chrome 60 (macOS Sierra)
**Referer**: [https://participedia.xyz/profile](https://participedia.xyz/profile)
**Screen size**: 1280 x 800 **Browser size**: 1600 x 845

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Fixed in PR https://github.com/participedia/frontend/pull/606
