### ISSUE TITLE
Usersnap Feedback - Clicking the logo on the top right should clear the search term and return [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#98]
**Sender**: jesi.carson@gmail.com
**Comment**: Clicking the logo on the top right should clear the search term and return to the home page. Instead it keeps feeding me the results for the previous search. 
[Open #112 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/112)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/20-55/6ff7f0d3-df70-4605-ae79-08f030fc1dbd.png'>![Usersnap Feedback - Clicking the logo on the top right should clear the search term and return (...)](https://usersnappublic.s3.amazonaws.com/2017-08-30/20-55/da8e2715-7834-4941-a112-17c8447a701a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-30/20-55/6ff7f0d3-df70-4605-ae79-08f030fc1dbd.png'>Download original image</a>

**Browser**: Chrome 60 (macOS Sierra)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Related to https://github.com/participedia/frontend/issues/577 and can be fixed as part of that issue.
