### ISSUE TITLE
Usersnap Feedback - Are these spam articles duplicates? This seems like a bug in addition to s[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#982]
**Sender**: jesi.carson@gmail.com
**Comment**: Are these spam articles duplicates? This seems like a bug in addition to spam. I'm going to hide these.
[Open #676 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/676)

<a href='https://usersnappublic.s3.amazonaws.com/2020-02-04/18-36/5ae64c34-5402-4213-b09e-ca3909489880.png'>![Usersnap Feedback - Are these spam articles duplicates? This seems like a bug in addition to s(...)](https://usersnappublic.s3.amazonaws.com/2020-02-04/18-36/16b0cf78-8d1b-4d04-8321-c821e44ad100.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-02-04/18-36/5ae64c34-5402-4213-b09e-ca3909489880.png'>Download original image</a>

**Browser**: Chrome 79 (Macintosh)
**Referer**: [https://participedia.net/user/418465](https://participedia.net/user/418465)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
ah, i was able to reproduce this by clicking the submit button multiple times while the publishing modal was up.

**Comment by ascott** [comment]
the solution would be to disable the submit button while the publishing action is in progress.

**Comment by jesicarson** [comment]
ok that sounds good. i could see people doing this. the other issue, however, is allowing the publication of multiple entries with the same title - this would mess up the components field, no?

**Comment by ascott** [comment]
@jesicarson if there are multiple entries with the same title, the components field will still work, but it may be confusing since there would be multiple entries with the same title. i would suggest that we treat that case of entries being added with the same title as an editing issue since it wouldn't cause any issues in the code. i would also guess it might be a small edge case since i'm not sure we've seen any issues related to that yet.

**Comment by jesicarson** [comment]
sounds good
