### ISSUE TITLE
Usersnap Feedback - Why are all the 'updated' months in Spanish? My default is set to English

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#983]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Why are all the 'updated' months in Spanish? My default is set to English
[Open #677 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/677)

<a href='https://usersnappublic.s3.amazonaws.com/2020-02-04/18-38/c10033aa-72fa-4c95-bdf3-e8b97583d254.png'>![Usersnap Feedback - Why are all the 'updated' months in Spanish? My default is set to English](https://usersnappublic.s3.amazonaws.com/2020-02-04/18-38/c78efea6-0392-49da-8e83-7e8e56a7a3ee.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-02-04/18-38/c10033aa-72fa-4c95-bdf3-e8b97583d254.png'>Download original image</a>

**Browser**: Chrome 79 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1067

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@plscully i haven't been able to reproduce this. Are you still seeing this bug?

**Comment by plscully** [comment]
@ascott it went away the next day after I noted it. Weird!

**Comment by ascott** [comment]
@plscully strange! let me know if you see it again.
