### ISSUE TITLE
Usersnap Feedback - Twitter share doesn't even include a link. Can we fix this?

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#986]
**Sender**: jesi.carson@gmail.com
**Comment**: Twitter share doesn't even include a link. Can we fix this?
[Open #680 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/680)

<a href='https://usersnappublic.s3.amazonaws.com/2020-02-07/19-42/0df9c18f-91e1-423d-9424-968052e902b5.png'>![Usersnap Feedback - Twitter share doesn't even include a link. Can we fix this?](https://usersnappublic.s3.amazonaws.com/2020-02-07/19-42/273d304f-fbb6-468a-b0f5-8cfa39efc386.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-02-07/19-42/0df9c18f-91e1-423d-9424-968052e902b5.png'>Download original image</a>

**Browser**: Chrome 79 (Macintosh)
**Referer**: [https://participedia.net/case/5187](https://participedia.net/case/5187)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 839

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
![Screen Shot 2020-02-07 at 10 42 34 AM](https://user-images.githubusercontent.com/13560530/74056534-1043f580-4997-11ea-8911-b361939f967e.png)

**Comment by ascott** [comment]
@jesicarson this is a bug related to the title of this entry. it's working as expected for other entries.

https://participedia.net/method/5097

<img width="1680" alt="Screen Shot 2020-02-07 at 12 09 27 PM" src="https://user-images.githubusercontent.com/130878/74062291-cbbe5700-49a2-11ea-9e88-789637f5b117.png">

i'll look into the bug affecting this entry.

**Comment by jesicarson** [comment]
Not sure how much we can customize this, so feel free to ignore this if not possible... but... 
1. Can we get it to insert the @ symbol before @participedia so we get notified and mentioned on twitter when something is shared from the site? 
2. we also don't need the dash after the case title. when you hit tweet, twitter automatically removes the hyperlink and creates a nice looking card with image, etc, but it leaves the random dash hanging there: -

**Comment by ascott** [comment]
@jesicarson i can make those changes to add the `@`  in order to tag the partipedia account and i can remove the dash between the title and the url

**Comment by jesicarson** [comment]
awesome! should we add "via" or "from" or "on" before @participedia: do you think? @ascott

**Comment by ascott** [comment]
@jesicarson this is the format we have currently on staging: 

<img width="698" alt="Screen Shot 2020-02-10 at 2 58 34 PM" src="https://user-images.githubusercontent.com/130878/74198298-df252880-4c15-11ea-9538-afe3ac928a4a.png">

i don't think we need to add via/from/on. the `.` before the @ symbol will make sure that even people that don't follow participedia will see the tweet.

**Comment by jesicarson** [comment]
> the . before the @ symbol will make sure that even people that don't follow participedia will see the tweet.

I'm not sure i understand this, can you clarify? if I tweeted what you've shown above without the .  my followers would see the tweet, even if they don't follow participedia, wouldn't they? or does tweeting @ someone only show the tweet to them? i guess i don't use twitter enough to know the shorthand, but is using . a common solution? thanks!

**Comment by ascott** [comment]
> if I tweeted what you've shown above without the . my followers would see the tweet, even if they don't follow participedia, wouldn't they?

no, without the `.`, only people who follow you and participedia would see that reply. with the `.` all of of your followers would see it. 

it's kinda of a strange solution with the `.`, but it is commonly used. this website does a pretty good job of explaining how mentions in tweets work, (despite the tongue in cheek url): http://www.momthisishowtwitterworks.com/.

if we think the `.` at the beginning is too weird or hard to understand, we can move where we put `@particpedia` in the tweet. as long as `@participedia` isn't the first thing in the tweet, then all of your followers will see the tweet.

**Comment by jesicarson** [comment]
Lol I have no idea how twitter works apparently 😂
I would totally delete that . if I saw it... which would have unintended consequences. But I am probably not the best test user for this, because 👆lol
Ok, give me a day to check out some other examples. Moving the @pp sounds good but I’d worry about long entry titles cutting it off, would that happen? 
Thanks for helping on this, with Scott away I’ve been wanting to share more content to social.

**Comment by ascott** [comment]
the character limit for tweets is 240 characters, so if the title was longer than that, then the `@participedia` tag would get cut off if we put it at the end. I could handle that by truncating the title at 240 characters - 13 chars for the `@participedia` tag to make sure that wouldn't happen. I did a quick look through our DB and didn't find any titles over 200 characters so far, so needing to truncate the title would be an edge case.

**Comment by jesicarson** [comment]
Funny enough, not a lot of sites include their own twitter handle, the only one I could find was Medium, but they include the @name of the author of the post. Here are a few screenshots.

![Screen Shot 2020-02-11 at 4 03 15 PM](https://user-images.githubusercontent.com/13560530/74365477-0d744680-4d83-11ea-8b44-29d063b9032c.png)

![Screen Shot 2020-02-11 at 4 04 07 PM](https://user-images.githubusercontent.com/13560530/74365504-1c5af900-4d83-11ea-90a0-bedd66a6a7a0.png)

![Screen Shot 2020-02-11 at 4 06 47 PM](https://user-images.githubusercontent.com/13560530/74365563-2ed53280-4d83-11ea-8806-7e50118fd687.png)

![Screen Shot 2020-02-11 at 4 07 53 PM](https://user-images.githubusercontent.com/13560530/74365572-34cb1380-4d83-11ea-97b1-8a474240a5e3.png)

etc.

Even so, I think its a good idea to include the @ before participedia, as it could lead to more followers. So, as you suggest, lets do either of the following: 
a) Title of Entry @participedia entry.url 
b) Very, Very Long Title... @participedia entry.url
We could start with A and monitor twitter to see if things are getting cut off. Or if its easy enough to do B at the same time, go for it. @ascott Thanks!

**Comment by ascott** [comment]
@jesicarson sounds good jesi. we can do a and b together.
