### ISSUE TITLE
Usersnap Feedback - LinkedIn looks better, however I can't share the article from the Particip[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#987]
**Sender**: jesi.carson@gmail.com
**Comment**: LinkedIn looks better, however I can't share the article from the Participedia account. Not sure if we have any control over that though. But just in case.
[Open #681 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/681)

<a href='https://usersnappublic.s3.amazonaws.com/2020-02-07/19-44/8c289f72-3c6b-4900-845d-3bd5ba4e6b56.png'>![Usersnap Feedback - LinkedIn looks better, however I can't share the article from the Particip(...)](https://usersnappublic.s3.amazonaws.com/2020-02-07/19-44/b232c635-1a23-4158-a29e-197b5da5f834.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-02-07/19-44/8c289f72-3c6b-4900-845d-3bd5ba4e6b56.png'>Download original image</a>

**Browser**: Chrome 79 (Macintosh)
**Referer**: [https://participedia.net/case/5187](https://participedia.net/case/5187)
**Screen size**: 1920 x 1080 **Browser size**: 1914 x 839

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
![Screen Shot 2020-02-07 at 10 43 44 AM](https://user-images.githubusercontent.com/13560530/74056594-2a7dd380-4997-11ea-97ec-a32490afe7d2.png)

![Screen Shot 2020-02-07 at 10 43 34 AM](https://user-images.githubusercontent.com/13560530/74056616-32d60e80-4997-11ea-8891-d0a57bcbbaed.png)

**Comment by ascott** [comment]
@jesicarson i'm not sure what you mean when you say you can't share the article from the Participedia account. could you elaborate?

**Comment by jesicarson** [comment]
In the second screenshot above, it shows me attempting to change it from Jesi Carson to Participedia, but the options are greyed out, and the text says "remove your attachment to post from another account" which is probably a linkedin dumb thing i'm guessing.

**Comment by ascott** [comment]
@jesicarson yeah that sounds like a LinkedIn thing and not related to our sharing code.
