### ISSUE TITLE
Usersnap Feedback - quick submit button disappeared on top bar. no floating + button needed on [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#99]
**Sender**: jesi.carson@gmail.com
**Comment**: quick submit button disappeared on top bar. no floating + button needed on home page. 
[Open #113 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/113)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-31/00-38/2dc6990b-4cbe-4e69-84ca-9498968d889c.png'>![Usersnap Feedback - quick submit button disappeared on top bar. no floating + button needed on (...)](https://usersnappublic.s3.amazonaws.com/2017-08-31/00-38/f9250260-ab77-4328-8e07-02166888c3de.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-31/00-38/2dc6990b-4cbe-4e69-84ca-9498968d889c.png'>Download original image</a>

**Browser**: Chrome 60 (macOS Sierra)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
Quick submit button in menu fixed in PR https://github.com/participedia/frontend/pull/609, removing floating add button from homepage will be done as https://github.com/participedia/frontend/issues/610
