### ISSUE TITLE
Usersnap Feedback - got the hanging publish bug again on this case, was able to get the images [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#991]
**Sender**: jesi.carson@gmail.com
**Comment**: got the hanging publish bug again on this case, was able to get the images to publish by deleting "edit" from the url and hitting enter.  but it was stuck on publish modal until i did that.
[Open #685 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/685)

<a href='https://usersnappublic.s3.amazonaws.com/2020-02-15/01-17/9cff0c0c-e338-4a61-80ec-620966b4f7b3.png'>![Usersnap Feedback - got the hanging publish bug again on this case, was able to get the images (...)](https://usersnappublic.s3.amazonaws.com/2020-02-15/01-17/0cd8272c-893c-4ccd-9f1d-b42c3b038336.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-02-15/01-17/9cff0c0c-e338-4a61-80ec-620966b4f7b3.png'>Download original image</a>

**Browser**: Chrome 79 (Macintosh)
**Referer**: [https://participedia.net/case/5600/](https://participedia.net/case/5600/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@zphingphong your AWS work will address this right? you can close this if so.

**Comment by ascott** [comment]
@jesicarson yes, the aws/image work will address this.
